Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 16/bookworm
  GitCommit: 3fda89cc5c2e588f46ae4f1ac117114c8e6814f1
  Tags:
  - 16beta1
  - 16beta1-bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 16/bullseye
  GitCommit: 4fe55381bab76d0d39195f84e00cfdd0759e65c0
  Tags:
  - 16beta1-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 16/alpine3.18
  GitCommit: 4fe55381bab76d0d39195f84e00cfdd0759e65c0
  Tags:
  - 16beta1-alpine3.18
  - 16beta1-alpine
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 16/alpine3.17
  GitCommit: 4fe55381bab76d0d39195f84e00cfdd0759e65c0
  Tags:
  - 16beta1-alpine3.17
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 15/bookworm
  GitCommit: 3fda89cc5c2e588f46ae4f1ac117114c8e6814f1
  Tags:
  - "15.3"
  - "15"
  - latest
  - 15.3-bookworm
  - 15-bookworm
  - bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 15/bullseye
  GitCommit: a23c0e97980edae5be2cd4eb68ff1f0762d031cd
  Tags:
  - 15.3-bullseye
  - 15-bullseye
  - bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 15/alpine3.18
  GitCommit: 5ea98fe00be95fbbe642732d62af3b4dbc83f442
  Tags:
  - 15.3-alpine3.18
  - 15-alpine3.18
  - alpine3.18
  - 15.3-alpine
  - 15-alpine
  - alpine
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 15/alpine3.17
  GitCommit: 5ea98fe00be95fbbe642732d62af3b4dbc83f442
  Tags:
  - 15.3-alpine3.17
  - 15-alpine3.17
  - alpine3.17
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 14/bookworm
  GitCommit: 3fda89cc5c2e588f46ae4f1ac117114c8e6814f1
  Tags:
  - "14.8"
  - "14"
  - 14.8-bookworm
  - 14-bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 14/bullseye
  GitCommit: 8ff11cd5ae43e73fd84d0b2bc8aa88537fe18649
  Tags:
  - 14.8-bullseye
  - 14-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 14/alpine3.18
  GitCommit: 5ea98fe00be95fbbe642732d62af3b4dbc83f442
  Tags:
  - 14.8-alpine3.18
  - 14-alpine3.18
  - 14.8-alpine
  - 14-alpine
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 14/alpine3.17
  GitCommit: 5ea98fe00be95fbbe642732d62af3b4dbc83f442
  Tags:
  - 14.8-alpine3.17
  - 14-alpine3.17
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 13/bookworm
  GitCommit: 3fda89cc5c2e588f46ae4f1ac117114c8e6814f1
  Tags:
  - "13.11"
  - "13"
  - 13.11-bookworm
  - 13-bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 13/bullseye
  GitCommit: 43d17d5ced92f230fa8c196e746f2e2aa288e5e8
  Tags:
  - 13.11-bullseye
  - 13-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 13/alpine3.18
  GitCommit: 5ea98fe00be95fbbe642732d62af3b4dbc83f442
  Tags:
  - 13.11-alpine3.18
  - 13-alpine3.18
  - 13.11-alpine
  - 13-alpine
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 13/alpine3.17
  GitCommit: 5ea98fe00be95fbbe642732d62af3b4dbc83f442
  Tags:
  - 13.11-alpine3.17
  - 13-alpine3.17
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 12/bookworm
  GitCommit: 3fda89cc5c2e588f46ae4f1ac117114c8e6814f1
  Tags:
  - "12.15"
  - "12"
  - 12.15-bookworm
  - 12-bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 12/bullseye
  GitCommit: d681c1da2faebccc790fffd3e71514548b458d50
  Tags:
  - 12.15-bullseye
  - 12-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 12/alpine3.18
  GitCommit: 5ea98fe00be95fbbe642732d62af3b4dbc83f442
  Tags:
  - 12.15-alpine3.18
  - 12-alpine3.18
  - 12.15-alpine
  - 12-alpine
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 12/alpine3.17
  GitCommit: 5ea98fe00be95fbbe642732d62af3b4dbc83f442
  Tags:
  - 12.15-alpine3.17
  - 12-alpine3.17
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 11/bookworm
  GitCommit: 3fda89cc5c2e588f46ae4f1ac117114c8e6814f1
  Tags:
  - 11.20-bookworm
  - 11-bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 11/bullseye
  GitCommit: ee629b1e31754d3aeed529a1a3610ac180f20e0b
  Tags:
  - 11.20-bullseye
  - 11-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 11/alpine3.18
  GitCommit: 5ea98fe00be95fbbe642732d62af3b4dbc83f442
  Tags:
  - 11.20-alpine3.18
  - 11-alpine3.18
  - 11.20-alpine
  - 11-alpine
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 11/alpine3.17
  GitCommit: 5ea98fe00be95fbbe642732d62af3b4dbc83f442
  Tags:
  - 11.20-alpine3.17
  - 11-alpine3.17
GitRepo: https://github.com/docker-library/postgres.git
KnownTags:
  11-alpine: {}
  11-alpine3.17: {}
  11-alpine3.18: {}
  11-bookworm: {}
  11-bullseye: {}
  11.20-alpine: {}
  11.20-alpine3.17: {}
  11.20-alpine3.18: {}
  11.20-bookworm: {}
  11.20-bullseye: {}
  "12": {}
  12-alpine: {}
  12-alpine3.17: {}
  12-alpine3.18: {}
  12-bookworm: {}
  12-bullseye: {}
  "12.15": {}
  12.15-alpine: {}
  12.15-alpine3.17: {}
  12.15-alpine3.18: {}
  12.15-bookworm: {}
  12.15-bullseye: {}
  "13": {}
  13-alpine: {}
  13-alpine3.17: {}
  13-alpine3.18: {}
  13-bookworm: {}
  13-bullseye: {}
  "13.11": {}
  13.11-alpine: {}
  13.11-alpine3.17: {}
  13.11-alpine3.18: {}
  13.11-bookworm: {}
  13.11-bullseye: {}
  "14": {}
  14-alpine: {}
  14-alpine3.17: {}
  14-alpine3.18: {}
  14-bookworm: {}
  14-bullseye: {}
  "14.8": {}
  14.8-alpine: {}
  14.8-alpine3.17: {}
  14.8-alpine3.18: {}
  14.8-bookworm: {}
  14.8-bullseye: {}
  "15": {}
  15-alpine: {}
  15-alpine3.17: {}
  15-alpine3.18: {}
  15-bookworm: {}
  15-bullseye: {}
  "15.3": {}
  15.3-alpine: {}
  15.3-alpine3.17: {}
  15.3-alpine3.18: {}
  15.3-bookworm: {}
  15.3-bullseye: {}
  16beta1: {}
  16beta1-alpine: {}
  16beta1-alpine3.17: {}
  16beta1-alpine3.18: {}
  16beta1-bookworm: {}
  16beta1-bullseye: {}
  alpine: {}
  alpine3.17: {}
  alpine3.18: {}
  bookworm: {}
  bullseye: {}
  latest: {}
Name: postgres
