Blocks:
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/latest/beta
  GitCommit: ""
  Tags:
  - beta
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/latest/beta
  GitCommit: ""
  Tags:
  - beta-java11
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/latest/beta
  GitCommit: ""
  Tags:
  - beta-java17
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/latest/kernel-slim
  GitCommit: ""
  Tags:
  - kernel-slim
  - kernel-slim-java8-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/latest/kernel-slim
  GitCommit: ""
  Tags:
  - kernel-slim-java11-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/latest/kernel-slim
  GitCommit: ""
  Tags:
  - kernel-slim-java17-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/latest/full
  GitCommit: ""
  Tags:
  - full
  - full-java8-openj9
  - latest
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/latest/full
  GitCommit: ""
  Tags:
  - full-java11-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/latest/full
  GitCommit: ""
  Tags:
  - full-java17-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/23.0.0.5/kernel-slim
  GitCommit: ""
  Tags:
  - 23.0.0.5-kernel-slim-java8-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/23.0.0.5/kernel-slim
  GitCommit: ""
  Tags:
  - 23.0.0.5-kernel-slim-java11-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/23.0.0.5/kernel-slim
  GitCommit: ""
  Tags:
  - 23.0.0.5-kernel-slim-java17-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/23.0.0.5/full
  GitCommit: ""
  Tags:
  - 23.0.0.5-full-java8-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/23.0.0.5/full
  GitCommit: ""
  Tags:
  - 23.0.0.5-full-java11-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/23.0.0.5/full
  GitCommit: ""
  Tags:
  - 23.0.0.5-full-java17-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/23.0.0.3/kernel-slim
  GitCommit: ""
  Tags:
  - 23.0.0.3-kernel-slim-java8-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/23.0.0.3/kernel-slim
  GitCommit: ""
  Tags:
  - 23.0.0.3-kernel-slim-java11-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/23.0.0.3/kernel-slim
  GitCommit: ""
  Tags:
  - 23.0.0.3-kernel-slim-java17-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/23.0.0.3/full
  GitCommit: ""
  Tags:
  - 23.0.0.3-full-java8-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/23.0.0.3/full
  GitCommit: ""
  Tags:
  - 23.0.0.3-full-java11-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/23.0.0.3/full
  GitCommit: ""
  Tags:
  - 23.0.0.3-full-java17-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/22.0.0.12/kernel-slim
  GitCommit: ""
  Tags:
  - 22.0.0.12-kernel-slim-java8-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/22.0.0.12/kernel-slim
  GitCommit: ""
  Tags:
  - 22.0.0.12-kernel-slim-java11-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/22.0.0.12/kernel-slim
  GitCommit: ""
  Tags:
  - 22.0.0.12-kernel-slim-java17-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/22.0.0.12/full
  GitCommit: ""
  Tags:
  - 22.0.0.12-full-java8-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/22.0.0.12/full
  GitCommit: ""
  Tags:
  - 22.0.0.12-full-java11-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: releases/22.0.0.12/full
  GitCommit: ""
  Tags:
  - 22.0.0.12-full-java17-openj9
GitRepo: https://github.com/OpenLiberty/ci.docker.git
KnownTags:
  22.0.0.12-full-java8-openj9: {}
  22.0.0.12-full-java11-openj9: {}
  22.0.0.12-full-java17-openj9: {}
  22.0.0.12-kernel-slim-java8-openj9: {}
  22.0.0.12-kernel-slim-java11-openj9: {}
  22.0.0.12-kernel-slim-java17-openj9: {}
  23.0.0.3-full-java8-openj9: {}
  23.0.0.3-full-java11-openj9: {}
  23.0.0.3-full-java17-openj9: {}
  23.0.0.3-kernel-slim-java8-openj9: {}
  23.0.0.3-kernel-slim-java11-openj9: {}
  23.0.0.3-kernel-slim-java17-openj9: {}
  23.0.0.5-full-java8-openj9: {}
  23.0.0.5-full-java11-openj9: {}
  23.0.0.5-full-java17-openj9: {}
  23.0.0.5-kernel-slim-java8-openj9: {}
  23.0.0.5-kernel-slim-java11-openj9: {}
  23.0.0.5-kernel-slim-java17-openj9: {}
  beta: {}
  beta-java11: {}
  beta-java17: {}
  full: {}
  full-java8-openj9: {}
  full-java11-openj9: {}
  full-java17-openj9: {}
  kernel-slim: {}
  kernel-slim-java8-openj9: {}
  kernel-slim-java11-openj9: {}
  kernel-slim-java17-openj9: {}
  latest: {}
Name: open-liberty
