Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: 15/mysql-tomcat
  GitCommit: e573aa8c0988c3c176848489c449e69d6d4564fa
  Tags:
  - "15"
  - "15.4"
  - 15.4.0
  - 15-mysql-tomcat
  - 15.4-mysql-tomcat
  - 15.4.0-mysql-tomcat
  - mysql-tomcat
  - stable-mysql-tomcat
  - stable-mysql
  - stable
  - latest
- Architectures:
  - amd64
  - arm64v8
  Directory: 15/postgres-tomcat
  GitCommit: e573aa8c0988c3c176848489c449e69d6d4564fa
  Tags:
  - 15-postgres-tomcat
  - 15.4-postgres-tomcat
  - 15.4.0-postgres-tomcat
  - postgres-tomcat
  - stable-postgres-tomcat
  - stable-postgres
- Architectures:
  - amd64
  - arm64v8
  Directory: 15/mariadb-tomcat
  GitCommit: e573aa8c0988c3c176848489c449e69d6d4564fa
  Tags:
  - 15-mariadb-tomcat
  - 15.4-mariadb-tomcat
  - 15.4.0-mariadb-tomcat
  - mariadb-tomcat
  - stable-mariadb-tomcat
  - stable-mariadb
- Architectures:
  - amd64
  - arm64v8
  Directory: 14/mysql-tomcat
  GitCommit: bedad6921006df1867cf3a87d3939176400c86f5
  Tags:
  - "14"
  - "14.10"
  - 14.10.13
  - 14-mysql-tomcat
  - 14.10-mysql-tomcat
  - 14.10.13-mysql-tomcat
  - lts-mysql-tomcat
  - lts-mysql
  - lts
- Architectures:
  - amd64
  - arm64v8
  Directory: 14/postgres-tomcat
  GitCommit: bedad6921006df1867cf3a87d3939176400c86f5
  Tags:
  - 14-postgres-tomcat
  - 14.10-postgres-tomcat
  - 14.10.13-postgres-tomcat
  - lts-postgres-tomcat
  - lts-postgres
- Architectures:
  - amd64
  - arm64v8
  Directory: 14/mariadb-tomcat
  GitCommit: bedad6921006df1867cf3a87d3939176400c86f5
  Tags:
  - 14-mariadb-tomcat
  - 14.10-mariadb-tomcat
  - 14.10.13-mariadb-tomcat
  - lts-mariadb-tomcat
  - lts-mariadb
GitRepo: https://github.com/xwiki-contrib/docker-xwiki.git
KnownTags:
  "14": {}
  14-mariadb-tomcat: {}
  14-mysql-tomcat: {}
  14-postgres-tomcat: {}
  "14.10": {}
  14.10-mariadb-tomcat: {}
  14.10-mysql-tomcat: {}
  14.10-postgres-tomcat: {}
  14.10.13: {}
  14.10.13-mariadb-tomcat: {}
  14.10.13-mysql-tomcat: {}
  14.10.13-postgres-tomcat: {}
  "15": {}
  15-mariadb-tomcat: {}
  15-mysql-tomcat: {}
  15-postgres-tomcat: {}
  "15.4": {}
  15.4-mariadb-tomcat: {}
  15.4-mysql-tomcat: {}
  15.4-postgres-tomcat: {}
  15.4.0: {}
  15.4.0-mariadb-tomcat: {}
  15.4.0-mysql-tomcat: {}
  15.4.0-postgres-tomcat: {}
  latest: {}
  lts: {}
  lts-mariadb: {}
  lts-mariadb-tomcat: {}
  lts-mysql: {}
  lts-mysql-tomcat: {}
  lts-postgres: {}
  lts-postgres-tomcat: {}
  mariadb-tomcat: {}
  mysql-tomcat: {}
  postgres-tomcat: {}
  stable: {}
  stable-mariadb: {}
  stable-mariadb-tomcat: {}
  stable-mysql: {}
  stable-mysql-tomcat: {}
  stable-postgres: {}
  stable-postgres-tomcat: {}
Name: xwiki
