Blocks:
- Architectures:
  - amd64
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 2.8.2
  - "2.8"
  - "2"
  - latest
GitRepo: https://github.com/docker/distribution-library-image.git
KnownTags:
  "2": {}
  "2.8": {}
  2.8.2: {}
  latest: {}
Name: registry
