Blocks:
- Architectures:
  - amd64
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 2.8.2
  - "2.8"
  - "2"
  - latest
- Architectures:
  - amd64
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 2.8.1
- Architectures:
  - amd64
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 2.8.2-beta.2
- Architectures:
  - amd64
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: 5fd2614beccba35242694b13f8a37653c05ea852
  Tags:
  - 2.8.0
- Architectures:
  - amd64
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: c70c2acb365928f10bfc7706cc0f3f4d16f7427b
  Tags:
  - 2.8.0-beta.1
- Architectures:
  - amd64
  - arm64v8
  - arm32v6
  Directory: ""
  GitCommit: ab00e8dae12d4515ed259015eab771ec92e92dd4
  Tags:
  - 2.7.1
  - "2.7"
- Architectures:
  - amd64
  - arm64v8
  - arm32v6
  Directory: ""
  GitCommit: fc40f1f1051bb4a42ee4661ccaa190c1bd6c6be9
  Tags:
  - 2.6.2
  - "2.6"
- Architectures: null
  Directory: ""
  GitCommit: f96d9029112d8da459312fb8249802bc4ec6ac21
  Tags:
  - 2.5.2
  - "2.5"
- Architectures:
  - amd64
  - arm64v8
  - arm32v6
  Directory: ""
  GitCommit: 8f5dd752a05240b275d46e7fe527959d10004e93
  Tags:
  - 2.7.0
GitRepo: https://github.com/docker/distribution-library-image.git
KnownTags:
  "2": {}
  "2.5": {}
  2.5.2: {}
  "2.6": {}
  2.6.2: {}
  "2.7": {}
  2.7.0: {}
  2.7.1: {}
  "2.8": {}
  2.8.0: {}
  2.8.0-beta.1: {}
  2.8.1: {}
  2.8.2: {}
  2.8.2-beta.2: {}
  latest: {}
Name: registry
