Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: f0eccac1ed27a05031c515591d3c9f29502efb27
  Tags:
  - 3.3.13-apache
  - 3.3-apache
  - 3-apache
  - apache
  - 3.3.13
  - "3.3"
  - "3"
  - latest
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: f0eccac1ed27a05031c515591d3c9f29502efb27
  Tags:
  - 3.3.13-fpm
  - 3.3-fpm
  - 3-fpm
  - fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 5030ec70f6a0dec12e39f5194fb29575b169f7b7
  Tags:
  - 3.3.13-fpm-alpine
  - 3.3-fpm-alpine
  - 3-fpm-alpine
  - fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 0f56039e5e2090c4383d595249c707cf5024cbb6
  Tags:
  - 3.3.12-apache
  - 3.3.12
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 0f56039e5e2090c4383d595249c707cf5024cbb6
  Tags:
  - 3.3.12-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 0f56039e5e2090c4383d595249c707cf5024cbb6
  Tags:
  - 3.3.12-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: d6a00844d6ddc441062dc4caf7e77de2b24bf8cc
  Tags:
  - 3.3.11-apache
  - 3.3.11
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: d6a00844d6ddc441062dc4caf7e77de2b24bf8cc
  Tags:
  - 3.3.11-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: d6a00844d6ddc441062dc4caf7e77de2b24bf8cc
  Tags:
  - 3.3.11-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: ea14b3035ab978ed104ca76e8ded6a8c438da3d0
  Tags:
  - 3.3.10-apache
  - 3.3.10
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: ea14b3035ab978ed104ca76e8ded6a8c438da3d0
  Tags:
  - 3.3.10-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: ea14b3035ab978ed104ca76e8ded6a8c438da3d0
  Tags:
  - 3.3.10-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 1b677083c85185c721ada312307150ac242e6103
  Tags:
  - 3.3.9-apache
  - 3.3.9
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 1b677083c85185c721ada312307150ac242e6103
  Tags:
  - 3.3.9-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 1b677083c85185c721ada312307150ac242e6103
  Tags:
  - 3.3.9-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: e58854f733ebb82e43bb0289278ed746753210b5
  Tags:
  - 3.3.7-apache
  - 3.3.7
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: e58854f733ebb82e43bb0289278ed746753210b5
  Tags:
  - 3.3.7-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: e58854f733ebb82e43bb0289278ed746753210b5
  Tags:
  - 3.3.7-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 1bf306d0747aec808a39fce09d4151bc643b770a
  Tags:
  - 3.3.6-apache
  - 3.3.6
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 1bf306d0747aec808a39fce09d4151bc643b770a
  Tags:
  - 3.3.6-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 1bf306d0747aec808a39fce09d4151bc643b770a
  Tags:
  - 3.3.6-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 8c28d073b877e5f88e72fdfee5432cecefec45d3
  Tags:
  - 3.3.5-apache
  - 3.3.5
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 8c28d073b877e5f88e72fdfee5432cecefec45d3
  Tags:
  - 3.3.5-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 8c28d073b877e5f88e72fdfee5432cecefec45d3
  Tags:
  - 3.3.5-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: b27e42dc1637d6c3b853582f407c3dea9e0f20a8
  Tags:
  - 3.3.4-apache
  - 3.3.4
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: b27e42dc1637d6c3b853582f407c3dea9e0f20a8
  Tags:
  - 3.3.4-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: b27e42dc1637d6c3b853582f407c3dea9e0f20a8
  Tags:
  - 3.3.4-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 9cb5f9d1db379c781d16cb6d0ca5ba933bfb10d3
  Tags:
  - 3.3.3-apache
  - 3.3.3
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 9cb5f9d1db379c781d16cb6d0ca5ba933bfb10d3
  Tags:
  - 3.3.3-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 9cb5f9d1db379c781d16cb6d0ca5ba933bfb10d3
  Tags:
  - 3.3.3-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 55fca287e605b3868b677351eda6dfee9fb3a453
  Tags:
  - 3.2.4-apache
  - 3.2-apache
  - 3.2.4
  - "3.2"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 55fca287e605b3868b677351eda6dfee9fb3a453
  Tags:
  - 3.2.4-fpm
  - 3.2-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 55fca287e605b3868b677351eda6dfee9fb3a453
  Tags:
  - 3.2.4-fpm-alpine
  - 3.2-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: apache
  GitCommit: 9419925a74a082b25bfd6db8a568ed7027b50700
  Tags:
  - 3.2.3-apache
  - 3.2.3
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: fpm
  GitCommit: 9419925a74a082b25bfd6db8a568ed7027b50700
  Tags:
  - 3.2.3-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: fpm-alpine
  GitCommit: 9419925a74a082b25bfd6db8a568ed7027b50700
  Tags:
  - 3.2.3-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: apache
  GitCommit: a70ae86e94eb4631515edd0f79df40fb9c756a4e
  Tags:
  - 3.2.2-apache
  - 3.2.2
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: fpm
  GitCommit: a70ae86e94eb4631515edd0f79df40fb9c756a4e
  Tags:
  - 3.2.2-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: fpm-alpine
  GitCommit: a70ae86e94eb4631515edd0f79df40fb9c756a4e
  Tags:
  - 3.2.2-fpm-alpine
- Architectures: null
  Directory: apache
  GitCommit: be5185a228ec41d989461cac11a7521c3eec2f55
  Tags:
  - "3.1"
GitRepo: https://github.com/postfixadmin/docker.git
KnownTags:
  "3": {}
  3-apache: {}
  3-fpm: {}
  3-fpm-alpine: {}
  "3.1": {}
  "3.2": {}
  3.2-apache: {}
  3.2-fpm: {}
  3.2-fpm-alpine: {}
  3.2.2: {}
  3.2.2-apache: {}
  3.2.2-fpm: {}
  3.2.2-fpm-alpine: {}
  3.2.3: {}
  3.2.3-apache: {}
  3.2.3-fpm: {}
  3.2.3-fpm-alpine: {}
  3.2.4: {}
  3.2.4-apache: {}
  3.2.4-fpm: {}
  3.2.4-fpm-alpine: {}
  "3.3": {}
  3.3-apache: {}
  3.3-fpm: {}
  3.3-fpm-alpine: {}
  3.3.3: {}
  3.3.3-apache: {}
  3.3.3-fpm: {}
  3.3.3-fpm-alpine: {}
  3.3.4: {}
  3.3.4-apache: {}
  3.3.4-fpm: {}
  3.3.4-fpm-alpine: {}
  3.3.5: {}
  3.3.5-apache: {}
  3.3.5-fpm: {}
  3.3.5-fpm-alpine: {}
  3.3.6: {}
  3.3.6-apache: {}
  3.3.6-fpm: {}
  3.3.6-fpm-alpine: {}
  3.3.7: {}
  3.3.7-apache: {}
  3.3.7-fpm: {}
  3.3.7-fpm-alpine: {}
  3.3.9: {}
  3.3.9-apache: {}
  3.3.9-fpm: {}
  3.3.9-fpm-alpine: {}
  3.3.10: {}
  3.3.10-apache: {}
  3.3.10-fpm: {}
  3.3.10-fpm-alpine: {}
  3.3.11: {}
  3.3.11-apache: {}
  3.3.11-fpm: {}
  3.3.11-fpm-alpine: {}
  3.3.12: {}
  3.3.12-apache: {}
  3.3.12-fpm: {}
  3.3.12-fpm-alpine: {}
  3.3.13: {}
  3.3.13-apache: {}
  3.3.13-fpm: {}
  3.3.13-fpm-alpine: {}
  apache: {}
  fpm: {}
  fpm-alpine: {}
  latest: {}
Name: postfixadmin
