Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: b4307d956cb1cfe64df1402cf6d68a1369ba56de
  Tags:
  - 3.3.13-apache
  - 3.3-apache
  - 3-apache
  - apache
  - 3.3.13
  - "3.3"
  - "3"
  - latest
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: b4307d956cb1cfe64df1402cf6d68a1369ba56de
  Tags:
  - 3.3.13-fpm
  - 3.3-fpm
  - 3-fpm
  - fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 5030ec70f6a0dec12e39f5194fb29575b169f7b7
  Tags:
  - 3.3.13-fpm-alpine
  - 3.3-fpm-alpine
  - 3-fpm-alpine
  - fpm-alpine
GitRepo: https://github.com/postfixadmin/docker.git
KnownTags:
  "3": {}
  3-apache: {}
  3-fpm: {}
  3-fpm-alpine: {}
  "3.3": {}
  3.3-apache: {}
  3.3-fpm: {}
  3.3-fpm-alpine: {}
  3.3.13: {}
  3.3.13-apache: {}
  3.3.13-fpm: {}
  3.3.13-fpm-alpine: {}
  apache: {}
  fpm: {}
  fpm-alpine: {}
  latest: {}
Name: postfixadmin
