Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  Directory: jdk8
  GitCommit: f28c433c77a244169b44cab3e2617a666dca845f
  Tags:
  - 4.0.12-jdk8
  - 4.0-jdk8
  - jdk8
  - 4.0.12-jdk8-jammy
  - 4.0-jdk8-jammy
  - jdk8-jammy
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: jdk11
  GitCommit: f28c433c77a244169b44cab3e2617a666dca845f
  Tags:
  - 4.0.12-jdk11
  - 4.0-jdk11
  - jdk11
  - 4.0.12-jdk11-jammy
  - 4.0-jdk11-jammy
  - jdk11-jammy
- Architectures:
  - amd64
  Directory: jdk11-alpine
  GitCommit: f28c433c77a244169b44cab3e2617a666dca845f
  Tags:
  - 4.0.12-jdk11-alpine
  - 4.0-jdk11-alpine
  - jdk11-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: jdk17
  GitCommit: f28c433c77a244169b44cab3e2617a666dca845f
  Tags:
  - 4.0.12-jdk17
  - 4.0-jdk17
  - jdk17
  - 4.0.12-jdk
  - 4.0-jdk
  - 4.0.12
  - "4.0"
  - "4"
  - jdk
  - latest
  - 4.0.12-jdk17-jammy
  - 4.0-jdk17-jammy
  - jdk17-jammy
  - 4.0.12-jdk-jammy
  - 4.0-jdk-jammy
  - 4.0.12-jammy
  - 4.0-jammy
  - 4-jammy
  - jdk-jammy
  - jammy
- Architectures:
  - amd64
  Directory: jdk17-alpine
  GitCommit: f28c433c77a244169b44cab3e2617a666dca845f
  Tags:
  - 4.0.12-jdk17-alpine
  - 4.0-jdk17-alpine
  - jdk17-alpine
  - 4.0.12-jdk-alpine
  - 4.0-jdk-alpine
  - 4.0.12-alpine
  - 4.0-alpine
  - 4-alpine
  - jdk-alpine
  - alpine
GitRepo: https://github.com/groovy/docker-groovy.git
KnownTags:
  "4": {}
  4-alpine: {}
  4-jammy: {}
  "4.0": {}
  4.0-alpine: {}
  4.0-jammy: {}
  4.0-jdk: {}
  4.0-jdk-alpine: {}
  4.0-jdk-jammy: {}
  4.0-jdk8: {}
  4.0-jdk8-jammy: {}
  4.0-jdk11: {}
  4.0-jdk11-alpine: {}
  4.0-jdk11-jammy: {}
  4.0-jdk17: {}
  4.0-jdk17-alpine: {}
  4.0-jdk17-jammy: {}
  4.0.12: {}
  4.0.12-alpine: {}
  4.0.12-jammy: {}
  4.0.12-jdk: {}
  4.0.12-jdk-alpine: {}
  4.0.12-jdk-jammy: {}
  4.0.12-jdk8: {}
  4.0.12-jdk8-jammy: {}
  4.0.12-jdk11: {}
  4.0.12-jdk11-alpine: {}
  4.0.12-jdk11-jammy: {}
  4.0.12-jdk17: {}
  4.0.12-jdk17-alpine: {}
  4.0.12-jdk17-jammy: {}
  alpine: {}
  jammy: {}
  jdk: {}
  jdk-alpine: {}
  jdk-jammy: {}
  jdk8: {}
  jdk8-jammy: {}
  jdk11: {}
  jdk11-alpine: {}
  jdk11-jammy: {}
  jdk17: {}
  jdk17-alpine: {}
  jdk17-jammy: {}
  latest: {}
Name: groovy
