Blocks:
- Architectures: null
  Directory: alpine3.11
  GitCommit: cd07d76987097b5389aa9be5f48df041aa74d699
  Tags:
  - 1.4.4-alpine3.11
  - 1.4-alpine3.11
  - 1-alpine3.11
  - latest
GitRepo: https://github.com/dshearer/jobber-docker.git
KnownTags:
  1-alpine3.11: {}
  1.4-alpine3.11: {}
  1.4.4-alpine3.11: {}
  latest: {}
Name: jobber
