Blocks:
- Architectures: null
  Directory: alpine3.11
  GitCommit: cd07d76987097b5389aa9be5f48df041aa74d699
  Tags:
  - 1.4.4-alpine3.11
  - 1.4-alpine3.11
  - 1-alpine3.11
  - latest
- Architectures: null
  Directory: alpine3.11
  GitCommit: f7b276c7e49184667f6fc7323e15735c3a08c1d2
  Tags:
  - 1.4.3-alpine3.11
- Architectures: null
  Directory: alpine3.10
  GitCommit: 64d2a0778ae73986cb90f1c374d9dfb42c9b8483
  Tags:
  - 1.4.0-alpine3.10
  - 1.4-alpine3.10
  - 1-alpine3.10
- Architectures: null
  Directory: alpine3.7
  GitCommit: 9afae73c3a114f2595468212b60309d9b0cf7fe3
  Tags:
  - 1.3.3-alpine3.7
  - 1.3-alpine3.7
  - 1-alpine3.7
- Architectures: null
  Directory: alpine3.7
  GitCommit: a46d8d7aa4f359a5a27a9ca7a7dbf7d1d3d71d38
  Tags:
  - 1.3.2-alpine3.7
- Architectures: null
  Directory: 1.3/alpine3.7
  GitCommit: 9f8d7477936b6693271f284c026a7b5e53d73684
  Tags:
  - 1.3.1-alpine3.7
GitRepo: https://github.com/dshearer/jobber-docker.git
KnownTags:
  1-alpine3.7: {}
  1-alpine3.10: {}
  1-alpine3.11: {}
  1.3-alpine3.7: {}
  1.3.1-alpine3.7: {}
  1.3.2-alpine3.7: {}
  1.3.3-alpine3.7: {}
  1.4-alpine3.10: {}
  1.4-alpine3.11: {}
  1.4.0-alpine3.10: {}
  1.4.3-alpine3.11: {}
  1.4.4-alpine3.11: {}
  latest: {}
Name: jobber
