Blocks:
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: "11.1"
  GitCommit: e56b3a008e9c47c7199d28db6d77d2cfecde526d
  Tags:
  - 11.1.1-rc-jammy
  - 11.1-rc-jammy
  - 11.1.1-rc
  - 11.1-rc
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: "11.0"
  GitCommit: e56b3a008e9c47c7199d28db6d77d2cfecde526d
  Tags:
  - 11.0.2-jammy
  - 11.0-jammy
  - 11-jammy
  - jammy
  - 11.0.2
  - "11.0"
  - "11"
  - latest
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: "10.11"
  GitCommit: e56b3a008e9c47c7199d28db6d77d2cfecde526d
  Tags:
  - 10.11.4-jammy
  - 10.11-jammy
  - 10-jammy
  - lts-jammy
  - 10.11.4
  - "10.11"
  - "10"
  - lts
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: "10.10"
  GitCommit: e56b3a008e9c47c7199d28db6d77d2cfecde526d
  Tags:
  - 10.10.5-jammy
  - 10.10-jammy
  - 10.10.5
  - "10.10"
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: "10.9"
  GitCommit: e56b3a008e9c47c7199d28db6d77d2cfecde526d
  Tags:
  - 10.9.7-jammy
  - 10.9-jammy
  - 10.9.7
  - "10.9"
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: "10.6"
  GitCommit: e56b3a008e9c47c7199d28db6d77d2cfecde526d
  Tags:
  - 10.6.14-focal
  - 10.6-focal
  - 10.6.14
  - "10.6"
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: "10.5"
  GitCommit: e56b3a008e9c47c7199d28db6d77d2cfecde526d
  Tags:
  - 10.5.21-focal
  - 10.5-focal
  - 10.5.21
  - "10.5"
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: "10.4"
  GitCommit: e56b3a008e9c47c7199d28db6d77d2cfecde526d
  Tags:
  - 10.4.30-focal
  - 10.4-focal
  - 10.4.30
  - "10.4"
GitRepo: https://github.com/MariaDB/mariadb-docker.git
KnownTags:
  "10": {}
  10-jammy: {}
  "10.4": {}
  10.4-focal: {}
  10.4.30: {}
  10.4.30-focal: {}
  "10.5": {}
  10.5-focal: {}
  10.5.21: {}
  10.5.21-focal: {}
  "10.6": {}
  10.6-focal: {}
  10.6.14: {}
  10.6.14-focal: {}
  "10.9": {}
  10.9-jammy: {}
  10.9.7: {}
  10.9.7-jammy: {}
  "10.10": {}
  10.10-jammy: {}
  10.10.5: {}
  10.10.5-jammy: {}
  "10.11": {}
  10.11-jammy: {}
  10.11.4: {}
  10.11.4-jammy: {}
  "11": {}
  11-jammy: {}
  "11.0": {}
  11.0-jammy: {}
  11.0.2: {}
  11.0.2-jammy: {}
  11.1-rc: {}
  11.1-rc-jammy: {}
  11.1.1-rc: {}
  11.1.1-rc-jammy: {}
  jammy: {}
  latest: {}
  lts: {}
  lts-jammy: {}
Name: mariadb
