Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: 5.9.0/community
  GitCommit: 9d7a9047bb1b1b736c01e50bf5d38c0a4d3d1697
  Tags:
  - 5.9.0
  - 5.9.0-community
  - "5.9"
  - 5.9-community
  - "5"
  - 5-community
  - community
  - latest
- Architectures:
  - amd64
  - arm64v8
  Directory: 5.9.0/enterprise
  GitCommit: 9d7a9047bb1b1b736c01e50bf5d38c0a4d3d1697
  Tags:
  - 5.9.0-enterprise
  - 5.9-enterprise
  - 5-enterprise
  - enterprise
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.4.21/community
  GitCommit: 9dea28f9da8f5792752853a1be16309950d03204
  Tags:
  - 4.4.21
  - 4.4.21-community
  - "4.4"
  - 4.4-community
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.4.21/enterprise
  GitCommit: 9dea28f9da8f5792752853a1be16309950d03204
  Tags:
  - 4.4.21-enterprise
  - 4.4-enterprise
GitRepo: https://github.com/neo4j/docker-neo4j-publish.git
KnownTags:
  "4.4": {}
  4.4-community: {}
  4.4-enterprise: {}
  4.4.21: {}
  4.4.21-community: {}
  4.4.21-enterprise: {}
  "5": {}
  5-community: {}
  5-enterprise: {}
  "5.9": {}
  5.9-community: {}
  5.9-enterprise: {}
  5.9.0: {}
  5.9.0-community: {}
  5.9.0-enterprise: {}
  community: {}
  enterprise: {}
  latest: {}
Name: neo4j
