Blocks:
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  Directory: 0.25.5/alpine3.18
  GitCommit: ""
  Tags:
  - 0.25.5-alpine3.18
  - 0.25-alpine3.18
  - alpine3.18
  - 0.25.5-alpine
  - 0.25-alpine
  - alpine
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  Directory: 0.25.5/scratch
  GitCommit: ""
  Tags:
  - 0.25.5-scratch
  - 0.25-scratch
  - scratch
  - 0.25.5-linux
  - 0.25-linux
  - linux
- Architectures:
  - windows-amd64
  Directory: 0.25.5/windowsservercore-1809
  GitCommit: ""
  Tags:
  - 0.25.5-windowsservercore-1809
  - 0.25-windowsservercore-1809
  - windowsservercore-1809
- Architectures:
  - windows-amd64
  Directory: 0.25.5/nanoserver-1809
  GitCommit: ""
  Tags:
  - 0.25.5-nanoserver-1809
  - 0.25-nanoserver-1809
  - nanoserver-1809
GitRepo: https://github.com/nats-io/nats-streaming-docker.git
KnownTags:
  0.25-alpine: {}
  0.25-alpine3.18: {}
  0.25-linux: {}
  0.25-nanoserver-1809: {}
  0.25-scratch: {}
  0.25-windowsservercore-1809: {}
  0.25.5-alpine: {}
  0.25.5-alpine3.18: {}
  0.25.5-linux: {}
  0.25.5-nanoserver-1809: {}
  0.25.5-scratch: {}
  0.25.5-windowsservercore-1809: {}
  alpine: {}
  alpine3.18: {}
  linux: {}
  nanoserver-1809: {}
  scratch: {}
  windowsservercore-1809: {}
Name: nats-streaming
