Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: kapacitor/1.5
  GitCommit: ""
  Tags:
  - "1.5"
  - 1.5.9
- Architectures: null
  Directory: kapacitor/1.5/alpine
  GitCommit: ""
  Tags:
  - 1.5-alpine
  - 1.5.9-alpine
- Architectures:
  - amd64
  - arm64v8
  Directory: kapacitor/1.6
  GitCommit: ""
  Tags:
  - "1.6"
  - 1.6.6
  - latest
- Architectures: null
  Directory: kapacitor/1.6/alpine
  GitCommit: ""
  Tags:
  - 1.6-alpine
  - 1.6.6-alpine
  - alpine
- Architectures:
  - amd64
  - arm64v8
  Directory: kapacitor/1.6
  GitCommit: ""
  Tags:
  - 1.6.5
- Architectures: null
  Directory: kapacitor/1.6/alpine
  GitCommit: ""
  Tags:
  - 1.6.5-alpine
- Architectures:
  - amd64
  - arm64v8
  Directory: kapacitor/1.6
  GitCommit: ""
  Tags:
  - 1.6.4
- Architectures: null
  Directory: kapacitor/1.6/alpine
  GitCommit: ""
  Tags:
  - 1.6.4-alpine
- Architectures:
  - amd64
  - arm64v8
  Directory: kapacitor/1.6
  GitCommit: ""
  Tags:
  - 1.6.3
- Architectures: null
  Directory: kapacitor/1.6/alpine
  GitCommit: ""
  Tags:
  - 1.6.3-alpine
- Architectures:
  - amd64
  - arm64v8
  Directory: kapacitor/1.6
  GitCommit: ""
  Tags:
  - 1.6.2
- Architectures: null
  Directory: kapacitor/1.6/alpine
  GitCommit: ""
  Tags:
  - 1.6.2-alpine
- Architectures:
  - amd64
  - arm64v8
  Directory: kapacitor/1.6
  GitCommit: ""
  Tags:
  - 1.6.1
- Architectures: null
  Directory: kapacitor/1.6/alpine
  GitCommit: ""
  Tags:
  - 1.6.1-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: kapacitor/1.4
  GitCommit: ""
  Tags:
  - "1.4"
  - 1.4.1
- Architectures: null
  Directory: kapacitor/1.4/alpine
  GitCommit: ""
  Tags:
  - 1.4-alpine
  - 1.4.1-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: kapacitor/1.5
  GitCommit: ""
  Tags:
  - 1.5.8
- Architectures: null
  Directory: kapacitor/1.5/alpine
  GitCommit: ""
  Tags:
  - 1.5.8-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: kapacitor/1.5
  GitCommit: ""
  Tags:
  - 1.5.7
- Architectures: null
  Directory: kapacitor/1.5/alpine
  GitCommit: ""
  Tags:
  - 1.5.7-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: kapacitor/1.5
  GitCommit: ""
  Tags:
  - 1.5.6
- Architectures: null
  Directory: kapacitor/1.5/alpine
  GitCommit: ""
  Tags:
  - 1.5.6-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: kapacitor/1.5
  GitCommit: ""
  Tags:
  - 1.5.5
- Architectures: null
  Directory: kapacitor/1.5/alpine
  GitCommit: ""
  Tags:
  - 1.5.5-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: kapacitor/1.5
  GitCommit: ""
  Tags:
  - 1.5.4
- Architectures: null
  Directory: kapacitor/1.5/alpine
  GitCommit: ""
  Tags:
  - 1.5.4-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: kapacitor/1.5
  GitCommit: ""
  Tags:
  - 1.5.3
- Architectures: null
  Directory: kapacitor/1.5/alpine
  GitCommit: ""
  Tags:
  - 1.5.3-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: kapacitor/1.5
  GitCommit: ""
  Tags:
  - 1.5.2
- Architectures: null
  Directory: kapacitor/1.5/alpine
  GitCommit: ""
  Tags:
  - 1.5.2-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: kapacitor/1.5
  GitCommit: ""
  Tags:
  - 1.5.1
- Architectures: null
  Directory: kapacitor/1.5/alpine
  GitCommit: ""
  Tags:
  - 1.5.1-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: kapacitor/1.5
  GitCommit: ""
  Tags:
  - 1.5.0
- Architectures: null
  Directory: kapacitor/1.5/alpine
  GitCommit: ""
  Tags:
  - 1.5.0-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: kapacitor/1.3
  GitCommit: ""
  Tags:
  - "1.3"
  - 1.3.3
- Architectures: null
  Directory: kapacitor/1.3/alpine
  GitCommit: ""
  Tags:
  - 1.3-alpine
  - 1.3.3-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: kapacitor/1.4
  GitCommit: ""
  Tags:
  - 1.4.0
- Architectures: null
  Directory: kapacitor/1.4/alpine
  GitCommit: ""
  Tags:
  - 1.4.0-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: kapacitor/1.2
  GitCommit: 74b2e90cd794ba5cba219d34876ca6425b069970
  Tags:
  - "1.2"
  - 1.2.1
- Architectures: null
  Directory: kapacitor/1.2/alpine
  GitCommit: 74b2e90cd794ba5cba219d34876ca6425b069970
  Tags:
  - 1.2-alpine
  - 1.2.1-alpine
- Architectures: null
  Directory: kapacitor/1.3
  GitCommit: 50b7868985aa3ecc9484802a1b9c3f4d289f49b7
  Tags:
  - 1.3.2
- Architectures: null
  Directory: kapacitor/1.3/alpine
  GitCommit: 50b7868985aa3ecc9484802a1b9c3f4d289f49b7
  Tags:
  - 1.3.2-alpine
- Architectures: null
  Directory: kapacitor/1.3
  GitCommit: 32861831b4b02f5d7ea1b58dea6cefc6ca192a75
  Tags:
  - 1.3.1
- Architectures: null
  Directory: kapacitor/1.3/alpine
  GitCommit: 6ac578811109d3eefb8535c82949307c7f1bb4c6
  Tags:
  - 1.3.1-alpine
- Architectures: null
  Directory: kapacitor/1.3
  GitCommit: 6359ccc62dbcd59f128b6abef74fd637ab103146
  Tags:
  - 1.3.0
- Architectures: null
  Directory: kapacitor/1.3/alpine
  GitCommit: 6359ccc62dbcd59f128b6abef74fd637ab103146
  Tags:
  - 1.3.0-alpine
- Architectures: null
  Directory: kapacitor/1.1
  GitCommit: 3a8019600cefcb4ffc85c3e3a155980d2dc3f5ff
  Tags:
  - "1.1"
  - 1.1.1
- Architectures: null
  Directory: kapacitor/1.1/alpine
  GitCommit: 3a8019600cefcb4ffc85c3e3a155980d2dc3f5ff
  Tags:
  - 1.1-alpine
  - 1.1.1-alpine
- Architectures: null
  Directory: kapacitor/1.2
  GitCommit: d3babf9a87cb217d99aeabcea369c917b81121e1
  Tags:
  - 1.2.0
- Architectures: null
  Directory: kapacitor/1.2/alpine
  GitCommit: d3babf9a87cb217d99aeabcea369c917b81121e1
  Tags:
  - 1.2.0-alpine
- Architectures: null
  Directory: kapacitor/1.0
  GitCommit: dec27fb32f5d9696cd0627f3ac97d353f7557b31
  Tags:
  - "1.0"
  - 1.0.2
- Architectures: null
  Directory: kapacitor/1.0/alpine
  GitCommit: dec27fb32f5d9696cd0627f3ac97d353f7557b31
  Tags:
  - 1.0-alpine
  - 1.0.2-alpine
- Architectures: null
  Directory: kapacitor/1.2
  GitCommit: ceb9e81abf0b7707d5184ffdf4c228ee33cda178
  Tags:
  - 1.2.0-rc1
- Architectures: null
  Directory: kapacitor/1.2/alpine
  GitCommit: ceb9e81abf0b7707d5184ffdf4c228ee33cda178
  Tags:
  - 1.2.0-rc1-alpine
- Architectures: null
  Directory: kapacitor/1.1
  GitCommit: 5bfae0d45f25aa52a2bfd2ebcc7f1af52dad90ae
  Tags:
  - 1.1.0
- Architectures: null
  Directory: kapacitor/1.1/alpine
  GitCommit: 5bfae0d45f25aa52a2bfd2ebcc7f1af52dad90ae
  Tags:
  - 1.1.0-alpine
- Architectures: null
  Directory: kapacitor/0.13
  GitCommit: ec08f02c8a4a15bcea2a6c46517eceb9284633a2
  Tags:
  - "0.13"
  - 0.13.1
- Architectures: null
  Directory: kapacitor/0.13/alpine
  GitCommit: ec08f02c8a4a15bcea2a6c46517eceb9284633a2
  Tags:
  - 0.13-alpine
  - 0.13.1-alpine
- Architectures: null
  Directory: kapacitor/1.1
  GitCommit: 16886a77b6f592184033965d5326720119e00bd3
  Tags:
  - 1.1.0-rc2
- Architectures: null
  Directory: kapacitor/1.1/alpine
  GitCommit: 16886a77b6f592184033965d5326720119e00bd3
  Tags:
  - 1.1.0-rc2-alpine
- Architectures: null
  Directory: kapacitor/1.1
  GitCommit: 6328eaddffcb11337d779694c38b4cb228184e5f
  Tags:
  - 1.1.0-rc1
- Architectures: null
  Directory: kapacitor/1.1/alpine
  GitCommit: 6328eaddffcb11337d779694c38b4cb228184e5f
  Tags:
  - 1.1.0-rc1-alpine
- Architectures: null
  Directory: kapacitor/1.0
  GitCommit: d2fb0a4ddcc93a8387aa313a43ff78b0964a379f
  Tags:
  - 1.0.1
- Architectures: null
  Directory: kapacitor/1.0/alpine
  GitCommit: d2fb0a4ddcc93a8387aa313a43ff78b0964a379f
  Tags:
  - 1.0.1-alpine
- Architectures: null
  Directory: kapacitor/1.0
  GitCommit: ec08f02c8a4a15bcea2a6c46517eceb9284633a2
  Tags:
  - 1.0.0
- Architectures: null
  Directory: kapacitor/1.0/alpine
  GitCommit: ec08f02c8a4a15bcea2a6c46517eceb9284633a2
  Tags:
  - 1.0.0-alpine
- Architectures: null
  Directory: "0.12"
  GitCommit: bbfea78a0a43bd4c6d67e139afb518bac3aa424b
  Tags:
  - "0.12"
  - 0.12.0
- Architectures: null
  Directory: kapacitor/1.0
  GitCommit: 269f3d4ee4a91ff8fe05d6a1c71a1e0ced1b900b
  Tags:
  - 1.0.0-rc2
- Architectures: null
  Directory: kapacitor/1.0/alpine
  GitCommit: 269f3d4ee4a91ff8fe05d6a1c71a1e0ced1b900b
  Tags:
  - 1.0.0-rc2-alpine
- Architectures: null
  Directory: kapacitor/1.0
  GitCommit: 22b661b4c141d237669f94e4740f234b7be43a7b
  Tags:
  - 1.0.0-rc1
- Architectures: null
  Directory: kapacitor/1.0/alpine
  GitCommit: 22b661b4c141d237669f94e4740f234b7be43a7b
  Tags:
  - 1.0.0-rc1-alpine
- Architectures: null
  Directory: kapacitor/1.0
  GitCommit: 22315c8e211defb2589fa6831c682391de492b88
  Tags:
  - 1.0.0-beta3
- Architectures: null
  Directory: kapacitor/1.0/alpine
  GitCommit: 22315c8e211defb2589fa6831c682391de492b88
  Tags:
  - 1.0.0-beta3-alpine
- Architectures: null
  Directory: kapacitor/1.0
  GitCommit: 215cf009c143dc739b5b10084ae330ca7f3665d6
  Tags:
  - 1.0.0-beta1
- Architectures: null
  Directory: kapacitor/1.0/alpine
  GitCommit: 215cf009c143dc739b5b10084ae330ca7f3665d6
  Tags:
  - 1.0.0-beta1-alpine
GitRepo: https://github.com/influxdata/influxdata-docker
KnownTags:
  "0.12": {}
  0.12.0: {}
  "0.13": {}
  0.13-alpine: {}
  0.13.1: {}
  0.13.1-alpine: {}
  "1.0": {}
  1.0-alpine: {}
  1.0.0: {}
  1.0.0-alpine: {}
  1.0.0-beta1: {}
  1.0.0-beta1-alpine: {}
  1.0.0-beta3: {}
  1.0.0-beta3-alpine: {}
  1.0.0-rc1: {}
  1.0.0-rc1-alpine: {}
  1.0.0-rc2: {}
  1.0.0-rc2-alpine: {}
  1.0.1: {}
  1.0.1-alpine: {}
  1.0.2: {}
  1.0.2-alpine: {}
  "1.1": {}
  1.1-alpine: {}
  1.1.0: {}
  1.1.0-alpine: {}
  1.1.0-rc1: {}
  1.1.0-rc1-alpine: {}
  1.1.0-rc2: {}
  1.1.0-rc2-alpine: {}
  1.1.1: {}
  1.1.1-alpine: {}
  "1.2": {}
  1.2-alpine: {}
  1.2.0: {}
  1.2.0-alpine: {}
  1.2.0-rc1: {}
  1.2.0-rc1-alpine: {}
  1.2.1: {}
  1.2.1-alpine: {}
  "1.3": {}
  1.3-alpine: {}
  1.3.0: {}
  1.3.0-alpine: {}
  1.3.1: {}
  1.3.1-alpine: {}
  1.3.2: {}
  1.3.2-alpine: {}
  1.3.3: {}
  1.3.3-alpine: {}
  "1.4": {}
  1.4-alpine: {}
  1.4.0: {}
  1.4.0-alpine: {}
  1.4.1: {}
  1.4.1-alpine: {}
  "1.5": {}
  1.5-alpine: {}
  1.5.0: {}
  1.5.0-alpine: {}
  1.5.1: {}
  1.5.1-alpine: {}
  1.5.2: {}
  1.5.2-alpine: {}
  1.5.3: {}
  1.5.3-alpine: {}
  1.5.4: {}
  1.5.4-alpine: {}
  1.5.5: {}
  1.5.5-alpine: {}
  1.5.6: {}
  1.5.6-alpine: {}
  1.5.7: {}
  1.5.7-alpine: {}
  1.5.8: {}
  1.5.8-alpine: {}
  1.5.9: {}
  1.5.9-alpine: {}
  "1.6": {}
  1.6-alpine: {}
  1.6.1: {}
  1.6.1-alpine: {}
  1.6.2: {}
  1.6.2-alpine: {}
  1.6.3: {}
  1.6.3-alpine: {}
  1.6.4: {}
  1.6.4-alpine: {}
  1.6.5: {}
  1.6.5-alpine: {}
  1.6.6: {}
  1.6.6-alpine: {}
  alpine: {}
  latest: {}
Name: kapacitor
