Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "9"
  File: ""
  GitCommit: ""
  Tags:
  - "9"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 9-slim
  File: ""
  GitCommit: ""
  Tags:
  - 9-slim
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "8"
  File: ""
  GitCommit: ""
  Tags:
  - "8.8"
  - "8"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8-slim
  File: ""
  GitCommit: ""
  Tags:
  - 8-slim
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8-slim-fips
  File: ""
  GitCommit: ""
  Tags:
  - 8-slim-fips
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "7"
  File: ""
  GitCommit: ""
  Tags:
  - "7.9"
  - "7"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 7-slim
  File: ""
  GitCommit: ""
  Tags:
  - 7-slim
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 7-slim-fips
  File: ""
  GitCommit: ""
  Tags:
  - 7-slim-fips
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "8"
  File: ""
  GitCommit: ""
  Tags:
  - "8.7"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "8"
  File: ""
  GitCommit: ""
  Tags:
  - "8.6"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: b2631b4c3944ae70c9463ae62aaa75a1a4877a16
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ae688d9eef59795cd485bd9d9f43ce9015c3c461
      GitFetch: ""
  Directory: "8"
  File: ""
  GitCommit: ""
  Tags:
  - "8.5"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "8"
  File: ""
  GitCommit: ""
  Tags:
  - "8.4"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "6"
  File: ""
  GitCommit: ""
  Tags:
  - "6.10"
  - "6"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 6-slim
  File: ""
  GitCommit: ""
  Tags:
  - 6-slim
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "8"
  File: ""
  GitCommit: ""
  Tags:
  - "8.3"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "8.2"
  File: ""
  GitCommit: ""
  Tags:
  - "8.2"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "8.1"
  File: ""
  GitCommit: ""
  Tags:
  - "8.1"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "8.0"
  File: ""
  GitCommit: ""
  Tags:
  - "8.0"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "7.8"
  File: ""
  GitCommit: ""
  Tags:
  - "7.8"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "7.8"
  File: ""
  GitCommit: ""
  Tags:
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "7.7"
  File: ""
  GitCommit: ""
  Tags:
  - "7.7"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "7.6"
  File: ""
  GitCommit: ""
  Tags:
  - "7.6"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "7.5"
  File: ""
  GitCommit: ""
  Tags:
  - "7.5"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "7.4"
  File: ""
  GitCommit: ""
  Tags:
  - "7.4"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "6.9"
  File: ""
  GitCommit: ""
  Tags:
  - "6.9"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "7.3"
  File: ""
  GitCommit: ""
  Tags:
  - "7.3"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "7.2"
  File: ""
  GitCommit: ""
  Tags:
  - "7.2"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "7.1"
  File: ""
  GitCommit: ""
  Tags:
  - "7.1"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "7.0"
  File: ""
  GitCommit: ""
  Tags:
  - "7.0"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "6.8"
  File: ""
  GitCommit: ""
  Tags:
  - "6.8"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "6.7"
  File: ""
  GitCommit: ""
  Tags:
  - "6.7"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "6.6"
  File: ""
  GitCommit: ""
  Tags:
  - "6.6"
- Architectures: null
  Directory: OracleLinux/5.11
  File: ""
  GitCommit: ""
  Tags:
  - "5"
  - "5.11"
GitRepo: https://github.com/oracle/container-images.git
KnownTags:
  "5": {}
  "5.11": {}
  "6": {}
  6-slim: {}
  "6.6": {}
  "6.7": {}
  "6.8": {}
  "6.9": {}
  "6.10": {}
  "7": {}
  7-slim: {}
  7-slim-fips: {}
  "7.0": {}
  "7.1": {}
  "7.2": {}
  "7.3": {}
  "7.4": {}
  "7.5": {}
  "7.6": {}
  "7.7": {}
  "7.8": {}
  "7.9": {}
  "8": {}
  8-slim: {}
  8-slim-fips: {}
  "8.0": {}
  "8.1": {}
  "8.2": {}
  "8.3": {}
  "8.4": {}
  "8.5": {}
  "8.6": {}
  "8.7": {}
  "8.8": {}
  "9": {}
  9-slim: {}
  latest: {}
Name: oraclelinux
