Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: "9"
  GitCommit: ""
  Tags:
  - "9"
- Architectures:
  - amd64
  - arm64v8
  Directory: 9-slim
  GitCommit: ""
  Tags:
  - 9-slim
- Architectures:
  - amd64
  - arm64v8
  Directory: "8"
  GitCommit: ""
  Tags:
  - "8.8"
  - "8"
- Architectures:
  - amd64
  - arm64v8
  Directory: 8-slim
  GitCommit: ""
  Tags:
  - 8-slim
- Architectures:
  - amd64
  - arm64v8
  Directory: 8-slim-fips
  GitCommit: ""
  Tags:
  - 8-slim-fips
- Architectures:
  - amd64
  - arm64v8
  Directory: "7"
  GitCommit: ""
  Tags:
  - "7.9"
  - "7"
- Architectures:
  - amd64
  - arm64v8
  Directory: 7-slim
  GitCommit: ""
  Tags:
  - 7-slim
- Architectures:
  - amd64
  - arm64v8
  Directory: 7-slim-fips
  GitCommit: ""
  Tags:
  - 7-slim-fips
GitRepo: https://github.com/oracle/container-images.git
KnownTags:
  "7": {}
  7-slim: {}
  7-slim-fips: {}
  "7.9": {}
  "8": {}
  8-slim: {}
  8-slim-fips: {}
  "8.8": {}
  "9": {}
  9-slim: {}
Name: oraclelinux
