Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.4/buster
  GitCommit: 13262afb82e457645a9b9f3f3eadb8e5acd4b5c1
  Tags:
  - 9.4.5-buster
  - 9.4-buster
  - 9-buster
  - buster
  - 9.4.5
  - "9.4"
  - "9"
  - latest
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.4/slim-buster
  GitCommit: 13262afb82e457645a9b9f3f3eadb8e5acd4b5c1
  Tags:
  - 9.4.5-slim-buster
  - 9.4-slim-buster
  - 9-slim-buster
  - slim-buster
  - 9.4.5-slim
  - 9.4-slim
  - 9-slim
  - slim
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.2/buster
  GitCommit: 13262afb82e457645a9b9f3f3eadb8e5acd4b5c1
  Tags:
  - 9.2.8-buster
  - 9.2-buster
  - 9.2.8
  - "9.2"
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.2/slim-buster
  GitCommit: 13262afb82e457645a9b9f3f3eadb8e5acd4b5c1
  Tags:
  - 9.2.8-slim-buster
  - 9.2-slim-buster
  - 9.2.8-slim
  - 9.2-slim
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.0/buster
  GitCommit: 13262afb82e457645a9b9f3f3eadb8e5acd4b5c1
  Tags:
  - 9.0.2-buster
  - 9.0-buster
  - 9.0.2
  - "9.0"
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.0/slim-buster
  GitCommit: 13262afb82e457645a9b9f3f3eadb8e5acd4b5c1
  Tags:
  - 9.0.2-slim-buster
  - 9.0-slim-buster
  - 9.0.2-slim
  - 9.0-slim
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.2/buster
  GitCommit: 47c8a1ef9ecdfe9603dfa5e3ee0bdfc4b64a944a
  Tags:
  - 9.2.7-buster
  - 9.2.7
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.2/slim-buster
  GitCommit: 47c8a1ef9ecdfe9603dfa5e3ee0bdfc4b64a944a
  Tags:
  - 9.2.7-slim-buster
  - 9.2.7-slim
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.4/buster
  GitCommit: 12cd297d7ccc2e97fe5e94548ae502b0cbb6735f
  Tags:
  - 9.4.4-buster
  - 9.4.4
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.4/slim-buster
  GitCommit: 12cd297d7ccc2e97fe5e94548ae502b0cbb6735f
  Tags:
  - 9.4.4-slim-buster
  - 9.4.4-slim
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.2/buster
  GitCommit: b2644d1604cc9a3e868b432f4901e86541a0841d
  Tags:
  - 9.2.6-buster
  - 9.2.6
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.2/slim-buster
  GitCommit: b2644d1604cc9a3e868b432f4901e86541a0841d
  Tags:
  - 9.2.6-slim-buster
  - 9.2.6-slim
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.2/buster
  GitCommit: 12cd297d7ccc2e97fe5e94548ae502b0cbb6735f
  Tags:
  - 9.2.5-buster
  - 9.2.5
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.2/slim-buster
  GitCommit: 12cd297d7ccc2e97fe5e94548ae502b0cbb6735f
  Tags:
  - 9.2.5-slim-buster
  - 9.2.5-slim
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.4/buster
  GitCommit: b29df0224a5f76407a41c6662513201650fde976
  Tags:
  - 9.4.3-buster
  - 9.4.3
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.4/slim-buster
  GitCommit: b29df0224a5f76407a41c6662513201650fde976
  Tags:
  - 9.4.3-slim-buster
  - 9.4.3-slim
- Architectures:
  - amd64
  - arm64v8
  Directory: 8.10/buster
  GitCommit: 4fd05c031a306bcc0057cdd04439700c418ffaf0
  Tags:
  - 8.10.7-buster
  - 8.10-buster
  - 8-buster
  - 8.10.7
  - "8.10"
  - "8"
- Architectures:
  - amd64
  - arm64v8
  Directory: 8.10/slim-buster
  GitCommit: 4fd05c031a306bcc0057cdd04439700c418ffaf0
  Tags:
  - 8.10.7-slim-buster
  - 8.10-slim-buster
  - 8-slim-buster
  - 8.10.7-slim
  - 8.10-slim
  - 8-slim
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.2/buster
  GitCommit: 4fd05c031a306bcc0057cdd04439700c418ffaf0
  Tags:
  - 9.2.4-buster
  - 9.2.4
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.2/slim-buster
  GitCommit: 4fd05c031a306bcc0057cdd04439700c418ffaf0
  Tags:
  - 9.2.4-slim-buster
  - 9.2.4-slim
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.4/buster
  GitCommit: 4fd05c031a306bcc0057cdd04439700c418ffaf0
  Tags:
  - 9.4.2-buster
  - 9.4.2
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.4/slim-buster
  GitCommit: 4fd05c031a306bcc0057cdd04439700c418ffaf0
  Tags:
  - 9.4.2-slim-buster
  - 9.4.2-slim
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.4/buster
  GitCommit: 94c169693cc6337c2cd3994da71fb5d9f0b399b0
  Tags:
  - 9.4.1-buster
  - 9.4.1
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.4/slim-buster
  GitCommit: 94c169693cc6337c2cd3994da71fb5d9f0b399b0
  Tags:
  - 9.4.1-slim-buster
  - 9.4.1-slim
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.2/buster
  GitCommit: 595046aa00340b831927be7edb2f4eaa1a83e4e1
  Tags:
  - 9.2.3-buster
  - 9.2.3
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.2/slim-buster
  GitCommit: 573ee754783f8d5c5674888768378c6832f8d121
  Tags:
  - 9.2.3-slim-buster
  - 9.2.3-slim
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.2/buster
  GitCommit: 210996a373f977e4fc8ed39508f8bdeff9a7d386
  Tags:
  - 9.2.2-buster
  - 9.2.2
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.2/slim-buster
  GitCommit: 210996a373f977e4fc8ed39508f8bdeff9a7d386
  Tags:
  - 9.2.2-slim-buster
  - 9.2.2-slim
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.2/buster
  GitCommit: 56d3f9996456bf633876fdb5d76bfb302b689f7c
  Tags:
  - 9.2.1-buster
  - 9.2.1
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.2/slim-buster
  GitCommit: 56d3f9996456bf633876fdb5d76bfb302b689f7c
  Tags:
  - 9.2.1-slim-buster
  - 9.2.1-slim
- Architectures: null
  Directory: 9.0/buster
  GitCommit: f08ade43f48981b87505fbecca852194954fa61b
  Tags:
  - 9.0.1-buster
  - 9.0.1
- Architectures: null
  Directory: 9.0/stretch
  GitCommit: 4181ccd382f72959ecb234204fd018b2c203c3fe
  Tags:
  - 9.0.1-stretch
  - 9.0-stretch
  - 9-stretch
  - stretch
- Architectures: null
  Directory: 8.10/stretch
  GitCommit: 4181ccd382f72959ecb234204fd018b2c203c3fe
  Tags:
  - 8.10.7-stretch
  - 8.10-stretch
  - 8-stretch
- Architectures: null
  Directory: 8.10/buster
  GitCommit: 47d2ca30933d9fa81bff1538c035008bb1c0c197
  Tags:
  - 8.10.5-buster
  - 8.10.5
- Architectures: null
  Directory: 8.10/stretch
  GitCommit: 47d2ca30933d9fa81bff1538c035008bb1c0c197
  Tags:
  - 8.10.5-stretch
- Architectures: null
  Directory: 8.10/buster
  GitCommit: bc860ec5b664fdd12353a46017e407f10045e9b0
  Tags:
  - 8.10.6-buster
  - 8.10.6
- Architectures: null
  Directory: 8.10/stretch
  GitCommit: bc860ec5b664fdd12353a46017e407f10045e9b0
  Tags:
  - 8.10.6-stretch
- Architectures: null
  Directory: 8.10/buster
  GitCommit: d9bf04e3d561c3ccef4528bbe74d1c89552c6d35
  Tags:
  - 8.10.4-buster
  - 8.10.4
- Architectures: null
  Directory: 8.10/stretch
  GitCommit: d9bf04e3d561c3ccef4528bbe74d1c89552c6d35
  Tags:
  - 8.10.4-stretch
- Architectures: null
  Directory: 8.10/buster
  GitCommit: 9a8e8618c43ab5445798261da7f6b6cf5435a2ff
  Tags:
  - 8.10.3-buster
  - 8.10.3
- Architectures: null
  Directory: 8.10/stretch
  GitCommit: 9a8e8618c43ab5445798261da7f6b6cf5435a2ff
  Tags:
  - 8.10.3-stretch
- Architectures: null
  Directory: 8.8/buster
  GitCommit: 9a8e8618c43ab5445798261da7f6b6cf5435a2ff
  Tags:
  - 8.8.4-buster
  - 8.8-buster
  - 8.8.4
  - "8.8"
- Architectures: null
  Directory: 8.8/stretch
  GitCommit: 9a8e8618c43ab5445798261da7f6b6cf5435a2ff
  Tags:
  - 8.8.4-stretch
  - 8.8-stretch
- Architectures: null
  Directory: 8.10/buster
  GitCommit: fb5c774c38a7ab2e7d233d95368be0f899353496
  Tags:
  - 8.10.2-buster
  - 8.10.2
- Architectures: null
  Directory: 8.10/stretch
  GitCommit: fb5c774c38a7ab2e7d233d95368be0f899353496
  Tags:
  - 8.10.2-stretch
- Architectures: null
  Directory: 8.10/buster
  GitCommit: 82f44382a183fcc1d0026d8abe58259195a8930c
  Tags:
  - 8.10.1-buster
  - 8.10.1
- Architectures: null
  Directory: 8.10/stretch
  GitCommit: 82f44382a183fcc1d0026d8abe58259195a8930c
  Tags:
  - 8.10.1-stretch
- Architectures: null
  Directory: 8.8/buster
  GitCommit: 82f44382a183fcc1d0026d8abe58259195a8930c
  Tags:
  - 8.8.3-buster
  - 8.8.3
- Architectures: null
  Directory: 8.8/stretch
  GitCommit: 82f44382a183fcc1d0026d8abe58259195a8930c
  Tags:
  - 8.8.3-stretch
- Architectures: null
  Directory: "8.6"
  GitCommit: c7675920a33d47aa30ff5456ee622cd61a2d62be
  Tags:
  - 8.6.5
  - "8.6"
- Architectures: null
  Directory: "8.8"
  GitCommit: 1eaf476bf1a9933898f8e96bb366308485d9353f
  Tags:
  - 8.8.2
- Architectures: null
  Directory: "8.8"
  GitCommit: aa517c24c51bbd54da5805517acd12120a9340ab
  Tags:
  - 8.8.1
- Architectures: null
  Directory: "8.4"
  GitCommit: 03467e1a14543d83d33833e669249a3c42f7b7c8
  Tags:
  - 8.4.4
  - "8.4"
- Architectures: null
  Directory: "8.6"
  GitCommit: 03467e1a14543d83d33833e669249a3c42f7b7c8
  Tags:
  - 8.6.3
- Architectures: null
  Directory: "8.6"
  GitCommit: 5362898713c831feb18b57f106385cac2b5daa1a
  Tags:
  - 8.6.2
- Architectures: null
  Directory: "8.4"
  GitCommit: af83447feb6ebeabbc0cbad27adb3895e6262951
  Tags:
  - 8.4.3
- Architectures: null
  Directory: "8.2"
  GitCommit: af83447feb6ebeabbc0cbad27adb3895e6262951
  Tags:
  - 8.2.2
  - "8.2"
- Architectures: null
  Directory: "8.2"
  GitCommit: ea501abb24273d6dab3121bb6373f6903f1a3c71
  Tags:
  - 8.2.1
- Architectures: null
  Directory: "8.0"
  GitCommit: 5f1ae82bd27501322100b915c9ae6cc9f9aea129
  Tags:
  - 8.0.2
  - "8.0"
GitRepo: https://github.com/haskell/docker-haskell
KnownTags:
  "8": {}
  8-buster: {}
  8-slim: {}
  8-slim-buster: {}
  8-stretch: {}
  "8.0": {}
  8.0.2: {}
  "8.2": {}
  8.2.1: {}
  8.2.2: {}
  "8.4": {}
  8.4.3: {}
  8.4.4: {}
  "8.6": {}
  8.6.2: {}
  8.6.3: {}
  8.6.5: {}
  "8.8": {}
  8.8-buster: {}
  8.8-stretch: {}
  8.8.1: {}
  8.8.2: {}
  8.8.3: {}
  8.8.3-buster: {}
  8.8.3-stretch: {}
  8.8.4: {}
  8.8.4-buster: {}
  8.8.4-stretch: {}
  "8.10": {}
  8.10-buster: {}
  8.10-slim: {}
  8.10-slim-buster: {}
  8.10-stretch: {}
  8.10.1: {}
  8.10.1-buster: {}
  8.10.1-stretch: {}
  8.10.2: {}
  8.10.2-buster: {}
  8.10.2-stretch: {}
  8.10.3: {}
  8.10.3-buster: {}
  8.10.3-stretch: {}
  8.10.4: {}
  8.10.4-buster: {}
  8.10.4-stretch: {}
  8.10.5: {}
  8.10.5-buster: {}
  8.10.5-stretch: {}
  8.10.6: {}
  8.10.6-buster: {}
  8.10.6-stretch: {}
  8.10.7: {}
  8.10.7-buster: {}
  8.10.7-slim: {}
  8.10.7-slim-buster: {}
  8.10.7-stretch: {}
  "9": {}
  9-buster: {}
  9-slim: {}
  9-slim-buster: {}
  9-stretch: {}
  "9.0": {}
  9.0-buster: {}
  9.0-slim: {}
  9.0-slim-buster: {}
  9.0-stretch: {}
  9.0.1: {}
  9.0.1-buster: {}
  9.0.1-stretch: {}
  9.0.2: {}
  9.0.2-buster: {}
  9.0.2-slim: {}
  9.0.2-slim-buster: {}
  "9.2": {}
  9.2-buster: {}
  9.2-slim: {}
  9.2-slim-buster: {}
  9.2.1: {}
  9.2.1-buster: {}
  9.2.1-slim: {}
  9.2.1-slim-buster: {}
  9.2.2: {}
  9.2.2-buster: {}
  9.2.2-slim: {}
  9.2.2-slim-buster: {}
  9.2.3: {}
  9.2.3-buster: {}
  9.2.3-slim: {}
  9.2.3-slim-buster: {}
  9.2.4: {}
  9.2.4-buster: {}
  9.2.4-slim: {}
  9.2.4-slim-buster: {}
  9.2.5: {}
  9.2.5-buster: {}
  9.2.5-slim: {}
  9.2.5-slim-buster: {}
  9.2.6: {}
  9.2.6-buster: {}
  9.2.6-slim: {}
  9.2.6-slim-buster: {}
  9.2.7: {}
  9.2.7-buster: {}
  9.2.7-slim: {}
  9.2.7-slim-buster: {}
  9.2.8: {}
  9.2.8-buster: {}
  9.2.8-slim: {}
  9.2.8-slim-buster: {}
  "9.4": {}
  9.4-buster: {}
  9.4-slim: {}
  9.4-slim-buster: {}
  9.4.1: {}
  9.4.1-buster: {}
  9.4.1-slim: {}
  9.4.1-slim-buster: {}
  9.4.2: {}
  9.4.2-buster: {}
  9.4.2-slim: {}
  9.4.2-slim-buster: {}
  9.4.3: {}
  9.4.3-buster: {}
  9.4.3-slim: {}
  9.4.3-slim-buster: {}
  9.4.4: {}
  9.4.4-buster: {}
  9.4.4-slim: {}
  9.4.4-slim-buster: {}
  9.4.5: {}
  9.4.5-buster: {}
  9.4.5-slim: {}
  9.4.5-slim-buster: {}
  buster: {}
  latest: {}
  slim: {}
  slim-buster: {}
  stretch: {}
Name: haskell
