Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.4/buster
  GitCommit: 13262afb82e457645a9b9f3f3eadb8e5acd4b5c1
  Tags:
  - 9.4.5-buster
  - 9.4-buster
  - 9-buster
  - buster
  - 9.4.5
  - "9.4"
  - "9"
  - latest
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.4/slim-buster
  GitCommit: 13262afb82e457645a9b9f3f3eadb8e5acd4b5c1
  Tags:
  - 9.4.5-slim-buster
  - 9.4-slim-buster
  - 9-slim-buster
  - slim-buster
  - 9.4.5-slim
  - 9.4-slim
  - 9-slim
  - slim
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.2/buster
  GitCommit: 13262afb82e457645a9b9f3f3eadb8e5acd4b5c1
  Tags:
  - 9.2.8-buster
  - 9.2-buster
  - 9.2.8
  - "9.2"
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.2/slim-buster
  GitCommit: 13262afb82e457645a9b9f3f3eadb8e5acd4b5c1
  Tags:
  - 9.2.8-slim-buster
  - 9.2-slim-buster
  - 9.2.8-slim
  - 9.2-slim
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.0/buster
  GitCommit: 13262afb82e457645a9b9f3f3eadb8e5acd4b5c1
  Tags:
  - 9.0.2-buster
  - 9.0-buster
  - 9.0.2
  - "9.0"
- Architectures:
  - amd64
  - arm64v8
  Directory: 9.0/slim-buster
  GitCommit: 13262afb82e457645a9b9f3f3eadb8e5acd4b5c1
  Tags:
  - 9.0.2-slim-buster
  - 9.0-slim-buster
  - 9.0.2-slim
  - 9.0-slim
GitRepo: https://github.com/haskell/docker-haskell
KnownTags:
  "9": {}
  9-buster: {}
  9-slim: {}
  9-slim-buster: {}
  "9.0": {}
  9.0-buster: {}
  9.0-slim: {}
  9.0-slim-buster: {}
  9.0.2: {}
  9.0.2-buster: {}
  9.0.2-slim: {}
  9.0.2-slim-buster: {}
  "9.2": {}
  9.2-buster: {}
  9.2-slim: {}
  9.2-slim-buster: {}
  9.2.8: {}
  9.2.8-buster: {}
  9.2.8-slim: {}
  9.2.8-slim-buster: {}
  "9.4": {}
  9.4-buster: {}
  9.4-slim: {}
  9.4-slim-buster: {}
  9.4.5: {}
  9.4.5-buster: {}
  9.4.5-slim: {}
  9.4.5-slim-buster: {}
  buster: {}
  latest: {}
  slim: {}
  slim-buster: {}
Name: haskell
