Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "1.6"
  GitCommit: 734961b7d2f6977c52a4136def06bf2f92d905d4
  Tags:
  - 1.6.2
  - "1.6"
  - "1"
  - latest
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 1.6/alpine
  GitCommit: 32bffc38a1a3efcf0ce6817953230bf352bfb7a8
  Tags:
  - 1.6.2-alpine
  - 1.6-alpine
  - 1-alpine
  - alpine
GitRepo: https://github.com/TimWolla/docker-spiped.git
KnownTags:
  "1": {}
  1-alpine: {}
  "1.6": {}
  1.6-alpine: {}
  1.6.2: {}
  1.6.2-alpine: {}
  alpine: {}
  latest: {}
Name: spiped
