Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "1.6"
  GitCommit: 734961b7d2f6977c52a4136def06bf2f92d905d4
  Tags:
  - 1.6.2
  - "1.6"
  - "1"
  - latest
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 1.6/alpine
  GitCommit: 32bffc38a1a3efcf0ce6817953230bf352bfb7a8
  Tags:
  - 1.6.2-alpine
  - 1.6-alpine
  - 1-alpine
  - alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "1.6"
  GitCommit: bec455b320f878b386328c2db0cb9a6ca9fd7755
  Tags:
  - 1.6.1
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 1.6/alpine
  GitCommit: f97eba885ee67cd0d8a32f4e70ab5388bb77944f
  Tags:
  - 1.6.1-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "1.6"
  GitCommit: b813c31745a94587dcdef8611fe84be2e266cb1b
  Tags:
  - 1.6.0
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 1.6/alpine
  GitCommit: 6b9b45b3bc78f5f41758df56357552a0f4808c5e
  Tags:
  - 1.6.0-alpine
- Architectures: null
  Directory: "1.5"
  GitCommit: caa1ecb53270efd9a088e3856398c48622b5afc8
  Tags:
  - 1.5.0
  - "1.5"
- Architectures: null
  Directory: 1.5/alpine
  GitCommit: 543c0f7021284d0aa36d5a894b2467656095126b
  Tags:
  - 1.5.0-alpine
  - 1.5-alpine
GitRepo: https://github.com/TimWolla/docker-spiped.git
KnownTags:
  "1": {}
  1-alpine: {}
  "1.5": {}
  1.5-alpine: {}
  1.5.0: {}
  1.5.0-alpine: {}
  "1.6": {}
  1.6-alpine: {}
  1.6.0: {}
  1.6.0-alpine: {}
  1.6.1: {}
  1.6.1-alpine: {}
  1.6.2: {}
  1.6.2-alpine: {}
  alpine: {}
  latest: {}
Name: spiped
