Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v5:
      Architecture: arm32v5
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    riscv64:
      Architecture: riscv64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "1.6"
  File: ""
  GitCommit: 6df25f7ecdd98bd0de7726944ed64165699d2edb
  Tags:
  - 1.6.4
  - "1.6"
  - "1"
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v6:
      Architecture: arm32v6
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    riscv64:
      Architecture: riscv64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1.6/alpine
  File: ""
  GitCommit: 2a6429d25e5ebccc2a8075cb8ec85d5dd951579e
  Tags:
  - 1.6.4-alpine
  - 1.6-alpine
  - 1-alpine
  - alpine
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v5:
      Architecture: arm32v5
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    mips64le:
      Architecture: mips64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "1.6"
  File: ""
  GitCommit: 917d35aa378a013b033fb1eaf34acdef342fa7b6
  Tags:
  - 1.6.3
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v6:
      Architecture: arm32v6
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    riscv64:
      Architecture: riscv64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1.6/alpine
  File: ""
  GitCommit: 917d35aa378a013b033fb1eaf34acdef342fa7b6
  Tags:
  - 1.6.3-alpine
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v5:
      Architecture: arm32v5
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    mips64le:
      Architecture: mips64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "1.6"
  File: ""
  GitCommit: 734961b7d2f6977c52a4136def06bf2f92d905d4
  Tags:
  - 1.6.2
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v6:
      Architecture: arm32v6
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    riscv64:
      Architecture: riscv64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1.6/alpine
  File: ""
  GitCommit: 646ceea9c33a13927a6702bf413650b6e66cea39
  Tags:
  - 1.6.2-alpine
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v5:
      Architecture: arm32v5
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    mips64le:
      Architecture: mips64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "1.6"
  File: ""
  GitCommit: bec455b320f878b386328c2db0cb9a6ca9fd7755
  Tags:
  - 1.6.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v6:
      Architecture: arm32v6
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1.6/alpine
  File: ""
  GitCommit: f97eba885ee67cd0d8a32f4e70ab5388bb77944f
  Tags:
  - 1.6.1-alpine
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v5:
      Architecture: arm32v5
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "1.6"
  File: ""
  GitCommit: b813c31745a94587dcdef8611fe84be2e266cb1b
  Tags:
  - 1.6.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v6:
      Architecture: arm32v6
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1.6/alpine
  File: ""
  GitCommit: 6b9b45b3bc78f5f41758df56357552a0f4808c5e
  Tags:
  - 1.6.0-alpine
- Architectures: null
  Directory: "1.5"
  File: ""
  GitCommit: caa1ecb53270efd9a088e3856398c48622b5afc8
  Tags:
  - 1.5.0
  - "1.5"
- Architectures: null
  Directory: 1.5/alpine
  File: ""
  GitCommit: 543c0f7021284d0aa36d5a894b2467656095126b
  Tags:
  - 1.5.0-alpine
  - 1.5-alpine
GitRepo: https://github.com/TimWolla/docker-spiped.git
KnownTags:
  "1": {}
  1-alpine: {}
  "1.5": {}
  1.5-alpine: {}
  1.5.0: {}
  1.5.0-alpine: {}
  "1.6": {}
  1.6-alpine: {}
  1.6.0: {}
  1.6.0-alpine: {}
  1.6.1: {}
  1.6.1-alpine: {}
  1.6.2: {}
  1.6.2-alpine: {}
  1.6.3: {}
  1.6.3-alpine: {}
  1.6.4: {}
  1.6.4-alpine: {}
  alpine: {}
  latest: {}
Name: spiped
