Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: release/3.2.x/3.2.20
  GitCommit: bec4afe6bc542be54c249d3b3597bcba31622362
  Tags:
  - 3.2.20
  - "3.2"
  - latest
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: release/3.2.x/3.2.20-tp3
  GitCommit: bec4afe6bc542be54c249d3b3597bcba31622362
  Tags:
  - 3.2.20-tp3
  - 3.2-tp3
- Architectures: null
  Directory: release/3.1.x/3.1.20
  GitCommit: a8a42acbe19dad60a051afe08ed625e66587dd37
  Tags:
  - 3.1.20
  - "3.1"
- Architectures: null
  Directory: release/3.1.x/3.1.20-tp3
  GitCommit: a8a42acbe19dad60a051afe08ed625e66587dd37
  Tags:
  - 3.1.20-tp3
  - 3.1-tp3
- Architectures: null
  Directory: release/3.0.x/3.0.44
  GitCommit: a8a42acbe19dad60a051afe08ed625e66587dd37
  Tags:
  - 3.0.44
  - "3.0"
- Architectures: null
  Directory: release/3.0.x/3.0.44-tp3
  GitCommit: a8a42acbe19dad60a051afe08ed625e66587dd37
  Tags:
  - 3.0.44-tp3
  - 3.0-tp3
- Architectures: null
  Directory: release/2.2.x/2.2.37
  GitCommit: a8a42acbe19dad60a051afe08ed625e66587dd37
  Tags:
  - 2.2.37
  - "2.2"
- Architectures: null
  Directory: release/2.2.x/2.2.37-spatial
  GitCommit: a8a42acbe19dad60a051afe08ed625e66587dd37
  Tags:
  - 2.2.37-spatial
GitRepo: https://github.com/orientechnologies/orientdb-docker.git
KnownTags:
  "2.2": {}
  2.2.37: {}
  2.2.37-spatial: {}
  "3.0": {}
  3.0-tp3: {}
  3.0.44: {}
  3.0.44-tp3: {}
  "3.1": {}
  3.1-tp3: {}
  3.1.20: {}
  3.1.20-tp3: {}
  "3.2": {}
  3.2-tp3: {}
  3.2.20: {}
  3.2.20-tp3: {}
  latest: {}
Name: orientdb
