Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: 1/apache
  GitCommit: 37aae82be48457f524a3cd475ea55d7c1ce0ef2c
  Tags:
  - 1.25.1
  - "1.25"
  - "1"
  - 1.25.1-apache
  - 1.25-apache
  - 1-apache
  - apache
  - latest
- Architectures:
  - amd64
  - arm64v8
  Directory: 1/fpm
  GitCommit: 37aae82be48457f524a3cd475ea55d7c1ce0ef2c
  Tags:
  - 1.25.1-fpm
  - 1.25-fpm
  - 1-fpm
  - fpm
GitRepo: https://github.com/backdrop-ops/backdrop-docker.git
KnownTags:
  "1": {}
  1-apache: {}
  1-fpm: {}
  "1.25": {}
  1.25-apache: {}
  1.25-fpm: {}
  1.25.1: {}
  1.25.1-apache: {}
  1.25.1-fpm: {}
  apache: {}
  fpm: {}
  latest: {}
Name: backdrop
