Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/apache
  File: ""
  GitCommit: 82f5f08f12c2e861cde61b7b4dac8ebd76f3ee1f
  Tags:
  - 1.31.0
  - "1.31"
  - "1"
  - 1.31.0-apache
  - 1.31-apache
  - 1-apache
  - apache
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/fpm
  File: ""
  GitCommit: 82f5f08f12c2e861cde61b7b4dac8ebd76f3ee1f
  Tags:
  - 1.31.0-fpm
  - 1.31-fpm
  - 1-fpm
  - fpm
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/apache
  File: ""
  GitCommit: 8af6f112829878eaef3c55f239aa9e6b35cbf2a7
  Tags:
  - 1.30.2
  - "1.30"
  - 1.30.2-apache
  - 1.30-apache
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/fpm
  File: ""
  GitCommit: 8af6f112829878eaef3c55f239aa9e6b35cbf2a7
  Tags:
  - 1.30.2-fpm
  - 1.30-fpm
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/apache
  File: ""
  GitCommit: 0f037348948190b7ce4f2e1afe67514818c5a9fc
  Tags:
  - 1.30.1
  - 1.30.1-apache
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/fpm
  File: ""
  GitCommit: 0f037348948190b7ce4f2e1afe67514818c5a9fc
  Tags:
  - 1.30.1-fpm
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/apache
  File: ""
  GitCommit: eec73e9b23f76ffc609be7cdaf27afeccdd91732
  Tags:
  - 1.30.0
  - 1.30.0-apache
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/fpm
  File: ""
  GitCommit: eec73e9b23f76ffc609be7cdaf27afeccdd91732
  Tags:
  - 1.30.0-fpm
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/apache
  File: ""
  GitCommit: 65dad6f2ee2a86b28b14d9dbf1578c62018cd681
  Tags:
  - 1.29.3
  - "1.29"
  - 1.29.3-apache
  - 1.29-apache
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/fpm
  File: ""
  GitCommit: 65dad6f2ee2a86b28b14d9dbf1578c62018cd681
  Tags:
  - 1.29.3-fpm
  - 1.29-fpm
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/apache
  File: ""
  GitCommit: 4f986f41b86617411c52eefc86b59380312f1751
  Tags:
  - 1.29.1
  - 1.29.1-apache
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/fpm
  File: ""
  GitCommit: 4f986f41b86617411c52eefc86b59380312f1751
  Tags:
  - 1.29.1-fpm
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/apache
  File: ""
  GitCommit: 95902d6610b2474ca88ff8faae40ed30e7d3318a
  Tags:
  - 1.26.1
  - "1.26"
  - 1.26.1-apache
  - 1.26-apache
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/fpm
  File: ""
  GitCommit: 95902d6610b2474ca88ff8faae40ed30e7d3318a
  Tags:
  - 1.26.1-fpm
  - 1.26-fpm
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/apache
  File: ""
  GitCommit: 37aae82be48457f524a3cd475ea55d7c1ce0ef2c
  Tags:
  - 1.25.1
  - "1.25"
  - 1.25.1-apache
  - 1.25-apache
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/fpm
  File: ""
  GitCommit: 37aae82be48457f524a3cd475ea55d7c1ce0ef2c
  Tags:
  - 1.25.1-fpm
  - 1.25-fpm
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/apache
  File: ""
  GitCommit: c6dc310e67b2b9d8778c8ed36aa38adfb90ebd9a
  Tags:
  - 1.24.2
  - "1.24"
  - 1.24.2-apache
  - 1.24-apache
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/fpm
  File: ""
  GitCommit: c6dc310e67b2b9d8778c8ed36aa38adfb90ebd9a
  Tags:
  - 1.24.2-fpm
  - 1.24-fpm
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/apache
  File: ""
  GitCommit: 8012e0b47794605356eddc14dc56b1eda4b36f0c
  Tags:
  - 1.23.1
  - "1.23"
  - 1.23.1-apache
  - 1.23-apache
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/fpm
  File: ""
  GitCommit: 8012e0b47794605356eddc14dc56b1eda4b36f0c
  Tags:
  - 1.23.1-fpm
  - 1.23-fpm
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/apache
  File: ""
  GitCommit: 69bc3670f97cf6d060e9379bea26b2fcdf0ebc3f
  Tags:
  - 1.23.0
  - 1.23.0-apache
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/fpm
  File: ""
  GitCommit: 69bc3670f97cf6d060e9379bea26b2fcdf0ebc3f
  Tags:
  - 1.23.0-fpm
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/apache
  File: ""
  GitCommit: 91ac0ee1e56bbff6d2fb49218b38a9cbf9d1a356
  Tags:
  - 1.21.4
  - "1.21"
  - 1.21.4-apache
  - 1.21-apache
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/fpm
  File: ""
  GitCommit: 01456d360386ed664298c53a74a75647e0965795
  Tags:
  - 1.21.4-fpm
  - 1.21-fpm
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/apache
  File: ""
  GitCommit: cb71efedce22392184d6d10aa67109e8f7e86725
  Tags:
  - 1.21.3
  - 1.21.3-apache
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/fpm
  File: ""
  GitCommit: cb71efedce22392184d6d10aa67109e8f7e86725
  Tags:
  - 1.21.3-fpm
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/apache
  File: ""
  GitCommit: b760ba970a67f3dcdc975ed8b77f915895184577
  Tags:
  - 1.17.3
  - "1.17"
  - 1.17.3-apache
  - 1.17-apache
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/fpm
  File: ""
  GitCommit: b760ba970a67f3dcdc975ed8b77f915895184577
  Tags:
  - 1.17.3-fpm
  - 1.17-fpm
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/apache
  File: ""
  GitCommit: 1c82e369b6bf1b8ab45becda7f9f9777fe7f6a7f
  Tags:
  - 1.13.2
  - "1.13"
  - 1.13.2-apache
  - 1.13-apache
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/fpm
  File: ""
  GitCommit: 1c82e369b6bf1b8ab45becda7f9f9777fe7f6a7f
  Tags:
  - 1.13.2-fpm
  - 1.13-fpm
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/apache
  File: ""
  GitCommit: d0e9a5029f1eb3eaf5bd06f74fd72403c069e31f
  Tags:
  - 1.10.1
  - "1.10"
  - 1.10.1-apache
  - 1.10-apache
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/fpm
  File: ""
  GitCommit: d0e9a5029f1eb3eaf5bd06f74fd72403c069e31f
  Tags:
  - 1.10.1-fpm
  - 1.10-fpm
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1/fpm
  File: ""
  GitCommit: 1c82e369b6bf1b8ab45becda7f9f9777fe7f6a7f
  Tags:
  - 1.13.1-fpm
GitRepo: https://github.com/backdrop-ops/backdrop-docker.git
KnownTags:
  "1": {}
  1-apache: {}
  1-fpm: {}
  "1.10": {}
  1.10-apache: {}
  1.10-fpm: {}
  1.10.1: {}
  1.10.1-apache: {}
  1.10.1-fpm: {}
  "1.13": {}
  1.13-apache: {}
  1.13-fpm: {}
  1.13.1-fpm: {}
  1.13.2: {}
  1.13.2-apache: {}
  1.13.2-fpm: {}
  "1.17": {}
  1.17-apache: {}
  1.17-fpm: {}
  1.17.3: {}
  1.17.3-apache: {}
  1.17.3-fpm: {}
  "1.21": {}
  1.21-apache: {}
  1.21-fpm: {}
  1.21.3: {}
  1.21.3-apache: {}
  1.21.3-fpm: {}
  1.21.4: {}
  1.21.4-apache: {}
  1.21.4-fpm: {}
  "1.23": {}
  1.23-apache: {}
  1.23-fpm: {}
  1.23.0: {}
  1.23.0-apache: {}
  1.23.0-fpm: {}
  1.23.1: {}
  1.23.1-apache: {}
  1.23.1-fpm: {}
  "1.24": {}
  1.24-apache: {}
  1.24-fpm: {}
  1.24.2: {}
  1.24.2-apache: {}
  1.24.2-fpm: {}
  "1.25": {}
  1.25-apache: {}
  1.25-fpm: {}
  1.25.1: {}
  1.25.1-apache: {}
  1.25.1-fpm: {}
  "1.26": {}
  1.26-apache: {}
  1.26-fpm: {}
  1.26.1: {}
  1.26.1-apache: {}
  1.26.1-fpm: {}
  "1.29": {}
  1.29-apache: {}
  1.29-fpm: {}
  1.29.1: {}
  1.29.1-apache: {}
  1.29.1-fpm: {}
  1.29.3: {}
  1.29.3-apache: {}
  1.29.3-fpm: {}
  "1.30": {}
  1.30-apache: {}
  1.30-fpm: {}
  1.30.0: {}
  1.30.0-apache: {}
  1.30.0-fpm: {}
  1.30.1: {}
  1.30.1-apache: {}
  1.30.1-fpm: {}
  1.30.2: {}
  1.30.2-apache: {}
  1.30.2-fpm: {}
  "1.31": {}
  1.31-apache: {}
  1.31-fpm: {}
  1.31.0: {}
  1.31.0-apache: {}
  1.31.0-fpm: {}
  apache: {}
  fpm: {}
  latest: {}
Name: backdrop
