Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "5.0"
  GitCommit: 5c69b4458049c150d8cc335841871aa4625dc217
  Tags:
  - 5.0.5
  - "5.0"
  - "5"
  - latest
  - 5.0.5-bullseye
  - 5.0-bullseye
  - 5-bullseye
  - bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 5.0/alpine
  GitCommit: cc904a5f85eb1bfd99af68c0ea3f1e5aeb5d5554
  Tags:
  - 5.0.5-alpine
  - 5.0-alpine
  - 5-alpine
  - alpine
  - 5.0.5-alpine3.18
  - 5.0-alpine3.18
  - 5-alpine3.18
  - alpine3.18
GitRepo: https://github.com/docker-library/redmine.git
KnownTags:
  "5": {}
  5-alpine: {}
  5-alpine3.18: {}
  5-bullseye: {}
  "5.0": {}
  5.0-alpine: {}
  5.0-alpine3.18: {}
  5.0-bullseye: {}
  5.0.5: {}
  5.0.5-alpine: {}
  5.0.5-alpine3.18: {}
  5.0.5-bullseye: {}
  alpine: {}
  alpine3.18: {}
  bullseye: {}
  latest: {}
Name: redmine
