Blocks:
- Architectures: null
  Directory: 1.39/apache
  GitCommit: ""
  Tags:
  - 1.39.3
  - "1.39"
  - stable
  - lts
  - latest
- Architectures: null
  Directory: 1.39/fpm
  GitCommit: ""
  Tags:
  - 1.39.3-fpm
  - 1.39-fpm
  - stable-fpm
  - lts-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: 1.39/fpm-alpine
  GitCommit: ""
  Tags:
  - 1.39.3-fpm-alpine
  - 1.39-fpm-alpine
  - stable-fpm-alpine
  - lts-fpm-alpine
- Architectures: null
  Directory: 1.38/apache
  GitCommit: ""
  Tags:
  - 1.38.6
  - "1.38"
  - legacy
- Architectures: null
  Directory: 1.38/fpm
  GitCommit: ""
  Tags:
  - 1.38.6-fpm
  - 1.38-fpm
  - legacy-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: 1.38/fpm-alpine
  GitCommit: ""
  Tags:
  - 1.38.6-fpm-alpine
  - 1.38-fpm-alpine
  - legacy-fpm-alpine
- Architectures: null
  Directory: 1.35/apache
  GitCommit: ""
  Tags:
  - 1.35.10
  - "1.35"
  - legacylts
- Architectures: null
  Directory: 1.35/fpm
  GitCommit: ""
  Tags:
  - 1.35.10-fpm
  - 1.35-fpm
  - legacylts-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: 1.35/fpm-alpine
  GitCommit: ""
  Tags:
  - 1.35.10-fpm-alpine
  - 1.35-fpm-alpine
  - legacylts-fpm-alpine
GitRepo: https://github.com/wikimedia/mediawiki-docker.git
KnownTags:
  "1.35": {}
  1.35-fpm: {}
  1.35-fpm-alpine: {}
  1.35.10: {}
  1.35.10-fpm: {}
  1.35.10-fpm-alpine: {}
  "1.38": {}
  1.38-fpm: {}
  1.38-fpm-alpine: {}
  1.38.6: {}
  1.38.6-fpm: {}
  1.38.6-fpm-alpine: {}
  "1.39": {}
  1.39-fpm: {}
  1.39-fpm-alpine: {}
  1.39.3: {}
  1.39.3-fpm: {}
  1.39.3-fpm-alpine: {}
  latest: {}
  legacy: {}
  legacy-fpm: {}
  legacy-fpm-alpine: {}
  legacylts: {}
  legacylts-fpm: {}
  legacylts-fpm-alpine: {}
  lts: {}
  lts-fpm: {}
  lts-fpm-alpine: {}
  stable: {}
  stable-fpm: {}
  stable-fpm-alpine: {}
Name: mediawiki
