Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: ""
  GitCommit: 26e7ea94e4d222de7d52531caee52149ac093c26
  Tags:
  - 1.0.0-alpha.4
  - 1.0.0-alpha
  - latest
- Architectures:
  - amd64
  - arm64v8
  Directory: ""
  GitCommit: 4b43fe8a1206434cb32a006cd155dd71462f092f
  Tags:
  - 0.54.0
  - "0.54"
- Architectures:
  - amd64
  - arm64v8
  Directory: ""
  GitCommit: b089fe7708d9dd619d648a6ec226fe0175b27740
  Tags:
  - 0.49.0
  - "0.49"
- Architectures: null
  Directory: ""
  GitCommit: e297febcf7ee27858c70505e1ba2db13d93730e0
  Tags:
  - 0.45.0
  - "0.45"
- Architectures: null
  Directory: ""
  GitCommit: e739e94d5fefd75e5eaf0ff5a6221a45da0d6959
  Tags:
  - 0.44.0
  - "0.44"
- Architectures:
  - amd64
  - arm64v8
  Directory: ""
  GitCommit: 26e7ea94e4d222de7d52531caee52149ac093c26
  Tags:
  - "1.0"
GitRepo: https://github.com/mongo-express/mongo-express-docker.git
KnownTags:
  "0.44": {}
  0.44.0: {}
  "0.45": {}
  0.45.0: {}
  "0.49": {}
  0.49.0: {}
  "0.54": {}
  0.54.0: {}
  "1.0": {}
  1.0.0-alpha: {}
  1.0.0-alpha.4: {}
  latest: {}
Name: mongo-express
