Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1.0/20-alpine3.19
  File: ""
  GitCommit: 403467f350d819b404f3d5150be7776217e810b7
  Tags:
  - 1.0.2-20-alpine3.19
  - 1.0-20-alpine3.19
  - 1-20-alpine3.19
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1.0/20-alpine3.18
  File: ""
  GitCommit: 403467f350d819b404f3d5150be7776217e810b7
  Tags:
  - 1.0.2-20
  - 1.0-20
  - 1-20
  - 1.0.2-20-alpine3.18
  - 1.0-20-alpine3.18
  - 1-20-alpine3.18
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1.0/18-alpine3.19
  File: ""
  GitCommit: 403467f350d819b404f3d5150be7776217e810b7
  Tags:
  - 1.0.2-18-alpine3.19
  - 1.0-18-alpine3.19
  - 1-18-alpine3.19
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1.0/18-alpine3.18
  File: ""
  GitCommit: 403467f350d819b404f3d5150be7776217e810b7
  Tags:
  - 1.0.2
  - "1.0"
  - "1"
  - 1.0.2-18
  - 1.0-18
  - 1-18
  - 1.0.2-18-alpine3.18
  - 1.0-18-alpine3.18
  - 1-18-alpine3.18
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1.0/20-alpine3.18
  File: ""
  GitCommit: 5fb537b2fd181e458f58137fdb55d061a8c23da5
  Tags:
  - 1.0.0-20-alpine3.18
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1.0/20-alpine3.17
  File: ""
  GitCommit: 5fb537b2fd181e458f58137fdb55d061a8c23da5
  Tags:
  - 1.0.0-20
  - 1.0.0-20-alpine3.17
  - 1.0-20-alpine3.17
  - 1-20-alpine3.17
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1.0/18-alpine3.18
  File: ""
  GitCommit: 5fb537b2fd181e458f58137fdb55d061a8c23da5
  Tags:
  - 1.0.0-18-alpine3.18
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1.0/18-alpine3.17
  File: ""
  GitCommit: 5fb537b2fd181e458f58137fdb55d061a8c23da5
  Tags:
  - 1.0.0
  - 1.0.0-18
  - 1.0.0-18-alpine3.17
  - 1.0-18-alpine3.17
  - 1-18-alpine3.17
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 26e7ea94e4d222de7d52531caee52149ac093c26
  Tags:
  - 1.0.0-alpha.4
  - 1.0.0-alpha
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 4b43fe8a1206434cb32a006cd155dd71462f092f
  Tags:
  - 0.54.0
  - "0.54"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: b089fe7708d9dd619d648a6ec226fe0175b27740
  Tags:
  - 0.49.0
  - "0.49"
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: e297febcf7ee27858c70505e1ba2db13d93730e0
  Tags:
  - 0.45.0
  - "0.45"
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: e739e94d5fefd75e5eaf0ff5a6221a45da0d6959
  Tags:
  - 0.44.0
  - "0.44"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1.0/20-alpine3.17
  File: ""
  GitCommit: 9c15cad889bd6c003c9aea5106fa1656d72aebd8
  Tags:
  - 1.0.2-20-alpine3.17
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1.0/18-alpine3.17
  File: ""
  GitCommit: 9c15cad889bd6c003c9aea5106fa1656d72aebd8
  Tags:
  - 1.0.2-18-alpine3.17
GitRepo: https://github.com/mongo-express/mongo-express-docker.git
KnownTags:
  "0.44": {}
  0.44.0: {}
  "0.45": {}
  0.45.0: {}
  "0.49": {}
  0.49.0: {}
  "0.54": {}
  0.54.0: {}
  "1": {}
  1-18: {}
  1-18-alpine3.17: {}
  1-18-alpine3.18: {}
  1-18-alpine3.19: {}
  1-20: {}
  1-20-alpine3.17: {}
  1-20-alpine3.18: {}
  1-20-alpine3.19: {}
  "1.0": {}
  1.0-18: {}
  1.0-18-alpine3.17: {}
  1.0-18-alpine3.18: {}
  1.0-18-alpine3.19: {}
  1.0-20: {}
  1.0-20-alpine3.17: {}
  1.0-20-alpine3.18: {}
  1.0-20-alpine3.19: {}
  1.0.0: {}
  1.0.0-18: {}
  1.0.0-18-alpine3.17: {}
  1.0.0-18-alpine3.18: {}
  1.0.0-20: {}
  1.0.0-20-alpine3.17: {}
  1.0.0-20-alpine3.18: {}
  1.0.0-alpha: {}
  1.0.0-alpha.4: {}
  1.0.2: {}
  1.0.2-18: {}
  1.0.2-18-alpine3.17: {}
  1.0.2-18-alpine3.18: {}
  1.0.2-18-alpine3.19: {}
  1.0.2-20: {}
  1.0.2-20-alpine3.17: {}
  1.0.2-20-alpine3.18: {}
  1.0.2-20-alpine3.19: {}
  latest: {}
Name: mongo-express
