Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: "9.2"
  GitCommit: 989825ee6dce2f6bf7b31051f1ba053b6c4426f2
  Tags:
  - 9.2.1
  - "9.2"
  - "9"
  - latest
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: "9.1"
  GitCommit: 989825ee6dce2f6bf7b31051f1ba053b6c4426f2
  Tags:
  - 9.1.1
  - "9.1"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: "9.0"
  GitCommit: 989825ee6dce2f6bf7b31051f1ba053b6c4426f2
  Tags:
  - 9.0.0
  - "9.0"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: "8.11"
  GitCommit: 989825ee6dce2f6bf7b31051f1ba053b6c4426f2
  Tags:
  - 8.11.2
  - "8.11"
  - "8"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: 8.11-slim
  GitCommit: 989825ee6dce2f6bf7b31051f1ba053b6c4426f2
  Tags:
  - 8.11.2-slim
  - 8.11-slim
  - 8-slim
GitRepo: https://github.com/apache/solr-docker.git
KnownTags:
  "8": {}
  8-slim: {}
  "8.11": {}
  8.11-slim: {}
  8.11.2: {}
  8.11.2-slim: {}
  "9": {}
  "9.0": {}
  9.0.0: {}
  "9.1": {}
  9.1.1: {}
  "9.2": {}
  9.2.1: {}
  latest: {}
Name: solr
