Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: d9e458fd8490a5c976f2c4e9cec922bebe96af30
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
