Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 01d2007806210d37a6e2e8e14c119e2ba88ec06e
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
