Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: cc4091909649096cd8afd924eced1d2e5ff7ae63
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
