Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 8a0f3d59372d004ddf94581442dd7577c9b554bf
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
