Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 5a2ae74342e6528e27d9f5e089d55fd489a33d69
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
