Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 73d35d4c9eea8c8c212e82f6b80c688221a4d1d6
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
