Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 1488533b57265100236f37b95475c355fdac8255
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
