Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 65dba8369447f9bc5cbb9569a7c780e8a653ca9c
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
