Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 536de2f889e63dbc411cfd408bc57c41f4a8bad2
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
