Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: fa4af2d9ebce5e7f5947194c975e5598de0bcdea
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
