Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: fad5d1c7fde5e79b117a07303cca5d8a6c4f8acb
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
