Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: dca75611de9532455b01e015fa8e1bae4b2d2d4b
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
