Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 217f4343f59409f73803e4499d26af52b36c42cf
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
