Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 8737b58f0f7673161c026016dd1f81fac5f0d757
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
