Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: fa6f05c3b03696821ec9c3a03b98220db6411564
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
