Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 08f41a5297c0b0d27fad6899032357061335bb92
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
