Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 92cf62bded14557c002e816e07e36df2e45b216e
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
