Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 36385de607241cccba05f15d3d6b48bbea5beac6
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
