Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 4c367f5b64b69b64d2529bda3eeb58c2f62c3375
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
