Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 69d1ccc0d066e79a0c1713878bb5d0c6aa15db5c
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
