Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: c3e797de98e03e415b5958a4e2080aa60ddbc253
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
