Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: dc6a09347858ef7a919c4a28dcc7ccf80c781a13
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
