Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: e6fdba6b2c6768dc9c6c090010e09c17628e0948
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
