Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: de7b43d93c25cda5141e1329b7dea0c0e810dd75
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
