Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: d6004a4ca03779b1aca721fd1376e9cfa48a414c
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
