Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 73a3d2aacd6ffd03b8ff3c925e4b04b34dc1cd95
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
