Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 35901b761ba780aed3bf9a3396c414408715f75d
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
