Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 7954acf861be4c823c3273bba4caeee8104f4f1e
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
