Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 6d93bc1c6c7948e5d934dd3e02fdede81ffc5d18
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
