Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 3e425852017b24fe9935533aa8790657e43bd908
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
