Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 2654783fe5c1032d4c2d9a26971b22cc58f0940b
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
