Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 26562d8268c7e77024c64721a4950cc20af04b5e
  Tags:
  - latest
  - base
GitRepo: https://github.com/clearlinux/docker-brew-clearlinux.git
KnownTags:
  base: {}
  latest: {}
Name: clearlinux
