Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 25/apache
  GitCommit: 570ac60ed20c5197eb050c8ec55eae5d9c3e58eb
  Tags:
  - 25.0.7-apache
  - 25.0-apache
  - 25-apache
  - stable-apache
  - production-apache
  - 25.0.7
  - "25.0"
  - "25"
  - stable
  - production
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 25/fpm
  GitCommit: 570ac60ed20c5197eb050c8ec55eae5d9c3e58eb
  Tags:
  - 25.0.7-fpm
  - 25.0-fpm
  - 25-fpm
  - stable-fpm
  - production-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 25/fpm-alpine
  GitCommit: fb5866ada90529aa04da11c9b0f96511b61a09d5
  Tags:
  - 25.0.7-fpm-alpine
  - 25.0-fpm-alpine
  - 25-fpm-alpine
  - stable-fpm-alpine
  - production-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 26/apache
  GitCommit: 22d28e45cdcdb553239af45c7b1566d628f72bc6
  Tags:
  - 26.0.2-apache
  - 26.0-apache
  - 26-apache
  - 26.0.2
  - "26.0"
  - "26"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 26/fpm
  GitCommit: 22d28e45cdcdb553239af45c7b1566d628f72bc6
  Tags:
  - 26.0.2-fpm
  - 26.0-fpm
  - 26-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 26/fpm-alpine
  GitCommit: 22d28e45cdcdb553239af45c7b1566d628f72bc6
  Tags:
  - 26.0.2-fpm-alpine
  - 26.0-fpm-alpine
  - 26-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 27/apache
  GitCommit: ceb2893af1c4ee9bec07082c82f5b638bb47cff7
  Tags:
  - 27.0.0-apache
  - 27.0-apache
  - 27-apache
  - apache
  - 27.0.0
  - "27.0"
  - "27"
  - latest
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 27/fpm
  GitCommit: ceb2893af1c4ee9bec07082c82f5b638bb47cff7
  Tags:
  - 27.0.0-fpm
  - 27.0-fpm
  - 27-fpm
  - fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 27/fpm-alpine
  GitCommit: ceb2893af1c4ee9bec07082c82f5b638bb47cff7
  Tags:
  - 27.0.0-fpm-alpine
  - 27.0-fpm-alpine
  - 27-fpm-alpine
  - fpm-alpine
GitRepo: https://github.com/nextcloud/docker.git
KnownTags:
  "25": {}
  25-apache: {}
  25-fpm: {}
  25-fpm-alpine: {}
  "25.0": {}
  25.0-apache: {}
  25.0-fpm: {}
  25.0-fpm-alpine: {}
  25.0.7: {}
  25.0.7-apache: {}
  25.0.7-fpm: {}
  25.0.7-fpm-alpine: {}
  "26": {}
  26-apache: {}
  26-fpm: {}
  26-fpm-alpine: {}
  "26.0": {}
  26.0-apache: {}
  26.0-fpm: {}
  26.0-fpm-alpine: {}
  26.0.2: {}
  26.0.2-apache: {}
  26.0.2-fpm: {}
  26.0.2-fpm-alpine: {}
  "27": {}
  27-apache: {}
  27-fpm: {}
  27-fpm-alpine: {}
  "27.0": {}
  27.0-apache: {}
  27.0-fpm: {}
  27.0-fpm-alpine: {}
  27.0.0: {}
  27.0.0-apache: {}
  27.0.0-fpm: {}
  27.0.0-fpm-alpine: {}
  apache: {}
  fpm: {}
  fpm-alpine: {}
  latest: {}
  production: {}
  production-apache: {}
  production-fpm: {}
  production-fpm-alpine: {}
  stable: {}
  stable-apache: {}
  stable-fpm: {}
  stable-fpm-alpine: {}
Name: nextcloud
