Blocks:
- Architectures: null
  Directory: ""
  GitCommit: e16e955a67f48c1e8dc0af87ba6c0b7f8302bad2
  Tags:
  - 5.0.1
  - "5.0"
  - "5"
  - latest
- Architectures: null
  Directory: onbuild
  GitCommit: 9df9b5e6b1519faf22e1565c2caaebf7cc1c665b
  Tags:
  - onbuild
- Architectures: null
  Directory: ""
  GitCommit: 74262f5482517f779681590b0194758ff75cf77c
  Tags:
  - 5.0.0.1
  - 5.0.0
- Architectures: null
  Directory: ""
  GitCommit: 04006011344175c10b6864193eee74d626b84b11
  Tags:
  - 4.2.6
  - "4.2"
  - "4"
GitRepo: https://github.com/docker-library/rails.git
KnownTags:
  "4": {}
  "4.2": {}
  4.2.6: {}
  "5": {}
  "5.0": {}
  5.0.0: {}
  5.0.0.1: {}
  5.0.1: {}
  latest: {}
  onbuild: {}
Name: rails
