Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: 5.2/5.2.9/debian
  GitCommit: dfb126db2d9c956d84ff381e7b1ee9f642edf716
  Tags:
  - 5.2.9-python38
  - 5.2-python38
  - 5-python38
  - python38
  - 5.2.9
  - "5.2"
  - "5"
  - latest
- Architectures:
  - amd64
  - arm64v8
  Directory: 5.2/5.2.8/debian
  GitCommit: dfb126db2d9c956d84ff381e7b1ee9f642edf716
  Tags:
  - 5.2.8-python38
  - 5.2.8
GitRepo: https://github.com/plone/plone.docker.git
KnownTags:
  "5": {}
  5-python38: {}
  "5.2": {}
  5.2-python38: {}
  5.2.8: {}
  5.2.8-python38: {}
  5.2.9: {}
  5.2.9-python38: {}
  latest: {}
  python38: {}
Name: plone
