Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "4"
  GitCommit: c9c54b18f79a66409a3153a94f629ea68f08647c
  Tags:
  - 4.8.1-standalone
  - 4-standalone
  - standalone
  - 4.8.1
  - "4"
  - latest
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 4/fastcgi
  GitCommit: c9c54b18f79a66409a3153a94f629ea68f08647c
  Tags:
  - 4.8.1-fastcgi
  - 4-fastcgi
  - fastcgi
GitRepo: https://github.com/TimWolla/docker-adminer.git
KnownTags:
  "4": {}
  4-fastcgi: {}
  4-standalone: {}
  4.8.1: {}
  4.8.1-fastcgi: {}
  4.8.1-standalone: {}
  fastcgi: {}
  latest: {}
  standalone: {}
Name: adminer
