Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "4"
  GitCommit: c9c54b18f79a66409a3153a94f629ea68f08647c
  Tags:
  - 4.8.1-standalone
  - 4-standalone
  - standalone
  - 4.8.1
  - "4"
  - latest
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 4/fastcgi
  GitCommit: c9c54b18f79a66409a3153a94f629ea68f08647c
  Tags:
  - 4.8.1-fastcgi
  - 4-fastcgi
  - fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "4"
  GitCommit: 40a2516bf4f95dc76a839b8b76e4a5eae2378e67
  Tags:
  - 4.8.0-standalone
  - 4.8.0
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 4/fastcgi
  GitCommit: 40a2516bf4f95dc76a839b8b76e4a5eae2378e67
  Tags:
  - 4.8.0-fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "4"
  GitCommit: d55937360e7c970a25bf8870305d981465a88cd9
  Tags:
  - 4.7.9-standalone
  - 4.7-standalone
  - 4.7.9
  - "4.7"
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 4/fastcgi
  GitCommit: d55937360e7c970a25bf8870305d981465a88cd9
  Tags:
  - 4.7.9-fastcgi
  - 4.7-fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "4"
  GitCommit: 5a55c1bb1bba06de4e7f806397ade6175d222ff5
  Tags:
  - 4.7.8-standalone
  - 4.7.8
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 4/fastcgi
  GitCommit: 5a55c1bb1bba06de4e7f806397ade6175d222ff5
  Tags:
  - 4.7.8-fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "4"
  GitCommit: 18344428b4b12907f82ab8c03e865094d1ae0663
  Tags:
  - 4.7.7-standalone
  - 4.7.7
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 4/fastcgi
  GitCommit: 18344428b4b12907f82ab8c03e865094d1ae0663
  Tags:
  - 4.7.7-fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "4"
  GitCommit: c58c6fbfee1872d639e7aa1cb73615b700421160
  Tags:
  - 4.7.6-standalone
  - 4.7.6
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 4/fastcgi
  GitCommit: 49294767416db575e1cb902b970cc60ba6912a6a
  Tags:
  - 4.7.6-fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: "4"
  GitCommit: 96cb9a7418cf208e3c64ef699b5a3e3eb890dee3
  Tags:
  - 4.7.5-standalone
  - 4.7.5
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: 4/fastcgi
  GitCommit: 96cb9a7418cf208e3c64ef699b5a3e3eb890dee3
  Tags:
  - 4.7.5-fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: "4"
  GitCommit: d564e3ea7af5d3335527d9b9eab30555967e458f
  Tags:
  - 4.7.4-standalone
  - 4.7.4
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: 4/fastcgi
  GitCommit: b8632301cfc1d850ffcc0672f5d36b005a5752ea
  Tags:
  - 4.7.4-fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: "4"
  GitCommit: 0b7ac63344767be6d7903444f40d8b9885b5d7bd
  Tags:
  - 4.7.3-standalone
  - 4.7.3
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: 4/fastcgi
  GitCommit: 0b7ac63344767be6d7903444f40d8b9885b5d7bd
  Tags:
  - 4.7.3-fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: "4"
  GitCommit: 0e417afc25da3af71e7cc4a069c6e3cf92e10159
  Tags:
  - 4.7.2-standalone
  - 4.7.2
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: 4/fastcgi
  GitCommit: 0e417afc25da3af71e7cc4a069c6e3cf92e10159
  Tags:
  - 4.7.2-fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: "4"
  GitCommit: 178f07b71e7a5590569bbf4934d446f5534bf160
  Tags:
  - 4.7.1-standalone
  - 4.7.1
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: 4/fastcgi
  GitCommit: 178f07b71e7a5590569bbf4934d446f5534bf160
  Tags:
  - 4.7.1-fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: "4"
  GitCommit: 9995b788b8948892a1aed163ab78796d5acaa276
  Tags:
  - 4.7.0-standalone
  - 4.7.0
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: 4/fastcgi
  GitCommit: 9995b788b8948892a1aed163ab78796d5acaa276
  Tags:
  - 4.7.0-fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: "4"
  GitCommit: aea009a06cada82b4ca0cadca279b63dea88e707
  Tags:
  - 4.6.3-standalone
  - 4.6-standalone
  - 4.6.3
  - "4.6"
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: 4/fastcgi
  GitCommit: aea009a06cada82b4ca0cadca279b63dea88e707
  Tags:
  - 4.6.3-fastcgi
  - 4.6-fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: "4"
  GitCommit: 2e70fec7eb301710fa4ac2080062175e350daaae
  Tags:
  - 4.6.2-standalone
  - 4.6.2
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: 4/fastcgi
  GitCommit: 2e70fec7eb301710fa4ac2080062175e350daaae
  Tags:
  - 4.6.2-fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: "4"
  GitCommit: 7730bed48bb21686486346ea70c75b423a5d3755
  Tags:
  - 4.6.1-standalone
  - 4.6.1
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: 4/fastcgi
  GitCommit: 7730bed48bb21686486346ea70c75b423a5d3755
  Tags:
  - 4.6.1-fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: "4.6"
  GitCommit: 59a748d49b48ee43f7f8d3f4df7154321c1fb6e0
  Tags:
  - 4.6.0-standalone
  - 4.6.0
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: 4.6/fastcgi
  GitCommit: 59a748d49b48ee43f7f8d3f4df7154321c1fb6e0
  Tags:
  - 4.6.0-fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: "4.5"
  GitCommit: e99f98a8334ff8dad913bf2cbe8ac476594e4089
  Tags:
  - 4.5.0-standalone
  - 4.5-standalone
  - 4.5.0
  - "4.5"
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: 4.5/fastcgi
  GitCommit: e99f98a8334ff8dad913bf2cbe8ac476594e4089
  Tags:
  - 4.5.0-fastcgi
  - 4.5-fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: "4.4"
  GitCommit: a49e226a52f856d35b28a907b53a649eb4eda7c5
  Tags:
  - 4.4.0-standalone
  - 4.4-standalone
  - 4.4.0
  - "4.4"
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: 4.4/fastcgi
  GitCommit: a49e226a52f856d35b28a907b53a649eb4eda7c5
  Tags:
  - 4.4.0-fastcgi
  - 4.4-fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: "4.3"
  GitCommit: 58a494d7add8975552d5ab03c16560f1961bae79
  Tags:
  - 4.3.1-standalone
  - 4.3-standalone
  - 4.3.1
  - "4.3"
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: 4.3/fastcgi
  GitCommit: 58a494d7add8975552d5ab03c16560f1961bae79
  Tags:
  - 4.3.1-fastcgi
  - 4.3-fastcgi
- Architectures: null
  Directory: "4.3"
  GitCommit: 583a3425bf560b744f0ac16be398b2b589474c8b
  Tags:
  - 4.3.0-standalone
  - 4.3.0
- Architectures: null
  Directory: 4.3/fastcgi
  GitCommit: a07553cc164c5fd9533cda44568a58dfad0fa864
  Tags:
  - 4.3.0-fastcgi
- Architectures: null
  Directory: "4.2"
  GitCommit: 66fd66f352b5447d154bfed125d10b0c9ea61c2b
  Tags:
  - 4.2.5-standalone
  - 4.2-standalone
  - 4.2.5
  - "4.2"
- Architectures: null
  Directory: 4.2/fastcgi
  GitCommit: 66fd66f352b5447d154bfed125d10b0c9ea61c2b
  Tags:
  - 4.2.5-fastcgi
  - 4.2-fastcgi
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "4"
  GitCommit: 40a2516bf4f95dc76a839b8b76e4a5eae2378e67
  Tags:
  - 4.8-standalone
  - "4.8"
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 4/fastcgi
  GitCommit: 40a2516bf4f95dc76a839b8b76e4a5eae2378e67
  Tags:
  - 4.8-fastcgi
GitRepo: https://github.com/TimWolla/docker-adminer.git
KnownTags:
  "4": {}
  4-fastcgi: {}
  4-standalone: {}
  "4.2": {}
  4.2-fastcgi: {}
  4.2-standalone: {}
  4.2.5: {}
  4.2.5-fastcgi: {}
  4.2.5-standalone: {}
  "4.3": {}
  4.3-fastcgi: {}
  4.3-standalone: {}
  4.3.0: {}
  4.3.0-fastcgi: {}
  4.3.0-standalone: {}
  4.3.1: {}
  4.3.1-fastcgi: {}
  4.3.1-standalone: {}
  "4.4": {}
  4.4-fastcgi: {}
  4.4-standalone: {}
  4.4.0: {}
  4.4.0-fastcgi: {}
  4.4.0-standalone: {}
  "4.5": {}
  4.5-fastcgi: {}
  4.5-standalone: {}
  4.5.0: {}
  4.5.0-fastcgi: {}
  4.5.0-standalone: {}
  "4.6": {}
  4.6-fastcgi: {}
  4.6-standalone: {}
  4.6.0: {}
  4.6.0-fastcgi: {}
  4.6.0-standalone: {}
  4.6.1: {}
  4.6.1-fastcgi: {}
  4.6.1-standalone: {}
  4.6.2: {}
  4.6.2-fastcgi: {}
  4.6.2-standalone: {}
  4.6.3: {}
  4.6.3-fastcgi: {}
  4.6.3-standalone: {}
  "4.7": {}
  4.7-fastcgi: {}
  4.7-standalone: {}
  4.7.0: {}
  4.7.0-fastcgi: {}
  4.7.0-standalone: {}
  4.7.1: {}
  4.7.1-fastcgi: {}
  4.7.1-standalone: {}
  4.7.2: {}
  4.7.2-fastcgi: {}
  4.7.2-standalone: {}
  4.7.3: {}
  4.7.3-fastcgi: {}
  4.7.3-standalone: {}
  4.7.4: {}
  4.7.4-fastcgi: {}
  4.7.4-standalone: {}
  4.7.5: {}
  4.7.5-fastcgi: {}
  4.7.5-standalone: {}
  4.7.6: {}
  4.7.6-fastcgi: {}
  4.7.6-standalone: {}
  4.7.7: {}
  4.7.7-fastcgi: {}
  4.7.7-standalone: {}
  4.7.8: {}
  4.7.8-fastcgi: {}
  4.7.8-standalone: {}
  4.7.9: {}
  4.7.9-fastcgi: {}
  4.7.9-standalone: {}
  "4.8": {}
  4.8-fastcgi: {}
  4.8-standalone: {}
  4.8.0: {}
  4.8.0-fastcgi: {}
  4.8.0-standalone: {}
  4.8.1: {}
  4.8.1-fastcgi: {}
  4.8.1-standalone: {}
  fastcgi: {}
  latest: {}
  standalone: {}
Name: adminer
