Blocks:
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: r-base/4.3.1
  GitCommit: 697411900789ece481e6a24be01e1ab3a3857b7d
  Tags:
  - 4.3.1
  - latest
GitRepo: https://github.com/rocker-org/rocker.git
KnownTags:
  4.3.1: {}
  latest: {}
Name: r-base
