Blocks:
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: r-base/4.3.1
  GitCommit: 697411900789ece481e6a24be01e1ab3a3857b7d
  Tags:
  - 4.3.1
  - latest
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: r-base/4.3.0
  GitCommit: 369880a2813efaba8a719188a71b3a655fda0845
  Tags:
  - 4.3.0
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: r-base/4.2.3
  GitCommit: c9e01210d9ca77b8b7f7293f71f88782a1ca2a4e
  Tags:
  - 4.2.3
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: r-base/4.2.2
  GitCommit: 2f92c6c8b8da7b3e61aabc44cacc0439bf267d31
  Tags:
  - 4.2.2
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: r-base/4.2.1
  GitCommit: dedd29461f0952fef9b432a58e2540ad58305a42
  Tags:
  - 4.2.1
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: r-base/4.2.0
  GitCommit: f69d608f08f472438672ec34f430141ea84c509a
  Tags:
  - 4.2.0
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: r-base/4.1.3
  GitCommit: 2fb991537d60c20bc11a93a76587d6e25bb3a054
  Tags:
  - 4.1.3
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: r-base/4.1.2
  GitCommit: df1414259dceb0282f163f29f4dccfa184d38d86
  Tags:
  - 4.1.2
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: r-base/4.1.1
  GitCommit: a2dc8a7816d7cf8adab20ee9baf7d4ae283b4b92
  Tags:
  - 4.1.1
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: r-base/4.1.0
  GitCommit: bc5f41cd3464bf18c571e7ff35383aab08b8ee71
  Tags:
  - 4.1.0
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: r-base/4.0.5
  GitCommit: dd592d5c3ab289f33bf06c6c84eda354ddc40a38
  Tags:
  - 4.0.5
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: r-base/4.0.4
  GitCommit: 6e6287d3c991ee7ff35e7d0c99ba70babc196cdc
  Tags:
  - 4.0.4
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: r-base/4.0.3
  GitCommit: f710db09bce5ed4670f80ff4bf5a6cc8f022b76b
  Tags:
  - 4.0.3
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: r-base/latest
  GitCommit: 206d35749495c5309183bfabaea90091eaff5cf4
  Tags:
  - 4.0.2
- Architectures:
  - amd64
  - arm64v8
  Directory: r-base/latest
  GitCommit: dee1c76816be5c370771243bee9a0e594717ed0f
  Tags:
  - 4.0.1
- Architectures:
  - amd64
  - arm64v8
  Directory: r-base/latest
  GitCommit: 0317dc922dc7b9181d86446436acdd7f77ee0f17
  Tags:
  - 4.0.0
- Architectures:
  - amd64
  - arm64v8
  Directory: r-base
  GitCommit: e76a46e4d082c0294437c34df1072f48c6fa3685
  Tags:
  - 3.6.3
- Architectures:
  - amd64
  - arm64v8
  Directory: r-base
  GitCommit: df56b98e4a2a4611fa9aacae99c4a304531c2640
  Tags:
  - 3.6.2
- Architectures:
  - amd64
  - arm64v8
  Directory: r-base
  GitCommit: 919df9809c677916100cf837be687f6704d6b1b1
  Tags:
  - 3.6.1
- Architectures:
  - amd64
  - arm64v8
  Directory: r-base
  GitCommit: 81766dfd355860d733d1cac98f583c2f3aa430ac
  Tags:
  - 3.6.0
- Architectures:
  - amd64
  - arm64v8
  Directory: r-base
  GitCommit: ab427992a183729b2698e06d078eca53853c8044
  Tags:
  - 3.5.3
- Architectures:
  - amd64
  - arm64v8
  Directory: r-base
  GitCommit: a7ecee9111f3b5dde35555d338a0e30401f5c095
  Tags:
  - 3.5.2
- Architectures:
  - amd64
  - arm64v8
  Directory: r-base
  GitCommit: b9f9289ef27f07dc2f2b64d56d12646770b9b233
  Tags:
  - 3.5.1
GitRepo: https://github.com/rocker-org/rocker.git
KnownTags:
  3.5.1: {}
  3.5.2: {}
  3.5.3: {}
  3.6.0: {}
  3.6.1: {}
  3.6.2: {}
  3.6.3: {}
  4.0.0: {}
  4.0.1: {}
  4.0.2: {}
  4.0.3: {}
  4.0.4: {}
  4.0.5: {}
  4.1.0: {}
  4.1.1: {}
  4.1.2: {}
  4.1.3: {}
  4.2.0: {}
  4.2.1: {}
  4.2.2: {}
  4.2.3: {}
  4.3.0: {}
  4.3.1: {}
  latest: {}
Name: r-base
