Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: "6.0"
  GitCommit: 84e3f6588620183b48b7eb62a18070b793eff019
  Tags:
  - 6.0.3
  - "6.0"
- Architectures:
  - amd64
  - arm64v8
  Directory: "6.1"
  GitCommit: 84e3f6588620183b48b7eb62a18070b793eff019
  Tags:
  - 6.1.0
  - "6.1"
  - "6"
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.0/jdk8
  GitCommit: 84e3f6588620183b48b7eb62a18070b793eff019
  Tags:
  - 7.0.3-jdk8-temurin
  - 7.0-jdk8-temurin
  - 7.0.3-jdk8
  - 7.0-jdk8
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.0/jdk11
  GitCommit: 84e3f6588620183b48b7eb62a18070b793eff019
  Tags:
  - 7.0.3-jdk11-temurin
  - 7.0-jdk11-temurin
  - 7.0.3-jdk11
  - 7.0-jdk11
  - 7.0.3
  - "7.0"
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.1/jdk8
  GitCommit: 84e3f6588620183b48b7eb62a18070b793eff019
  Tags:
  - 7.1.3-jdk8-temurin
  - 7.1-jdk8-temurin
  - 7.1.3-jdk8
  - 7.1-jdk8
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.1/jdk11
  GitCommit: 84e3f6588620183b48b7eb62a18070b793eff019
  Tags:
  - 7.1.3-jdk11-temurin
  - 7.1-jdk11-temurin
  - 7.1.3-jdk11
  - 7.1-jdk11
  - 7.1.3
  - "7.1"
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.2/jdk8
  GitCommit: 84e3f6588620183b48b7eb62a18070b793eff019
  Tags:
  - 7.2.2-jdk8-temurin
  - 7.2-jdk8-temurin
  - 7.2.2-jdk8
  - 7.2-jdk8
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.2/jdk11
  GitCommit: 84e3f6588620183b48b7eb62a18070b793eff019
  Tags:
  - 7.2.2-jdk11-temurin
  - 7.2-jdk11-temurin
  - 7.2.2-jdk11
  - 7.2-jdk11
  - 7.2.2
  - "7.2"
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.3/jdk8
  GitCommit: 3e0e7b00746f56ef7232b68c5e25afa6d688bd7c
  Tags:
  - 7.3.3-jdk8-temurin
  - 7.3-jdk8-temurin
  - 7.3.3-jdk8
  - 7.3-jdk8
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.3/jdk11
  GitCommit: 3e0e7b00746f56ef7232b68c5e25afa6d688bd7c
  Tags:
  - 7.3.3-jdk11-temurin
  - 7.3-jdk11-temurin
  - 7.3.3-jdk11
  - 7.3-jdk11
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.3/jdk17
  GitCommit: 3e0e7b00746f56ef7232b68c5e25afa6d688bd7c
  Tags:
  - 7.3.3-jdk17-temurin
  - 7.3-jdk17-temurin
  - 7.3.3-jdk17
  - 7.3-jdk17
  - 7.3.3
  - "7.3"
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.4/jdk8
  GitCommit: 3e0e7b00746f56ef7232b68c5e25afa6d688bd7c
  Tags:
  - 7.4.0-jdk8-temurin
  - 7.4-jdk8-temurin
  - 7-jdk8-temurin
  - 7.4.0-jdk8
  - 7.4-jdk8
  - 7-jdk8
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.4/jdk11
  GitCommit: 3e0e7b00746f56ef7232b68c5e25afa6d688bd7c
  Tags:
  - 7.4.0-jdk11-temurin
  - 7.4-jdk11-temurin
  - 7-jdk11-temurin
  - 7.4.0-jdk11
  - 7.4-jdk11
  - 7-jdk11
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.4/jdk17
  GitCommit: 3e0e7b00746f56ef7232b68c5e25afa6d688bd7c
  Tags:
  - 7.4.0-jdk17-temurin
  - 7.4-jdk17-temurin
  - 7-jdk17-temurin
  - 7.4.0-jdk17
  - 7.4-jdk17
  - 7-jdk17
  - 7.4.0
  - "7.4"
  - "7"
  - latest
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.3/jdk8
  GitCommit: 26cf14f6d72e66571f356ecc63993a7197a2e023
  Tags:
  - 7.3.2-jdk8-temurin
  - 7.3.2-jdk8
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.3/jdk11
  GitCommit: 26cf14f6d72e66571f356ecc63993a7197a2e023
  Tags:
  - 7.3.2-jdk11-temurin
  - 7.3.2-jdk11
  - 7.3.2
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.3/jdk8
  GitCommit: f20479553347a4eccea04186ec3d30208cd824b7
  Tags:
  - 7.3.0-jdk8-temurin
  - 7.3.0-jdk8
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.3/jdk11
  GitCommit: f20479553347a4eccea04186ec3d30208cd824b7
  Tags:
  - 7.3.0-jdk11-temurin
  - 7.3.0-jdk11
  - 7.3.0
- Architectures:
  - amd64
  Directory: 7.0/jdk8
  GitCommit: f3aaece15133b9405aef20c5d378c5a83aba7585
  Tags:
  - 7.0.3-jdk8-openjdk
  - 7.0-jdk8-openjdk
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.0/jdk11
  GitCommit: f3aaece15133b9405aef20c5d378c5a83aba7585
  Tags:
  - 7.0.3-jdk11-openjdk
  - 7.0-jdk11-openjdk
- Architectures:
  - amd64
  Directory: 7.1/jdk8
  GitCommit: ee4aaa6a12fbe0658c5ba7c0b35d6b65bb5f1bd5
  Tags:
  - 7.1.3-jdk8-openjdk
  - 7.1-jdk8-openjdk
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.1/jdk11
  GitCommit: ee4aaa6a12fbe0658c5ba7c0b35d6b65bb5f1bd5
  Tags:
  - 7.1.3-jdk11-openjdk
  - 7.1-jdk11-openjdk
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.2/jdk11
  GitCommit: 347dcb6cdbba7960b3bbfbb7a4d331f828288f03
  Tags:
  - 7.2.2-jdk11-openjdk
  - 7.2-jdk11-openjdk
  - 7-jdk11-openjdk
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.2/jdk8
  GitCommit: 347dcb6cdbba7960b3bbfbb7a4d331f828288f03
  Tags:
  - 7.2.2-jdk8-openjdk
  - 7.2-jd8-openjdk
  - 7-jdk8-openjdk
- Architectures:
  - amd64
  Directory: 7.1/jdk8
  GitCommit: 7bdd2632e1cae0bf838899d591aadb2dd128c41a
  Tags:
  - 7.1.2-jdk8-openjdk
  - 7.1.2-jdk8
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.1/jdk11
  GitCommit: 7bdd2632e1cae0bf838899d591aadb2dd128c41a
  Tags:
  - 7.1.2-jdk11-openjdk
  - 7.1.2-jdk11
  - 7.1.2
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.2/jdk11
  GitCommit: fe38e8a5b87c4cb29b964a49f9ce7f0a50752b48
  Tags:
  - 7.2.0-jdk11-openjdk
  - 7.2.0-jdk11
  - 7.2.0
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.2/jdk8
  GitCommit: fe38e8a5b87c4cb29b964a49f9ce7f0a50752b48
  Tags:
  - 7.2.0-jdk8-openjdk
  - 7.2.0-jdk8
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.2/jdk8
  GitCommit: 9b286d6ad71126b2848b76a56d75f1e7cfb8d4ab
  Tags:
  - 7.2.0-jdk9
- Architectures:
  - amd64
  Directory: 7.1/jdk8
  GitCommit: f3aaece15133b9405aef20c5d378c5a83aba7585
  Tags:
  - 7.1.1-jdk8-openjdk
  - 7.1.1-jdk8
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.1/jdk11
  GitCommit: f3aaece15133b9405aef20c5d378c5a83aba7585
  Tags:
  - 7.1.1-jdk11-openjdk
  - 7.1.1-jdk11
  - 7.1.1
- Architectures:
  - amd64
  Directory: 7.1/jdk8
  GitCommit: 45001c033ed1837a9374a9285b7d2e8acfee6dca
  Tags:
  - 7.1.0-jdk8-openjdk
  - 7.1.0-jdk8
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.1/jdk11
  GitCommit: 45001c033ed1837a9374a9285b7d2e8acfee6dca
  Tags:
  - 7.1.0-jdk11-openjdk
  - 7.1.0-jdk11
  - 7.1.0
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.0/jre8
  GitCommit: c93f3767ee869fdc4b1d8df73b03c55096a596eb
  Tags:
  - 7.0.3-jre8
  - 7.0-jre8
  - 7-jre8
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.0/jre8-alpine
  GitCommit: c93f3767ee869fdc4b1d8df73b03c55096a596eb
  Tags:
  - 7.0.3-jre8-alpine
  - 7.0-jre8-alpine
  - 7-jre8-alpine
  - 7.0.3-alpine
  - 7.0-alpine
  - 7-alpine
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.0/jre11
  GitCommit: c93f3767ee869fdc4b1d8df73b03c55096a596eb
  Tags:
  - 7.0.3-jre11
  - 7.0-jre11
  - 7-jre11
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.0/jre8
  GitCommit: db18f37e9da49a859943e5a1156a19b01e441dc5
  Tags:
  - 7.0.2-jre8
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.0/jre8-alpine
  GitCommit: db18f37e9da49a859943e5a1156a19b01e441dc5
  Tags:
  - 7.0.2-jre8-alpine
  - 7.0.2-alpine
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.0/jre11
  GitCommit: db18f37e9da49a859943e5a1156a19b01e441dc5
  Tags:
  - 7.0.2-jre11
  - 7.0.2
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.0/jre10
  GitCommit: db18f37e9da49a859943e5a1156a19b01e441dc5
  Tags:
  - 7.0.2-jre10
  - 7.0-jre10
  - 7-jre10
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.0/jre8
  GitCommit: 74135bdf4ac57d3c6a23d402ee847577d5db7ea5
  Tags:
  - 7.0.1-jre8
  - 7.0.1
- Architectures:
  - amd64
  - arm64v8
  Directory: 7.0/jre8-alpine
  GitCommit: 74135bdf4ac57d3c6a23d402ee847577d5db7ea5
  Tags:
  - 7.0.1-jre8-alpine
  - 7.0.1-alpine
- Architectures: null
  Directory: 7.0/jre8
  GitCommit: 0842a9d0397d1d4d6fbe157c9ffbbbd574c0c53b
  Tags:
  - 7.0.0-jre8
  - 7.0.0
- Architectures: null
  Directory: 7.0/jre8-alpine
  GitCommit: 0842a9d0397d1d4d6fbe157c9ffbbbd574c0c53b
  Tags:
  - 7.0.0-jre8-alpine
  - 7.0.0-alpine
GitRepo: https://github.com/Lightstreamer/Docker.git
KnownTags:
  "6": {}
  "6.0": {}
  6.0.3: {}
  "6.1": {}
  6.1.0: {}
  "7": {}
  7-alpine: {}
  7-jdk8: {}
  7-jdk8-openjdk: {}
  7-jdk8-temurin: {}
  7-jdk11: {}
  7-jdk11-openjdk: {}
  7-jdk11-temurin: {}
  7-jdk17: {}
  7-jdk17-temurin: {}
  7-jre8: {}
  7-jre8-alpine: {}
  7-jre10: {}
  7-jre11: {}
  "7.0": {}
  7.0-alpine: {}
  7.0-jdk8: {}
  7.0-jdk8-openjdk: {}
  7.0-jdk8-temurin: {}
  7.0-jdk11: {}
  7.0-jdk11-openjdk: {}
  7.0-jdk11-temurin: {}
  7.0-jre8: {}
  7.0-jre8-alpine: {}
  7.0-jre10: {}
  7.0-jre11: {}
  7.0.0: {}
  7.0.0-alpine: {}
  7.0.0-jre8: {}
  7.0.0-jre8-alpine: {}
  7.0.1: {}
  7.0.1-alpine: {}
  7.0.1-jre8: {}
  7.0.1-jre8-alpine: {}
  7.0.2: {}
  7.0.2-alpine: {}
  7.0.2-jre8: {}
  7.0.2-jre8-alpine: {}
  7.0.2-jre10: {}
  7.0.2-jre11: {}
  7.0.3: {}
  7.0.3-alpine: {}
  7.0.3-jdk8: {}
  7.0.3-jdk8-openjdk: {}
  7.0.3-jdk8-temurin: {}
  7.0.3-jdk11: {}
  7.0.3-jdk11-openjdk: {}
  7.0.3-jdk11-temurin: {}
  7.0.3-jre8: {}
  7.0.3-jre8-alpine: {}
  7.0.3-jre11: {}
  "7.1": {}
  7.1-jdk8: {}
  7.1-jdk8-openjdk: {}
  7.1-jdk8-temurin: {}
  7.1-jdk11: {}
  7.1-jdk11-openjdk: {}
  7.1-jdk11-temurin: {}
  7.1.0: {}
  7.1.0-jdk8: {}
  7.1.0-jdk8-openjdk: {}
  7.1.0-jdk11: {}
  7.1.0-jdk11-openjdk: {}
  7.1.1: {}
  7.1.1-jdk8: {}
  7.1.1-jdk8-openjdk: {}
  7.1.1-jdk11: {}
  7.1.1-jdk11-openjdk: {}
  7.1.2: {}
  7.1.2-jdk8: {}
  7.1.2-jdk8-openjdk: {}
  7.1.2-jdk11: {}
  7.1.2-jdk11-openjdk: {}
  7.1.3: {}
  7.1.3-jdk8: {}
  7.1.3-jdk8-openjdk: {}
  7.1.3-jdk8-temurin: {}
  7.1.3-jdk11: {}
  7.1.3-jdk11-openjdk: {}
  7.1.3-jdk11-temurin: {}
  "7.2": {}
  7.2-jd8-openjdk: {}
  7.2-jdk8: {}
  7.2-jdk8-temurin: {}
  7.2-jdk11: {}
  7.2-jdk11-openjdk: {}
  7.2-jdk11-temurin: {}
  7.2.0: {}
  7.2.0-jdk8: {}
  7.2.0-jdk8-openjdk: {}
  7.2.0-jdk9: {}
  7.2.0-jdk11: {}
  7.2.0-jdk11-openjdk: {}
  7.2.2: {}
  7.2.2-jdk8: {}
  7.2.2-jdk8-openjdk: {}
  7.2.2-jdk8-temurin: {}
  7.2.2-jdk11: {}
  7.2.2-jdk11-openjdk: {}
  7.2.2-jdk11-temurin: {}
  "7.3": {}
  7.3-jdk8: {}
  7.3-jdk8-temurin: {}
  7.3-jdk11: {}
  7.3-jdk11-temurin: {}
  7.3-jdk17: {}
  7.3-jdk17-temurin: {}
  7.3.0: {}
  7.3.0-jdk8: {}
  7.3.0-jdk8-temurin: {}
  7.3.0-jdk11: {}
  7.3.0-jdk11-temurin: {}
  7.3.2: {}
  7.3.2-jdk8: {}
  7.3.2-jdk8-temurin: {}
  7.3.2-jdk11: {}
  7.3.2-jdk11-temurin: {}
  7.3.3: {}
  7.3.3-jdk8: {}
  7.3.3-jdk8-temurin: {}
  7.3.3-jdk11: {}
  7.3.3-jdk11-temurin: {}
  7.3.3-jdk17: {}
  7.3.3-jdk17-temurin: {}
  "7.4": {}
  7.4-jdk8: {}
  7.4-jdk8-temurin: {}
  7.4-jdk11: {}
  7.4-jdk11-temurin: {}
  7.4-jdk17: {}
  7.4-jdk17-temurin: {}
  7.4.0: {}
  7.4.0-jdk8: {}
  7.4.0-jdk8-temurin: {}
  7.4.0-jdk11: {}
  7.4.0-jdk11-temurin: {}
  7.4.0-jdk17: {}
  7.4.0-jdk17-temurin: {}
  latest: {}
Name: lightstreamer
