Blocks:
- Architectures: null
  Directory: alpine
  GitCommit: e1cd2cd1de40103c20adfe40079f2b6282215e72
  Tags:
  - "3.13"
  - 3.13.7
  - latest
GitRepo: https://github.com/TeamSpeak-Systems/teamspeak-linux-docker-images
KnownTags:
  "3.13": {}
  3.13.7: {}
  latest: {}
Name: teamspeak
