Blocks:
- Architectures: null
  Directory: alpine
  GitCommit: e1cd2cd1de40103c20adfe40079f2b6282215e72
  Tags:
  - "3.13"
  - 3.13.7
  - latest
- Architectures: null
  Directory: alpine
  GitCommit: ab76b77f97ba4c150126aaa6a045d3c7f8265ae9
  Tags:
  - 3.13.6
- Architectures: null
  Directory: alpine
  GitCommit: cdd39f87a2b808cf8d4c78eee4fa053622dda2c3
  Tags:
  - 3.13.5
- Architectures: null
  Directory: alpine
  GitCommit: 5539fed973c4550e7f98bd0ca4ab80a67801ba33
  Tags:
  - 3.13.3
- Architectures: null
  Directory: alpine
  GitCommit: f3fdade4d0a97c79d35dda2a5de9042c27d3db86
  Tags:
  - 3.13.2
- Architectures: null
  Directory: alpine
  GitCommit: dd1e68d64552f8848f88b542d2c6d4707a6f20b6
  Tags:
  - "3.12"
  - 3.12.1
- Architectures: null
  Directory: alpine
  GitCommit: 4fc46f2faacc29937e14d7e7cd1da68287001ef7
  Tags:
  - 3.12.0
- Architectures: null
  Directory: alpine
  GitCommit: 12ce1ade4fbc630e0126d863132d21b27a16330a
  Tags:
  - "3.11"
  - 3.11.0
- Architectures: null
  Directory: alpine
  GitCommit: 33fca5e21e07d2af4940d576a4e03d88a4a0956f
  Tags:
  - "3.10"
  - 3.10.2
- Architectures: null
  Directory: alpine
  GitCommit: 4b200eadeb7dcf081679085465e0c024c353bdba
  Tags:
  - 3.10.1
- Architectures: null
  Directory: alpine
  GitCommit: cfb7288d6c568208212c77c08bc0fd8f21c19f50
  Tags:
  - 3.10.0
- Architectures: null
  Directory: alpine
  GitCommit: ef39847a374333c5de84d4cb730bbbc99dd9f18b
  Tags:
  - "3.9"
  - 3.9.1
- Architectures: null
  Directory: alpine
  GitCommit: 2aa15dba1f1af163eb1b3107e32d023a162b792e
  Tags:
  - 3.9.0
- Architectures: null
  Directory: alpine
  GitCommit: b216589f4f6ffcf84d80a648d5dff314ff9dde45
  Tags:
  - "3.8"
  - 3.8.0
- Architectures: null
  Directory: alpine
  GitCommit: d0c8785270b45f1d99fe1393813155c3db455395
  Tags:
  - "3.7"
  - 3.7.1
- Architectures: null
  Directory: alpine
  GitCommit: 90183e0bdcf800895679949d3eab137e7ae43a77
  Tags:
  - 3.7.0
- Architectures: null
  Directory: alpine
  GitCommit: 65f88d83549b4337d46bebb704a2e2a74e949ad2
  Tags:
  - "3.6"
  - 3.6.1
- Architectures: null
  Directory: alpine
  GitCommit: ad73b4d4972ed67eb44d73f4c70558fbc409f9ce
  Tags:
  - 3.6.0
- Architectures: null
  Directory: alpine
  GitCommit: 74b8d3b3c0ef7b9b7d239498a94884b26483217f
  Tags:
  - "3.5"
  - 3.5.1
- Architectures: null
  Directory: alpine
  GitCommit: 39bf86017d0ab13a18d6da08de355c31d42d79e4
  Tags:
  - 3.5.0
- Architectures: null
  Directory: alpine
  GitCommit: ca34caf6fd01b1e476b34ed65b5cabd898ce71f7
  Tags:
  - "3.4"
  - 3.4.0
- Architectures: null
  Directory: alpine
  GitCommit: 4d4ead5c57161e18cf57b8623e892a934de1a643
  Tags:
  - "3.3"
  - 3.3.1
- Architectures: null
  Directory: alpine
  GitCommit: ed11a8e865fbf9eec6883aea38d45664c99afd91
  Tags:
  - 3.3.0
- Architectures: null
  Directory: alpine
  GitCommit: 1da75dc61e5f8358942ee0a0f63154be07791b70
  Tags:
  - "3.2"
  - 3.2.0
- Architectures: null
  Directory: alpine
  GitCommit: 3389ddef4c0c3177d6bf2505af6d41642393aa82
  Tags:
  - "3.1"
  - 3.1.3
- Architectures: null
  Directory: alpine
  GitCommit: 2d3e33931086e8576a5d06c933c444e03a0e1207
  Tags:
  - 3.1.2
- Architectures: null
  Directory: 3.1.1
  GitCommit: 0acf85c990d8289ab5b4c51c1583df4437271995
  Tags:
  - 3.1.1
- Architectures: null
  Directory: 3.1.0
  GitCommit: 29dd9a63a4ade302705d3643bc507605c5e4dfe0
  Tags:
  - 3.1.0
- Architectures: null
  Directory: 3.1.0
  GitCommit: 0aa60b817eec11e41f8a93b225bab48f82133b1b
  Tags:
  - 3.1.0-beta-2
- Architectures: null
  Directory: 3.1.0
  GitCommit: c07609623893eb96bda1616acd63898bca72ffec
  Tags:
  - 3.1.0-beta-1
- Architectures: null
  Directory: 3.1.0
  GitCommit: 0aa60b817eec11e41f8a93b225bab48f82133b1b
  Tags:
  - 3.1.0-Beta-2
- Architectures: null
  Directory: 3.1.0
  GitCommit: c07609623893eb96bda1616acd63898bca72ffec
  Tags:
  - 3.1.0-Beta-1
GitRepo: https://github.com/TeamSpeak-Systems/teamspeak-linux-docker-images
KnownTags:
  "3.1": {}
  3.1.0: {}
  3.1.0-Beta-1: {}
  3.1.0-Beta-2: {}
  3.1.0-beta-1: {}
  3.1.0-beta-2: {}
  3.1.1: {}
  3.1.2: {}
  3.1.3: {}
  "3.2": {}
  3.2.0: {}
  "3.3": {}
  3.3.0: {}
  3.3.1: {}
  "3.4": {}
  3.4.0: {}
  "3.5": {}
  3.5.0: {}
  3.5.1: {}
  "3.6": {}
  3.6.0: {}
  3.6.1: {}
  "3.7": {}
  3.7.0: {}
  3.7.1: {}
  "3.8": {}
  3.8.0: {}
  "3.9": {}
  3.9.0: {}
  3.9.1: {}
  "3.10": {}
  3.10.0: {}
  3.10.1: {}
  3.10.2: {}
  "3.11": {}
  3.11.0: {}
  "3.12": {}
  3.12.0: {}
  3.12.1: {}
  "3.13": {}
  3.13.2: {}
  3.13.3: {}
  3.13.5: {}
  3.13.6: {}
  3.13.7: {}
  latest: {}
Name: teamspeak
