Blocks:
- Architectures: null
  Directory: ga/latest/kernel
  GitCommit: ""
  Tags:
  - kernel
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ga/latest/kernel
  GitCommit: ""
  Tags:
  - kernel-java11-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ga/latest/kernel
  GitCommit: ""
  Tags:
  - kernel-java17-openj9
- Architectures: null
  Directory: ga/latest/full
  GitCommit: ""
  Tags:
  - full
  - latest
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ga/latest/full
  GitCommit: ""
  Tags:
  - full-java11-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ga/latest/full
  GitCommit: ""
  Tags:
  - full-java17-openj9
- Architectures: null
  Directory: ga/23.0.0.5/kernel
  GitCommit: ""
  Tags:
  - 23.0.0.5-kernel-java8-ibmjava
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ga/23.0.0.5/kernel
  GitCommit: ""
  Tags:
  - 23.0.0.5-kernel-java11-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ga/23.0.0.5/kernel
  GitCommit: ""
  Tags:
  - 23.0.0.5-kernel-java17-openj9
- Architectures: null
  Directory: ga/23.0.0.5/full
  GitCommit: ""
  Tags:
  - 23.0.0.5-full-java8-ibmjava
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ga/23.0.0.5/full
  GitCommit: ""
  Tags:
  - 23.0.0.5-full-java11-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ga/23.0.0.5/full
  GitCommit: ""
  Tags:
  - 23.0.0.5-full-java17-openj9
- Architectures: null
  Directory: ga/23.0.0.3/kernel
  GitCommit: ""
  Tags:
  - 23.0.0.3-kernel-java8-ibmjava
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ga/23.0.0.3/kernel
  GitCommit: ""
  Tags:
  - 23.0.0.3-kernel-java11-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ga/23.0.0.3/kernel
  GitCommit: ""
  Tags:
  - 23.0.0.3-kernel-java17-openj9
- Architectures: null
  Directory: ga/23.0.0.3/full
  GitCommit: ""
  Tags:
  - 23.0.0.3-full-java8-ibmjava
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ga/23.0.0.3/full
  GitCommit: ""
  Tags:
  - 23.0.0.3-full-java11-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ga/23.0.0.3/full
  GitCommit: ""
  Tags:
  - 23.0.0.3-full-java17-openj9
- Architectures: null
  Directory: ga/22.0.0.12/kernel
  GitCommit: ""
  Tags:
  - 22.0.0.12-kernel-java8-ibmjava
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ga/22.0.0.12/kernel
  GitCommit: ""
  Tags:
  - 22.0.0.12-kernel-java11-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ga/22.0.0.12/kernel
  GitCommit: ""
  Tags:
  - 22.0.0.12-kernel-java17-openj9
- Architectures: null
  Directory: ga/22.0.0.12/full
  GitCommit: ""
  Tags:
  - 22.0.0.12-full-java8-ibmjava
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ga/22.0.0.12/full
  GitCommit: ""
  Tags:
  - 22.0.0.12-full-java11-openj9
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ga/22.0.0.12/full
  GitCommit: ""
  Tags:
  - 22.0.0.12-full-java17-openj9
GitRepo: https://github.com/WASdev/ci.docker.git
KnownTags:
  22.0.0.12-full-java8-ibmjava: {}
  22.0.0.12-full-java11-openj9: {}
  22.0.0.12-full-java17-openj9: {}
  22.0.0.12-kernel-java8-ibmjava: {}
  22.0.0.12-kernel-java11-openj9: {}
  22.0.0.12-kernel-java17-openj9: {}
  23.0.0.3-full-java8-ibmjava: {}
  23.0.0.3-full-java11-openj9: {}
  23.0.0.3-full-java17-openj9: {}
  23.0.0.3-kernel-java8-ibmjava: {}
  23.0.0.3-kernel-java11-openj9: {}
  23.0.0.3-kernel-java17-openj9: {}
  23.0.0.5-full-java8-ibmjava: {}
  23.0.0.5-full-java11-openj9: {}
  23.0.0.5-full-java17-openj9: {}
  23.0.0.5-kernel-java8-ibmjava: {}
  23.0.0.5-kernel-java11-openj9: {}
  23.0.0.5-kernel-java17-openj9: {}
  full: {}
  full-java11-openj9: {}
  full-java17-openj9: {}
  kernel: {}
  kernel-java11-openj9: {}
  kernel-java17-openj9: {}
  latest: {}
Name: websphere-liberty
