Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: 3f7f06a4eeb066e03f81f5e3d170d1e13606e69e
  Tags:
  - "1"
  - "1.7"
  - 1.7.3
  - 1.7.3-1
  - latest
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: 054c998138c8f8ec6be03c7db711b8435de41e2b
  Tags:
  - 1.7.2
  - 1.7.2-1
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: 1990ddf1f3052cabb010a5a052a4a6e87d82f6fa
  Tags:
  - 1.7.0
  - 1.7.0-1
GitRepo: https://github.com/varnish/docker-hitch.git
KnownTags:
  "1": {}
  "1.7": {}
  1.7.0: {}
  1.7.0-1: {}
  1.7.2: {}
  1.7.2-1: {}
  1.7.3: {}
  1.7.3-1: {}
  latest: {}
Name: hitch
