Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 3fe55c4296018b04c7e1d2efdfcadce9c4017e0a
  Tags:
  - "1"
  - "1.8"
  - 1.8.0
  - 1.8.0-1
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 3f7f06a4eeb066e03f81f5e3d170d1e13606e69e
  Tags:
  - "1.7"
  - 1.7.3
  - 1.7.3-1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 054c998138c8f8ec6be03c7db711b8435de41e2b
  Tags:
  - 1.7.2
  - 1.7.2-1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 1990ddf1f3052cabb010a5a052a4a6e87d82f6fa
  Tags:
  - 1.7.0
  - 1.7.0-1
GitRepo: https://github.com/varnish/docker-hitch.git
KnownTags:
  "1": {}
  "1.7": {}
  1.7.0: {}
  1.7.0-1: {}
  1.7.2: {}
  1.7.2-1: {}
  1.7.3: {}
  1.7.3-1: {}
  "1.8": {}
  1.8.0: {}
  1.8.0-1: {}
  latest: {}
Name: hitch
