Blocks:
- Architectures:
  - amd64
  - ppc64le
  - s390x
  - arm64v8
  Directory: 8/jdk/ubuntu/focal
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-8u372-b07-jdk-focal
  - open-8-jdk-focal
- Architectures:
  - amd64
  - s390x
  - arm64v8
  Directory: 8/jdk/ubuntu/jammy
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-8u372-b07-jdk-jammy
  - open-8-jdk-jammy
- Architectures:
  - amd64
  - ppc64le
  - arm64v8
  Directory: 8/jdk/centos
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-8u372-b07-jdk-centos7
  - open-8-jdk-centos7
- Architectures:
  - amd64
  - ppc64le
  - s390x
  - arm64v8
  Directory: 8/jre/ubuntu/focal
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-8u372-b07-jre-focal
  - open-8-jre-focal
- Architectures:
  - amd64
  - s390x
  - arm64v8
  Directory: 8/jre/ubuntu/jammy
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-8u372-b07-jre-jammy
  - open-8-jre-jammy
- Architectures:
  - amd64
  - ppc64le
  - arm64v8
  Directory: 8/jre/centos
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-8u372-b07-jre-centos7
  - open-8-jre-centos7
- Architectures:
  - amd64
  - ppc64le
  - s390x
  - arm64v8
  Directory: 11/jdk/ubuntu/focal
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-11.0.19_7-jdk-focal
  - open-11-jdk-focal
- Architectures:
  - amd64
  - s390x
  - arm64v8
  Directory: 11/jdk/ubuntu/jammy
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-11.0.19_7-jdk-jammy
  - open-11-jdk-jammy
- Architectures:
  - amd64
  - ppc64le
  - arm64v8
  Directory: 11/jdk/centos
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-11.0.19_7-jdk-centos7
  - open-11-jdk-centos7
- Architectures:
  - amd64
  - ppc64le
  - s390x
  - arm64v8
  Directory: 11/jre/ubuntu/focal
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-11.0.19_7-jre-focal
  - open-11-jre-focal
- Architectures:
  - amd64
  - s390x
  - arm64v8
  Directory: 11/jre/ubuntu/jammy
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-11.0.19_7-jre-jammy
  - open-11-jre-jammy
- Architectures:
  - amd64
  - ppc64le
  - arm64v8
  Directory: 11/jre/centos
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-11.0.19_7-jre-centos7
  - open-11-jre-centos7
- Architectures:
  - amd64
  - ppc64le
  - s390x
  - arm64v8
  Directory: 17/jdk/ubuntu/focal
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-17.0.7_7-jdk-focal
  - open-17-jdk-focal
- Architectures:
  - amd64
  - s390x
  - arm64v8
  Directory: 17/jdk/ubuntu/jammy
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-17.0.7_7-jdk-jammy
  - open-17-jdk-jammy
- Architectures:
  - amd64
  - ppc64le
  - arm64v8
  Directory: 17/jdk/centos
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-17.0.7_7-jdk-centos7
  - open-17-jdk-centos7
- Architectures:
  - amd64
  - ppc64le
  - s390x
  - arm64v8
  Directory: 17/jre/ubuntu/focal
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-17.0.7_7-jre-focal
  - open-17-jre-focal
- Architectures:
  - amd64
  - s390x
  - arm64v8
  Directory: 17/jre/ubuntu/jammy
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-17.0.7_7-jre-jammy
  - open-17-jre-jammy
- Architectures:
  - amd64
  - ppc64le
  - arm64v8
  Directory: 17/jre/centos
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-17.0.7_7-jre-centos7
  - open-17-jre-centos7
- Architectures:
  - amd64
  - ppc64le
  - s390x
  - arm64v8
  Directory: 19/jdk/ubuntu/focal
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-19.0.2_7-jdk-focal
  - open-19-jdk-focal
- Architectures:
  - amd64
  - s390x
  - arm64v8
  Directory: 19/jdk/ubuntu/jammy
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-19.0.2_7-jdk-jammy
  - open-19-jdk-jammy
- Architectures:
  - amd64
  - ppc64le
  - arm64v8
  Directory: 19/jdk/centos
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-19.0.2_7-jdk-centos7
  - open-19-jdk-centos7
- Architectures:
  - amd64
  - ppc64le
  - s390x
  - arm64v8
  Directory: 19/jre/ubuntu/focal
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-19.0.2_7-jre-focal
  - open-19-jre-focal
- Architectures:
  - amd64
  - s390x
  - arm64v8
  Directory: 19/jre/ubuntu/jammy
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-19.0.2_7-jre-jammy
  - open-19-jre-jammy
- Architectures:
  - amd64
  - ppc64le
  - arm64v8
  Directory: 19/jre/centos
  GitCommit: 3779c8ee30b1d94d34470a170a9ba4e734626a33
  Tags:
  - open-19.0.2_7-jre-centos7
  - open-19-jre-centos7
GitRepo: https://github.com/ibmruntimes/semeru-containers.git
KnownTags:
  open-8-jdk-centos7: {}
  open-8-jdk-focal: {}
  open-8-jdk-jammy: {}
  open-8-jre-centos7: {}
  open-8-jre-focal: {}
  open-8-jre-jammy: {}
  open-8u372-b07-jdk-centos7: {}
  open-8u372-b07-jdk-focal: {}
  open-8u372-b07-jdk-jammy: {}
  open-8u372-b07-jre-centos7: {}
  open-8u372-b07-jre-focal: {}
  open-8u372-b07-jre-jammy: {}
  open-11-jdk-centos7: {}
  open-11-jdk-focal: {}
  open-11-jdk-jammy: {}
  open-11-jre-centos7: {}
  open-11-jre-focal: {}
  open-11-jre-jammy: {}
  open-11.0.19_7-jdk-centos7: {}
  open-11.0.19_7-jdk-focal: {}
  open-11.0.19_7-jdk-jammy: {}
  open-11.0.19_7-jre-centos7: {}
  open-11.0.19_7-jre-focal: {}
  open-11.0.19_7-jre-jammy: {}
  open-17-jdk-centos7: {}
  open-17-jdk-focal: {}
  open-17-jdk-jammy: {}
  open-17-jre-centos7: {}
  open-17-jre-focal: {}
  open-17-jre-jammy: {}
  open-17.0.7_7-jdk-centos7: {}
  open-17.0.7_7-jdk-focal: {}
  open-17.0.7_7-jdk-jammy: {}
  open-17.0.7_7-jre-centos7: {}
  open-17.0.7_7-jre-focal: {}
  open-17.0.7_7-jre-jammy: {}
  open-19-jdk-centos7: {}
  open-19-jdk-focal: {}
  open-19-jdk-jammy: {}
  open-19-jre-centos7: {}
  open-19-jre-focal: {}
  open-19-jre-jammy: {}
  open-19.0.2_7-jdk-centos7: {}
  open-19.0.2_7-jdk-focal: {}
  open-19.0.2_7-jdk-jammy: {}
  open-19.0.2_7-jre-centos7: {}
  open-19.0.2_7-jre-focal: {}
  open-19.0.2_7-jre-jammy: {}
Name: ibm-semeru-runtimes
