Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: eclipse-temurin-11
  GitCommit: 7e54809c453c0bdfaf856b3831f6b6050f5a12eb
  Tags:
  - 3.9.2-eclipse-temurin-11
  - 3.9-eclipse-temurin-11
  - 3-eclipse-temurin-11
- Architectures:
  - amd64
  Directory: eclipse-temurin-11-alpine
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-eclipse-temurin-11-alpine
  - 3.9-eclipse-temurin-11-alpine
  - 3-eclipse-temurin-11-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: eclipse-temurin-11-focal
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-eclipse-temurin-11-focal
  - 3.9-eclipse-temurin-11-focal
  - 3-eclipse-temurin-11-focal
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: eclipse-temurin-17
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-eclipse-temurin-17
  - 3.9-eclipse-temurin-17
  - 3-eclipse-temurin-17
- Architectures:
  - amd64
  Directory: eclipse-temurin-17-alpine
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-eclipse-temurin-17-alpine
  - 3.9-eclipse-temurin-17-alpine
  - 3-eclipse-temurin-17-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: eclipse-temurin-17-focal
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-eclipse-temurin-17-focal
  - 3.9-eclipse-temurin-17-focal
  - 3-eclipse-temurin-17-focal
- Architectures:
  - amd64
  - arm64v8
  Directory: eclipse-temurin-20
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-eclipse-temurin-20
  - 3.9.2
  - 3.9.2-eclipse-temurin
  - 3.9-eclipse-temurin-20
  - "3.9"
  - 3.9-eclipse-temurin
  - 3-eclipse-temurin-20
  - "3"
  - latest
  - 3-eclipse-temurin
  - eclipse-temurin
- Architectures:
  - amd64
  Directory: eclipse-temurin-20-alpine
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-eclipse-temurin-20-alpine
  - 3.9-eclipse-temurin-20-alpine
  - 3-eclipse-temurin-20-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  Directory: eclipse-temurin-8
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-eclipse-temurin-8
  - 3.9-eclipse-temurin-8
  - 3-eclipse-temurin-8
- Architectures:
  - amd64
  Directory: eclipse-temurin-8-alpine
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-eclipse-temurin-8-alpine
  - 3.9-eclipse-temurin-8-alpine
  - 3-eclipse-temurin-8-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  Directory: eclipse-temurin-8-focal
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-eclipse-temurin-8-focal
  - 3.9-eclipse-temurin-8-focal
  - 3-eclipse-temurin-8-focal
- Architectures:
  - amd64
  - ppc64le
  - s390x
  Directory: ibmjava-8
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-ibmjava-8
  - 3.9.2-ibmjava
  - 3.9-ibmjava-8
  - 3.9-ibmjava
  - 3-ibmjava-8
  - 3-ibmjava
  - ibmjava
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ibm-semeru-11-focal
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-ibm-semeru-11-focal
  - 3.9-ibm-semeru-11-focal
  - 3-ibm-semeru-11-focal
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ibm-semeru-17-focal
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-ibm-semeru-17-focal
  - 3.9-ibm-semeru-17-focal
  - 3-ibm-semeru-17-focal
- Architectures:
  - amd64
  - arm64v8
  Directory: amazoncorretto-11
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-amazoncorretto-11
  - 3.9.2-amazoncorretto
  - 3.9-amazoncorretto-11
  - 3.9-amazoncorretto
  - 3-amazoncorretto-11
  - 3-amazoncorretto
  - amazoncorretto
- Architectures:
  - amd64
  - arm64v8
  Directory: amazoncorretto-11-debian
  GitCommit: 01cb02d874b08d33960e71ab4b65b0f14bbc7b88
  Tags:
  - 3.9.2-amazoncorretto-11-debian
  - 3.9.2-amazoncorretto-11-debian-bookworm
  - 3.9-amazoncorretto-11-debian
  - 3.9-amazoncorretto-11-debian-bookworm
  - 3-amazoncorretto-11-debian
  - 3-amazoncorretto-11-debian-bookworm
- Architectures:
  - amd64
  - arm64v8
  Directory: amazoncorretto-17
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-amazoncorretto-17
  - 3.9-amazoncorretto-17
  - 3-amazoncorretto-17
- Architectures:
  - amd64
  - arm64v8
  Directory: amazoncorretto-17-debian
  GitCommit: 01cb02d874b08d33960e71ab4b65b0f14bbc7b88
  Tags:
  - 3.9.2-amazoncorretto-17-debian
  - 3.9.2-amazoncorretto-17-debian-bookworm
  - 3.9-amazoncorretto-17-debian
  - 3.9-amazoncorretto-17-debian-bookworm
  - 3-amazoncorretto-17-debian
  - 3-amazoncorretto-17-debian-bookworm
- Architectures:
  - amd64
  - arm64v8
  Directory: amazoncorretto-20
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-amazoncorretto-20
  - 3.9-amazoncorretto-20
  - 3-amazoncorretto-20
- Architectures:
  - amd64
  - arm64v8
  Directory: amazoncorretto-20-debian
  GitCommit: 01cb02d874b08d33960e71ab4b65b0f14bbc7b88
  Tags:
  - 3.9.2-amazoncorretto-20-debian
  - 3.9.2-amazoncorretto-20-debian-bookworm
  - 3.9-amazoncorretto-20-debian
  - 3.9-amazoncorretto-20-debian-bookworm
  - 3-amazoncorretto-20-debian
  - 3-amazoncorretto-20-debian-bookworm
- Architectures:
  - amd64
  - arm64v8
  Directory: amazoncorretto-8
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-amazoncorretto-8
  - 3.9-amazoncorretto-8
  - 3-amazoncorretto-8
- Architectures:
  - amd64
  - arm64v8
  Directory: amazoncorretto-8-debian
  GitCommit: 01cb02d874b08d33960e71ab4b65b0f14bbc7b88
  Tags:
  - 3.9.2-amazoncorretto-8-debian
  - 3.9.2-amazoncorretto-8-debian-bookworm
  - 3.9-amazoncorretto-8-debian
  - 3.9-amazoncorretto-8-debian-bookworm
  - 3-amazoncorretto-8-debian
  - 3-amazoncorretto-8-debian-bookworm
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: sapmachine-11
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-sapmachine-11
  - 3.9-sapmachine-11
  - 3-sapmachine-11
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: sapmachine-17
  GitCommit: 5f8a86d716eb63fb5a1ef03e5cb743f5df4ffa0a
  Tags:
  - 3.9.2-sapmachine-17
  - 3.9.2-sapmachine
  - 3.9-sapmachine-17
  - 3.9-sapmachine
  - 3-sapmachine-17
  - 3-sapmachine
  - sapmachine
GitRepo: https://github.com/carlossg/docker-maven.git
KnownTags:
  "3": {}
  3-amazoncorretto: {}
  3-amazoncorretto-8: {}
  3-amazoncorretto-8-debian: {}
  3-amazoncorretto-8-debian-bookworm: {}
  3-amazoncorretto-11: {}
  3-amazoncorretto-11-debian: {}
  3-amazoncorretto-11-debian-bookworm: {}
  3-amazoncorretto-17: {}
  3-amazoncorretto-17-debian: {}
  3-amazoncorretto-17-debian-bookworm: {}
  3-amazoncorretto-20: {}
  3-amazoncorretto-20-debian: {}
  3-amazoncorretto-20-debian-bookworm: {}
  3-eclipse-temurin: {}
  3-eclipse-temurin-8: {}
  3-eclipse-temurin-8-alpine: {}
  3-eclipse-temurin-8-focal: {}
  3-eclipse-temurin-11: {}
  3-eclipse-temurin-11-alpine: {}
  3-eclipse-temurin-11-focal: {}
  3-eclipse-temurin-17: {}
  3-eclipse-temurin-17-alpine: {}
  3-eclipse-temurin-17-focal: {}
  3-eclipse-temurin-20: {}
  3-eclipse-temurin-20-alpine: {}
  3-ibm-semeru-11-focal: {}
  3-ibm-semeru-17-focal: {}
  3-ibmjava: {}
  3-ibmjava-8: {}
  3-sapmachine: {}
  3-sapmachine-11: {}
  3-sapmachine-17: {}
  "3.9": {}
  3.9-amazoncorretto: {}
  3.9-amazoncorretto-8: {}
  3.9-amazoncorretto-8-debian: {}
  3.9-amazoncorretto-8-debian-bookworm: {}
  3.9-amazoncorretto-11: {}
  3.9-amazoncorretto-11-debian: {}
  3.9-amazoncorretto-11-debian-bookworm: {}
  3.9-amazoncorretto-17: {}
  3.9-amazoncorretto-17-debian: {}
  3.9-amazoncorretto-17-debian-bookworm: {}
  3.9-amazoncorretto-20: {}
  3.9-amazoncorretto-20-debian: {}
  3.9-amazoncorretto-20-debian-bookworm: {}
  3.9-eclipse-temurin: {}
  3.9-eclipse-temurin-8: {}
  3.9-eclipse-temurin-8-alpine: {}
  3.9-eclipse-temurin-8-focal: {}
  3.9-eclipse-temurin-11: {}
  3.9-eclipse-temurin-11-alpine: {}
  3.9-eclipse-temurin-11-focal: {}
  3.9-eclipse-temurin-17: {}
  3.9-eclipse-temurin-17-alpine: {}
  3.9-eclipse-temurin-17-focal: {}
  3.9-eclipse-temurin-20: {}
  3.9-eclipse-temurin-20-alpine: {}
  3.9-ibm-semeru-11-focal: {}
  3.9-ibm-semeru-17-focal: {}
  3.9-ibmjava: {}
  3.9-ibmjava-8: {}
  3.9-sapmachine: {}
  3.9-sapmachine-11: {}
  3.9-sapmachine-17: {}
  3.9.2: {}
  3.9.2-amazoncorretto: {}
  3.9.2-amazoncorretto-8: {}
  3.9.2-amazoncorretto-8-debian: {}
  3.9.2-amazoncorretto-8-debian-bookworm: {}
  3.9.2-amazoncorretto-11: {}
  3.9.2-amazoncorretto-11-debian: {}
  3.9.2-amazoncorretto-11-debian-bookworm: {}
  3.9.2-amazoncorretto-17: {}
  3.9.2-amazoncorretto-17-debian: {}
  3.9.2-amazoncorretto-17-debian-bookworm: {}
  3.9.2-amazoncorretto-20: {}
  3.9.2-amazoncorretto-20-debian: {}
  3.9.2-amazoncorretto-20-debian-bookworm: {}
  3.9.2-eclipse-temurin: {}
  3.9.2-eclipse-temurin-8: {}
  3.9.2-eclipse-temurin-8-alpine: {}
  3.9.2-eclipse-temurin-8-focal: {}
  3.9.2-eclipse-temurin-11: {}
  3.9.2-eclipse-temurin-11-alpine: {}
  3.9.2-eclipse-temurin-11-focal: {}
  3.9.2-eclipse-temurin-17: {}
  3.9.2-eclipse-temurin-17-alpine: {}
  3.9.2-eclipse-temurin-17-focal: {}
  3.9.2-eclipse-temurin-20: {}
  3.9.2-eclipse-temurin-20-alpine: {}
  3.9.2-ibm-semeru-11-focal: {}
  3.9.2-ibm-semeru-17-focal: {}
  3.9.2-ibmjava: {}
  3.9.2-ibmjava-8: {}
  3.9.2-sapmachine: {}
  3.9.2-sapmachine-11: {}
  3.9.2-sapmachine-17: {}
  amazoncorretto: {}
  eclipse-temurin: {}
  ibmjava: {}
  latest: {}
  sapmachine: {}
Name: maven
