Blocks:
- Architectures: null
  Directory: ""
  GitCommit: a2a08d733833327354b5d3336ffbd19e4f369a2d
  Tags:
  - 1.2.9
  - latest
- Architectures: null
  Directory: ""
  GitCommit: 741c78fb0287dc0850f5f131e099610a7acc2bf9
  Tags:
  - 1.2.8
- Architectures: null
  Directory: ""
  GitCommit: b28650fbd0f447b821505d2ec18667fbbde8a108
  Tags:
  - 1.2.8-rc1
- Architectures: null
  Directory: ""
  GitCommit: b741365fdf375bb7409314b4a161a91290935d3f
  Tags:
  - 1.2.7
- Architectures: null
  Directory: ""
  GitCommit: 3725bf97c64a9425fc609d32df907170657a6b84
  Tags:
  - 1.2.6
- Architectures: null
  Directory: ""
  GitCommit: e8268874ec7b6af365cf6a90e02ad3af89c82830
  Tags:
  - 1.2.6-rc2
- Architectures: null
  Directory: ""
  GitCommit: 67e6cf4171fcabd2e3b8b809105e7dfb15114ce1
  Tags:
  - 1.2.5
- Architectures: null
  Directory: ""
  GitCommit: e33419371f34db2ebbe9a67271de30620e01e88e
  Tags:
  - 1.2.6-rc1
GitRepo: https://github.com/docker-archive/swarm-library-image.git
KnownTags:
  1.2.5: {}
  1.2.6: {}
  1.2.6-rc1: {}
  1.2.6-rc2: {}
  1.2.7: {}
  1.2.8: {}
  1.2.8-rc1: {}
  1.2.9: {}
  latest: {}
Name: swarm
