Blocks:
- Architectures:
  - amd64
  Directory: alpine/3.9.11
  GitCommit: 2f0e4d0d5f501633e6254812320283bf0c710757
  Tags:
  - "3.9"
  - 3.9.11
- Architectures:
  - amd64
  - arm64v8
  Directory: alpine/3.10.7
  GitCommit: 5c926a243d7c952a58f97488781f5eaf6d6704b9
  Tags:
  - "3.10"
  - 3.10.7
- Architectures:
  - amd64
  - arm64v8
  Directory: alpine/3.11.1
  GitCommit: 5c926a243d7c952a58f97488781f5eaf6d6704b9
  Tags:
  - "3.11"
  - 3.11.1
  - latest
GitRepo: https://github.com/arangodb/arangodb-docker
KnownTags:
  "3.9": {}
  3.9.11: {}
  "3.10": {}
  3.10.7: {}
  "3.11": {}
  3.11.1: {}
  latest: {}
Name: arangodb
