Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 5.036.001-main-bullseye
  GitCommit: ""
  Tags:
  - 5.36.1
  - "5.36"
  - "5"
  - latest
  - stable
  - 5.36.1-bullseye
  - 5.36-bullseye
  - 5-bullseye
  - bullseye
  - stable-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 5.036.001-main-buster
  GitCommit: ""
  Tags:
  - 5.36.1-buster
  - 5.36-buster
  - 5-buster
  - buster
  - stable-buster
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 5.036.001-slim-bullseye
  GitCommit: ""
  Tags:
  - 5.36.1-slim
  - 5.36-slim
  - 5-slim
  - slim
  - stable-slim
  - 5.36.1-slim-bullseye
  - 5.36-slim-bullseye
  - 5-slim-bullseye
  - slim-bullseye
  - stable-slim-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 5.036.001-slim-buster
  GitCommit: ""
  Tags:
  - 5.36.1-slim-buster
  - 5.36-slim-buster
  - 5-slim-buster
  - slim-buster
  - stable-slim-buster
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 5.036.001-main
  GitCommit: ""
  Tags:
  - 5.36.1-threaded
  - 5.36-threaded
  - 5-threaded
  - threaded
  - stable-threaded
  - 5.36.1-threaded-bullseye
  - 5.36-threaded-bullseye
  - 5-threaded-bullseye
  - threaded-bullseye
  - stable-threaded-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 5.036.001-main
  GitCommit: ""
  Tags:
  - 5.36.1-threaded-buster
  - 5.36-threaded-buster
  - 5-threaded-buster
  - threaded-buster
  - stable-threaded-buster
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 5.036.001-slim
  GitCommit: ""
  Tags:
  - 5.36.1-slim-threaded
  - 5.36-slim-threaded
  - 5-slim-threaded
  - slim-threaded
  - stable-slim-threaded
  - 5.36.1-slim-threaded-bullseye
  - 5.36-slim-threaded-bullseye
  - 5-slim-threaded-bullseye
  - slim-threaded-bullseye
  - stable-slim-threaded-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 5.036.001-slim
  GitCommit: ""
  Tags:
  - 5.36.1-slim-threaded-buster
  - 5.36-slim-threaded-buster
  - 5-slim-threaded-buster
  - slim-threaded-buster
  - stable-slim-threaded-buster
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 5.034.001-main-bullseye
  GitCommit: ""
  Tags:
  - 5.34.1
  - "5.34"
  - 5.34.1-bullseye
  - 5.34-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 5.034.001-main-buster
  GitCommit: ""
  Tags:
  - 5.34.1-buster
  - 5.34-buster
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 5.034.001-slim-bullseye
  GitCommit: ""
  Tags:
  - 5.34.1-slim
  - 5.34-slim
  - 5.34.1-slim-bullseye
  - 5.34-slim-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 5.034.001-slim-buster
  GitCommit: ""
  Tags:
  - 5.34.1-slim-buster
  - 5.34-slim-buster
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 5.034.001-main
  GitCommit: ""
  Tags:
  - 5.34.1-threaded
  - 5.34-threaded
  - 5.34.1-threaded-bullseye
  - 5.34-threaded-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 5.034.001-main
  GitCommit: ""
  Tags:
  - 5.34.1-threaded-buster
  - 5.34-threaded-buster
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 5.034.001-slim
  GitCommit: ""
  Tags:
  - 5.34.1-slim-threaded
  - 5.34-slim-threaded
  - 5.34.1-slim-threaded-bullseye
  - 5.34-slim-threaded-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 5.034.001-slim
  GitCommit: ""
  Tags:
  - 5.34.1-slim-threaded-buster
  - 5.34-slim-threaded-buster
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 5.032.001-main-bullseye
  GitCommit: ""
  Tags:
  - 5.32.1
  - "5.32"
  - 5.32.1-bullseye
  - 5.32-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 5.032.001-main-buster
  GitCommit: ""
  Tags:
  - 5.32.1-buster
  - 5.32-buster
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 5.032.001-slim-bullseye
  GitCommit: ""
  Tags:
  - 5.32.1-slim
  - 5.32-slim
  - 5.32.1-slim-bullseye
  - 5.32-slim-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 5.032.001-slim-buster
  GitCommit: ""
  Tags:
  - 5.32.1-slim-buster
  - 5.32-slim-buster
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 5.032.001-main
  GitCommit: ""
  Tags:
  - 5.32.1-threaded
  - 5.32-threaded
  - 5.32.1-threaded-bullseye
  - 5.32-threaded-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 5.032.001-main
  GitCommit: ""
  Tags:
  - 5.32.1-threaded-buster
  - 5.32-threaded-buster
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 5.032.001-slim
  GitCommit: ""
  Tags:
  - 5.32.1-slim-threaded
  - 5.32-slim-threaded
  - 5.32.1-slim-threaded-bullseye
  - 5.32-slim-threaded-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 5.032.001-slim
  GitCommit: ""
  Tags:
  - 5.32.1-slim-threaded-buster
  - 5.32-slim-threaded-buster
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 5.037.011-main-bullseye
  GitCommit: ""
  Tags:
  - 5.37.11
  - "5.37"
  - devel
  - 5.37.11-bullseye
  - 5.37-bullseye
  - devel-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 5.037.011-main-buster
  GitCommit: ""
  Tags:
  - 5.37.11-buster
  - 5.37-buster
  - devel-buster
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 5.037.011-slim-bullseye
  GitCommit: ""
  Tags:
  - 5.37.11-slim
  - 5.37-slim
  - devel-slim
  - 5.37.11-slim-bullseye
  - 5.37-slim-bullseye
  - devel-slim-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 5.037.011-slim-buster
  GitCommit: ""
  Tags:
  - 5.37.11-slim-buster
  - 5.37-slim-buster
  - devel-slim-buster
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 5.037.011-main
  GitCommit: ""
  Tags:
  - 5.37.11-threaded
  - 5.37-threaded
  - devel-threaded
  - 5.37.11-threaded-bullseye
  - 5.37-threaded-bullseye
  - devel-threaded-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 5.037.011-main
  GitCommit: ""
  Tags:
  - 5.37.11-threaded-buster
  - 5.37-threaded-buster
  - devel-threaded-buster
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 5.037.011-slim
  GitCommit: ""
  Tags:
  - 5.37.11-slim-threaded
  - 5.37-slim-threaded
  - devel-slim-threaded
  - 5.37.11-slim-threaded-bullseye
  - 5.37-slim-threaded-bullseye
  - devel-slim-threaded-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 5.037.011-slim
  GitCommit: ""
  Tags:
  - 5.37.11-slim-threaded-buster
  - 5.37-slim-threaded-buster
  - devel-slim-threaded-buster
GitRepo: https://github.com/perl/docker-perl.git
KnownTags:
  "5": {}
  5-bullseye: {}
  5-buster: {}
  5-slim: {}
  5-slim-bullseye: {}
  5-slim-buster: {}
  5-slim-threaded: {}
  5-slim-threaded-bullseye: {}
  5-slim-threaded-buster: {}
  5-threaded: {}
  5-threaded-bullseye: {}
  5-threaded-buster: {}
  "5.32": {}
  5.32-bullseye: {}
  5.32-buster: {}
  5.32-slim: {}
  5.32-slim-bullseye: {}
  5.32-slim-buster: {}
  5.32-slim-threaded: {}
  5.32-slim-threaded-bullseye: {}
  5.32-slim-threaded-buster: {}
  5.32-threaded: {}
  5.32-threaded-bullseye: {}
  5.32-threaded-buster: {}
  5.32.1: {}
  5.32.1-bullseye: {}
  5.32.1-buster: {}
  5.32.1-slim: {}
  5.32.1-slim-bullseye: {}
  5.32.1-slim-buster: {}
  5.32.1-slim-threaded: {}
  5.32.1-slim-threaded-bullseye: {}
  5.32.1-slim-threaded-buster: {}
  5.32.1-threaded: {}
  5.32.1-threaded-bullseye: {}
  5.32.1-threaded-buster: {}
  "5.34": {}
  5.34-bullseye: {}
  5.34-buster: {}
  5.34-slim: {}
  5.34-slim-bullseye: {}
  5.34-slim-buster: {}
  5.34-slim-threaded: {}
  5.34-slim-threaded-bullseye: {}
  5.34-slim-threaded-buster: {}
  5.34-threaded: {}
  5.34-threaded-bullseye: {}
  5.34-threaded-buster: {}
  5.34.1: {}
  5.34.1-bullseye: {}
  5.34.1-buster: {}
  5.34.1-slim: {}
  5.34.1-slim-bullseye: {}
  5.34.1-slim-buster: {}
  5.34.1-slim-threaded: {}
  5.34.1-slim-threaded-bullseye: {}
  5.34.1-slim-threaded-buster: {}
  5.34.1-threaded: {}
  5.34.1-threaded-bullseye: {}
  5.34.1-threaded-buster: {}
  "5.36": {}
  5.36-bullseye: {}
  5.36-buster: {}
  5.36-slim: {}
  5.36-slim-bullseye: {}
  5.36-slim-buster: {}
  5.36-slim-threaded: {}
  5.36-slim-threaded-bullseye: {}
  5.36-slim-threaded-buster: {}
  5.36-threaded: {}
  5.36-threaded-bullseye: {}
  5.36-threaded-buster: {}
  5.36.1: {}
  5.36.1-bullseye: {}
  5.36.1-buster: {}
  5.36.1-slim: {}
  5.36.1-slim-bullseye: {}
  5.36.1-slim-buster: {}
  5.36.1-slim-threaded: {}
  5.36.1-slim-threaded-bullseye: {}
  5.36.1-slim-threaded-buster: {}
  5.36.1-threaded: {}
  5.36.1-threaded-bullseye: {}
  5.36.1-threaded-buster: {}
  "5.37": {}
  5.37-bullseye: {}
  5.37-buster: {}
  5.37-slim: {}
  5.37-slim-bullseye: {}
  5.37-slim-buster: {}
  5.37-slim-threaded: {}
  5.37-slim-threaded-bullseye: {}
  5.37-slim-threaded-buster: {}
  5.37-threaded: {}
  5.37-threaded-bullseye: {}
  5.37-threaded-buster: {}
  5.37.11: {}
  5.37.11-bullseye: {}
  5.37.11-buster: {}
  5.37.11-slim: {}
  5.37.11-slim-bullseye: {}
  5.37.11-slim-buster: {}
  5.37.11-slim-threaded: {}
  5.37.11-slim-threaded-bullseye: {}
  5.37.11-slim-threaded-buster: {}
  5.37.11-threaded: {}
  5.37.11-threaded-bullseye: {}
  5.37.11-threaded-buster: {}
  bullseye: {}
  buster: {}
  devel: {}
  devel-bullseye: {}
  devel-buster: {}
  devel-slim: {}
  devel-slim-bullseye: {}
  devel-slim-buster: {}
  devel-slim-threaded: {}
  devel-slim-threaded-bullseye: {}
  devel-slim-threaded-buster: {}
  devel-threaded: {}
  devel-threaded-bullseye: {}
  devel-threaded-buster: {}
  latest: {}
  slim: {}
  slim-bullseye: {}
  slim-buster: {}
  slim-threaded: {}
  slim-threaded-bullseye: {}
  slim-threaded-buster: {}
  stable: {}
  stable-bullseye: {}
  stable-buster: {}
  stable-slim: {}
  stable-slim-bullseye: {}
  stable-slim-buster: {}
  stable-slim-threaded: {}
  stable-slim-threaded-bullseye: {}
  stable-slim-threaded-buster: {}
  stable-threaded: {}
  stable-threaded-bullseye: {}
  stable-threaded-buster: {}
  threaded: {}
  threaded-bullseye: {}
  threaded-buster: {}
Name: perl
