Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.0/scala2.12-java11-python3-ubuntu
  GitCommit: 028efd4637fb2cf791d5bd9ea70b2fca472de4b7
  Tags:
  - 3.5.0-scala2.12-java11-python3-ubuntu
  - 3.5.0-python3
  - 3.5.0
  - python3
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.0/scala2.12-java11-r-ubuntu
  GitCommit: 028efd4637fb2cf791d5bd9ea70b2fca472de4b7
  Tags:
  - 3.5.0-scala2.12-java11-r-ubuntu
  - 3.5.0-r
  - r
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.0/scala2.12-java11-ubuntu
  GitCommit: 028efd4637fb2cf791d5bd9ea70b2fca472de4b7
  Tags:
  - 3.5.0-scala2.12-java11-ubuntu
  - 3.5.0-scala
  - scala
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.0/scala2.12-java11-python3-r-ubuntu
  GitCommit: 028efd4637fb2cf791d5bd9ea70b2fca472de4b7
  Tags:
  - 3.5.0-scala2.12-java11-python3-r-ubuntu
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.1/scala2.12-java11-python3-ubuntu
  GitCommit: 58d288546e8419d229f14b62b6a653999e0390f1
  Tags:
  - 3.4.1-scala2.12-java11-python3-ubuntu
  - 3.4.1-python3
  - 3.4.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.1/scala2.12-java11-r-ubuntu
  GitCommit: 58d288546e8419d229f14b62b6a653999e0390f1
  Tags:
  - 3.4.1-scala2.12-java11-r-ubuntu
  - 3.4.1-r
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.1/scala2.12-java11-ubuntu
  GitCommit: 58d288546e8419d229f14b62b6a653999e0390f1
  Tags:
  - 3.4.1-scala2.12-java11-ubuntu
  - 3.4.1-scala
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.1/scala2.12-java11-python3-r-ubuntu
  GitCommit: 58d288546e8419d229f14b62b6a653999e0390f1
  Tags:
  - 3.4.1-scala2.12-java11-python3-r-ubuntu
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.0/scala2.12-java11-python3-ubuntu
  GitCommit: 7f9b414de48639d69c64acfd81e6792517b86f61
  Tags:
  - 3.4.0-scala2.12-java11-python3-ubuntu
  - 3.4.0-python3
  - 3.4.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.0/scala2.12-java11-r-ubuntu
  GitCommit: 7f9b414de48639d69c64acfd81e6792517b86f61
  Tags:
  - 3.4.0-scala2.12-java11-r-ubuntu
  - 3.4.0-r
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.0/scala2.12-java11-ubuntu
  GitCommit: 7f9b414de48639d69c64acfd81e6792517b86f61
  Tags:
  - 3.4.0-scala2.12-java11-ubuntu
  - 3.4.0-scala
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.0/scala2.12-java11-python3-r-ubuntu
  GitCommit: 7f9b414de48639d69c64acfd81e6792517b86f61
  Tags:
  - 3.4.0-scala2.12-java11-python3-r-ubuntu
GitRepo: https://github.com/apache/spark-docker.git
KnownTags:
  3.4.0: {}
  3.4.0-python3: {}
  3.4.0-r: {}
  3.4.0-scala: {}
  3.4.0-scala2.12-java11-python3-r-ubuntu: {}
  3.4.0-scala2.12-java11-python3-ubuntu: {}
  3.4.0-scala2.12-java11-r-ubuntu: {}
  3.4.0-scala2.12-java11-ubuntu: {}
  3.4.1: {}
  3.4.1-python3: {}
  3.4.1-r: {}
  3.4.1-scala: {}
  3.4.1-scala2.12-java11-python3-r-ubuntu: {}
  3.4.1-scala2.12-java11-python3-ubuntu: {}
  3.4.1-scala2.12-java11-r-ubuntu: {}
  3.4.1-scala2.12-java11-ubuntu: {}
  3.5.0: {}
  3.5.0-python3: {}
  3.5.0-r: {}
  3.5.0-scala: {}
  3.5.0-scala2.12-java11-python3-r-ubuntu: {}
  3.5.0-scala2.12-java11-python3-ubuntu: {}
  3.5.0-scala2.12-java11-r-ubuntu: {}
  3.5.0-scala2.12-java11-ubuntu: {}
  latest: {}
  python3: {}
  r: {}
  scala: {}
Name: spark
