Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./4.0.0-preview1/scala2.13-java17-python3-ubuntu
  File: ""
  GitCommit: b9f1f8e8ebed1959c2be3864a114b52f67519092
  Tags:
  - 4.0.0-preview1-scala2.13-java17-python3-ubuntu
  - 4.0.0-preview1-python3
  - 4.0.0-preview1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./4.0.0-preview1/scala2.13-java17-r-ubuntu
  File: ""
  GitCommit: b9f1f8e8ebed1959c2be3864a114b52f67519092
  Tags:
  - 4.0.0-preview1-scala2.13-java17-r-ubuntu
  - 4.0.0-preview1-r
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./4.0.0-preview1/scala2.13-java17-ubuntu
  File: ""
  GitCommit: b9f1f8e8ebed1959c2be3864a114b52f67519092
  Tags:
  - 4.0.0-preview1-scala2.13-java17-ubuntu
  - 4.0.0-preview1-scala
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./4.0.0-preview1/scala2.13-java17-python3-r-ubuntu
  File: ""
  GitCommit: b9f1f8e8ebed1959c2be3864a114b52f67519092
  Tags:
  - 4.0.0-preview1-scala2.13-java17-python3-r-ubuntu
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.2/scala2.12-java17-python3-ubuntu
  File: ""
  GitCommit: b9f1f8e8ebed1959c2be3864a114b52f67519092
  Tags:
  - 3.5.2-scala2.12-java17-python3-ubuntu
  - 3.5.2-java17-python3
  - 3.5.2-java17
  - python3-java17
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.2/scala2.12-java17-r-ubuntu
  File: ""
  GitCommit: b9f1f8e8ebed1959c2be3864a114b52f67519092
  Tags:
  - 3.5.2-scala2.12-java17-r-ubuntu
  - 3.5.2-java17-r
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.2/scala2.12-java17-ubuntu
  File: ""
  GitCommit: b9f1f8e8ebed1959c2be3864a114b52f67519092
  Tags:
  - 3.5.2-scala2.12-java17-ubuntu
  - 3.5.2-java17-scala
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.2/scala2.12-java17-python3-r-ubuntu
  File: ""
  GitCommit: b9f1f8e8ebed1959c2be3864a114b52f67519092
  Tags:
  - 3.5.2-scala2.12-java17-python3-r-ubuntu
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.2/scala2.12-java11-python3-ubuntu
  File: ""
  GitCommit: b9f1f8e8ebed1959c2be3864a114b52f67519092
  Tags:
  - 3.5.2-scala2.12-java11-python3-ubuntu
  - 3.5.2-python3
  - 3.5.2
  - python3
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.2/scala2.12-java11-r-ubuntu
  File: ""
  GitCommit: b9f1f8e8ebed1959c2be3864a114b52f67519092
  Tags:
  - 3.5.2-scala2.12-java11-r-ubuntu
  - 3.5.2-r
  - r
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.2/scala2.12-java11-ubuntu
  File: ""
  GitCommit: b9f1f8e8ebed1959c2be3864a114b52f67519092
  Tags:
  - 3.5.2-scala2.12-java11-ubuntu
  - 3.5.2-scala
  - scala
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.2/scala2.12-java11-python3-r-ubuntu
  File: ""
  GitCommit: b9f1f8e8ebed1959c2be3864a114b52f67519092
  Tags:
  - 3.5.2-scala2.12-java11-python3-r-ubuntu
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.2/scala2.12-java11-python3-ubuntu
  File: ""
  GitCommit: b9f1f8e8ebed1959c2be3864a114b52f67519092
  Tags:
  - 3.4.2-scala2.12-java11-python3-ubuntu
  - 3.4.2-python3
  - 3.4.2
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.2/scala2.12-java11-r-ubuntu
  File: ""
  GitCommit: b9f1f8e8ebed1959c2be3864a114b52f67519092
  Tags:
  - 3.4.2-scala2.12-java11-r-ubuntu
  - 3.4.2-r
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.2/scala2.12-java11-ubuntu
  File: ""
  GitCommit: b9f1f8e8ebed1959c2be3864a114b52f67519092
  Tags:
  - 3.4.2-scala2.12-java11-ubuntu
  - 3.4.2-scala
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.2/scala2.12-java11-python3-r-ubuntu
  File: ""
  GitCommit: b9f1f8e8ebed1959c2be3864a114b52f67519092
  Tags:
  - 3.4.2-scala2.12-java11-python3-r-ubuntu
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.1/scala2.12-java11-python3-ubuntu
  File: ""
  GitCommit: 58d288546e8419d229f14b62b6a653999e0390f1
  Tags:
  - 3.4.1-scala2.12-java11-python3-ubuntu
  - 3.4.1-python3
  - 3.4.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.1/scala2.12-java11-r-ubuntu
  File: ""
  GitCommit: 58d288546e8419d229f14b62b6a653999e0390f1
  Tags:
  - 3.4.1-scala2.12-java11-r-ubuntu
  - 3.4.1-r
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.1/scala2.12-java11-ubuntu
  File: ""
  GitCommit: 58d288546e8419d229f14b62b6a653999e0390f1
  Tags:
  - 3.4.1-scala2.12-java11-ubuntu
  - 3.4.1-scala
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.1/scala2.12-java11-python3-r-ubuntu
  File: ""
  GitCommit: 58d288546e8419d229f14b62b6a653999e0390f1
  Tags:
  - 3.4.1-scala2.12-java11-python3-r-ubuntu
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.1/scala2.12-java17-python3-ubuntu
  File: ""
  GitCommit: 4f2d96a415c89cfe0fde89a55e9034d095224c94
  Tags:
  - 3.5.1-scala2.12-java17-python3-ubuntu
  - 3.5.1-java17-python3
  - 3.5.1-java17
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.1/scala2.12-java17-r-ubuntu
  File: ""
  GitCommit: 4f2d96a415c89cfe0fde89a55e9034d095224c94
  Tags:
  - 3.5.1-scala2.12-java17-r-ubuntu
  - 3.5.1-java17-r
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.1/scala2.12-java17-ubuntu
  File: ""
  GitCommit: 4f2d96a415c89cfe0fde89a55e9034d095224c94
  Tags:
  - 3.5.1-scala2.12-java17-ubuntu
  - 3.5.1-java17-scala
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.1/scala2.12-java17-python3-r-ubuntu
  File: ""
  GitCommit: 4f2d96a415c89cfe0fde89a55e9034d095224c94
  Tags:
  - 3.5.1-scala2.12-java17-python3-r-ubuntu
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.1/scala2.12-java11-python3-ubuntu
  File: ""
  GitCommit: 4f2d96a415c89cfe0fde89a55e9034d095224c94
  Tags:
  - 3.5.1-scala2.12-java11-python3-ubuntu
  - 3.5.1-python3
  - 3.5.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.1/scala2.12-java11-r-ubuntu
  File: ""
  GitCommit: 4f2d96a415c89cfe0fde89a55e9034d095224c94
  Tags:
  - 3.5.1-scala2.12-java11-r-ubuntu
  - 3.5.1-r
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.1/scala2.12-java11-ubuntu
  File: ""
  GitCommit: 4f2d96a415c89cfe0fde89a55e9034d095224c94
  Tags:
  - 3.5.1-scala2.12-java11-ubuntu
  - 3.5.1-scala
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.1/scala2.12-java11-python3-r-ubuntu
  File: ""
  GitCommit: 4f2d96a415c89cfe0fde89a55e9034d095224c94
  Tags:
  - 3.5.1-scala2.12-java11-python3-r-ubuntu
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.0/scala2.12-java17-python3-ubuntu
  File: ""
  GitCommit: 6f68fe0f7051c10f2bf43a50a7decfce2e97baf0
  Tags:
  - 3.5.0-scala2.12-java17-python3-ubuntu
  - 3.5.0-java17-python3
  - 3.5.0-java17
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.0/scala2.12-java17-r-ubuntu
  File: ""
  GitCommit: 6f68fe0f7051c10f2bf43a50a7decfce2e97baf0
  Tags:
  - 3.5.0-scala2.12-java17-r-ubuntu
  - 3.5.0-java17-r
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.0/scala2.12-java17-ubuntu
  File: ""
  GitCommit: 6f68fe0f7051c10f2bf43a50a7decfce2e97baf0
  Tags:
  - 3.5.0-scala2.12-java17-ubuntu
  - 3.5.0-java17-scala
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.0/scala2.12-java17-python3-r-ubuntu
  File: ""
  GitCommit: 6f68fe0f7051c10f2bf43a50a7decfce2e97baf0
  Tags:
  - 3.5.0-scala2.12-java17-python3-r-ubuntu
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.0/scala2.12-java11-python3-ubuntu
  File: ""
  GitCommit: 028efd4637fb2cf791d5bd9ea70b2fca472de4b7
  Tags:
  - 3.5.0-scala2.12-java11-python3-ubuntu
  - 3.5.0-python3
  - 3.5.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.0/scala2.12-java11-r-ubuntu
  File: ""
  GitCommit: 028efd4637fb2cf791d5bd9ea70b2fca472de4b7
  Tags:
  - 3.5.0-scala2.12-java11-r-ubuntu
  - 3.5.0-r
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.0/scala2.12-java11-ubuntu
  File: ""
  GitCommit: 028efd4637fb2cf791d5bd9ea70b2fca472de4b7
  Tags:
  - 3.5.0-scala2.12-java11-ubuntu
  - 3.5.0-scala
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.5.0/scala2.12-java11-python3-r-ubuntu
  File: ""
  GitCommit: 028efd4637fb2cf791d5bd9ea70b2fca472de4b7
  Tags:
  - 3.5.0-scala2.12-java11-python3-r-ubuntu
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.0/scala2.12-java11-python3-ubuntu
  File: ""
  GitCommit: 7f9b414de48639d69c64acfd81e6792517b86f61
  Tags:
  - 3.4.0-scala2.12-java11-python3-ubuntu
  - 3.4.0-python3
  - 3.4.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.0/scala2.12-java11-r-ubuntu
  File: ""
  GitCommit: 7f9b414de48639d69c64acfd81e6792517b86f61
  Tags:
  - 3.4.0-scala2.12-java11-r-ubuntu
  - 3.4.0-r
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.0/scala2.12-java11-ubuntu
  File: ""
  GitCommit: 7f9b414de48639d69c64acfd81e6792517b86f61
  Tags:
  - 3.4.0-scala2.12-java11-ubuntu
  - 3.4.0-scala
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ./3.4.0/scala2.12-java11-python3-r-ubuntu
  File: ""
  GitCommit: 7f9b414de48639d69c64acfd81e6792517b86f61
  Tags:
  - 3.4.0-scala2.12-java11-python3-r-ubuntu
GitRepo: https://github.com/apache/spark-docker.git
KnownTags:
  3.4.0: {}
  3.4.0-python3: {}
  3.4.0-r: {}
  3.4.0-scala: {}
  3.4.0-scala2.12-java11-python3-r-ubuntu: {}
  3.4.0-scala2.12-java11-python3-ubuntu: {}
  3.4.0-scala2.12-java11-r-ubuntu: {}
  3.4.0-scala2.12-java11-ubuntu: {}
  3.4.1: {}
  3.4.1-python3: {}
  3.4.1-r: {}
  3.4.1-scala: {}
  3.4.1-scala2.12-java11-python3-r-ubuntu: {}
  3.4.1-scala2.12-java11-python3-ubuntu: {}
  3.4.1-scala2.12-java11-r-ubuntu: {}
  3.4.1-scala2.12-java11-ubuntu: {}
  3.4.2: {}
  3.4.2-python3: {}
  3.4.2-r: {}
  3.4.2-scala: {}
  3.4.2-scala2.12-java11-python3-r-ubuntu: {}
  3.4.2-scala2.12-java11-python3-ubuntu: {}
  3.4.2-scala2.12-java11-r-ubuntu: {}
  3.4.2-scala2.12-java11-ubuntu: {}
  3.5.0: {}
  3.5.0-java17: {}
  3.5.0-java17-python3: {}
  3.5.0-java17-r: {}
  3.5.0-java17-scala: {}
  3.5.0-python3: {}
  3.5.0-r: {}
  3.5.0-scala: {}
  3.5.0-scala2.12-java11-python3-r-ubuntu: {}
  3.5.0-scala2.12-java11-python3-ubuntu: {}
  3.5.0-scala2.12-java11-r-ubuntu: {}
  3.5.0-scala2.12-java11-ubuntu: {}
  3.5.0-scala2.12-java17-python3-r-ubuntu: {}
  3.5.0-scala2.12-java17-python3-ubuntu: {}
  3.5.0-scala2.12-java17-r-ubuntu: {}
  3.5.0-scala2.12-java17-ubuntu: {}
  3.5.1: {}
  3.5.1-java17: {}
  3.5.1-java17-python3: {}
  3.5.1-java17-r: {}
  3.5.1-java17-scala: {}
  3.5.1-python3: {}
  3.5.1-r: {}
  3.5.1-scala: {}
  3.5.1-scala2.12-java11-python3-r-ubuntu: {}
  3.5.1-scala2.12-java11-python3-ubuntu: {}
  3.5.1-scala2.12-java11-r-ubuntu: {}
  3.5.1-scala2.12-java11-ubuntu: {}
  3.5.1-scala2.12-java17-python3-r-ubuntu: {}
  3.5.1-scala2.12-java17-python3-ubuntu: {}
  3.5.1-scala2.12-java17-r-ubuntu: {}
  3.5.1-scala2.12-java17-ubuntu: {}
  3.5.2: {}
  3.5.2-java17: {}
  3.5.2-java17-python3: {}
  3.5.2-java17-r: {}
  3.5.2-java17-scala: {}
  3.5.2-python3: {}
  3.5.2-r: {}
  3.5.2-scala: {}
  3.5.2-scala2.12-java11-python3-r-ubuntu: {}
  3.5.2-scala2.12-java11-python3-ubuntu: {}
  3.5.2-scala2.12-java11-r-ubuntu: {}
  3.5.2-scala2.12-java11-ubuntu: {}
  3.5.2-scala2.12-java17-python3-r-ubuntu: {}
  3.5.2-scala2.12-java17-python3-ubuntu: {}
  3.5.2-scala2.12-java17-r-ubuntu: {}
  3.5.2-scala2.12-java17-ubuntu: {}
  4.0.0-preview1: {}
  4.0.0-preview1-python3: {}
  4.0.0-preview1-r: {}
  4.0.0-preview1-scala: {}
  4.0.0-preview1-scala2.13-java17-python3-r-ubuntu: {}
  4.0.0-preview1-scala2.13-java17-python3-ubuntu: {}
  4.0.0-preview1-scala2.13-java17-r-ubuntu: {}
  4.0.0-preview1-scala2.13-java17-ubuntu: {}
  latest: {}
  python3: {}
  python3-java17: {}
  r: {}
  scala: {}
Name: spark
