Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: enterprise/debian11
  GitCommit: 1bb3ab4e95e31129c32653db28ff7f163d13671d
  Tags:
  - ee-6.3.0.5
  - ee-6.3.0.5_1
- Architectures:
  - amd64
  - arm64v8
  Directory: community/debian11
  GitCommit: 1bb3ab4e95e31129c32653db28ff7f163d13671d
  Tags:
  - ce-6.3.0.5
  - ce-6.3.0.5_1
GitRepo: https://github.com/aerospike/aerospike-server.docker.git
KnownTags:
  ce-6.3.0.5: {}
  ce-6.3.0.5_1: {}
  ee-6.3.0.5: {}
  ee-6.3.0.5_1: {}
Name: aerospike
