Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: ""
  GitCommit: 9b88acabe6265b4a6df693f26432563e95d8a8f7
  Tags:
  - 5.3.2
  - "5.3"
  - latest
- Architectures:
  - amd64
  - arm64v8
  Directory: ""
  GitCommit: 9dd974bffff06d56e844a099c709583864c970e6
  Tags:
  - 5.2.8
  - "5.2"
- Architectures:
  - amd64
  - arm64v8
  Directory: ""
  GitCommit: 1389b454dc1478efcbde8f9846bdd8ac6f7f0f8a
  Tags:
  - 4.8.4
  - "4.8"
GitRepo: https://github.com/crate/docker-crate.git
KnownTags:
  "4.8": {}
  4.8.4: {}
  "5.2": {}
  5.2.8: {}
  "5.3": {}
  5.3.2: {}
  latest: {}
Name: crate
