Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: debian/bookworm/curl
  GitCommit: 3e18c3af1f5dce6a48abf036857f9097b6bd79cc
  Tags:
  - bookworm-curl
  - stable-curl
  - curl
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: debian/bookworm/scm
  GitCommit: 84e7e46026131a108a6480e5ed2969e8acf2d4e2
  Tags:
  - bookworm-scm
  - stable-scm
  - scm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: debian/bookworm
  GitCommit: 84e7e46026131a108a6480e5ed2969e8acf2d4e2
  Tags:
  - bookworm
  - stable
  - latest
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: debian/bullseye/curl
  GitCommit: 93d6db0797f91ab674535553b7e0e762941a02d0
  Tags:
  - bullseye-curl
  - oldstable-curl
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: debian/bullseye/scm
  GitCommit: 65d69325ad741cea6dee20781c1faaab2e003d87
  Tags:
  - bullseye-scm
  - oldstable-scm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: debian/bullseye
  GitCommit: 65d69325ad741cea6dee20781c1faaab2e003d87
  Tags:
  - bullseye
  - oldstable
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: debian/buster/curl
  GitCommit: 93d6db0797f91ab674535553b7e0e762941a02d0
  Tags:
  - buster-curl
  - oldoldstable-curl
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: debian/buster/scm
  GitCommit: 65d69325ad741cea6dee20781c1faaab2e003d87
  Tags:
  - buster-scm
  - oldoldstable-scm
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: debian/buster
  GitCommit: 65d69325ad741cea6dee20781c1faaab2e003d87
  Tags:
  - buster
  - oldoldstable
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - riscv64
  - s390x
  Directory: debian/sid/curl
  GitCommit: 3e18c3af1f5dce6a48abf036857f9097b6bd79cc
  Tags:
  - sid-curl
  - unstable-curl
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - riscv64
  - s390x
  Directory: debian/sid/scm
  GitCommit: 65d69325ad741cea6dee20781c1faaab2e003d87
  Tags:
  - sid-scm
  - unstable-scm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - riscv64
  - s390x
  Directory: debian/sid
  GitCommit: 65d69325ad741cea6dee20781c1faaab2e003d87
  Tags:
  - sid
  - unstable
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ubuntu/bionic/curl
  GitCommit: 93d6db0797f91ab674535553b7e0e762941a02d0
  Tags:
  - bionic-curl
  - 18.04-curl
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ubuntu/bionic/scm
  GitCommit: 65d69325ad741cea6dee20781c1faaab2e003d87
  Tags:
  - bionic-scm
  - 18.04-scm
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ubuntu/bionic
  GitCommit: 98a5ab81d47a106c458cdf90733df0ee8beea06c
  Tags:
  - bionic
  - "18.04"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: ubuntu/focal/curl
  GitCommit: 93d6db0797f91ab674535553b7e0e762941a02d0
  Tags:
  - focal-curl
  - 20.04-curl
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: ubuntu/focal/scm
  GitCommit: 65d69325ad741cea6dee20781c1faaab2e003d87
  Tags:
  - focal-scm
  - 20.04-scm
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: ubuntu/focal
  GitCommit: 98a5ab81d47a106c458cdf90733df0ee8beea06c
  Tags:
  - focal
  - "20.04"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: ubuntu/jammy/curl
  GitCommit: 93d6db0797f91ab674535553b7e0e762941a02d0
  Tags:
  - jammy-curl
  - 22.04-curl
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: ubuntu/jammy/scm
  GitCommit: e2fc735283ba4e96efc3e4acf2b74bc3eccbf327
  Tags:
  - jammy-scm
  - 22.04-scm
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: ubuntu/jammy
  GitCommit: e2fc735283ba4e96efc3e4acf2b74bc3eccbf327
  Tags:
  - jammy
  - "22.04"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: ubuntu/kinetic/curl
  GitCommit: 3e18c3af1f5dce6a48abf036857f9097b6bd79cc
  Tags:
  - kinetic-curl
  - 22.10-curl
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: ubuntu/kinetic/scm
  GitCommit: c96f4f3e1d5bc19fba5c652f57af0a35bb929718
  Tags:
  - kinetic-scm
  - 22.10-scm
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: ubuntu/kinetic
  GitCommit: c96f4f3e1d5bc19fba5c652f57af0a35bb929718
  Tags:
  - kinetic
  - "22.10"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: ubuntu/lunar/curl
  GitCommit: 3e18c3af1f5dce6a48abf036857f9097b6bd79cc
  Tags:
  - lunar-curl
  - 23.04-curl
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: ubuntu/lunar/scm
  GitCommit: 31e15bc4a2352c20998e5da6bd8aaa727fd19d06
  Tags:
  - lunar-scm
  - 23.04-scm
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: ubuntu/lunar
  GitCommit: 31e15bc4a2352c20998e5da6bd8aaa727fd19d06
  Tags:
  - lunar
  - "23.04"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: ubuntu/mantic/curl
  GitCommit: ba367c3a52946cee45274b62f7f8b27e07807289
  Tags:
  - mantic-curl
  - 23.10-curl
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: ubuntu/mantic/scm
  GitCommit: ba367c3a52946cee45274b62f7f8b27e07807289
  Tags:
  - mantic-scm
  - 23.10-scm
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: ubuntu/mantic
  GitCommit: ba367c3a52946cee45274b62f7f8b27e07807289
  Tags:
  - mantic
  - "23.10"
GitRepo: https://github.com/docker-library/buildpack-deps.git
KnownTags:
  "18.04": {}
  18.04-curl: {}
  18.04-scm: {}
  "20.04": {}
  20.04-curl: {}
  20.04-scm: {}
  "22.04": {}
  22.04-curl: {}
  22.04-scm: {}
  "22.10": {}
  22.10-curl: {}
  22.10-scm: {}
  "23.04": {}
  23.04-curl: {}
  23.04-scm: {}
  "23.10": {}
  23.10-curl: {}
  23.10-scm: {}
  bionic: {}
  bionic-curl: {}
  bionic-scm: {}
  bookworm: {}
  bookworm-curl: {}
  bookworm-scm: {}
  bullseye: {}
  bullseye-curl: {}
  bullseye-scm: {}
  buster: {}
  buster-curl: {}
  buster-scm: {}
  curl: {}
  focal: {}
  focal-curl: {}
  focal-scm: {}
  jammy: {}
  jammy-curl: {}
  jammy-scm: {}
  kinetic: {}
  kinetic-curl: {}
  kinetic-scm: {}
  latest: {}
  lunar: {}
  lunar-curl: {}
  lunar-scm: {}
  mantic: {}
  mantic-curl: {}
  mantic-scm: {}
  oldoldstable: {}
  oldoldstable-curl: {}
  oldoldstable-scm: {}
  oldstable: {}
  oldstable-curl: {}
  oldstable-scm: {}
  scm: {}
  sid: {}
  sid-curl: {}
  sid-scm: {}
  stable: {}
  stable-curl: {}
  stable-scm: {}
  unstable: {}
  unstable-curl: {}
  unstable-scm: {}
Name: buildpack-deps
