Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: dockerfiles/bionic
  GitCommit: ""
  Tags:
  - bionic
  - nd18.04
- Architectures:
  - amd64
  - arm64v8
  Directory: dockerfiles/bionic-non-free
  GitCommit: ""
  Tags:
  - bionic-non-free
  - nd18.04-non-free
- Architectures:
  - amd64
  - arm64v8
  Directory: dockerfiles/focal
  GitCommit: ""
  Tags:
  - focal
  - nd20.04
- Architectures:
  - amd64
  - arm64v8
  Directory: dockerfiles/focal-non-free
  GitCommit: ""
  Tags:
  - focal-non-free
  - nd20.04-non-free
- Architectures:
  - amd64
  - arm64v8
  Directory: dockerfiles/jammy
  GitCommit: ""
  Tags:
  - jammy
  - nd22.04
- Architectures:
  - amd64
  - arm64v8
  Directory: dockerfiles/jammy-non-free
  GitCommit: ""
  Tags:
  - jammy-non-free
  - nd22.04-non-free
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: dockerfiles/buster
  GitCommit: ""
  Tags:
  - buster
  - nd100
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: dockerfiles/buster-non-free
  GitCommit: ""
  Tags:
  - buster-non-free
  - nd100-non-free
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: dockerfiles/bullseye
  GitCommit: ""
  Tags:
  - bullseye
  - nd110
  - latest
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: dockerfiles/bullseye-non-free
  GitCommit: ""
  Tags:
  - bullseye-non-free
  - nd110-non-free
  - non-free
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: dockerfiles/bookworm
  GitCommit: ""
  Tags:
  - bookworm
  - nd120
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: dockerfiles/bookworm-non-free
  GitCommit: ""
  Tags:
  - bookworm-non-free
  - nd120-non-free
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: dockerfiles/sid
  GitCommit: ""
  Tags:
  - sid
  - nd
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: dockerfiles/sid-non-free
  GitCommit: ""
  Tags:
  - sid-non-free
  - nd-non-free
GitRepo: https://github.com/neurodebian/dockerfiles.git
KnownTags:
  bionic: {}
  bionic-non-free: {}
  bookworm: {}
  bookworm-non-free: {}
  bullseye: {}
  bullseye-non-free: {}
  buster: {}
  buster-non-free: {}
  focal: {}
  focal-non-free: {}
  jammy: {}
  jammy-non-free: {}
  latest: {}
  nd: {}
  nd-non-free: {}
  nd18.04: {}
  nd18.04-non-free: {}
  nd20.04: {}
  nd20.04-non-free: {}
  nd22.04: {}
  nd22.04-non-free: {}
  nd100: {}
  nd100-non-free: {}
  nd110: {}
  nd110-non-free: {}
  nd120: {}
  nd120-non-free: {}
  non-free: {}
  sid: {}
  sid-non-free: {}
Name: neurodebian
