Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/focal
  File: ""
  GitCommit: 89ca52860d80889fd878392a29150e46d9d91a71
  Tags:
  - focal
  - nd20.04
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/focal-non-free
  File: ""
  GitCommit: 89ca52860d80889fd878392a29150e46d9d91a71
  Tags:
  - focal-non-free
  - nd20.04-non-free
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/jammy
  File: ""
  GitCommit: 89ca52860d80889fd878392a29150e46d9d91a71
  Tags:
  - jammy
  - nd22.04
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/jammy-non-free
  File: ""
  GitCommit: 89ca52860d80889fd878392a29150e46d9d91a71
  Tags:
  - jammy-non-free
  - nd22.04-non-free
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/noble
  File: ""
  GitCommit: 89ca52860d80889fd878392a29150e46d9d91a71
  Tags:
  - noble
  - nd24.04
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/noble-non-free
  File: ""
  GitCommit: 89ca52860d80889fd878392a29150e46d9d91a71
  Tags:
  - noble-non-free
  - nd24.04-non-free
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/bullseye
  File: ""
  GitCommit: 89ca52860d80889fd878392a29150e46d9d91a71
  Tags:
  - bullseye
  - nd110
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/bullseye-non-free
  File: ""
  GitCommit: 89ca52860d80889fd878392a29150e46d9d91a71
  Tags:
  - bullseye-non-free
  - nd110-non-free
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/bookworm
  File: ""
  GitCommit: 89ca52860d80889fd878392a29150e46d9d91a71
  Tags:
  - bookworm
  - nd120
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/bookworm-non-free
  File: ""
  GitCommit: 89ca52860d80889fd878392a29150e46d9d91a71
  Tags:
  - bookworm-non-free
  - nd120-non-free
  - non-free
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/trixie
  File: ""
  GitCommit: a0af1d460705d7efc9d6de9483f1ce4aa48ad152
  Tags:
  - trixie
  - nd130
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/trixie-non-free
  File: ""
  GitCommit: a0af1d460705d7efc9d6de9483f1ce4aa48ad152
  Tags:
  - trixie-non-free
  - nd130-non-free
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/sid
  File: ""
  GitCommit: a0af1d460705d7efc9d6de9483f1ce4aa48ad152
  Tags:
  - sid
  - nd
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/sid-non-free
  File: ""
  GitCommit: a0af1d460705d7efc9d6de9483f1ce4aa48ad152
  Tags:
  - sid-non-free
  - nd-non-free
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/buster
  File: ""
  GitCommit: a0af1d460705d7efc9d6de9483f1ce4aa48ad152
  Tags:
  - buster
  - nd100
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/buster-non-free
  File: ""
  GitCommit: a0af1d460705d7efc9d6de9483f1ce4aa48ad152
  Tags:
  - buster-non-free
  - nd100-non-free
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/bionic
  File: ""
  GitCommit: 1da9308291ad33a33447519ec1835bb3e37acebc
  Tags:
  - bionic
  - nd18.04
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/bionic-non-free
  File: ""
  GitCommit: 1da9308291ad33a33447519ec1835bb3e37acebc
  Tags:
  - bionic-non-free
  - nd18.04-non-free
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/xenial
  File: ""
  GitCommit: 53a254d17e6c1c21787ed44b6e848c1af46ea9be
  Tags:
  - xenial
  - nd16.04
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/xenial-non-free
  File: ""
  GitCommit: 53a254d17e6c1c21787ed44b6e848c1af46ea9be
  Tags:
  - xenial-non-free
  - nd16.04-non-free
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/impish
  File: ""
  GitCommit: c9aa5f02de44d51bfcd81af986829550b227daeb
  Tags:
  - impish
  - nd21.10
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/impish-non-free
  File: ""
  GitCommit: c9aa5f02de44d51bfcd81af986829550b227daeb
  Tags:
  - impish-non-free
  - nd21.10-non-free
- Architectures: null
  Directory: dockerfiles/stretch
  File: ""
  GitCommit: 97b3bc1860afafc294abbec1f95bc239ddeddd88
  Tags:
  - stretch
  - nd90
- Architectures: null
  Directory: dockerfiles/stretch-non-free
  File: ""
  GitCommit: 97b3bc1860afafc294abbec1f95bc239ddeddd88
  Tags:
  - stretch-non-free
  - nd90-non-free
- Architectures: null
  Directory: dockerfiles/hirsute
  File: ""
  GitCommit: a95bab388a1791db8ca2830d78417637bd0ca167
  Tags:
  - hirsute
  - nd21.04
- Architectures: null
  Directory: dockerfiles/hirsute-non-free
  File: ""
  GitCommit: a95bab388a1791db8ca2830d78417637bd0ca167
  Tags:
  - hirsute-non-free
  - nd21.04-non-free
- Architectures: null
  Directory: dockerfiles/groovy
  File: ""
  GitCommit: 1e23b9e778a6d38877359febf13a013551a045ae
  Tags:
  - groovy
  - nd20.10
- Architectures: null
  Directory: dockerfiles/groovy-non-free
  File: ""
  GitCommit: 1e23b9e778a6d38877359febf13a013551a045ae
  Tags:
  - groovy-non-free
  - nd20.10-non-free
- Architectures: null
  Directory: dockerfiles/trusty
  File: ""
  GitCommit: 54ea480e6e3b2563e3e5dcd3df74ca3d280876e1
  Tags:
  - trusty
  - nd14.04
- Architectures: null
  Directory: dockerfiles/trusty-non-free
  File: ""
  GitCommit: 54ea480e6e3b2563e3e5dcd3df74ca3d280876e1
  Tags:
  - trusty-non-free
  - nd14.04-non-free
- Architectures: null
  Directory: dockerfiles/jessie
  File: ""
  GitCommit: 54ea480e6e3b2563e3e5dcd3df74ca3d280876e1
  Tags:
  - jessie
  - nd80
- Architectures: null
  Directory: dockerfiles/jessie-non-free
  File: ""
  GitCommit: 54ea480e6e3b2563e3e5dcd3df74ca3d280876e1
  Tags:
  - jessie-non-free
  - nd80-non-free
- Architectures: null
  Directory: dockerfiles/disco
  File: ""
  GitCommit: b48258339ba2e3addd11ccaed4933f8e5153033c
  Tags:
  - disco
  - nd19.04
- Architectures: null
  Directory: dockerfiles/disco-non-free
  File: ""
  GitCommit: b48258339ba2e3addd11ccaed4933f8e5153033c
  Tags:
  - disco-non-free
  - nd19.04-non-free
- Architectures: null
  Directory: dockerfiles/cosmic
  File: ""
  GitCommit: 28179a5247bf4681dd56cd11c542f57fafbe0354
  Tags:
  - cosmic
  - nd18.10
- Architectures: null
  Directory: dockerfiles/cosmic-non-free
  File: ""
  GitCommit: 28179a5247bf4681dd56cd11c542f57fafbe0354
  Tags:
  - cosmic-non-free
  - nd18.10-non-free
- Architectures: null
  Directory: dockerfiles/wheezy
  File: ""
  GitCommit: 3af4359d1781af273f5fbc5aa8e6ff1055eb4aa4
  Tags:
  - wheezy
  - nd70
- Architectures: null
  Directory: dockerfiles/wheezy-non-free
  File: ""
  GitCommit: 3af4359d1781af273f5fbc5aa8e6ff1055eb4aa4
  Tags:
  - wheezy-non-free
  - nd70-non-free
- Architectures: null
  Directory: dockerfiles/artful
  File: ""
  GitCommit: 88af27888a5aee76924c3b6840fc47f9cd8f63cb
  Tags:
  - artful
  - nd17.10
- Architectures: null
  Directory: dockerfiles/artful-non-free
  File: ""
  GitCommit: 88af27888a5aee76924c3b6840fc47f9cd8f63cb
  Tags:
  - artful-non-free
  - nd17.10-non-free
- Architectures: null
  Directory: dockerfiles/zesty
  File: ""
  GitCommit: 16393dd2b676c6128a4b9742cb51b9ce9ab7d436
  Tags:
  - zesty
  - nd17.04
- Architectures: null
  Directory: dockerfiles/zesty-non-free
  File: ""
  GitCommit: 16393dd2b676c6128a4b9742cb51b9ce9ab7d436
  Tags:
  - zesty-non-free
  - nd17.04-non-free
GitRepo: https://github.com/neurodebian/dockerfiles.git
KnownTags:
  artful: {}
  artful-non-free: {}
  bionic: {}
  bionic-non-free: {}
  bookworm: {}
  bookworm-non-free: {}
  bullseye: {}
  bullseye-non-free: {}
  buster: {}
  buster-non-free: {}
  cosmic: {}
  cosmic-non-free: {}
  disco: {}
  disco-non-free: {}
  focal: {}
  focal-non-free: {}
  groovy: {}
  groovy-non-free: {}
  hirsute: {}
  hirsute-non-free: {}
  impish: {}
  impish-non-free: {}
  jammy: {}
  jammy-non-free: {}
  jessie: {}
  jessie-non-free: {}
  latest: {}
  nd: {}
  nd-non-free: {}
  nd14.04: {}
  nd14.04-non-free: {}
  nd16.04: {}
  nd16.04-non-free: {}
  nd17.04: {}
  nd17.04-non-free: {}
  nd17.10: {}
  nd17.10-non-free: {}
  nd18.04: {}
  nd18.04-non-free: {}
  nd18.10: {}
  nd18.10-non-free: {}
  nd19.04: {}
  nd19.04-non-free: {}
  nd20.04: {}
  nd20.04-non-free: {}
  nd20.10: {}
  nd20.10-non-free: {}
  nd21.04: {}
  nd21.04-non-free: {}
  nd21.10: {}
  nd21.10-non-free: {}
  nd22.04: {}
  nd22.04-non-free: {}
  nd24.04: {}
  nd24.04-non-free: {}
  nd70: {}
  nd70-non-free: {}
  nd80: {}
  nd80-non-free: {}
  nd90: {}
  nd90-non-free: {}
  nd100: {}
  nd100-non-free: {}
  nd110: {}
  nd110-non-free: {}
  nd120: {}
  nd120-non-free: {}
  nd130: {}
  nd130-non-free: {}
  noble: {}
  noble-non-free: {}
  non-free: {}
  sid: {}
  sid-non-free: {}
  stretch: {}
  stretch-non-free: {}
  trixie: {}
  trixie-non-free: {}
  trusty: {}
  trusty-non-free: {}
  wheezy: {}
  wheezy-non-free: {}
  xenial: {}
  xenial-non-free: {}
  zesty: {}
  zesty-non-free: {}
Name: neurodebian
