Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/bionic
  File: ""
  GitCommit: ""
  Tags:
  - bionic
  - nd18.04
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/bionic-non-free
  File: ""
  GitCommit: ""
  Tags:
  - bionic-non-free
  - nd18.04-non-free
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/focal
  File: ""
  GitCommit: ""
  Tags:
  - focal
  - nd20.04
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/focal-non-free
  File: ""
  GitCommit: ""
  Tags:
  - focal-non-free
  - nd20.04-non-free
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/jammy
  File: ""
  GitCommit: ""
  Tags:
  - jammy
  - nd22.04
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/jammy-non-free
  File: ""
  GitCommit: ""
  Tags:
  - jammy-non-free
  - nd22.04-non-free
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/buster
  File: ""
  GitCommit: ""
  Tags:
  - buster
  - nd100
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/buster-non-free
  File: ""
  GitCommit: ""
  Tags:
  - buster-non-free
  - nd100-non-free
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/bullseye
  File: ""
  GitCommit: ""
  Tags:
  - bullseye
  - nd110
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/bullseye-non-free
  File: ""
  GitCommit: ""
  Tags:
  - bullseye-non-free
  - nd110-non-free
  - non-free
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/bookworm
  File: ""
  GitCommit: ""
  Tags:
  - bookworm
  - nd120
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/bookworm-non-free
  File: ""
  GitCommit: ""
  Tags:
  - bookworm-non-free
  - nd120-non-free
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/sid
  File: ""
  GitCommit: ""
  Tags:
  - sid
  - nd
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/sid-non-free
  File: ""
  GitCommit: ""
  Tags:
  - sid-non-free
  - nd-non-free
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/xenial
  File: ""
  GitCommit: ""
  Tags:
  - xenial
  - nd16.04
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/xenial-non-free
  File: ""
  GitCommit: ""
  Tags:
  - xenial-non-free
  - nd16.04-non-free
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/impish
  File: ""
  GitCommit: ""
  Tags:
  - impish
  - nd21.10
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: dockerfiles/impish-non-free
  File: ""
  GitCommit: ""
  Tags:
  - impish-non-free
  - nd21.10-non-free
- Architectures: null
  Directory: dockerfiles/stretch
  File: ""
  GitCommit: ""
  Tags:
  - stretch
  - nd90
- Architectures: null
  Directory: dockerfiles/stretch-non-free
  File: ""
  GitCommit: ""
  Tags:
  - stretch-non-free
  - nd90-non-free
- Architectures: null
  Directory: dockerfiles/hirsute
  File: ""
  GitCommit: ""
  Tags:
  - hirsute
  - nd21.04
- Architectures: null
  Directory: dockerfiles/hirsute-non-free
  File: ""
  GitCommit: ""
  Tags:
  - hirsute-non-free
  - nd21.04-non-free
- Architectures: null
  Directory: dockerfiles/groovy
  File: ""
  GitCommit: ""
  Tags:
  - groovy
  - nd20.10
- Architectures: null
  Directory: dockerfiles/groovy-non-free
  File: ""
  GitCommit: ""
  Tags:
  - groovy-non-free
  - nd20.10-non-free
- Architectures: null
  Directory: dockerfiles/trusty
  File: ""
  GitCommit: ""
  Tags:
  - trusty
  - nd14.04
- Architectures: null
  Directory: dockerfiles/trusty-non-free
  File: ""
  GitCommit: ""
  Tags:
  - trusty-non-free
  - nd14.04-non-free
- Architectures: null
  Directory: dockerfiles/jessie
  File: ""
  GitCommit: ""
  Tags:
  - jessie
  - nd80
- Architectures: null
  Directory: dockerfiles/jessie-non-free
  File: ""
  GitCommit: ""
  Tags:
  - jessie-non-free
  - nd80-non-free
- Architectures: null
  Directory: dockerfiles/disco
  File: ""
  GitCommit: ""
  Tags:
  - disco
  - nd19.04
- Architectures: null
  Directory: dockerfiles/disco-non-free
  File: ""
  GitCommit: ""
  Tags:
  - disco-non-free
  - nd19.04-non-free
- Architectures: null
  Directory: dockerfiles/cosmic
  File: ""
  GitCommit: ""
  Tags:
  - cosmic
  - nd18.10
- Architectures: null
  Directory: dockerfiles/cosmic-non-free
  File: ""
  GitCommit: ""
  Tags:
  - cosmic-non-free
  - nd18.10-non-free
- Architectures: null
  Directory: dockerfiles/wheezy
  File: ""
  GitCommit: ""
  Tags:
  - wheezy
  - nd70
- Architectures: null
  Directory: dockerfiles/wheezy-non-free
  File: ""
  GitCommit: ""
  Tags:
  - wheezy-non-free
  - nd70-non-free
- Architectures: null
  Directory: dockerfiles/artful
  File: ""
  GitCommit: ""
  Tags:
  - artful
  - nd17.10
- Architectures: null
  Directory: dockerfiles/artful-non-free
  File: ""
  GitCommit: ""
  Tags:
  - artful-non-free
  - nd17.10-non-free
- Architectures: null
  Directory: dockerfiles/zesty
  File: ""
  GitCommit: ""
  Tags:
  - zesty
  - nd17.04
- Architectures: null
  Directory: dockerfiles/zesty-non-free
  File: ""
  GitCommit: ""
  Tags:
  - zesty-non-free
  - nd17.04-non-free
GitRepo: https://github.com/neurodebian/dockerfiles.git
KnownTags:
  artful: {}
  artful-non-free: {}
  bionic: {}
  bionic-non-free: {}
  bookworm: {}
  bookworm-non-free: {}
  bullseye: {}
  bullseye-non-free: {}
  buster: {}
  buster-non-free: {}
  cosmic: {}
  cosmic-non-free: {}
  disco: {}
  disco-non-free: {}
  focal: {}
  focal-non-free: {}
  groovy: {}
  groovy-non-free: {}
  hirsute: {}
  hirsute-non-free: {}
  impish: {}
  impish-non-free: {}
  jammy: {}
  jammy-non-free: {}
  jessie: {}
  jessie-non-free: {}
  latest: {}
  nd: {}
  nd-non-free: {}
  nd14.04: {}
  nd14.04-non-free: {}
  nd16.04: {}
  nd16.04-non-free: {}
  nd17.04: {}
  nd17.04-non-free: {}
  nd17.10: {}
  nd17.10-non-free: {}
  nd18.04: {}
  nd18.04-non-free: {}
  nd18.10: {}
  nd18.10-non-free: {}
  nd19.04: {}
  nd19.04-non-free: {}
  nd20.04: {}
  nd20.04-non-free: {}
  nd20.10: {}
  nd20.10-non-free: {}
  nd21.04: {}
  nd21.04-non-free: {}
  nd21.10: {}
  nd21.10-non-free: {}
  nd22.04: {}
  nd22.04-non-free: {}
  nd70: {}
  nd70-non-free: {}
  nd80: {}
  nd80-non-free: {}
  nd90: {}
  nd90-non-free: {}
  nd100: {}
  nd100-non-free: {}
  nd110: {}
  nd110-non-free: {}
  nd120: {}
  nd120-non-free: {}
  non-free: {}
  sid: {}
  sid-non-free: {}
  stretch: {}
  stretch-non-free: {}
  trusty: {}
  trusty-non-free: {}
  wheezy: {}
  wheezy-non-free: {}
  xenial: {}
  xenial-non-free: {}
  zesty: {}
  zesty-non-free: {}
Name: neurodebian
