Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 1.70.0/buster
  GitCommit: dcb74d779e8a74263dc8b91d58d8ce7f3c0c805b
  Tags:
  - 1-buster
  - 1.70-buster
  - 1.70.0-buster
  - buster
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 1.70.0/buster/slim
  GitCommit: dcb74d779e8a74263dc8b91d58d8ce7f3c0c805b
  Tags:
  - 1-slim-buster
  - 1.70-slim-buster
  - 1.70.0-slim-buster
  - slim-buster
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 1.70.0/bullseye
  GitCommit: dcb74d779e8a74263dc8b91d58d8ce7f3c0c805b
  Tags:
  - 1-bullseye
  - 1.70-bullseye
  - 1.70.0-bullseye
  - bullseye
  - "1"
  - "1.70"
  - 1.70.0
  - latest
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 1.70.0/bullseye/slim
  GitCommit: dcb74d779e8a74263dc8b91d58d8ce7f3c0c805b
  Tags:
  - 1-slim-bullseye
  - 1.70-slim-bullseye
  - 1.70.0-slim-bullseye
  - slim-bullseye
  - 1-slim
  - 1.70-slim
  - 1.70.0-slim
  - slim
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 1.70.0/bookworm
  GitCommit: dcb74d779e8a74263dc8b91d58d8ce7f3c0c805b
  Tags:
  - 1-bookworm
  - 1.70-bookworm
  - 1.70.0-bookworm
  - bookworm
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 1.70.0/bookworm/slim
  GitCommit: dcb74d779e8a74263dc8b91d58d8ce7f3c0c805b
  Tags:
  - 1-slim-bookworm
  - 1.70-slim-bookworm
  - 1.70.0-slim-bookworm
  - slim-bookworm
- Architectures:
  - amd64
  - arm64v8
  Directory: 1.70.0/alpine3.17
  GitCommit: dcb74d779e8a74263dc8b91d58d8ce7f3c0c805b
  Tags:
  - 1-alpine3.17
  - 1.70-alpine3.17
  - 1.70.0-alpine3.17
  - alpine3.17
- Architectures:
  - amd64
  - arm64v8
  Directory: 1.70.0/alpine3.18
  GitCommit: dcb74d779e8a74263dc8b91d58d8ce7f3c0c805b
  Tags:
  - 1-alpine3.18
  - 1.70-alpine3.18
  - 1.70.0-alpine3.18
  - alpine3.18
  - 1-alpine
  - 1.70-alpine
  - 1.70.0-alpine
  - alpine
GitRepo: https://github.com/rust-lang/docker-rust.git
KnownTags:
  "1": {}
  1-alpine: {}
  1-alpine3.17: {}
  1-alpine3.18: {}
  1-bookworm: {}
  1-bullseye: {}
  1-buster: {}
  1-slim: {}
  1-slim-bookworm: {}
  1-slim-bullseye: {}
  1-slim-buster: {}
  "1.70": {}
  1.70-alpine: {}
  1.70-alpine3.17: {}
  1.70-alpine3.18: {}
  1.70-bookworm: {}
  1.70-bullseye: {}
  1.70-buster: {}
  1.70-slim: {}
  1.70-slim-bookworm: {}
  1.70-slim-bullseye: {}
  1.70-slim-buster: {}
  1.70.0: {}
  1.70.0-alpine: {}
  1.70.0-alpine3.17: {}
  1.70.0-alpine3.18: {}
  1.70.0-bookworm: {}
  1.70.0-bullseye: {}
  1.70.0-buster: {}
  1.70.0-slim: {}
  1.70.0-slim-bookworm: {}
  1.70.0-slim-bullseye: {}
  1.70.0-slim-buster: {}
  alpine: {}
  alpine3.17: {}
  alpine3.18: {}
  bookworm: {}
  bullseye: {}
  buster: {}
  latest: {}
  slim: {}
  slim-bookworm: {}
  slim-bullseye: {}
  slim-buster: {}
Name: rust
