Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: amd64/hola-mundo
      File: ""
      GitCommit: b715c35271f1d18832480bde75fe17b93db26414
      GitFetch: ""
    arm32v5:
      Architecture: arm32v5
      Directory: arm32v5/hola-mundo
      File: ""
      GitCommit: b715c35271f1d18832480bde75fe17b93db26414
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: arm32v7/hola-mundo
      File: ""
      GitCommit: b715c35271f1d18832480bde75fe17b93db26414
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: arm64v8/hola-mundo
      File: ""
      GitCommit: b715c35271f1d18832480bde75fe17b93db26414
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i386/hola-mundo
      File: ""
      GitCommit: b715c35271f1d18832480bde75fe17b93db26414
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ppc64le/hola-mundo
      File: ""
      GitCommit: b715c35271f1d18832480bde75fe17b93db26414
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: s390x/hola-mundo
      File: ""
      GitCommit: b715c35271f1d18832480bde75fe17b93db26414
      GitFetch: ""
  Directory: ""
  GitCommit: ""
  Tags:
  - linux
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  GitCommit: ""
  Tags:
  - nanoserver-sac2016
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  GitCommit: ""
  Tags:
  - nanoserver-1709
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  GitCommit: ""
  Tags:
  - nanoserver-1803
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  GitCommit: ""
  Tags:
  - nanoserver-1809
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  GitCommit: ""
  Tags:
  - nanoserver
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  GitCommit: ""
  Tags:
  - nanoserver1709
- Architectures:
    amd64:
      Architecture: amd64
      Directory: amd64/hola-mundo
      File: ""
      GitCommit: 7d0ee592e4ed60e2da9d59331e16ecdcadc1ed87
      GitFetch: ""
    arm32v5:
      Architecture: arm32v5
      Directory: arm32v5/hola-mundo
      File: ""
      GitCommit: 7d0ee592e4ed60e2da9d59331e16ecdcadc1ed87
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: arm32v7/hola-mundo
      File: ""
      GitCommit: 7d0ee592e4ed60e2da9d59331e16ecdcadc1ed87
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: arm64v8/hola-mundo
      File: ""
      GitCommit: 7d0ee592e4ed60e2da9d59331e16ecdcadc1ed87
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i386/hola-mundo
      File: ""
      GitCommit: c0f93c30814d7a2487648efc712dc031a89bac79
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ppc64le/hola-mundo
      File: ""
      GitCommit: 7d0ee592e4ed60e2da9d59331e16ecdcadc1ed87
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: s390x/hola-mundo
      File: ""
      GitCommit: 7d0ee592e4ed60e2da9d59331e16ecdcadc1ed87
      GitFetch: ""
  Directory: ""
  GitCommit: ""
  Tags:
  - latest
GitRepo: https://github.com/docker-library/hello-world.git
KnownTags:
  latest: {}
  linux: {}
  nanoserver: {}
  nanoserver-1709: {}
  nanoserver-1803: {}
  nanoserver-1809: {}
  nanoserver-sac2016: {}
  nanoserver1709: {}
Name: hola-mundo
