Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: amd64/hola-mundo
      File: ""
      GitCommit: b715c35271f1d18832480bde75fe17b93db26414
      GitFetch: ""
    arm32v5:
      Architecture: arm32v5
      Directory: arm32v5/hola-mundo
      File: ""
      GitCommit: b715c35271f1d18832480bde75fe17b93db26414
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: arm32v7/hola-mundo
      File: ""
      GitCommit: b715c35271f1d18832480bde75fe17b93db26414
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: arm64v8/hola-mundo
      File: ""
      GitCommit: b715c35271f1d18832480bde75fe17b93db26414
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i386/hola-mundo
      File: ""
      GitCommit: b715c35271f1d18832480bde75fe17b93db26414
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ppc64le/hola-mundo
      File: ""
      GitCommit: b715c35271f1d18832480bde75fe17b93db26414
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: s390x/hola-mundo
      File: ""
      GitCommit: b715c35271f1d18832480bde75fe17b93db26414
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 9c93e37114a7fe99b5fc0d776e0b8dff99cbbb75
  Tags:
  - linux
  - latest
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 9c93e37114a7fe99b5fc0d776e0b8dff99cbbb75
  Tags:
  - nanoserver-sac2016
  - nanoserver
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 9c93e37114a7fe99b5fc0d776e0b8dff99cbbb75
  Tags:
  - nanoserver-1709
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 9c93e37114a7fe99b5fc0d776e0b8dff99cbbb75
  Tags:
  - nanoserver-1803
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 9c93e37114a7fe99b5fc0d776e0b8dff99cbbb75
  Tags:
  - nanoserver-1809
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: b9c8214f529b04e37683fddba4a4244308f046e8
  Tags:
  - nanoserver1709
GitRepo: https://github.com/docker-library/hello-world.git
KnownTags:
  latest: {}
  linux: {}
  nanoserver: {}
  nanoserver-1709: {}
  nanoserver-1803: {}
  nanoserver-1809: {}
  nanoserver-sac2016: {}
  nanoserver1709: {}
Name: hola-mundo
