Blocks:
- Architectures: null
  Directory: docker/2.0
  GitCommit: ""
  Tags:
  - 2.0.15
  - "2.0"
  - "2"
  - latest
- Architectures: null
  Directory: docker/2.0-openssl
  GitCommit: ""
  Tags:
  - 2.0.15-openssl
  - 2.0-openssl
  - 2-openssl
  - openssl
- Architectures: null
  Directory: docker/1.6-openssl
  GitCommit: ""
  Tags:
  - 1.6.15-openssl
  - 1.6-openssl
- Architectures: null
  Directory: docker/1.6
  GitCommit: ""
  Tags:
  - 1.6.15
  - "1.6"
- Architectures: null
  Directory: docker/1.5
  GitCommit: ""
  Tags:
  - 1.5.11
  - "1.5"
- Architectures: null
  Directory: docker/2.0
  GitCommit: ""
  Tags:
  - 2.0.14
- Architectures: null
  Directory: docker/2.0-openssl
  GitCommit: ""
  Tags:
  - 2.0.14-openssl
- Architectures: null
  Directory: docker/2.0
  GitCommit: ""
  Tags:
  - 2.0.13
- Architectures: null
  Directory: docker/2.0-openssl
  GitCommit: ""
  Tags:
  - 2.0.13-openssl
- Architectures: null
  Directory: docker/2.0
  GitCommit: ""
  Tags:
  - 2.0.12
- Architectures: null
  Directory: docker/2.0-openssl
  GitCommit: ""
  Tags:
  - 2.0.12-openssl
- Architectures: null
  Directory: docker/2.0
  GitCommit: ""
  Tags:
  - 2.0.11
- Architectures: null
  Directory: docker/2.0-openssl
  GitCommit: ""
  Tags:
  - 2.0.11-openssl
- Architectures: null
  Directory: docker/2.0
  GitCommit: ""
  Tags:
  - 2.0.10
- Architectures: null
  Directory: docker/2.0-openssl
  GitCommit: ""
  Tags:
  - 2.0.10-openssl
- Architectures: null
  Directory: docker/1.6
  GitCommit: ""
  Tags:
  - 1.6.14
- Architectures: null
  Directory: docker/1.6-openssl
  GitCommit: ""
  Tags:
  - 1.6.14-openssl
- Architectures: null
  Directory: docker/2.0
  GitCommit: ""
  Tags:
  - 2.0.9
- Architectures: null
  Directory: docker/2.0-openssl
  GitCommit: ""
  Tags:
  - 2.0.9-openssl
- Architectures: null
  Directory: docker/2.0
  GitCommit: ""
  Tags:
  - 2.0.8
- Architectures: null
  Directory: docker/2.0-openssl
  GitCommit: ""
  Tags:
  - 2.0.8-openssl
- Architectures: null
  Directory: docker/1.6
  GitCommit: ""
  Tags:
  - 1.6.13
- Architectures: null
  Directory: docker/1.6-openssl
  GitCommit: ""
  Tags:
  - 1.6.13-openssl
- Architectures: null
  Directory: docker/1.5
  GitCommit: ""
  Tags:
  - 1.5.10
- Architectures: null
  Directory: docker/2.0
  GitCommit: ""
  Tags:
  - 2.0.7
- Architectures: null
  Directory: docker/2.0-openssl
  GitCommit: ""
  Tags:
  - 2.0.7-openssl
- Architectures: null
  Directory: docker/2.0
  GitCommit: ""
  Tags:
  - 2.0.6
- Architectures: null
  Directory: docker/2.0-openssl
  GitCommit: ""
  Tags:
  - 2.0.6-openssl
- Architectures: null
  Directory: docker/1.6
  GitCommit: ""
  Tags:
  - 1.6.12
- Architectures: null
  Directory: docker/1.6-openssl
  GitCommit: ""
  Tags:
  - 1.6.12-openssl
- Architectures: null
  Directory: docker/2.0
  GitCommit: ""
  Tags:
  - 2.0.5
- Architectures: null
  Directory: docker/2.0-openssl
  GitCommit: ""
  Tags:
  - 2.0.5-openssl
- Architectures: null
  Directory: docker/2.0
  GitCommit: ""
  Tags:
  - 2.0.4
- Architectures: null
  Directory: docker/2.0-openssl
  GitCommit: ""
  Tags:
  - 2.0.4-openssl
- Architectures: null
  Directory: docker/2.0
  GitCommit: ""
  Tags:
  - 2.0.3
- Architectures: null
  Directory: docker/2.0-openssl
  GitCommit: ""
  Tags:
  - 2.0.3-openssl
- Architectures: null
  Directory: docker/2.0
  GitCommit: ""
  Tags:
  - 2.0.1
- Architectures: null
  Directory: docker/2.0-openssl
  GitCommit: ""
  Tags:
  - 2.0.1-openssl
- Architectures: null
  Directory: docker/2.0
  GitCommit: ""
  Tags:
  - 2.0.0
- Architectures: null
  Directory: docker/2.0-openssl
  GitCommit: ""
  Tags:
  - 2.0.0-openssl
- Architectures: null
  Directory: docker/1.6
  GitCommit: ""
  Tags:
  - 1.6.11
- Architectures: null
  Directory: docker/1.6-openssl
  GitCommit: ""
  Tags:
  - 1.6.11-openssl
- Architectures: null
  Directory: docker/1.5
  GitCommit: ""
  Tags:
  - 1.5.9
- Architectures: null
  Directory: docker/1.6
  GitCommit: ""
  Tags:
  - 1.6.10
- Architectures: null
  Directory: docker/1.6
  GitCommit: ""
  Tags:
  - 1.6.9
- Architectures: null
  Directory: docker/1.6
  GitCommit: ""
  Tags:
  - 1.6.8
- Architectures: null
  Directory: docker/1.6
  GitCommit: ""
  Tags:
  - 1.6.7
- Architectures: null
  Directory: docker/1.6
  GitCommit: ""
  Tags:
  - 1.6.6
- Architectures: null
  Directory: docker/1.6
  GitCommit: ""
  Tags:
  - 1.6.5
- Architectures: null
  Directory: docker/1.5
  GitCommit: ""
  Tags:
  - 1.5.8
- Architectures: null
  Directory: docker/1.6
  GitCommit: ""
  Tags:
  - 1.6.4
- Architectures: null
  Directory: docker/1.6
  GitCommit: ""
  Tags:
  - 1.6.3
- Architectures: null
  Directory: docker/1.6
  GitCommit: ""
  Tags:
  - 1.6.2
- Architectures: null
  Directory: docker/1.6
  GitCommit: ""
  Tags:
  - 1.6.1
- Architectures: null
  Directory: docker/1.5
  GitCommit: ""
  Tags:
  - 1.5.6
- Architectures: null
  Directory: docker/1.5
  GitCommit: ""
  Tags:
  - 1.5.5
- Architectures: null
  Directory: docker/1.5
  GitCommit: ""
  Tags:
  - 1.5.4
- Architectures: null
  Directory: docker/1.5
  GitCommit: ""
  Tags:
  - 1.5.3
- Architectures: null
  Directory: docker/1.4.12
  GitCommit: 0bb602ed7a89da80d25e6b959a130fdcf0556be5
  Tags:
  - 1.4.12
- Architectures: null
  Directory: docker/1.4.8
  GitCommit: 25a1f7d1994fd4b8d1d25ab0275f7a8f071abfb1
  Tags:
  - 1.4.8
- Architectures: null
  Directory: docker/1.4.4
  GitCommit: 25a1f7d1994fd4b8d1d25ab0275f7a8f071abfb1
  Tags:
  - 1.4.4
- Architectures: null
  Directory: docker/1.4.10
  GitCommit: 53616be0e296f6186f52c791e241c76d53380078
  Tags:
  - 1.4.10
GitRepo: https://github.com/eclipse/mosquitto.git
KnownTags:
  1.4.4: {}
  1.4.8: {}
  1.4.10: {}
  1.4.12: {}
  "1.5": {}
  1.5.3: {}
  1.5.4: {}
  1.5.5: {}
  1.5.6: {}
  1.5.8: {}
  1.5.9: {}
  1.5.10: {}
  1.5.11: {}
  "1.6": {}
  1.6-openssl: {}
  1.6.1: {}
  1.6.2: {}
  1.6.3: {}
  1.6.4: {}
  1.6.5: {}
  1.6.6: {}
  1.6.7: {}
  1.6.8: {}
  1.6.9: {}
  1.6.10: {}
  1.6.11: {}
  1.6.11-openssl: {}
  1.6.12: {}
  1.6.12-openssl: {}
  1.6.13: {}
  1.6.13-openssl: {}
  1.6.14: {}
  1.6.14-openssl: {}
  1.6.15: {}
  1.6.15-openssl: {}
  "2": {}
  2-openssl: {}
  "2.0": {}
  2.0-openssl: {}
  2.0.0: {}
  2.0.0-openssl: {}
  2.0.1: {}
  2.0.1-openssl: {}
  2.0.3: {}
  2.0.3-openssl: {}
  2.0.4: {}
  2.0.4-openssl: {}
  2.0.5: {}
  2.0.5-openssl: {}
  2.0.6: {}
  2.0.6-openssl: {}
  2.0.7: {}
  2.0.7-openssl: {}
  2.0.8: {}
  2.0.8-openssl: {}
  2.0.9: {}
  2.0.9-openssl: {}
  2.0.10: {}
  2.0.10-openssl: {}
  2.0.11: {}
  2.0.11-openssl: {}
  2.0.12: {}
  2.0.12-openssl: {}
  2.0.13: {}
  2.0.13-openssl: {}
  2.0.14: {}
  2.0.14-openssl: {}
  2.0.15: {}
  2.0.15-openssl: {}
  latest: {}
  openssl: {}
Name: eclipse-mosquitto
