Blocks:
- Architectures: null
  Directory: docker/2.0
  GitCommit: ""
  Tags:
  - 2.0.15
  - "2.0"
  - "2"
  - latest
- Architectures: null
  Directory: docker/2.0-openssl
  GitCommit: ""
  Tags:
  - 2.0.15-openssl
  - 2.0-openssl
  - 2-openssl
  - openssl
- Architectures: null
  Directory: docker/1.6-openssl
  GitCommit: ""
  Tags:
  - 1.6.15-openssl
  - 1.6-openssl
GitRepo: https://github.com/eclipse/mosquitto.git
KnownTags:
  1.6-openssl: {}
  1.6.15-openssl: {}
  "2": {}
  2-openssl: {}
  "2.0": {}
  2.0-openssl: {}
  2.0.15: {}
  2.0.15-openssl: {}
  latest: {}
  openssl: {}
Name: eclipse-mosquitto
