Blocks:
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: 44fe135864ee751aa7dacf9923f3d7478339d700
  Tags:
  - 2.0.21
  - 2.0.21-openssl
  - "2.0"
  - 2.0-openssl
  - "2"
  - 2-openssl
  - openssl
  - latest
- Architectures: null
  Directory: docker/1.6-openssl
  File: ""
  GitCommit: 44fe135864ee751aa7dacf9923f3d7478339d700
  Tags:
  - 1.6.15-openssl
  - 1.6-openssl
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: fb9b1153924ae0e2dfb3bcb4266ee5bb49a5c515
  Tags:
  - 2.0.20
  - 2.0.20-openssl
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: e96ddfc6e58f7087b9fa57a717d7f56d2c00f9fe
  Tags:
  - 2.0.19
  - 2.0.19-openssl
- Architectures: null
  Directory: docker/2.0
  File: ""
  GitCommit: f4400fa422eacac8417efbc45dd1284526dce8d4
  Tags:
  - 2.0.18
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: f4400fa422eacac8417efbc45dd1284526dce8d4
  Tags:
  - 2.0.18-openssl
- Architectures: null
  Directory: docker/2.0
  File: ""
  GitCommit: f762a3fd1ced66b6cd32d8dc137f0523708dac1f
  Tags:
  - 2.0.17
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: f762a3fd1ced66b6cd32d8dc137f0523708dac1f
  Tags:
  - 2.0.17-openssl
- Architectures: null
  Directory: docker/2.0
  File: ""
  GitCommit: 166d1489f2c425f8b04bf1a25dd90e9724628eac
  Tags:
  - 2.0.16
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: 166d1489f2c425f8b04bf1a25dd90e9724628eac
  Tags:
  - 2.0.16-openssl
- Architectures: null
  Directory: docker/2.0
  File: ""
  GitCommit: cc1aac336ecbbc251ed4a5126257f6f4fe3ed27c
  Tags:
  - 2.0.15
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: cc1aac336ecbbc251ed4a5126257f6f4fe3ed27c
  Tags:
  - 2.0.15-openssl
- Architectures: null
  Directory: docker/1.6
  File: ""
  GitCommit: a8448a9c7b14bdaee6ec80419d43fd6544e789b6
  Tags:
  - 1.6.15
  - "1.6"
- Architectures: null
  Directory: docker/1.5
  File: ""
  GitCommit: a8448a9c7b14bdaee6ec80419d43fd6544e789b6
  Tags:
  - 1.5.11
  - "1.5"
- Architectures: null
  Directory: docker/2.0
  File: ""
  GitCommit: 8212bbe29b6fc0a49c30a15b22a36ff0ac7b9d32
  Tags:
  - 2.0.14
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: 8212bbe29b6fc0a49c30a15b22a36ff0ac7b9d32
  Tags:
  - 2.0.14-openssl
- Architectures: null
  Directory: docker/2.0
  File: ""
  GitCommit: 6e6866f0c244f88a1f210e52233c15f9accb6a1d
  Tags:
  - 2.0.13
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: 6e6866f0c244f88a1f210e52233c15f9accb6a1d
  Tags:
  - 2.0.13-openssl
- Architectures: null
  Directory: docker/2.0
  File: ""
  GitCommit: 9afeeb1a568470871511a78de6b5927010ede1f5
  Tags:
  - 2.0.12
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: 9afeeb1a568470871511a78de6b5927010ede1f5
  Tags:
  - 2.0.12-openssl
- Architectures: null
  Directory: docker/2.0
  File: ""
  GitCommit: 17bbca22fb5dc57bfdc83ac60be67e34208825fd
  Tags:
  - 2.0.11
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: 17bbca22fb5dc57bfdc83ac60be67e34208825fd
  Tags:
  - 2.0.11-openssl
- Architectures: null
  Directory: docker/2.0
  File: ""
  GitCommit: 1c79920d78321c69add9d6d6f879dd73387bc25e
  Tags:
  - 2.0.10
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: 1c79920d78321c69add9d6d6f879dd73387bc25e
  Tags:
  - 2.0.10-openssl
- Architectures: null
  Directory: docker/1.6
  File: ""
  GitCommit: 1c79920d78321c69add9d6d6f879dd73387bc25e
  Tags:
  - 1.6.14
- Architectures: null
  Directory: docker/1.6-openssl
  File: ""
  GitCommit: 1c79920d78321c69add9d6d6f879dd73387bc25e
  Tags:
  - 1.6.14-openssl
- Architectures: null
  Directory: docker/2.0
  File: ""
  GitCommit: 9f21a43eeeafdbb998409d075b986df23c18e649
  Tags:
  - 2.0.9
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: 9f21a43eeeafdbb998409d075b986df23c18e649
  Tags:
  - 2.0.9-openssl
- Architectures: null
  Directory: docker/2.0
  File: ""
  GitCommit: 5c45bc4e8407d94d29b39152b580d2b4cc8082e9
  Tags:
  - 2.0.8
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: 5c45bc4e8407d94d29b39152b580d2b4cc8082e9
  Tags:
  - 2.0.8-openssl
- Architectures: null
  Directory: docker/1.6
  File: ""
  GitCommit: 5c45bc4e8407d94d29b39152b580d2b4cc8082e9
  Tags:
  - 1.6.13
- Architectures: null
  Directory: docker/1.6-openssl
  File: ""
  GitCommit: 5c45bc4e8407d94d29b39152b580d2b4cc8082e9
  Tags:
  - 1.6.13-openssl
- Architectures: null
  Directory: docker/1.5
  File: ""
  GitCommit: 5c45bc4e8407d94d29b39152b580d2b4cc8082e9
  Tags:
  - 1.5.10
- Architectures: null
  Directory: docker/2.0
  File: ""
  GitCommit: 0736414306caa4229c5b476b616bb0491c423145
  Tags:
  - 2.0.7
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: 0736414306caa4229c5b476b616bb0491c423145
  Tags:
  - 2.0.7-openssl
- Architectures: null
  Directory: docker/2.0
  File: ""
  GitCommit: f1180dd23a32f4c6b7651abbb2646823f73ee5e4
  Tags:
  - 2.0.6
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: f1180dd23a32f4c6b7651abbb2646823f73ee5e4
  Tags:
  - 2.0.6-openssl
- Architectures: null
  Directory: docker/1.6
  File: ""
  GitCommit: f1180dd23a32f4c6b7651abbb2646823f73ee5e4
  Tags:
  - 1.6.12
- Architectures: null
  Directory: docker/1.6-openssl
  File: ""
  GitCommit: f1180dd23a32f4c6b7651abbb2646823f73ee5e4
  Tags:
  - 1.6.12-openssl
- Architectures: null
  Directory: docker/2.0
  File: ""
  GitCommit: e78c04de9bd64b622d1e18f459be933968a20a91
  Tags:
  - 2.0.5
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: e78c04de9bd64b622d1e18f459be933968a20a91
  Tags:
  - 2.0.5-openssl
- Architectures: null
  Directory: docker/2.0
  File: ""
  GitCommit: faeb9e9122c35d24bc6667a48275e37b5732f54a
  Tags:
  - 2.0.4
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: faeb9e9122c35d24bc6667a48275e37b5732f54a
  Tags:
  - 2.0.4-openssl
- Architectures: null
  Directory: docker/2.0
  File: ""
  GitCommit: 119b883e86caebe24adc22d32c0073757b259de6
  Tags:
  - 2.0.3
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: 119b883e86caebe24adc22d32c0073757b259de6
  Tags:
  - 2.0.3-openssl
- Architectures: null
  Directory: docker/2.0
  File: ""
  GitCommit: 38b930776c40505843375423f0d969f85ce860b7
  Tags:
  - 2.0.1
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: 38b930776c40505843375423f0d969f85ce860b7
  Tags:
  - 2.0.1-openssl
- Architectures: null
  Directory: docker/2.0
  File: ""
  GitCommit: 122e6ecfd3ec31084a4d25c1412b3d615c617148
  Tags:
  - 2.0.0
- Architectures: null
  Directory: docker/2.0-openssl
  File: ""
  GitCommit: 122e6ecfd3ec31084a4d25c1412b3d615c617148
  Tags:
  - 2.0.0-openssl
- Architectures: null
  Directory: docker/1.6
  File: ""
  GitCommit: 367a282c61460a1f021df086887ad195e26fc968
  Tags:
  - 1.6.11
- Architectures: null
  Directory: docker/1.6-openssl
  File: ""
  GitCommit: 367a282c61460a1f021df086887ad195e26fc968
  Tags:
  - 1.6.11-openssl
- Architectures: null
  Directory: docker/1.5
  File: ""
  GitCommit: 367a282c61460a1f021df086887ad195e26fc968
  Tags:
  - 1.5.9
- Architectures: null
  Directory: docker/1.6
  File: ""
  GitCommit: f39bf49f9059bfbf2b802fbe8ea435dab42ebf0c
  Tags:
  - 1.6.10
- Architectures: null
  Directory: docker/1.6
  File: ""
  GitCommit: 68c1e51035467ade10533c7bb88aa9765241c104
  Tags:
  - 1.6.9
- Architectures: null
  Directory: docker/1.6
  File: ""
  GitCommit: 6bfd52af9e29165bbf82e3c67b0c4f8310e92b43
  Tags:
  - 1.6.8
- Architectures: null
  Directory: docker/1.6
  File: ""
  GitCommit: eaab1799337ef33594d165b179d20b1c6305f9f3
  Tags:
  - 1.6.7
- Architectures: null
  Directory: docker/1.6
  File: ""
  GitCommit: 2e94e5999bc794afe618051176926ed67812106a
  Tags:
  - 1.6.6
- Architectures: null
  Directory: docker/1.6
  File: ""
  GitCommit: 095bbb5e441e45538e924d90483dacb51d62b927
  Tags:
  - 1.6.5
- Architectures: null
  Directory: docker/1.5
  File: ""
  GitCommit: 095bbb5e441e45538e924d90483dacb51d62b927
  Tags:
  - 1.5.8
- Architectures: null
  Directory: docker/1.6
  File: ""
  GitCommit: a5cd27a68ebb0acc828f2b490cc631acfdbd272c
  Tags:
  - 1.6.4
- Architectures: null
  Directory: docker/1.6
  File: ""
  GitCommit: a5620d9d554cb1b28799eb0491336b53265b6a24
  Tags:
  - 1.6.3
- Architectures: null
  Directory: docker/1.6
  File: ""
  GitCommit: 995f90dbafa82c7fd3d24f7174d094f11c2d6c85
  Tags:
  - 1.6.2
- Architectures: null
  Directory: docker/1.6
  File: ""
  GitCommit: d5264338008dc2459d6994e4d527d3b06cc43d7f
  Tags:
  - 1.6.1
- Architectures: null
  Directory: docker/1.5
  File: ""
  GitCommit: ff36baa49e37eb27d998314d46f01ddd914fdd65
  Tags:
  - 1.5.6
- Architectures: null
  Directory: docker/1.5
  File: ""
  GitCommit: a0a37d385db4421d7151f1fe969a7b00d4516c24
  Tags:
  - 1.5.5
- Architectures: null
  Directory: docker/1.5
  File: ""
  GitCommit: 8960b1fe29a745cd0ed14ab914833f01adaa5c24
  Tags:
  - 1.5.4
- Architectures: null
  Directory: docker/1.5
  File: ""
  GitCommit: da2879c33b6baf00b8b50a38da8d7f176cd85afa
  Tags:
  - 1.5.3
- Architectures: null
  Directory: docker/1.4.12
  File: ""
  GitCommit: 0bb602ed7a89da80d25e6b959a130fdcf0556be5
  Tags:
  - 1.4.12
- Architectures: null
  Directory: docker/1.4.8
  File: ""
  GitCommit: 25a1f7d1994fd4b8d1d25ab0275f7a8f071abfb1
  Tags:
  - 1.4.8
- Architectures: null
  Directory: docker/1.4.4
  File: ""
  GitCommit: 25a1f7d1994fd4b8d1d25ab0275f7a8f071abfb1
  Tags:
  - 1.4.4
- Architectures: null
  Directory: docker/1.4.10
  File: ""
  GitCommit: 53616be0e296f6186f52c791e241c76d53380078
  Tags:
  - 1.4.10
GitRepo: https://github.com/eclipse/mosquitto.git
KnownTags:
  1.4.4: {}
  1.4.8: {}
  1.4.10: {}
  1.4.12: {}
  "1.5": {}
  1.5.3: {}
  1.5.4: {}
  1.5.5: {}
  1.5.6: {}
  1.5.8: {}
  1.5.9: {}
  1.5.10: {}
  1.5.11: {}
  "1.6": {}
  1.6-openssl: {}
  1.6.1: {}
  1.6.2: {}
  1.6.3: {}
  1.6.4: {}
  1.6.5: {}
  1.6.6: {}
  1.6.7: {}
  1.6.8: {}
  1.6.9: {}
  1.6.10: {}
  1.6.11: {}
  1.6.11-openssl: {}
  1.6.12: {}
  1.6.12-openssl: {}
  1.6.13: {}
  1.6.13-openssl: {}
  1.6.14: {}
  1.6.14-openssl: {}
  1.6.15: {}
  1.6.15-openssl: {}
  "2": {}
  2-openssl: {}
  "2.0": {}
  2.0-openssl: {}
  2.0.0: {}
  2.0.0-openssl: {}
  2.0.1: {}
  2.0.1-openssl: {}
  2.0.3: {}
  2.0.3-openssl: {}
  2.0.4: {}
  2.0.4-openssl: {}
  2.0.5: {}
  2.0.5-openssl: {}
  2.0.6: {}
  2.0.6-openssl: {}
  2.0.7: {}
  2.0.7-openssl: {}
  2.0.8: {}
  2.0.8-openssl: {}
  2.0.9: {}
  2.0.9-openssl: {}
  2.0.10: {}
  2.0.10-openssl: {}
  2.0.11: {}
  2.0.11-openssl: {}
  2.0.12: {}
  2.0.12-openssl: {}
  2.0.13: {}
  2.0.13-openssl: {}
  2.0.14: {}
  2.0.14-openssl: {}
  2.0.15: {}
  2.0.15-openssl: {}
  2.0.16: {}
  2.0.16-openssl: {}
  2.0.17: {}
  2.0.17-openssl: {}
  2.0.18: {}
  2.0.18-openssl: {}
  2.0.19: {}
  2.0.19-openssl: {}
  2.0.20: {}
  2.0.20-openssl: {}
  2.0.21: {}
  2.0.21-openssl: {}
  latest: {}
  openssl: {}
Name: eclipse-mosquitto
