Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: pkg/docker
  GitCommit: 92ffcb89f8e145299e837438f0a0de93d73ffede
  Tags:
  - 1.30.0-go1.20
  - go1.20
  - go1
  - go
- Architectures:
  - amd64
  - arm64v8
  Directory: pkg/docker
  GitCommit: 92ffcb89f8e145299e837438f0a0de93d73ffede
  Tags:
  - 1.30.0-jsc11
  - jsc11
  - jsc
- Architectures:
  - amd64
  - arm64v8
  Directory: pkg/docker
  GitCommit: 92ffcb89f8e145299e837438f0a0de93d73ffede
  Tags:
  - 1.30.0-node18
  - node18
  - node
- Architectures:
  - amd64
  - arm64v8
  Directory: pkg/docker
  GitCommit: 92ffcb89f8e145299e837438f0a0de93d73ffede
  Tags:
  - 1.30.0-perl5.36
  - perl5.36
  - perl5
  - perl
- Architectures:
  - amd64
  - arm64v8
  Directory: pkg/docker
  GitCommit: 92ffcb89f8e145299e837438f0a0de93d73ffede
  Tags:
  - 1.30.0-php8.2
  - php8.2
  - php8
  - php
- Architectures:
  - amd64
  - arm64v8
  Directory: pkg/docker
  GitCommit: 92ffcb89f8e145299e837438f0a0de93d73ffede
  Tags:
  - 1.30.0-python3.11
  - python3.11
  - python3
  - python
- Architectures:
  - amd64
  - arm64v8
  Directory: pkg/docker
  GitCommit: 92ffcb89f8e145299e837438f0a0de93d73ffede
  Tags:
  - 1.30.0-ruby3.2
  - ruby3.2
  - ruby3
  - ruby
- Architectures:
  - amd64
  - arm64v8
  Directory: pkg/docker
  GitCommit: 92ffcb89f8e145299e837438f0a0de93d73ffede
  Tags:
  - 1.30.0-minimal
  - minimal
  - latest
- Architectures:
  - amd64
  - arm64v8
  Directory: pkg/docker
  GitCommit: b9bc222021e77bbdfb12576b3e315b962cf6b399
  Tags:
  - 1.29.1-go1.20
- Architectures:
  - amd64
  - arm64v8
  Directory: pkg/docker
  GitCommit: b9bc222021e77bbdfb12576b3e315b962cf6b399
  Tags:
  - 1.29.1-jsc11
- Architectures:
  - amd64
  - arm64v8
  Directory: pkg/docker
  GitCommit: b9bc222021e77bbdfb12576b3e315b962cf6b399
  Tags:
  - 1.29.1-node18
- Architectures:
  - amd64
  - arm64v8
  Directory: pkg/docker
  GitCommit: b9bc222021e77bbdfb12576b3e315b962cf6b399
  Tags:
  - 1.29.1-perl5.36
- Architectures:
  - amd64
  - arm64v8
  Directory: pkg/docker
  GitCommit: b9bc222021e77bbdfb12576b3e315b962cf6b399
  Tags:
  - 1.29.1-php8.2
- Architectures:
  - amd64
  - arm64v8
  Directory: pkg/docker
  GitCommit: b9bc222021e77bbdfb12576b3e315b962cf6b399
  Tags:
  - 1.29.1-python3.11
- Architectures:
  - amd64
  - arm64v8
  Directory: pkg/docker
  GitCommit: b9bc222021e77bbdfb12576b3e315b962cf6b399
  Tags:
  - 1.29.1-ruby3.2
- Architectures:
  - amd64
  - arm64v8
  Directory: pkg/docker
  GitCommit: b9bc222021e77bbdfb12576b3e315b962cf6b399
  Tags:
  - 1.29.1-minimal
GitRepo: https://github.com/nginx/unit.git
KnownTags:
  1.29.1-go1.20: {}
  1.29.1-jsc11: {}
  1.29.1-minimal: {}
  1.29.1-node18: {}
  1.29.1-perl5.36: {}
  1.29.1-php8.2: {}
  1.29.1-python3.11: {}
  1.29.1-ruby3.2: {}
  1.30.0-go1.20: {}
  1.30.0-jsc11: {}
  1.30.0-minimal: {}
  1.30.0-node18: {}
  1.30.0-perl5.36: {}
  1.30.0-php8.2: {}
  1.30.0-python3.11: {}
  1.30.0-ruby3.2: {}
  go: {}
  go1: {}
  go1.20: {}
  jsc: {}
  jsc11: {}
  latest: {}
  minimal: {}
  node: {}
  node18: {}
  perl: {}
  perl5: {}
  perl5.36: {}
  php: {}
  php8: {}
  php8.2: {}
  python: {}
  python3: {}
  python3.11: {}
  ruby: {}
  ruby3: {}
  ruby3.2: {}
Name: unit
