Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: latest/glibc
  GitCommit: ""
  Tags:
  - 1.36.1-glibc
  - 1.36-glibc
  - 1-glibc
  - stable-glibc
  - glibc
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - riscv64
  Directory: latest/uclibc
  GitCommit: ""
  Tags:
  - 1.36.1-uclibc
  - 1.36-uclibc
  - 1-uclibc
  - stable-uclibc
  - uclibc
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: latest/musl
  GitCommit: ""
  Tags:
  - 1.36.1-musl
  - 1.36-musl
  - 1-musl
  - stable-musl
  - musl
- Architectures:
  - amd64
  - arm32v5
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - riscv64
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 1.36.1
  - "1.36"
  - "1"
  - stable
  - latest
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: latest-1/glibc
  GitCommit: ""
  Tags:
  - 1.35.0-glibc
  - 1.35-glibc
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - riscv64
  Directory: latest-1/uclibc
  GitCommit: ""
  Tags:
  - 1.35.0-uclibc
  - 1.35-uclibc
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: latest-1/musl
  GitCommit: ""
  Tags:
  - 1.35.0-musl
  - 1.35-musl
- Architectures:
  - amd64
  - arm32v5
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - riscv64
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 1.35.0
  - "1.35"
GitRepo: https://github.com/docker-library/busybox.git
KnownTags:
  "1": {}
  1-glibc: {}
  1-musl: {}
  1-uclibc: {}
  "1.35": {}
  1.35-glibc: {}
  1.35-musl: {}
  1.35-uclibc: {}
  1.35.0: {}
  1.35.0-glibc: {}
  1.35.0-musl: {}
  1.35.0-uclibc: {}
  "1.36": {}
  1.36-glibc: {}
  1.36-musl: {}
  1.36-uclibc: {}
  1.36.1: {}
  1.36.1-glibc: {}
  1.36.1-musl: {}
  1.36.1-uclibc: {}
  glibc: {}
  latest: {}
  musl: {}
  stable: {}
  stable-glibc: {}
  stable-musl: {}
  stable-uclibc: {}
  uclibc: {}
Name: busybox
