Blocks:
- Architectures: null
  Directory: docker/1.4.8
  GitCommit: c6335f7f0f9a645d77d4402962a1c2691395100d
  Tags:
  - 1.4.8
  - latest
- Architectures: null
  Directory: docker/1.4.4
  GitCommit: c6335f7f0f9a645d77d4402962a1c2691395100d
  Tags:
  - 1.4.4
GitRepo: https://github.com/eclipse/mosquitto.git
KnownTags:
  1.4.4: {}
  1.4.8: {}
  latest: {}
Name: mosquitto
