Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 2ef3b5fe2539efd8dd876727376ddee2c22079b5
  Tags:
  - 1.9.2-apache
  - 1.9-apache
  - 1-apache
  - apache
  - 1.9.2
  - "1.9"
  - "1"
  - latest
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 2ef3b5fe2539efd8dd876727376ddee2c22079b5
  Tags:
  - 1.9.2-fpm
  - 1.9-fpm
  - 1-fpm
  - fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 2ef3b5fe2539efd8dd876727376ddee2c22079b5
  Tags:
  - 1.9.2-fpm-alpine
  - 1.9-fpm-alpine
  - 1-fpm-alpine
  - fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 38f550a34a4eb96419d9d3ebabe802c439103218
  Tags:
  - 1.9.1-apache
  - 1.9.1
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 38f550a34a4eb96419d9d3ebabe802c439103218
  Tags:
  - 1.9.1-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 38f550a34a4eb96419d9d3ebabe802c439103218
  Tags:
  - 1.9.1-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 194f6035a6f05671e649be6eb96d189353abcc16
  Tags:
  - 1.8.2-apache
  - 1.8-apache
  - 1.8.2
  - "1.8"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 194f6035a6f05671e649be6eb96d189353abcc16
  Tags:
  - 1.8.2-fpm
  - 1.8-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 194f6035a6f05671e649be6eb96d189353abcc16
  Tags:
  - 1.8.2-fpm-alpine
  - 1.8-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: f1756127e0b8eebad4f301d4fe6790f6d9794ce2
  Tags:
  - 1.8.1-apache
  - 1.8.1
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: f1756127e0b8eebad4f301d4fe6790f6d9794ce2
  Tags:
  - 1.8.1-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: f1756127e0b8eebad4f301d4fe6790f6d9794ce2
  Tags:
  - 1.8.1-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: fe07662938efe12d7c8c82bea32d1d34874d0665
  Tags:
  - 1.7.9-apache
  - 1.7-apache
  - 1.7.9
  - "1.7"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: fe07662938efe12d7c8c82bea32d1d34874d0665
  Tags:
  - 1.7.9-fpm
  - 1.7-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: fe07662938efe12d7c8c82bea32d1d34874d0665
  Tags:
  - 1.7.9-fpm-alpine
  - 1.7-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: apache
  GitCommit: 145cd047695c10929b498e3fb5dfc0abab49e61b
  Tags:
  - 1.7.6-apache
  - 1.7.6
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: fpm
  GitCommit: 145cd047695c10929b498e3fb5dfc0abab49e61b
  Tags:
  - 1.7.6-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: fpm-alpine
  GitCommit: 145cd047695c10929b498e3fb5dfc0abab49e61b
  Tags:
  - 1.7.6-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: apache
  GitCommit: 07bd842c0a92214c5b27f492b2f7e2f8add261a1
  Tags:
  - 1.7.5-apache
  - 1.7.5
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: fpm
  GitCommit: 07bd842c0a92214c5b27f492b2f7e2f8add261a1
  Tags:
  - 1.7.5-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: fpm-alpine
  GitCommit: 07bd842c0a92214c5b27f492b2f7e2f8add261a1
  Tags:
  - 1.7.5-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: apache
  GitCommit: 03c2472a9fefb0b0ec87cb3dfd82091b7561c5e8
  Tags:
  - 1.7.4-apache
  - 1.7.4
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: fpm
  GitCommit: 03c2472a9fefb0b0ec87cb3dfd82091b7561c5e8
  Tags:
  - 1.7.4-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: fpm-alpine
  GitCommit: 03c2472a9fefb0b0ec87cb3dfd82091b7561c5e8
  Tags:
  - 1.7.4-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: apache
  GitCommit: ce1aacd32cb0854595a5324049bb84bfdc2babf5
  Tags:
  - 1.7.3-apache
  - 1.7.3
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: fpm
  GitCommit: ce1aacd32cb0854595a5324049bb84bfdc2babf5
  Tags:
  - 1.7.3-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: fpm-alpine
  GitCommit: ce1aacd32cb0854595a5324049bb84bfdc2babf5
  Tags:
  - 1.7.3-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: 1.7.2/apache
  GitCommit: 6d66e2a1f1bebd2faee9ac97b8c1d449e6d80f99
  Tags:
  - 1.7.2-apache
  - 1.7.2
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: 1.7.2/fpm
  GitCommit: 6d66e2a1f1bebd2faee9ac97b8c1d449e6d80f99
  Tags:
  - 1.7.2-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  Directory: 1.7.2/fpm-alpine
  GitCommit: 6d66e2a1f1bebd2faee9ac97b8c1d449e6d80f99
  Tags:
  - 1.7.2-fpm-alpine
GitRepo: https://github.com/YOURLS/docker.git
KnownTags:
  "1": {}
  1-apache: {}
  1-fpm: {}
  1-fpm-alpine: {}
  "1.7": {}
  1.7-apache: {}
  1.7-fpm: {}
  1.7-fpm-alpine: {}
  1.7.2: {}
  1.7.2-apache: {}
  1.7.2-fpm: {}
  1.7.2-fpm-alpine: {}
  1.7.3: {}
  1.7.3-apache: {}
  1.7.3-fpm: {}
  1.7.3-fpm-alpine: {}
  1.7.4: {}
  1.7.4-apache: {}
  1.7.4-fpm: {}
  1.7.4-fpm-alpine: {}
  1.7.5: {}
  1.7.5-apache: {}
  1.7.5-fpm: {}
  1.7.5-fpm-alpine: {}
  1.7.6: {}
  1.7.6-apache: {}
  1.7.6-fpm: {}
  1.7.6-fpm-alpine: {}
  1.7.9: {}
  1.7.9-apache: {}
  1.7.9-fpm: {}
  1.7.9-fpm-alpine: {}
  "1.8": {}
  1.8-apache: {}
  1.8-fpm: {}
  1.8-fpm-alpine: {}
  1.8.1: {}
  1.8.1-apache: {}
  1.8.1-fpm: {}
  1.8.1-fpm-alpine: {}
  1.8.2: {}
  1.8.2-apache: {}
  1.8.2-fpm: {}
  1.8.2-fpm-alpine: {}
  "1.9": {}
  1.9-apache: {}
  1.9-fpm: {}
  1.9-fpm-alpine: {}
  1.9.1: {}
  1.9.1-apache: {}
  1.9.1-fpm: {}
  1.9.1-fpm-alpine: {}
  1.9.2: {}
  1.9.2-apache: {}
  1.9.2-fpm: {}
  1.9.2-fpm-alpine: {}
  apache: {}
  fpm: {}
  fpm-alpine: {}
  latest: {}
Name: yourls
