Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 2ef3b5fe2539efd8dd876727376ddee2c22079b5
  Tags:
  - 1.9.2-apache
  - 1.9-apache
  - 1-apache
  - apache
  - 1.9.2
  - "1.9"
  - "1"
  - latest
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 2ef3b5fe2539efd8dd876727376ddee2c22079b5
  Tags:
  - 1.9.2-fpm
  - 1.9-fpm
  - 1-fpm
  - fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 2ef3b5fe2539efd8dd876727376ddee2c22079b5
  Tags:
  - 1.9.2-fpm-alpine
  - 1.9-fpm-alpine
  - 1-fpm-alpine
  - fpm-alpine
GitRepo: https://github.com/YOURLS/docker.git
KnownTags:
  "1": {}
  1-apache: {}
  1-fpm: {}
  1-fpm-alpine: {}
  "1.9": {}
  1.9-apache: {}
  1.9-fpm: {}
  1.9-fpm-alpine: {}
  1.9.2: {}
  1.9.2-apache: {}
  1.9.2-fpm: {}
  1.9.2-fpm-alpine: {}
  apache: {}
  fpm: {}
  fpm-alpine: {}
  latest: {}
Name: yourls
