Blocks:
- Architectures:
  - amd64
  - arm64v8
  - arm32v6
  - i386
  Directory: 0.X
  GitCommit: 152f49d818b2764c437ee1fd20ee4d13791a8296
  Tags:
  - 1.13.3
  - latest
- Architectures:
  - amd64
  - arm64v8
  - arm32v6
  - i386
  Directory: 0.X
  GitCommit: 48d258c844d65814e16c123f8d3750a4e73e4350
  Tags:
  - 1.12.7
- Architectures:
  - amd64
  - arm64v8
  - arm32v6
  - i386
  Directory: 0.X
  GitCommit: e90ed0d020018291fabd520e9c36196c1e58f049
  Tags:
  - 1.11.11
GitRepo: https://github.com/hashicorp/docker-vault.git
KnownTags:
  1.11.11: {}
  1.12.7: {}
  1.13.3: {}
  latest: {}
Name: vault
