Blocks:
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: ""
  GitCommit: 0df142c37386f5be35c3355d316d7bc444825e0b
  Tags:
  - "42.3"
  - latest
  - leap
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: 2b8e47140b2a964ac827d17d4b5edd52ee22997d
  Tags:
  - tumbleweed
- Architectures:
  - amd64
  Directory: ""
  GitCommit: fd39ce9631c3b6a110b6c1e8e5756a20d0863a77
  Tags:
  - "42.2"
- Architectures: null
  Directory: ""
  GitCommit: 28ae2ecb12d4ec628bd0ca561ae5ed6b64c1eecd
  Tags:
  - "42.1"
- Architectures: null
  Directory: ""
  GitCommit: f1cf8438c9d72afa0d4022c27fd6ee3e47b70e4c
  Tags:
  - "13.2"
  - harlequin
GitRepo: https://github.com/openSUSE/docker-containers-build.git
KnownTags:
  "13.2": {}
  "42.1": {}
  "42.2": {}
  "42.3": {}
  harlequin: {}
  latest: {}
  leap: {}
  tumbleweed: {}
Name: opensuse
