Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: chronograf/1.7
  GitCommit: ""
  Tags:
  - "1.7"
  - 1.7.17
- Architectures: null
  Directory: chronograf/1.7/alpine
  GitCommit: ""
  Tags:
  - 1.7-alpine
  - 1.7.17-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: chronograf/1.8
  GitCommit: ""
  Tags:
  - "1.8"
  - 1.8.10
- Architectures: null
  Directory: chronograf/1.8/alpine
  GitCommit: ""
  Tags:
  - 1.8-alpine
  - 1.8.10-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: chronograf/1.9
  GitCommit: ""
  Tags:
  - "1.9"
  - 1.9.4
- Architectures: null
  Directory: chronograf/1.9/alpine
  GitCommit: ""
  Tags:
  - 1.9-alpine
  - 1.9.4-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: chronograf/1.10
  GitCommit: ""
  Tags:
  - "1.10"
  - 1.10.1
  - latest
- Architectures: null
  Directory: chronograf/1.10/alpine
  GitCommit: ""
  Tags:
  - 1.10-alpine
  - 1.10.1-alpine
  - alpine
GitRepo: https://github.com/influxdata/influxdata-docker
KnownTags:
  "1.7": {}
  1.7-alpine: {}
  1.7.17: {}
  1.7.17-alpine: {}
  "1.8": {}
  1.8-alpine: {}
  1.8.10: {}
  1.8.10-alpine: {}
  "1.9": {}
  1.9-alpine: {}
  1.9.4: {}
  1.9.4-alpine: {}
  "1.10": {}
  1.10-alpine: {}
  1.10.1: {}
  1.10.1-alpine: {}
  alpine: {}
  latest: {}
Name: chronograf
