Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: 2023.04/bullseye
  GitCommit: 908f33d76c1437ddfdee8596049d8a9877c03d60
  Tags:
  - latest
  - "2023.04"
- Architectures:
  - amd64
  - arm64v8
  Directory: 2023.04/alpine3.17
  GitCommit: 908f33d76c1437ddfdee8596049d8a9877c03d60
  Tags:
  - alpine
  - 2023.04-alpine
GitRepo: https://github.com/Raku/docker
KnownTags:
  "2023.04": {}
  2023.04-alpine: {}
  alpine: {}
  latest: {}
Name: rakudo-star
