Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2024.02/bookworm
  File: ""
  GitCommit: 1357b3acb550569e7ecf2da22fc32c32319fb872
  Tags:
  - latest
  - "2024.02"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2024.02/alpine3.19
  File: ""
  GitCommit: 1357b3acb550569e7ecf2da22fc32c32319fb872
  Tags:
  - alpine
  - 2024.02-alpine
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2023.08/bookworm
  File: ""
  GitCommit: 9b9e5827fb816027ae946c1d0b6ccdc9e0ee4501
  Tags:
  - "2023.08"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2023.08/alpine3.18
  File: ""
  GitCommit: 9b9e5827fb816027ae946c1d0b6ccdc9e0ee4501
  Tags:
  - 2023.08-alpine
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2023.06/bookworm
  File: ""
  GitCommit: 40594a60036aa9918d742cc942adade6edc223cd
  Tags:
  - "2023.06"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2023.06/alpine3.18
  File: ""
  GitCommit: 40594a60036aa9918d742cc942adade6edc223cd
  Tags:
  - 2023.06-alpine
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2023.04/bullseye
  File: ""
  GitCommit: 908f33d76c1437ddfdee8596049d8a9877c03d60
  Tags:
  - "2023.04"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2023.04/alpine3.17
  File: ""
  GitCommit: 908f33d76c1437ddfdee8596049d8a9877c03d60
  Tags:
  - 2023.04-alpine
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2023.02/bullseye
  File: ""
  GitCommit: d6873e88a8979536ba7d485aef309b7126965e0d
  Tags:
  - "2023.02"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2023.02/alpine3.17
  File: ""
  GitCommit: d6873e88a8979536ba7d485aef309b7126965e0d
  Tags:
  - 2023.02-alpine
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2022.12/bullseye
  File: ""
  GitCommit: 65c49addd32f616805979c6d3572f846f303a505
  Tags:
  - "2022.12"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2022.12/alpine3.17
  File: ""
  GitCommit: 65c49addd32f616805979c6d3572f846f303a505
  Tags:
  - 2022.12-alpine
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2022.07/bullseye
  File: ""
  GitCommit: 480676899ac59052927dd84dc17882f2ba8f8abc
  Tags:
  - "2022.07"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2022.07/alpine3.16
  File: ""
  GitCommit: 480676899ac59052927dd84dc17882f2ba8f8abc
  Tags:
  - 2022.07-alpine
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2021.04/buster
  File: ""
  GitCommit: 26de33ad42a6033cd105e354416c9aab3e7c91d1
  Tags:
  - "2021.04"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2021.04/alpine3.13
  File: ""
  GitCommit: 26de33ad42a6033cd105e354416c9aab3e7c91d1
  Tags:
  - 2021.04-alpine
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2020.10/buster
  File: ""
  GitCommit: 9101edf7704759d30c6fd180f3f9646109e1327d
  Tags:
  - "2020.10"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2020.10/alpine3.12
  File: ""
  GitCommit: 9101edf7704759d30c6fd180f3f9646109e1327d
  Tags:
  - 2020.10-alpine
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: d893fa621e755045c80fb4d0615c2810812d98f7
  Tags:
  - "2020.01"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: alpine
  File: ""
  GitCommit: d893fa621e755045c80fb4d0615c2810812d98f7
  Tags:
  - 2020.01-alpine
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: e26d1937190790a6b6110ba8220b98fe3bb97c04
  Tags:
  - "2019.03"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: alpine
  File: ""
  GitCommit: d2175a31e85d52cfad674814422ecf9779ea08e1
  Tags:
  - 2019.03-alpine
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: ""
  Tags:
  - "2018.10"
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: ""
  Tags:
  - "2018.06"
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: ""
  Tags:
  - "2018.04"
GitRepo: https://github.com/Raku/docker
KnownTags:
  "2018.04": {}
  "2018.06": {}
  "2018.10": {}
  "2019.03": {}
  2019.03-alpine: {}
  "2020.01": {}
  2020.01-alpine: {}
  "2020.10": {}
  2020.10-alpine: {}
  "2021.04": {}
  2021.04-alpine: {}
  "2022.07": {}
  2022.07-alpine: {}
  "2022.12": {}
  2022.12-alpine: {}
  "2023.02": {}
  2023.02-alpine: {}
  "2023.04": {}
  2023.04-alpine: {}
  "2023.06": {}
  2023.06-alpine: {}
  "2023.08": {}
  2023.08-alpine: {}
  "2024.02": {}
  2024.02-alpine: {}
  alpine: {}
  latest: {}
Name: rakudo-star
