Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: bullseye/2.4.2
  File: ""
  GitCommit: 826a4193366e7d0ff176d101679385125b8fa4f1
  Tags:
  - 2.4.2-bullseye-slim
  - 2.4-bullseye-slim
  - 2-bullseye-slim
  - bullseye-slim
  - 2.4.2
  - "2.4"
  - "2"
  - latest
- Architectures: null
  Directory: buster/2.4.1
  File: ""
  GitCommit: bfe019bd289169c95503283d73a0fc223576b0ae
  Tags:
  - 2.4.1-buster-slim
  - 2.4-buster-slim
  - 2-buster-slim
  - buster-slim
  - 2.4.1
- Architectures: null
  Directory: centos8/2.4.1
  File: ""
  GitCommit: bfe019bd289169c95503283d73a0fc223576b0ae
  Tags:
  - 2.4.1-centos
  - 2.4-centos
  - 2-centos
  - centos
- Architectures: null
  Directory: buster/2.4.0
  File: ""
  GitCommit: 444f7754822cb3e96cb2b66042d8e87d2227be0b
  Tags:
  - 2.4.0-buster-slim
  - 2.4.0
- Architectures: null
  Directory: centos8/2.4.0
  File: ""
  GitCommit: 444f7754822cb3e96cb2b66042d8e87d2227be0b
  Tags:
  - 2.4.0-centos
- Architectures: null
  Directory: bionic/2.3.7
  File: ""
  GitCommit: 6efa057f145112f259949ce5b37a3bd6384eb5c5
  Tags:
  - 2.3.7
  - "2.3"
- Architectures: null
  Directory: jessie/2.3.6
  File: ""
  GitCommit: 05946c0dbe3c7fa9338d3827428b2c32074a1447
  Tags:
  - 2.3.6
GitRepo: https://github.com/rethinkdb/rethinkdb-dockerfiles.git
KnownTags:
  "2": {}
  2-bullseye-slim: {}
  2-buster-slim: {}
  2-centos: {}
  "2.3": {}
  2.3.6: {}
  2.3.7: {}
  "2.4": {}
  2.4-bullseye-slim: {}
  2.4-buster-slim: {}
  2.4-centos: {}
  2.4.0: {}
  2.4.0-buster-slim: {}
  2.4.0-centos: {}
  2.4.1: {}
  2.4.1-buster-slim: {}
  2.4.1-centos: {}
  2.4.2: {}
  2.4.2-bullseye-slim: {}
  bullseye-slim: {}
  buster-slim: {}
  centos: {}
  latest: {}
Name: rethinkdb
