Blocks:
- Architectures:
  - amd64
  - arm64v8
  - s390x
  Directory: bullseye/2.4.2
  GitCommit: 826a4193366e7d0ff176d101679385125b8fa4f1
  Tags:
  - 2.4.2-bullseye-slim
  - 2.4-bullseye-slim
  - 2-bullseye-slim
  - bullseye-slim
  - 2.4.2
  - "2.4"
  - "2"
  - latest
- Architectures: null
  Directory: buster/2.4.1
  GitCommit: bfe019bd289169c95503283d73a0fc223576b0ae
  Tags:
  - 2.4.1-buster-slim
  - 2.4-buster-slim
  - 2-buster-slim
  - buster-slim
  - 2.4.1
- Architectures: null
  Directory: centos8/2.4.1
  GitCommit: bfe019bd289169c95503283d73a0fc223576b0ae
  Tags:
  - 2.4.1-centos
  - 2.4-centos
  - 2-centos
  - centos
- Architectures: null
  Directory: buster/2.4.0
  GitCommit: 444f7754822cb3e96cb2b66042d8e87d2227be0b
  Tags:
  - 2.4.0-buster-slim
  - 2.4.0
- Architectures: null
  Directory: centos8/2.4.0
  GitCommit: 444f7754822cb3e96cb2b66042d8e87d2227be0b
  Tags:
  - 2.4.0-centos
- Architectures: null
  Directory: bionic/2.3.7
  GitCommit: ""
  Tags:
  - 2.3.7
  - "2.3"
- Architectures: null
  Directory: jessie/2.3.6
  GitCommit: ""
  Tags:
  - 2.3.6
GitRepo: https://github.com/rethinkdb/rethinkdb-dockerfiles.git
KnownTags:
  "2": {}
  2-bullseye-slim: {}
  2-buster-slim: {}
  2-centos: {}
  "2.3": {}
  2.3.6: {}
  2.3.7: {}
  "2.4": {}
  2.4-bullseye-slim: {}
  2.4-buster-slim: {}
  2.4-centos: {}
  2.4.0: {}
  2.4.0-buster-slim: {}
  2.4.0-centos: {}
  2.4.1: {}
  2.4.1-buster-slim: {}
  2.4.1-centos: {}
  2.4.2: {}
  2.4.2-bullseye-slim: {}
  bullseye-slim: {}
  buster-slim: {}
  centos: {}
  latest: {}
Name: rethinkdb
