Blocks:
- Architectures:
  - amd64
  - arm64v8
  - s390x
  Directory: bullseye/2.4.2
  GitCommit: 826a4193366e7d0ff176d101679385125b8fa4f1
  Tags:
  - 2.4.2-bullseye-slim
  - 2.4-bullseye-slim
  - 2-bullseye-slim
  - bullseye-slim
  - 2.4.2
  - "2.4"
  - "2"
  - latest
GitRepo: https://github.com/rethinkdb/rethinkdb-dockerfiles.git
KnownTags:
  "2": {}
  2-bullseye-slim: {}
  "2.4": {}
  2.4-bullseye-slim: {}
  2.4.2: {}
  2.4.2-bullseye-slim: {}
  bullseye-slim: {}
  latest: {}
Name: rethinkdb
