Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: ""
  GitCommit: 6ffc2b92062bc0ea906a68aee9a82a8dc8e8fbc9
  Tags:
  - "5.0"
  - 5.0-20230619
  - latest
- Architectures:
  - amd64
  - arm64v8
  Directory: ""
  GitCommit: bfcc62e8b793dbd0713264dd9502ebe390038fae
  Tags:
  - "4.0"
  - 4.0-20230610
- Architectures:
  - amd64
  - arm64v8
  Directory: ""
  GitCommit: aec9891fe13fac3dcc8f1393c8256396078dc88e
  Tags:
  - "3.0"
  - 3.0-20230617
GitRepo: https://github.com/vmware/photon-docker-image.git
KnownTags:
  "3.0": {}
  3.0-20230617: {}
  "4.0": {}
  4.0-20230610: {}
  "5.0": {}
  5.0-20230619: {}
  latest: {}
Name: photon
