Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: "8"
  GitCommit: 0404371923419eeb901956b8cb4fcc308da088b2
  Tags:
  - 8.8.1
- Architectures:
  - amd64
  - arm64v8
  Directory: "7"
  GitCommit: e95712a301d6adacde7ef3d31d54dd9bca752426
  Tags:
  - 7.17.10
GitRepo: https://github.com/docker-library/elasticsearch.git
KnownTags:
  7.17.10: {}
  8.8.1: {}
Name: elasticsearch
