Blocks:
- Architectures: null
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.6.2
  - "0.6"
  - "0"
  - latest
GitRepo: https://github.com/tianon/docker-brew-cirros.git
KnownTags:
  "0": {}
  "0.6": {}
  0.6.2: {}
  latest: {}
Name: cirros
