Blocks:
- Architectures: null
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.6.2
  - "0.6"
  - "0"
  - latest
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  Directory: ""
  GitCommit: ddf8fe17964242f32980c92879414cf74f8cbbff
  Tags:
  - 0.6.1
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  Directory: ""
  GitCommit: 9e8006aaa29017ce2ee85e5373772f39f1f10ac9
  Tags:
  - 0.6.0
- Architectures:
  - amd64
  - arm32v5
  - arm64v8
  - i386
  - ppc64le
  Directory: ""
  GitCommit: 36e8b0fd2c270f14631d1767f668a4db83890efb
  Tags:
  - 0.5.3
  - "0.5"
- Architectures: null
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.5.2
- Architectures: null
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.5.1
- Architectures: null
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.5.0
- Architectures: null
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.4.0
  - "0.4"
GitRepo: https://github.com/tianon/docker-brew-cirros.git
KnownTags:
  "0": {}
  "0.4": {}
  0.4.0: {}
  "0.5": {}
  0.5.0: {}
  0.5.1: {}
  0.5.2: {}
  0.5.3: {}
  "0.6": {}
  0.6.0: {}
  0.6.1: {}
  0.6.2: {}
  latest: {}
Name: cirros
