Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: ""
  Tags:
  - 0.6.2
  - "0.6"
  - "0"
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: arches/amd64
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: arches/arm32v7
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: arches/arm64v8
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: arches/ppc64le
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: ddf8fe17964242f32980c92879414cf74f8cbbff
  Tags:
  - 0.6.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: arches/amd64
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: arches/arm32v7
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: arches/arm64v8
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: arches/ppc64le
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 9e8006aaa29017ce2ee85e5373772f39f1f10ac9
  Tags:
  - 0.6.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: arches/amd64
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v5:
      Architecture: arm32v5
      Directory: arches/arm32v5
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: arches/arm64v8
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: arches/i386
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: arches/ppc64le
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 36e8b0fd2c270f14631d1767f668a4db83890efb
  Tags:
  - 0.5.3
  - "0.5"
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: ""
  Tags:
  - 0.5.2
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: ""
  Tags:
  - 0.5.1
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: ""
  Tags:
  - 0.5.0
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: ""
  Tags:
  - 0.4.0
  - "0.4"
GitRepo: https://github.com/tianon/docker-brew-cirros.git
KnownTags:
  "0": {}
  "0.4": {}
  0.4.0: {}
  "0.5": {}
  0.5.0: {}
  0.5.1: {}
  0.5.2: {}
  0.5.3: {}
  "0.6": {}
  0.6.0: {}
  0.6.1: {}
  0.6.2: {}
  latest: {}
Name: cirros
