Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - riscv64
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - linux
- Architectures:
  - windows-amd64
  Directory: ""
  GitCommit: ""
  Tags:
  - nanoserver-ltsc2022
- Architectures:
  - windows-amd64
  Directory: ""
  GitCommit: ""
  Tags:
  - nanoserver-1809
- Architectures:
  - windows-amd64
  Directory: ""
  GitCommit: ""
  Tags:
  - nanoserver-1803
- Architectures:
  - windows-amd64
  Directory: ""
  GitCommit: ""
  Tags:
  - nanoserver-sac2016
- Architectures:
  - windows-amd64
  Directory: ""
  GitCommit: ""
  Tags:
  - nanoserver-1709
- Architectures:
  - windows-amd64
  Directory: ""
  GitCommit: ""
  Tags:
  - nanoserver
- Architectures:
  - windows-amd64
  Directory: ""
  GitCommit: ""
  Tags:
  - nanoserver1709
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - latest
GitRepo: https://github.com/docker-library/hello-world.git
KnownTags:
  latest: {}
  linux: {}
  nanoserver: {}
  nanoserver-1709: {}
  nanoserver-1803: {}
  nanoserver-1809: {}
  nanoserver-ltsc2022: {}
  nanoserver-sac2016: {}
  nanoserver1709: {}
Name: hello-world
