Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - riscv64
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - linux
- Architectures:
  - windows-amd64
  Directory: ""
  GitCommit: ""
  Tags:
  - nanoserver-ltsc2022
- Architectures:
  - windows-amd64
  Directory: ""
  GitCommit: ""
  Tags:
  - nanoserver-1809
GitRepo: https://github.com/docker-library/hello-world.git
KnownTags:
  linux: {}
  nanoserver-1809: {}
  nanoserver-ltsc2022: {}
Name: hello-world
