Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: amd64/hello-world
      File: ""
      GitCommit: 3fb6ebca4163bf5b9cc496ac3e8f11cb1e754aee
      GitFetch: ""
    arm32v5:
      Architecture: arm32v5
      Directory: arm32v5/hello-world
      File: ""
      GitCommit: 3fb6ebca4163bf5b9cc496ac3e8f11cb1e754aee
      GitFetch: ""
    arm32v6:
      Architecture: arm32v6
      Directory: arm32v6/hello-world
      File: ""
      GitCommit: 61f3ba26fe1d027b5b443c04ac2b0690fd97561a
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: arm32v7/hello-world
      File: ""
      GitCommit: 3fb6ebca4163bf5b9cc496ac3e8f11cb1e754aee
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: arm64v8/hello-world
      File: ""
      GitCommit: 3fb6ebca4163bf5b9cc496ac3e8f11cb1e754aee
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i386/hello-world
      File: ""
      GitCommit: 3fb6ebca4163bf5b9cc496ac3e8f11cb1e754aee
      GitFetch: ""
    mips64le:
      Architecture: mips64le
      Directory: mips64le/hello-world
      File: ""
      GitCommit: 3fb6ebca4163bf5b9cc496ac3e8f11cb1e754aee
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ppc64le/hello-world
      File: ""
      GitCommit: 3fb6ebca4163bf5b9cc496ac3e8f11cb1e754aee
      GitFetch: ""
    riscv64:
      Architecture: riscv64
      Directory: riscv64/hello-world
      File: ""
      GitCommit: 3fb6ebca4163bf5b9cc496ac3e8f11cb1e754aee
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: s390x/hello-world
      File: ""
      GitCommit: 3fb6ebca4163bf5b9cc496ac3e8f11cb1e754aee
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: c6676f682a833388a087758d8789b43fbe003397
  Tags:
  - linux
  - latest
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: c6676f682a833388a087758d8789b43fbe003397
  Tags:
  - nanoserver-ltsc2022
  - nanoserver
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: c6676f682a833388a087758d8789b43fbe003397
  Tags:
  - nanoserver-1809
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 88475d7d4cfb43feda2b74a5bfdaf5ff8f964fb1
  Tags:
  - nanoserver-1803
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 9c93e37114a7fe99b5fc0d776e0b8dff99cbbb75
  Tags:
  - nanoserver-sac2016
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 9c93e37114a7fe99b5fc0d776e0b8dff99cbbb75
  Tags:
  - nanoserver-1709
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: b9c8214f529b04e37683fddba4a4244308f046e8
  Tags:
  - nanoserver1709
GitRepo: https://github.com/docker-library/hello-world.git
KnownTags:
  latest: {}
  linux: {}
  nanoserver: {}
  nanoserver-1709: {}
  nanoserver-1803: {}
  nanoserver-1809: {}
  nanoserver-ltsc2022: {}
  nanoserver-sac2016: {}
  nanoserver1709: {}
Name: hello-world
