Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: amd64/hello-world
      File: ""
      GitCommit: 6930d60e10e81283a57be3ee3a2b5ca328a40304
      GitFetch: ""
    arm32v5:
      Architecture: arm32v5
      Directory: arm32v5/hello-world
      File: ""
      GitCommit: 6930d60e10e81283a57be3ee3a2b5ca328a40304
      GitFetch: ""
    arm32v6:
      Architecture: arm32v6
      Directory: arm32v6/hello-world
      File: ""
      GitCommit: 6930d60e10e81283a57be3ee3a2b5ca328a40304
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: arm32v7/hello-world
      File: ""
      GitCommit: 6930d60e10e81283a57be3ee3a2b5ca328a40304
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: arm64v8/hello-world
      File: ""
      GitCommit: 6930d60e10e81283a57be3ee3a2b5ca328a40304
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i386/hello-world
      File: ""
      GitCommit: 6930d60e10e81283a57be3ee3a2b5ca328a40304
      GitFetch: ""
    mips64le:
      Architecture: mips64le
      Directory: mips64le/hello-world
      File: ""
      GitCommit: 6930d60e10e81283a57be3ee3a2b5ca328a40304
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ppc64le/hello-world
      File: ""
      GitCommit: 6930d60e10e81283a57be3ee3a2b5ca328a40304
      GitFetch: ""
    riscv64:
      Architecture: riscv64
      Directory: riscv64/hello-world
      File: ""
      GitCommit: 6930d60e10e81283a57be3ee3a2b5ca328a40304
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: s390x/hello-world
      File: ""
      GitCommit: 6930d60e10e81283a57be3ee3a2b5ca328a40304
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: d2ad81cd7a88c0114e152da6a3849aba64a68610
  Tags:
  - linux
  - latest
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: d2ad81cd7a88c0114e152da6a3849aba64a68610
  Tags:
  - nanoserver-ltsc2025
  - nanoserver
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: d2ad81cd7a88c0114e152da6a3849aba64a68610
  Tags:
  - nanoserver-ltsc2022
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 08987c71f648c985f54be2a80bed4223cbd0723b
  Tags:
  - nanoserver-1809
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 88475d7d4cfb43feda2b74a5bfdaf5ff8f964fb1
  Tags:
  - nanoserver-1803
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 9c93e37114a7fe99b5fc0d776e0b8dff99cbbb75
  Tags:
  - nanoserver-sac2016
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 9c93e37114a7fe99b5fc0d776e0b8dff99cbbb75
  Tags:
  - nanoserver-1709
- Architectures:
    windows:
      Architecture: windows
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    windows-amd64:
      Architecture: windows-amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: b9c8214f529b04e37683fddba4a4244308f046e8
  Tags:
  - nanoserver1709
GitRepo: https://github.com/docker-library/hello-world.git
KnownTags:
  latest: {}
  linux: {}
  nanoserver: {}
  nanoserver-1709: {}
  nanoserver-1803: {}
  nanoserver-1809: {}
  nanoserver-ltsc2022: {}
  nanoserver-ltsc2025: {}
  nanoserver-sac2016: {}
  nanoserver1709: {}
Name: hello-world
