Blocks:
- Architectures: null
  Directory: ""
  GitCommit: 8c107a2ed9ee79927da495f556a81a6999221bab
  Tags:
  - latest
  - base
  - base-20230611.0.157136
- Architectures: null
  Directory: ""
  GitCommit: 8c107a2ed9ee79927da495f556a81a6999221bab
  Tags:
  - base-devel
  - base-devel-20230611.0.157136
GitRepo: https://gitlab.archlinux.org/archlinux/archlinux-docker.git
KnownTags:
  base: {}
  base-20230611.0.157136: {}
  base-devel: {}
  base-devel-20230611.0.157136: {}
  latest: {}
Name: archlinux
