Blocks:
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: 3.3.2
  GitCommit: ""
  Tags:
  - latest
  - 3.3.2
  - "3.3"
  - "3"
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: 3.2.3
  GitCommit: ""
  Tags:
  - 3.2.3
  - "3.2"
- Architectures:
  - amd64
  - arm64v8
  Directory: 3.1.2
  GitCommit: ""
  Tags:
  - 3.1.2
  - "3.1"
- Architectures:
  - amd64
  - arm64v8
  Directory: 2.3.1
  GitCommit: ""
  Tags:
  - 2.3.1
  - "2.3"
  - "2"
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: 3.3.1
  GitCommit: ""
  Tags:
  - 3.3.1
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: 3.2.2
  GitCommit: ""
  Tags:
  - 3.2.2
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: 3.3.0
  GitCommit: ""
  Tags:
  - 3.3.0
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: 3.2.1
  GitCommit: ""
  Tags:
  - 3.2.1
- Architectures:
  - amd64
  - arm64v8
  Directory: 3.2.0
  GitCommit: ""
  Tags:
  - 3.2.0
- Architectures:
  - amd64
  - arm64v8
  Directory: 3.1.1
  GitCommit: ""
  Tags:
  - 3.1.1
- Architectures:
  - amd64
  - arm64v8
  Directory: 3.0.1
  GitCommit: ""
  Tags:
  - 3.0.1
  - "3.0"
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: 3.1.0
  GitCommit: ""
  Tags:
  - 3.1.0
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: 3.0.0
  GitCommit: ""
  Tags:
  - 3.0.0
- Architectures:
  - amd64
  Directory: 2.3.0
  GitCommit: ""
  Tags:
  - 2.3.0
- Architectures:
  - amd64
  Directory: 2.2.0
  GitCommit: ""
  Tags:
  - 2.2.0
  - "2.2"
- Architectures:
  - amd64
  Directory: 2.1.2
  GitCommit: ""
  Tags:
  - 2.1.2
  - "2.1"
- Architectures:
  - amd64
  Directory: 1.7.2
  GitCommit: ""
  Tags:
  - 1.7.2
  - "1.7"
  - "1"
- Architectures:
  - amd64
  Directory: 1.7.2-couchperuser
  GitCommit: ""
  Tags:
  - 1.7.2-couchperuser
  - 1.7-couchperuser
  - 1-couchperuser
GitRepo: https://github.com/apache/couchdb-docker
KnownTags:
  "1": {}
  1-couchperuser: {}
  "1.7": {}
  1.7-couchperuser: {}
  1.7.2: {}
  1.7.2-couchperuser: {}
  "2": {}
  "2.1": {}
  2.1.2: {}
  "2.2": {}
  2.2.0: {}
  "2.3": {}
  2.3.0: {}
  2.3.1: {}
  "3": {}
  "3.0": {}
  3.0.0: {}
  3.0.1: {}
  "3.1": {}
  3.1.0: {}
  3.1.1: {}
  3.1.2: {}
  "3.2": {}
  3.2.0: {}
  3.2.1: {}
  3.2.2: {}
  3.2.3: {}
  "3.3": {}
  3.3.0: {}
  3.3.1: {}
  3.3.2: {}
  latest: {}
Name: couchdb
