Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.4.3
  File: ""
  GitCommit: 8a7dfc18fe8a9ba55a1c544ee3416f945dbb94ad
  Tags:
  - latest
  - 3.4.3
  - "3.4"
  - "3"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.4.3-nouveau
  File: ""
  GitCommit: 8a7dfc18fe8a9ba55a1c544ee3416f945dbb94ad
  Tags:
  - 3.4.3-nouveau
  - 3.4-nouveau
  - 3-nouveau
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.3.3
  File: ""
  GitCommit: 8a7dfc18fe8a9ba55a1c544ee3416f945dbb94ad
  Tags:
  - 3.3.3
  - "3.3"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.4.2
  File: ""
  GitCommit: 734c61f2a9421637ff58be225665477be52dd4b7
  Tags:
  - 3.4.2
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.4.2-nouveau
  File: ""
  GitCommit: 734c61f2a9421637ff58be225665477be52dd4b7
  Tags:
  - 3.4.2-nouveau
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.4.1
  File: ""
  GitCommit: e748fc4a483c1a651758df4900258701570d2533
  Tags:
  - 3.4.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.4.1-nouveau
  File: ""
  GitCommit: e748fc4a483c1a651758df4900258701570d2533
  Tags:
  - 3.4.1-nouveau
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.2.3
  File: ""
  GitCommit: 58910ed097489dc588b2a87592406f8faa1bdadf
  Tags:
  - 3.2.3
  - "3.2"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.1.2
  File: ""
  GitCommit: 58910ed097489dc588b2a87592406f8faa1bdadf
  Tags:
  - 3.1.2
  - "3.1"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2.3.1
  File: ""
  GitCommit: 58910ed097489dc588b2a87592406f8faa1bdadf
  Tags:
  - 2.3.1
  - "2.3"
  - "2"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.3.2
  File: ""
  GitCommit: b616800e739db18c19e6a8b4131528157f945bcd
  Tags:
  - 3.3.2
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.3.1
  File: ""
  GitCommit: a29d12f0dd4d73f1dcefb07212af4b9ba3185d9e
  Tags:
  - 3.3.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.2.2
  File: ""
  GitCommit: a29d12f0dd4d73f1dcefb07212af4b9ba3185d9e
  Tags:
  - 3.2.2
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.3.0
  File: ""
  GitCommit: f39f58d2870d9116f1176780f838e9e2ca8f96b6
  Tags:
  - 3.3.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.2.1
  File: ""
  GitCommit: 4dc3a6b1f2bd8d46489cad5828912f0a64bf0b36
  Tags:
  - 3.2.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.2.0
  File: ""
  GitCommit: c2dc5a84add2d673bce151e0aa8174d09d227d22
  Tags:
  - 3.2.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.1.1
  File: ""
  GitCommit: 4993111e388d203d2200a3dd88449517db548c05
  Tags:
  - 3.1.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.0.1
  File: ""
  GitCommit: e3ca492e13f65ffd72593ac3d7c43c737787e2b2
  Tags:
  - 3.0.1
  - "3.0"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.1.0
  File: ""
  GitCommit: 01e1c16bb405c1174393c76a7ebc3792b0c5e2c9
  Tags:
  - 3.1.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.0.0
  File: ""
  GitCommit: f56c425bb7d64918a57936376e0070e7742768cd
  Tags:
  - 3.0.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2.3.0
  File: ""
  GitCommit: 3bcc626d30623789b4750d076f059bcd010c2a04
  Tags:
  - 2.3.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2.2.0
  File: ""
  GitCommit: f429c1ccf22fe8cf7717383462fbf2f56e6d0301
  Tags:
  - 2.2.0
  - "2.2"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2.1.2
  File: ""
  GitCommit: ca9b039d036d1482fd1e5ce67176f05cf959beed
  Tags:
  - 2.1.2
  - "2.1"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1.7.2
  File: ""
  GitCommit: ca9b039d036d1482fd1e5ce67176f05cf959beed
  Tags:
  - 1.7.2
  - "1.7"
  - "1"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 1.7.2-couchperuser
  File: ""
  GitCommit: ca9b039d036d1482fd1e5ce67176f05cf959beed
  Tags:
  - 1.7.2-couchperuser
  - 1.7-couchperuser
  - 1-couchperuser
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.4.1-nouveau
  File: ""
  GitCommit: f68db4cb1bdc671ddff413d9ccf2113a55b430f2
  Tags:
  - latest-nouveau
GitRepo: https://github.com/apache/couchdb-docker
KnownTags:
  "1": {}
  1-couchperuser: {}
  "1.7": {}
  1.7-couchperuser: {}
  1.7.2: {}
  1.7.2-couchperuser: {}
  "2": {}
  "2.1": {}
  2.1.2: {}
  "2.2": {}
  2.2.0: {}
  "2.3": {}
  2.3.0: {}
  2.3.1: {}
  "3": {}
  3-nouveau: {}
  "3.0": {}
  3.0.0: {}
  3.0.1: {}
  "3.1": {}
  3.1.0: {}
  3.1.1: {}
  3.1.2: {}
  "3.2": {}
  3.2.0: {}
  3.2.1: {}
  3.2.2: {}
  3.2.3: {}
  "3.3": {}
  3.3.0: {}
  3.3.1: {}
  3.3.2: {}
  3.3.3: {}
  "3.4": {}
  3.4-nouveau: {}
  3.4.1: {}
  3.4.1-nouveau: {}
  3.4.2: {}
  3.4.2-nouveau: {}
  3.4.3: {}
  3.4.3-nouveau: {}
  latest: {}
  latest-nouveau: {}
Name: couchdb
