Blocks:
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: 3.3.2
  GitCommit: ""
  Tags:
  - latest
  - 3.3.2
  - "3.3"
  - "3"
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: 3.2.3
  GitCommit: ""
  Tags:
  - 3.2.3
  - "3.2"
- Architectures:
  - amd64
  - arm64v8
  Directory: 3.1.2
  GitCommit: ""
  Tags:
  - 3.1.2
  - "3.1"
- Architectures:
  - amd64
  - arm64v8
  Directory: 2.3.1
  GitCommit: ""
  Tags:
  - 2.3.1
  - "2.3"
  - "2"
GitRepo: https://github.com/apache/couchdb-docker
KnownTags:
  "2": {}
  "2.3": {}
  2.3.1: {}
  "3": {}
  "3.1": {}
  3.1.2: {}
  "3.2": {}
  3.2.3: {}
  "3.3": {}
  3.3.2: {}
  latest: {}
Name: couchdb
