Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  Directory: jdk8
  GitCommit: 01f24d7f28637c911d3c2f0650b52d08f526b57f
  Tags:
  - 8.1.1-jdk8
  - 8.1-jdk8
  - 8-jdk8
  - jdk8
  - 8.1.1-jdk8-jammy
  - 8.1-jdk8-jammy
  - 8-jdk8-jammy
  - jdk8-jammy
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  Directory: jdk8-focal
  GitCommit: 01f24d7f28637c911d3c2f0650b52d08f526b57f
  Tags:
  - 8.1.1-jdk8-focal
  - 8.1-jdk8-focal
  - 8-jdk8-focal
  - jdk8-focal
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: jdk11
  GitCommit: 01f24d7f28637c911d3c2f0650b52d08f526b57f
  Tags:
  - 8.1.1-jdk11
  - 8.1-jdk11
  - 8-jdk11
  - jdk11
  - 8.1.1-jdk11-jammy
  - 8.1-jdk11-jammy
  - 8-jdk11-jammy
  - jdk11-jammy
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: jdk11-focal
  GitCommit: 01f24d7f28637c911d3c2f0650b52d08f526b57f
  Tags:
  - 8.1.1-jdk11-focal
  - 8.1-jdk11-focal
  - 8-jdk11-focal
  - jdk11-focal
- Architectures:
  - amd64
  Directory: jdk11-alpine
  GitCommit: 01f24d7f28637c911d3c2f0650b52d08f526b57f
  Tags:
  - 8.1.1-jdk11-alpine
  - 8.1-jdk11-alpine
  - 8-jdk11-alpine
  - jdk11-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: jdk17
  GitCommit: 01f24d7f28637c911d3c2f0650b52d08f526b57f
  Tags:
  - 8.1.1-jdk17
  - 8.1-jdk17
  - 8-jdk17
  - jdk17
  - 8.1.1-jdk
  - 8.1-jdk
  - 8-jdk
  - jdk
  - 8.1.1
  - "8.1"
  - "8"
  - latest
  - 8.1.1-jdk17-jammy
  - 8.1-jdk17-jammy
  - 8-jdk17-jammy
  - jdk17-jammy
  - 8.1.1-jdk-jammy
  - 8.1-jdk-jammy
  - 8-jdk-jammy
  - jdk-jammy
  - 8.1.1-jammy
  - 8.1-jammy
  - 8-jammy
  - jammy
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: jdk17-focal
  GitCommit: 01f24d7f28637c911d3c2f0650b52d08f526b57f
  Tags:
  - 8.1.1-jdk17-focal
  - 8.1-jdk17-focal
  - 8-jdk17-focal
  - jdk17-focal
  - 8.1.1-jdk-focal
  - 8.1-jdk-focal
  - 8-jdk-focal
  - jdk-focal
  - 8.1.1-focal
  - 8.1-focal
  - 8-focal
  - focal
- Architectures:
  - amd64
  Directory: jdk17-alpine
  GitCommit: 01f24d7f28637c911d3c2f0650b52d08f526b57f
  Tags:
  - 8.1.1-jdk17-alpine
  - 8.1-jdk17-alpine
  - 8-jdk17-alpine
  - jdk17-alpine
  - 8.1.1-jdk-alpine
  - 8.1-jdk-alpine
  - 8-jdk-alpine
  - jdk-alpine
  - 8.1.1-alpine
  - 8.1-alpine
  - 8-alpine
  - alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  Directory: jdk8
  GitCommit: d67e322404924034e73ade97552ff7b1ffd6bbca
  Tags:
  - 7.6.1-jdk8
  - 7.6-jdk8
  - 7-jdk8
  - 7.6.1-jdk8-jammy
  - 7.6-jdk8-jammy
  - 7-jdk8-jammy
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  Directory: jdk8-focal
  GitCommit: d67e322404924034e73ade97552ff7b1ffd6bbca
  Tags:
  - 7.6.1-jdk8-focal
  - 7.6-jdk8-focal
  - 7-jdk8-focal
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: jdk11
  GitCommit: d67e322404924034e73ade97552ff7b1ffd6bbca
  Tags:
  - 7.6.1-jdk11
  - 7.6-jdk11
  - 7-jdk11
  - 7.6.1-jdk11-jammy
  - 7.6-jdk11-jammy
  - 7-jdk11-jammy
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: jdk11-focal
  GitCommit: d67e322404924034e73ade97552ff7b1ffd6bbca
  Tags:
  - 7.6.1-jdk11-focal
  - 7.6-jdk11-focal
  - 7-jdk11-focal
- Architectures:
  - amd64
  Directory: jdk11-alpine
  GitCommit: d67e322404924034e73ade97552ff7b1ffd6bbca
  Tags:
  - 7.6.1-jdk11-alpine
  - 7.6-jdk11-alpine
  - 7-jdk11-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: jdk17
  GitCommit: d67e322404924034e73ade97552ff7b1ffd6bbca
  Tags:
  - 7.6.1-jdk17
  - 7.6-jdk17
  - 7-jdk17
  - 7.6.1-jdk
  - 7.6-jdk
  - 7-jdk
  - 7.6.1
  - "7.6"
  - "7"
  - 7.6.1-jdk17-jammy
  - 7.6-jdk17-jammy
  - 7-jdk17-jammy
  - 7.6.1-jdk-jammy
  - 7.6-jdk-jammy
  - 7-jdk-jammy
  - 7.6.1-jammy
  - 7.6-jammy
  - 7-jammy
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: jdk17-focal
  GitCommit: d67e322404924034e73ade97552ff7b1ffd6bbca
  Tags:
  - 7.6.1-jdk17-focal
  - 7.6-jdk17-focal
  - 7-jdk17-focal
  - 7.6.1-jdk-focal
  - 7.6-jdk-focal
  - 7-jdk-focal
  - 7.6.1-focal
  - 7.6-focal
  - 7-focal
- Architectures:
  - amd64
  Directory: jdk17-alpine
  GitCommit: d67e322404924034e73ade97552ff7b1ffd6bbca
  Tags:
  - 7.6.1-jdk17-alpine
  - 7.6-jdk17-alpine
  - 7-jdk17-alpine
  - 7.6.1-jdk-alpine
  - 7.6-jdk-alpine
  - 7-jdk-alpine
  - 7.6.1-alpine
  - 7.6-alpine
  - 7-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  Directory: jdk8
  GitCommit: 71d126ec98c6eda90e1818a575486e461adef750
  Tags:
  - 6.9.4-jdk8
  - 6.9-jdk8
  - 6-jdk8
  - 6.9.4-jdk8-jammy
  - 6.9-jdk8-jammy
  - 6-jdk8-jammy
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  Directory: jdk8-focal
  GitCommit: 71d126ec98c6eda90e1818a575486e461adef750
  Tags:
  - 6.9.4-jdk8-focal
  - 6.9-jdk8-focal
  - 6-jdk8-focal
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: jdk11
  GitCommit: 71d126ec98c6eda90e1818a575486e461adef750
  Tags:
  - 6.9.4-jdk11
  - 6.9-jdk11
  - 6-jdk11
  - 6.9.4-jdk11-jammy
  - 6.9-jdk11-jammy
  - 6-jdk11-jammy
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: jdk11-focal
  GitCommit: 71d126ec98c6eda90e1818a575486e461adef750
  Tags:
  - 6.9.4-jdk11-focal
  - 6.9-jdk11-focal
  - 6-jdk11-focal
- Architectures:
  - amd64
  Directory: jdk11-alpine
  GitCommit: 71d126ec98c6eda90e1818a575486e461adef750
  Tags:
  - 6.9.4-jdk11-alpine
  - 6.9-jdk11-alpine
  - 6-jdk11-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: jdk17
  GitCommit: 71d126ec98c6eda90e1818a575486e461adef750
  Tags:
  - 6.9.4-jdk17
  - 6.9-jdk17
  - 6-jdk17
  - 6.9.4-jdk
  - 6.9-jdk
  - 6-jdk
  - 6.9.4
  - "6.9"
  - "6"
  - 6.9.4-jdk17-jammy
  - 6.9-jdk17-jammy
  - 6-jdk17-jammy
  - 6.9.4-jdk-jammy
  - 6.9-jdk-jammy
  - 6-jdk-jammy
  - 6.9.4-jammy
  - 6.9-jammy
  - 6-jammy
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: jdk17-focal
  GitCommit: 71d126ec98c6eda90e1818a575486e461adef750
  Tags:
  - 6.9.4-jdk17-focal
  - 6.9-jdk17-focal
  - 6-jdk17-focal
  - 6.9.4-jdk-focal
  - 6.9-jdk-focal
  - 6-jdk-focal
  - 6.9.4-focal
  - 6.9-focal
  - 6-focal
- Architectures:
  - amd64
  Directory: jdk17-alpine
  GitCommit: 71d126ec98c6eda90e1818a575486e461adef750
  Tags:
  - 6.9.4-jdk17-alpine
  - 6.9-jdk17-alpine
  - 6-jdk17-alpine
  - 6.9.4-jdk-alpine
  - 6.9-jdk-alpine
  - 6-jdk-alpine
  - 6.9.4-alpine
  - 6.9-alpine
  - 6-alpine
GitRepo: https://github.com/keeganwitt/docker-gradle.git
KnownTags:
  "6": {}
  6-alpine: {}
  6-focal: {}
  6-jammy: {}
  6-jdk: {}
  6-jdk-alpine: {}
  6-jdk-focal: {}
  6-jdk-jammy: {}
  6-jdk8: {}
  6-jdk8-focal: {}
  6-jdk8-jammy: {}
  6-jdk11: {}
  6-jdk11-alpine: {}
  6-jdk11-focal: {}
  6-jdk11-jammy: {}
  6-jdk17: {}
  6-jdk17-alpine: {}
  6-jdk17-focal: {}
  6-jdk17-jammy: {}
  "6.9": {}
  6.9-alpine: {}
  6.9-focal: {}
  6.9-jammy: {}
  6.9-jdk: {}
  6.9-jdk-alpine: {}
  6.9-jdk-focal: {}
  6.9-jdk-jammy: {}
  6.9-jdk8: {}
  6.9-jdk8-focal: {}
  6.9-jdk8-jammy: {}
  6.9-jdk11: {}
  6.9-jdk11-alpine: {}
  6.9-jdk11-focal: {}
  6.9-jdk11-jammy: {}
  6.9-jdk17: {}
  6.9-jdk17-alpine: {}
  6.9-jdk17-focal: {}
  6.9-jdk17-jammy: {}
  6.9.4: {}
  6.9.4-alpine: {}
  6.9.4-focal: {}
  6.9.4-jammy: {}
  6.9.4-jdk: {}
  6.9.4-jdk-alpine: {}
  6.9.4-jdk-focal: {}
  6.9.4-jdk-jammy: {}
  6.9.4-jdk8: {}
  6.9.4-jdk8-focal: {}
  6.9.4-jdk8-jammy: {}
  6.9.4-jdk11: {}
  6.9.4-jdk11-alpine: {}
  6.9.4-jdk11-focal: {}
  6.9.4-jdk11-jammy: {}
  6.9.4-jdk17: {}
  6.9.4-jdk17-alpine: {}
  6.9.4-jdk17-focal: {}
  6.9.4-jdk17-jammy: {}
  "7": {}
  7-alpine: {}
  7-focal: {}
  7-jammy: {}
  7-jdk: {}
  7-jdk-alpine: {}
  7-jdk-focal: {}
  7-jdk-jammy: {}
  7-jdk8: {}
  7-jdk8-focal: {}
  7-jdk8-jammy: {}
  7-jdk11: {}
  7-jdk11-alpine: {}
  7-jdk11-focal: {}
  7-jdk11-jammy: {}
  7-jdk17: {}
  7-jdk17-alpine: {}
  7-jdk17-focal: {}
  7-jdk17-jammy: {}
  "7.6": {}
  7.6-alpine: {}
  7.6-focal: {}
  7.6-jammy: {}
  7.6-jdk: {}
  7.6-jdk-alpine: {}
  7.6-jdk-focal: {}
  7.6-jdk-jammy: {}
  7.6-jdk8: {}
  7.6-jdk8-focal: {}
  7.6-jdk8-jammy: {}
  7.6-jdk11: {}
  7.6-jdk11-alpine: {}
  7.6-jdk11-focal: {}
  7.6-jdk11-jammy: {}
  7.6-jdk17: {}
  7.6-jdk17-alpine: {}
  7.6-jdk17-focal: {}
  7.6-jdk17-jammy: {}
  7.6.1: {}
  7.6.1-alpine: {}
  7.6.1-focal: {}
  7.6.1-jammy: {}
  7.6.1-jdk: {}
  7.6.1-jdk-alpine: {}
  7.6.1-jdk-focal: {}
  7.6.1-jdk-jammy: {}
  7.6.1-jdk8: {}
  7.6.1-jdk8-focal: {}
  7.6.1-jdk8-jammy: {}
  7.6.1-jdk11: {}
  7.6.1-jdk11-alpine: {}
  7.6.1-jdk11-focal: {}
  7.6.1-jdk11-jammy: {}
  7.6.1-jdk17: {}
  7.6.1-jdk17-alpine: {}
  7.6.1-jdk17-focal: {}
  7.6.1-jdk17-jammy: {}
  "8": {}
  8-alpine: {}
  8-focal: {}
  8-jammy: {}
  8-jdk: {}
  8-jdk-alpine: {}
  8-jdk-focal: {}
  8-jdk-jammy: {}
  8-jdk8: {}
  8-jdk8-focal: {}
  8-jdk8-jammy: {}
  8-jdk11: {}
  8-jdk11-alpine: {}
  8-jdk11-focal: {}
  8-jdk11-jammy: {}
  8-jdk17: {}
  8-jdk17-alpine: {}
  8-jdk17-focal: {}
  8-jdk17-jammy: {}
  "8.1": {}
  8.1-alpine: {}
  8.1-focal: {}
  8.1-jammy: {}
  8.1-jdk: {}
  8.1-jdk-alpine: {}
  8.1-jdk-focal: {}
  8.1-jdk-jammy: {}
  8.1-jdk8: {}
  8.1-jdk8-focal: {}
  8.1-jdk8-jammy: {}
  8.1-jdk11: {}
  8.1-jdk11-alpine: {}
  8.1-jdk11-focal: {}
  8.1-jdk11-jammy: {}
  8.1-jdk17: {}
  8.1-jdk17-alpine: {}
  8.1-jdk17-focal: {}
  8.1-jdk17-jammy: {}
  8.1.1: {}
  8.1.1-alpine: {}
  8.1.1-focal: {}
  8.1.1-jammy: {}
  8.1.1-jdk: {}
  8.1.1-jdk-alpine: {}
  8.1.1-jdk-focal: {}
  8.1.1-jdk-jammy: {}
  8.1.1-jdk8: {}
  8.1.1-jdk8-focal: {}
  8.1.1-jdk8-jammy: {}
  8.1.1-jdk11: {}
  8.1.1-jdk11-alpine: {}
  8.1.1-jdk11-focal: {}
  8.1.1-jdk11-jammy: {}
  8.1.1-jdk17: {}
  8.1.1-jdk17-alpine: {}
  8.1.1-jdk17-focal: {}
  8.1.1-jdk17-jammy: {}
  alpine: {}
  focal: {}
  jammy: {}
  jdk: {}
  jdk-alpine: {}
  jdk-focal: {}
  jdk-jammy: {}
  jdk8: {}
  jdk8-focal: {}
  jdk8-jammy: {}
  jdk11: {}
  jdk11-alpine: {}
  jdk11-focal: {}
  jdk11-jammy: {}
  jdk17: {}
  jdk17-alpine: {}
  jdk17-focal: {}
  jdk17-jammy: {}
  latest: {}
Name: gradle
