Blocks:
- Architectures:
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - riscv64
  - s390x
  - i386
  - amd64
  Directory: ""
  GitCommit: c025403b1536857f35630b3c7fe5aabf8b6d256a
  Tags:
  - "20230329"
  - edge
- Architectures:
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  - i386
  - amd64
  Directory: ""
  GitCommit: 66fa0fe063bbb4f03220088a4f4d8bb34db1b803
  Tags:
  - 3.18.2
  - "3.18"
  - "3"
  - latest
- Architectures:
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  - i386
  - amd64
  Directory: ""
  GitCommit: e229397d4700b27c523f966afbddc420674f0d34
  Tags:
  - 3.17.4
  - "3.17"
- Architectures:
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  - i386
  - amd64
  Directory: ""
  GitCommit: 9d643ac53dd82876d3f700dfb8e4edf91982f171
  Tags:
  - 3.16.6
  - "3.16"
- Architectures:
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  - i386
  - amd64
  Directory: ""
  GitCommit: 87b711179ac0b3685f8c590428bcc6470a8fd78b
  Tags:
  - 3.15.9
  - "3.15"
GitRepo: https://github.com/alpinelinux/docker-alpine.git
KnownTags:
  "3": {}
  "3.15": {}
  3.15.9: {}
  "3.16": {}
  3.16.6: {}
  "3.17": {}
  3.17.4: {}
  "3.18": {}
  3.18.2: {}
  "20230329": {}
  edge: {}
  latest: {}
Name: alpine
