Blocks:
- Architectures: null
  Directory: "0.9"
  GitCommit: d322572f7dd6ea468a14a4d832fbec26f152c71e
  Tags:
  - "0.9"
  - 0.9.3
- Architectures: null
  Directory: "0.10"
  GitCommit: e1f81dfe3e8fac5588e12d2b880166d1743dbecd
  Tags:
  - "0.10"
  - 0.10.0
- Architectures: null
  Directory: "0.11"
  GitCommit: 00e197d889426695446baec4e034b5ddbb15bcb3
  Tags:
  - "0.11"
  - 0.11.0
- Architectures: null
  Directory: "0.12"
  GitCommit: d7e73876549d205898b1922bcbf69e74ef11c288
  Tags:
  - "0.12"
  - 0.12.0
  - latest
GitRepo: git://github.com/ahawkins/docker-thrift
KnownTags:
  "0.9": {}
  0.9.3: {}
  "0.10": {}
  0.10.0: {}
  "0.11": {}
  0.11.0: {}
  "0.12": {}
  0.12.0: {}
  latest: {}
Name: thrift
