Blocks:
- Architectures: null
  Directory: "3.4"
  GitCommit: d7f1d0e61cffe81d6ca9797c63fc25eba7e277db
  Tags:
  - 1.10.4-python3
  - 1.10-python3
  - 1-python3
  - python3
  - 1.10.4
  - "1.10"
  - "1"
  - latest
- Architectures: null
  Directory: 3.4/onbuild
  GitCommit: 4fe080675e4a85ef6ee25c811e9d3d3ef0905794
  Tags:
  - python3-onbuild
  - onbuild
- Architectures: null
  Directory: "2.7"
  GitCommit: d7f1d0e61cffe81d6ca9797c63fc25eba7e277db
  Tags:
  - 1.10.4-python2
  - 1.10-python2
  - 1-python2
  - python2
- Architectures: null
  Directory: 2.7/onbuild
  GitCommit: cecbb2bbbcb69d1b8358398eaf8d9638e3bdd447
  Tags:
  - python2-onbuild
- Architectures: null
  Directory: "3.4"
  GitCommit: 642cc5e4ccdc2f706d445b072ebc6c4193e22c10
  Tags:
  - 1.10.3-python3
  - 1.10.3
- Architectures: null
  Directory: "2.7"
  GitCommit: 642cc5e4ccdc2f706d445b072ebc6c4193e22c10
  Tags:
  - 1.10.3-python2
- Architectures: null
  Directory: "3.4"
  GitCommit: 55ed1a6140b7152aa96a230ddb4d5a1f45fa6e52
  Tags:
  - 1.10.2-python3
  - 1.10.2
- Architectures: null
  Directory: "2.7"
  GitCommit: 55ed1a6140b7152aa96a230ddb4d5a1f45fa6e52
  Tags:
  - 1.10.2-python2
- Architectures: null
  Directory: "3.4"
  GitCommit: 16723cfa3765534e4e9eebe4f70c5404eb2b4532
  Tags:
  - 1.10.1-python3
  - 1.10.1
- Architectures: null
  Directory: "2.7"
  GitCommit: 16723cfa3765534e4e9eebe4f70c5404eb2b4532
  Tags:
  - 1.10.1-python2
- Architectures: null
  Directory: "3.4"
  GitCommit: f610710985af4757e51695fee47f33de47b0293c
  Tags:
  - 1.9.8-python3
  - 1.9-python3
  - 1.9.8
  - "1.9"
- Architectures: null
  Directory: "2.7"
  GitCommit: f610710985af4757e51695fee47f33de47b0293c
  Tags:
  - 1.9.8-python2
  - 1.9-python2
- Architectures: null
  Directory: "3.4"
  GitCommit: 819c332058c3638ab8f4fa5b9f70518e9aaf6325
  Tags:
  - 1.9.7-python3
  - 1.9.7
- Architectures: null
  Directory: "2.7"
  GitCommit: 819c332058c3638ab8f4fa5b9f70518e9aaf6325
  Tags:
  - 1.9.7-python2
GitRepo: https://github.com/docker-library/django.git
KnownTags:
  "1": {}
  1-python2: {}
  1-python3: {}
  "1.9": {}
  1.9-python2: {}
  1.9-python3: {}
  1.9.7: {}
  1.9.7-python2: {}
  1.9.7-python3: {}
  1.9.8: {}
  1.9.8-python2: {}
  1.9.8-python3: {}
  "1.10": {}
  1.10-python2: {}
  1.10-python3: {}
  1.10.1: {}
  1.10.1-python2: {}
  1.10.1-python3: {}
  1.10.2: {}
  1.10.2-python2: {}
  1.10.2-python3: {}
  1.10.3: {}
  1.10.3-python2: {}
  1.10.3-python3: {}
  1.10.4: {}
  1.10.4-python2: {}
  1.10.4-python3: {}
  latest: {}
  onbuild: {}
  python2: {}
  python2-onbuild: {}
  python3: {}
  python3-onbuild: {}
Name: django
