Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: stable/bullseye
  GitCommit: ""
  Tags:
  - 3.0.5-sdk
  - 3.0-sdk
  - 3-sdk
  - stable-sdk
  - sdk
  - 3.0.5
  - "3.0"
  - "3"
  - stable
  - latest
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: beta/bullseye
  GitCommit: ""
  Tags:
  - 3.1.0-163.1.beta-sdk
  - beta-sdk
  - 3.1.0-163.1.beta
  - beta
GitRepo: https://github.com/dart-lang/dart-docker.git
KnownTags:
  "3": {}
  3-sdk: {}
  "3.0": {}
  3.0-sdk: {}
  3.0.5: {}
  3.0.5-sdk: {}
  3.1.0-163.1.beta: {}
  3.1.0-163.1.beta-sdk: {}
  beta: {}
  beta-sdk: {}
  latest: {}
  sdk: {}
  stable: {}
  stable-sdk: {}
Name: dart
