Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: "8"
  GitCommit: babe715a9ea3c4024d56d1bdffdc5feaed901df6
  Tags:
  - 8.8.1
- Architectures:
  - amd64
  - arm64v8
  Directory: "7"
  GitCommit: 6dc8cf4590a7259135398fe84648b76fdb79ac2e
  Tags:
  - 7.17.10
GitRepo: https://github.com/docker-library/kibana.git
KnownTags:
  7.17.10: {}
  8.8.1: {}
Name: kibana
