Blocks:
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: dockerfiles/official/11
  GitCommit: c2a79726eae76118b0b204bb201920ce200d0703
  Tags:
  - "11"
  - 11.0.19
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: dockerfiles/official/17
  GitCommit: b5e632a4b8a28d1618215983fa95859979c63280
  Tags:
  - "17"
  - 17.0.7
  - lts
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: dockerfiles/official/20
  GitCommit: 2f4f203530b69b9e7b120c1f1e0d8e8baafa40f2
  Tags:
  - "20"
  - 20.0.1
  - latest
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: dockerfiles/official/11
  GitCommit: 1d9a8aa21f4cb661656e617b0133b7d154c3992b
  Tags:
  - 11.0.18
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: dockerfiles/official/17
  GitCommit: 8d5fd07f2e40428a2027de2abf78ac9be0e3bc9d
  Tags:
  - 17.0.6
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: dockerfiles/official/19
  GitCommit: c515da6c71d27d6bbf8fca4c0e782a50e9f8319c
  Tags:
  - "19"
  - 19.0.2
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: dockerfiles/official/17
  GitCommit: fb4f1fe1d5cb453891a95bfdec43c0196a09e324
  Tags:
  - 17.0.5
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: dockerfiles/official/11
  GitCommit: 936dab0baa76e5db609e4c0dffc632dc4f42eca8
  Tags:
  - 11.0.17
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  Directory: dockerfiles/official/19
  GitCommit: e2320c79758f23b60d17726185c9ede2a5622f54
  Tags:
  - 19.0.1
- Architectures:
  - amd64
  Directory: dockerfiles/official/11
  GitCommit: 17162c754beee7214df6e681f47b472a5c9797d4
  Tags:
  - 11.0.16.1
- Architectures:
  - amd64
  Directory: dockerfiles/official/17
  GitCommit: 8d6f6161c31efc6e62377a5f839236a91b60802b
  Tags:
  - 17.0.4.1
- Architectures:
  - amd64
  Directory: dockerfiles/official/18
  GitCommit: b20731a5af730e7e329f65259640f83f40ce6044
  Tags:
  - "18"
  - 18.0.2.1
- Architectures:
  - amd64
  Directory: dockerfiles/official/11
  GitCommit: 5314a0515530a90f6333ce4f0028cb46c34ff5fc
  Tags:
  - 11.0.16
- Architectures:
  - amd64
  Directory: dockerfiles/official/17
  GitCommit: 9dba89fee0089f4a9bf3ebd16b56a49d9df38e75
  Tags:
  - 17.0.4
- Architectures:
  - amd64
  Directory: dockerfiles/official/18
  GitCommit: 544a77605c07bc4913710a73a29761051c04b87b
  Tags:
  - 18.0.2
- Architectures:
  - amd64
  Directory: dockerfiles/official/11
  GitCommit: d028c06a13e42a57f3e4c94e8465f52cfa1856c3
  Tags:
  - 11.0.15.0.1
- Architectures:
  - amd64
  Directory: dockerfiles/official/17
  GitCommit: 7845161fe8ba5aad389c2630014eff9db086c375
  Tags:
  - 17.0.3.0.1
- Architectures:
  - amd64
  Directory: dockerfiles/official/18
  GitCommit: c247ad2575c2c012261361b668d11ab262bb0ae8
  Tags:
  - 18.0.1.1
- Architectures:
  - amd64
  Directory: dockerfiles/official/18
  GitCommit: b234e5091408dff3eb8002b878d00e708e443dfa
  Tags:
  - 18.0.1
- Architectures:
  - amd64
  Directory: dockerfiles/official/11
  GitCommit: aacecdf1eace8f2c8ac15da2a6ebb22ba05b2c35
  Tags:
  - 11.0.15
- Architectures:
  - amd64
  Directory: dockerfiles/official/17
  GitCommit: 9c31cb08e574355fc56dcfa2563dd646e5e4e1be
  Tags:
  - 17.0.3
- Architectures:
  - amd64
  Directory: dockerfiles/official/11
  GitCommit: dc86b1da3824d9cd56abc1aa6e1283636be33432
  Tags:
  - 11.0.14.1
- Architectures:
  - amd64
  Directory: dockerfiles/official/17
  GitCommit: 8c7b8fa87fff57615c3a9b7bee48eb272fe2c621
  Tags:
  - 17.0.2
- Architectures:
  - amd64
  Directory: dockerfiles/official/11
  GitCommit: 971778f645a5c8ac177faec0cae899edc3e92d10
  Tags:
  - 11.0.14
- Architectures:
  - amd64
  Directory: dockerfiles/official/11
  GitCommit: aa479cf28c5fb001f882ee1deb73a34ca07b6e2f
  Tags:
  - 11.0.13
- Architectures:
  - amd64
  Directory: dockerfiles/official/17
  GitCommit: 3dc4a11fc80fafb0b51c5c5e6efdf91a891c553c
  Tags:
  - 17.0.1
- Architectures:
  - amd64
  Directory: dockerfiles/official/11
  GitCommit: 60fd8df23db6501bc6c508f8c87d07e94d36f043
  Tags:
  - 11.0.12
- Architectures:
  - amd64
  Directory: dockerfiles/official/stable
  GitCommit: aecea5c02c476f8a30a96e12da9c6b27ac6f2c48
  Tags:
  - "16"
  - 16.0.2
- Architectures:
  - amd64
  Directory: dockerfiles/official/stable
  GitCommit: 0449b4147caed3eb6fcf46ef3301d12af13e819a
  Tags:
  - 16.0.1
- Architectures:
  - amd64
  Directory: dockerfiles/official/lts
  GitCommit: ee2eebb7494ba8ba3a18e43be50aac47913c310a
  Tags:
  - 11.0.11
- Architectures:
  - amd64
  Directory: dockerfiles/official/lts
  GitCommit: 9166199c6294bf8d82b5d6f9f7135eefa7cc8cd3
  Tags:
  - 11.0.10
- Architectures:
  - amd64
  Directory: dockerfiles/official/stable
  GitCommit: e4191a268cf29841379db71bf49573d15d6170a3
  Tags:
  - "15"
  - 15.0.2
- Architectures:
  - amd64
  Directory: dockerfiles/official/stable
  GitCommit: 836b0941086b06678b2323d056ac957cd8d0b10a
  Tags:
  - 15.0.1
- Architectures:
  - amd64
  Directory: dockerfiles/official/lts
  GitCommit: 26f260d947d20aa72799c1035f0c74285f6e0dee
  Tags:
  - 11.0.9.1
- Architectures:
  - amd64
  Directory: dockerfiles/official/lts
  GitCommit: 40a062e0108c0c238f03a510c7eda91f3f970713
  Tags:
  - 11.0.9
- Architectures:
  - amd64
  Directory: dockerfiles/official/lts
  GitCommit: cd2ca5e0de3ca0b167aba34661f1b8f37210f66a
  Tags:
  - 11.0.8
- Architectures:
  - amd64
  Directory: dockerfiles/official/stable
  GitCommit: a7de58e1065752db7737baeb95ea02796eef43f1
  Tags:
  - "14"
  - 14.0.2
- Architectures:
  - amd64
  Directory: dockerfiles/official/lts
  GitCommit: 3d2d199e3c53a0de726491827ef0587c3c9b4f20
  Tags:
  - 11.0.7
- Architectures:
  - amd64
  Directory: dockerfiles/official/stable
  GitCommit: dddf6cf714e932b34e25d69f8cdb9c2381851199
  Tags:
  - 14.0.1
- Architectures:
  - amd64
  Directory: dockerfiles/official/lts
  GitCommit: 569e25607d9a64dba5dc52d4b67c25b5c7a6e5a5
  Tags:
  - 11.0.6.0.1
- Architectures:
  - amd64
  Directory: dockerfiles/official/lts
  GitCommit: 2c8a65f330ca09a10aea3581626218fd748f9401
  Tags:
  - 11.0.6
- Architectures:
  - amd64
  Directory: dockerfiles/official/stable
  GitCommit: c1f267171fbf6dc4520b7e14e4e5c421ddfffb81
  Tags:
  - "13"
  - 13.0.2
- Architectures:
  - amd64
  Directory: dockerfiles/official/lts
  GitCommit: 1c93a00d33e446e1feff9ea40eaa320e1093e309
  Tags:
  - 11.0.5
- Architectures:
  - amd64
  Directory: dockerfiles/official/stable
  GitCommit: 9c0699a4b6a48335a9929cce5895dc6e6871b73d
  Tags:
  - 13.0.1
- Architectures:
  - amd64
  Directory: dockerfiles/official/lts
  GitCommit: 7346e49a86c5d8a44f6bf71f43b17e832b2d14e6
  Tags:
  - 11.0.4
- Architectures:
  - amd64
  Directory: dockerfiles/official/stable
  GitCommit: d58f6c1977d616bcd8669d09687acd86199bb219
  Tags:
  - "12"
  - 12.0.2
- Architectures:
  - amd64
  Directory: dockerfiles/official/stable
  GitCommit: 89924265b4359478b58a29207f0dfe7323b18784
  Tags:
  - 12.0.1
- Architectures:
  - amd64
  Directory: dockerfiles/official/lts
  GitCommit: 89924265b4359478b58a29207f0dfe7323b18784
  Tags:
  - 11.0.3
GitRepo: https://github.com/SAP/SapMachine-infrastructure.git
KnownTags:
  "11": {}
  11.0.3: {}
  11.0.4: {}
  11.0.5: {}
  11.0.6: {}
  11.0.6.0.1: {}
  11.0.7: {}
  11.0.8: {}
  11.0.9: {}
  11.0.9.1: {}
  11.0.10: {}
  11.0.11: {}
  11.0.12: {}
  11.0.13: {}
  11.0.14: {}
  11.0.14.1: {}
  11.0.15: {}
  11.0.15.0.1: {}
  11.0.16: {}
  11.0.16.1: {}
  11.0.17: {}
  11.0.18: {}
  11.0.19: {}
  "12": {}
  12.0.1: {}
  12.0.2: {}
  "13": {}
  13.0.1: {}
  13.0.2: {}
  "14": {}
  14.0.1: {}
  14.0.2: {}
  "15": {}
  15.0.1: {}
  15.0.2: {}
  "16": {}
  16.0.1: {}
  16.0.2: {}
  "17": {}
  17.0.1: {}
  17.0.2: {}
  17.0.3: {}
  17.0.3.0.1: {}
  17.0.4: {}
  17.0.4.1: {}
  17.0.5: {}
  17.0.6: {}
  17.0.7: {}
  "18": {}
  18.0.1: {}
  18.0.1.1: {}
  18.0.2: {}
  18.0.2.1: {}
  "19": {}
  19.0.1: {}
  19.0.2: {}
  "20": {}
  20.0.1: {}
  latest: {}
  lts: {}
Name: sapmachine
