Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.11-bookworm
  - 0.26-python3.11-bookworm
  - 0-python3.11-bookworm
  - python3.11-bookworm
  - 0.26.0-bookworm
  - 0.26-bookworm
  - 0-bookworm
  - bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.11-bullseye
  - 0.26-python3.11-bullseye
  - 0-python3.11-bullseye
  - python3.11-bullseye
  - 0.26.0-bullseye
  - 0.26-bullseye
  - 0-bullseye
  - bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.11-alpine3.18
  - 0.26-python3.11-alpine3.18
  - 0-python3.11-alpine3.18
  - python3.11-alpine3.18
  - 0.26.0-alpine3.18
  - 0.26-alpine3.18
  - 0-alpine3.18
  - alpine3.18
  - 0.26.0-python3.11-alpine
  - 0.26-python3.11-alpine
  - 0-python3.11-alpine
  - python3.11-alpine
  - 0.26.0-alpine
  - 0.26-alpine
  - 0-alpine
  - alpine
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.11-alpine3.17
  - 0.26-python3.11-alpine3.17
  - 0-python3.11-alpine3.17
  - python3.11-alpine3.17
  - 0.26.0-alpine3.17
  - 0.26-alpine3.17
  - 0-alpine3.17
  - alpine3.17
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.10-bookworm
  - 0.26-python3.10-bookworm
  - 0-python3.10-bookworm
  - python3.10-bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.10-bullseye
  - 0.26-python3.10-bullseye
  - 0-python3.10-bullseye
  - python3.10-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.10-alpine3.18
  - 0.26-python3.10-alpine3.18
  - 0-python3.10-alpine3.18
  - python3.10-alpine3.18
  - 0.26.0-python3.10-alpine
  - 0.26-python3.10-alpine
  - 0-python3.10-alpine
  - python3.10-alpine
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.10-alpine3.17
  - 0.26-python3.10-alpine3.17
  - 0-python3.10-alpine3.17
  - python3.10-alpine3.17
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.9-bookworm
  - 0.26-python3.9-bookworm
  - 0-python3.9-bookworm
  - python3.9-bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.9-bullseye
  - 0.26-python3.9-bullseye
  - 0-python3.9-bullseye
  - python3.9-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.9-alpine3.18
  - 0.26-python3.9-alpine3.18
  - 0-python3.9-alpine3.18
  - python3.9-alpine3.18
  - 0.26.0-python3.9-alpine
  - 0.26-python3.9-alpine
  - 0-python3.9-alpine
  - python3.9-alpine
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.9-alpine3.17
  - 0.26-python3.9-alpine3.17
  - 0-python3.9-alpine3.17
  - python3.9-alpine3.17
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.8-bookworm
  - 0.26-python3.8-bookworm
  - 0-python3.8-bookworm
  - python3.8-bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.8-bullseye
  - 0.26-python3.8-bullseye
  - 0-python3.8-bullseye
  - python3.8-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.8-alpine3.18
  - 0.26-python3.8-alpine3.18
  - 0-python3.8-alpine3.18
  - python3.8-alpine3.18
  - 0.26.0-python3.8-alpine
  - 0.26-python3.8-alpine
  - 0-python3.8-alpine
  - python3.8-alpine
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.8-alpine3.17
  - 0.26-python3.8-alpine3.17
  - 0-python3.8-alpine3.17
  - python3.8-alpine3.17
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.7-bookworm
  - 0.26-python3.7-bookworm
  - 0-python3.7-bookworm
  - python3.7-bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.7-bullseye
  - 0.26-python3.7-bullseye
  - 0-python3.7-bullseye
  - python3.7-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.7-alpine3.18
  - 0.26-python3.7-alpine3.18
  - 0-python3.7-alpine3.18
  - python3.7-alpine3.18
  - 0.26.0-python3.7-alpine
  - 0.26-python3.7-alpine
  - 0-python3.7-alpine
  - python3.7-alpine
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-python3.7-alpine3.17
  - 0.26-python3.7-alpine3.17
  - 0-python3.7-alpine3.17
  - python3.7-alpine3.17
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-pypy3.9-bookworm
  - 0.26-pypy3.9-bookworm
  - 0-pypy3.9-bookworm
  - pypy3.9-bookworm
  - 0.26.0-pypy-bookworm
  - 0.26-pypy-bookworm
  - 0-pypy-bookworm
  - pypy-bookworm
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-pypy3.9-bullseye
  - 0.26-pypy3.9-bullseye
  - 0-pypy3.9-bullseye
  - pypy3.9-bullseye
  - 0.26.0-pypy-bullseye
  - 0.26-pypy-bullseye
  - 0-pypy-bullseye
  - pypy-bullseye
- Architectures:
  - windows-amd64
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-pypy3.9-windowsservercore-ltsc2022
  - 0.26-pypy3.9-windowsservercore-ltsc2022
  - 0-pypy3.9-windowsservercore-ltsc2022
  - pypy3.9-windowsservercore-ltsc2022
  - 0.26.0-pypy-windowsservercore-ltsc2022
  - 0.26-pypy-windowsservercore-ltsc2022
  - 0-pypy-windowsservercore-ltsc2022
  - pypy-windowsservercore-ltsc2022
- Architectures:
  - windows-amd64
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-pypy3.9-windowsservercore-1809
  - 0.26-pypy3.9-windowsservercore-1809
  - 0-pypy3.9-windowsservercore-1809
  - pypy3.9-windowsservercore-1809
  - 0.26.0-pypy-windowsservercore-1809
  - 0.26-pypy-windowsservercore-1809
  - 0-pypy-windowsservercore-1809
  - pypy-windowsservercore-1809
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-pypy3.8-bookworm
  - 0.26-pypy3.8-bookworm
  - 0-pypy3.8-bookworm
  - pypy3.8-bookworm
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-pypy3.8-bullseye
  - 0.26-pypy3.8-bullseye
  - 0-pypy3.8-bullseye
  - pypy3.8-bullseye
- Architectures:
  - windows-amd64
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-pypy3.8-windowsservercore-ltsc2022
  - 0.26-pypy3.8-windowsservercore-ltsc2022
  - 0-pypy3.8-windowsservercore-ltsc2022
  - pypy3.8-windowsservercore-ltsc2022
- Architectures:
  - windows-amd64
  Directory: ""
  GitCommit: ""
  Tags:
  - 0.26.0-pypy3.8-windowsservercore-1809
  - 0.26-pypy3.8-windowsservercore-1809
  - 0-pypy3.8-windowsservercore-1809
  - pypy3.8-windowsservercore-1809
GitRepo: https://github.com/hylang/docker-hylang.git
KnownTags:
  0-alpine: {}
  0-alpine3.17: {}
  0-alpine3.18: {}
  0-bookworm: {}
  0-bullseye: {}
  0-pypy-bookworm: {}
  0-pypy-bullseye: {}
  0-pypy-windowsservercore-1809: {}
  0-pypy-windowsservercore-ltsc2022: {}
  0-pypy3.8-bookworm: {}
  0-pypy3.8-bullseye: {}
  0-pypy3.8-windowsservercore-1809: {}
  0-pypy3.8-windowsservercore-ltsc2022: {}
  0-pypy3.9-bookworm: {}
  0-pypy3.9-bullseye: {}
  0-pypy3.9-windowsservercore-1809: {}
  0-pypy3.9-windowsservercore-ltsc2022: {}
  0-python3.7-alpine: {}
  0-python3.7-alpine3.17: {}
  0-python3.7-alpine3.18: {}
  0-python3.7-bookworm: {}
  0-python3.7-bullseye: {}
  0-python3.8-alpine: {}
  0-python3.8-alpine3.17: {}
  0-python3.8-alpine3.18: {}
  0-python3.8-bookworm: {}
  0-python3.8-bullseye: {}
  0-python3.9-alpine: {}
  0-python3.9-alpine3.17: {}
  0-python3.9-alpine3.18: {}
  0-python3.9-bookworm: {}
  0-python3.9-bullseye: {}
  0-python3.10-alpine: {}
  0-python3.10-alpine3.17: {}
  0-python3.10-alpine3.18: {}
  0-python3.10-bookworm: {}
  0-python3.10-bullseye: {}
  0-python3.11-alpine: {}
  0-python3.11-alpine3.17: {}
  0-python3.11-alpine3.18: {}
  0-python3.11-bookworm: {}
  0-python3.11-bullseye: {}
  0.26-alpine: {}
  0.26-alpine3.17: {}
  0.26-alpine3.18: {}
  0.26-bookworm: {}
  0.26-bullseye: {}
  0.26-pypy-bookworm: {}
  0.26-pypy-bullseye: {}
  0.26-pypy-windowsservercore-1809: {}
  0.26-pypy-windowsservercore-ltsc2022: {}
  0.26-pypy3.8-bookworm: {}
  0.26-pypy3.8-bullseye: {}
  0.26-pypy3.8-windowsservercore-1809: {}
  0.26-pypy3.8-windowsservercore-ltsc2022: {}
  0.26-pypy3.9-bookworm: {}
  0.26-pypy3.9-bullseye: {}
  0.26-pypy3.9-windowsservercore-1809: {}
  0.26-pypy3.9-windowsservercore-ltsc2022: {}
  0.26-python3.7-alpine: {}
  0.26-python3.7-alpine3.17: {}
  0.26-python3.7-alpine3.18: {}
  0.26-python3.7-bookworm: {}
  0.26-python3.7-bullseye: {}
  0.26-python3.8-alpine: {}
  0.26-python3.8-alpine3.17: {}
  0.26-python3.8-alpine3.18: {}
  0.26-python3.8-bookworm: {}
  0.26-python3.8-bullseye: {}
  0.26-python3.9-alpine: {}
  0.26-python3.9-alpine3.17: {}
  0.26-python3.9-alpine3.18: {}
  0.26-python3.9-bookworm: {}
  0.26-python3.9-bullseye: {}
  0.26-python3.10-alpine: {}
  0.26-python3.10-alpine3.17: {}
  0.26-python3.10-alpine3.18: {}
  0.26-python3.10-bookworm: {}
  0.26-python3.10-bullseye: {}
  0.26-python3.11-alpine: {}
  0.26-python3.11-alpine3.17: {}
  0.26-python3.11-alpine3.18: {}
  0.26-python3.11-bookworm: {}
  0.26-python3.11-bullseye: {}
  0.26.0-alpine: {}
  0.26.0-alpine3.17: {}
  0.26.0-alpine3.18: {}
  0.26.0-bookworm: {}
  0.26.0-bullseye: {}
  0.26.0-pypy-bookworm: {}
  0.26.0-pypy-bullseye: {}
  0.26.0-pypy-windowsservercore-1809: {}
  0.26.0-pypy-windowsservercore-ltsc2022: {}
  0.26.0-pypy3.8-bookworm: {}
  0.26.0-pypy3.8-bullseye: {}
  0.26.0-pypy3.8-windowsservercore-1809: {}
  0.26.0-pypy3.8-windowsservercore-ltsc2022: {}
  0.26.0-pypy3.9-bookworm: {}
  0.26.0-pypy3.9-bullseye: {}
  0.26.0-pypy3.9-windowsservercore-1809: {}
  0.26.0-pypy3.9-windowsservercore-ltsc2022: {}
  0.26.0-python3.7-alpine: {}
  0.26.0-python3.7-alpine3.17: {}
  0.26.0-python3.7-alpine3.18: {}
  0.26.0-python3.7-bookworm: {}
  0.26.0-python3.7-bullseye: {}
  0.26.0-python3.8-alpine: {}
  0.26.0-python3.8-alpine3.17: {}
  0.26.0-python3.8-alpine3.18: {}
  0.26.0-python3.8-bookworm: {}
  0.26.0-python3.8-bullseye: {}
  0.26.0-python3.9-alpine: {}
  0.26.0-python3.9-alpine3.17: {}
  0.26.0-python3.9-alpine3.18: {}
  0.26.0-python3.9-bookworm: {}
  0.26.0-python3.9-bullseye: {}
  0.26.0-python3.10-alpine: {}
  0.26.0-python3.10-alpine3.17: {}
  0.26.0-python3.10-alpine3.18: {}
  0.26.0-python3.10-bookworm: {}
  0.26.0-python3.10-bullseye: {}
  0.26.0-python3.11-alpine: {}
  0.26.0-python3.11-alpine3.17: {}
  0.26.0-python3.11-alpine3.18: {}
  0.26.0-python3.11-bookworm: {}
  0.26.0-python3.11-bullseye: {}
  alpine: {}
  alpine3.17: {}
  alpine3.18: {}
  bookworm: {}
  bullseye: {}
  pypy-bookworm: {}
  pypy-bullseye: {}
  pypy-windowsservercore-1809: {}
  pypy-windowsservercore-ltsc2022: {}
  pypy3.8-bookworm: {}
  pypy3.8-bullseye: {}
  pypy3.8-windowsservercore-1809: {}
  pypy3.8-windowsservercore-ltsc2022: {}
  pypy3.9-bookworm: {}
  pypy3.9-bullseye: {}
  pypy3.9-windowsservercore-1809: {}
  pypy3.9-windowsservercore-ltsc2022: {}
  python3.7-alpine: {}
  python3.7-alpine3.17: {}
  python3.7-alpine3.18: {}
  python3.7-bookworm: {}
  python3.7-bullseye: {}
  python3.8-alpine: {}
  python3.8-alpine3.17: {}
  python3.8-alpine3.18: {}
  python3.8-bookworm: {}
  python3.8-bullseye: {}
  python3.9-alpine: {}
  python3.9-alpine3.17: {}
  python3.9-alpine3.18: {}
  python3.9-bookworm: {}
  python3.9-bullseye: {}
  python3.10-alpine: {}
  python3.10-alpine3.17: {}
  python3.10-alpine3.18: {}
  python3.10-bookworm: {}
  python3.10-bullseye: {}
  python3.11-alpine: {}
  python3.11-alpine3.17: {}
  python3.11-alpine3.18: {}
  python3.11-bookworm: {}
  python3.11-bullseye: {}
Name: hylang
