Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 8.2/bullseye
  GitCommit: a4ef0077f546b7e9be444720b14f2cba14f8f2eb
  Tags:
  - 8.2.0-bullseye
  - 8.2-bullseye
  - 8-bullseye
  - bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: 8.2/alpine3.16
  GitCommit: 24aabb5cd0330eab9c8baeddf4fc8fcf0d714d3b
  Tags:
  - 8.2.0-alpine3.16
  - 8.2-alpine3.16
  - 8-alpine3.16
  - alpine3.16
  - 8.2.0-alpine
  - 8.2-alpine
  - 8-alpine
  - alpine
GitRepo: https://github.com/IdentityPython/satosa-docker.git
KnownTags:
  8-alpine: {}
  8-alpine3.16: {}
  8-bullseye: {}
  8.2-alpine: {}
  8.2-alpine3.16: {}
  8.2-bullseye: {}
  8.2.0-alpine: {}
  8.2.0-alpine3.16: {}
  8.2.0-bullseye: {}
  alpine: {}
  alpine3.16: {}
  bullseye: {}
Name: satosa
