Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v5:
      Architecture: arm32v5
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8.4/bookworm
  File: ""
  GitCommit: 69038a84d541717d66420f3ad8ec7c9da22c91b4
  Tags:
  - 8.4.0-bookworm
  - 8.4-bookworm
  - 8-bookworm
  - bookworm
  - 8.4.0
  - "8.4"
  - "8"
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v6:
      Architecture: arm32v6
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8.4/alpine3.19
  File: ""
  GitCommit: 74a847396f1190ec26679fc3bf09ffcc42d2e999
  Tags:
  - 8.4.0-alpine3.19
  - 8.4-alpine3.19
  - 8-alpine3.19
  - alpine3.19
  - 8.4.0-alpine
  - 8.4-alpine
  - 8-alpine
  - alpine
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v5:
      Architecture: arm32v5
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8.2/bullseye
  File: ""
  GitCommit: a4ef0077f546b7e9be444720b14f2cba14f8f2eb
  Tags:
  - 8.2.0-bullseye
  - 8.2-bullseye
  - 8-bullseye
  - bullseye
  - 8.2.0
  - "8.2"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v6:
      Architecture: arm32v6
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8.2/alpine3.16
  File: ""
  GitCommit: 24aabb5cd0330eab9c8baeddf4fc8fcf0d714d3b
  Tags:
  - 8.2.0-alpine3.16
  - 8.2-alpine3.16
  - 8-alpine3.16
  - alpine3.16
  - 8.2.0-alpine
  - 8.2-alpine
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v5:
      Architecture: arm32v5
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    mips64le:
      Architecture: mips64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8.1/bullseye
  File: ""
  GitCommit: f62013ad3b8a785b37b3acc2c0b0ead94aae8b95
  Tags:
  - 8.1.1-bullseye
  - 8.1-bullseye
  - 8.1.1
  - "8.1"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v6:
      Architecture: arm32v6
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8.1/alpine3.16
  File: ""
  GitCommit: f62013ad3b8a785b37b3acc2c0b0ead94aae8b95
  Tags:
  - 8.1.1-alpine3.16
  - 8.1-alpine3.16
  - 8.1.1-alpine
  - 8.1-alpine
GitRepo: https://github.com/IdentityPython/satosa-docker.git
KnownTags:
  "8": {}
  8-alpine: {}
  8-alpine3.16: {}
  8-alpine3.19: {}
  8-bookworm: {}
  8-bullseye: {}
  "8.1": {}
  8.1-alpine: {}
  8.1-alpine3.16: {}
  8.1-bullseye: {}
  8.1.1: {}
  8.1.1-alpine: {}
  8.1.1-alpine3.16: {}
  8.1.1-bullseye: {}
  "8.2": {}
  8.2-alpine: {}
  8.2-alpine3.16: {}
  8.2-bullseye: {}
  8.2.0: {}
  8.2.0-alpine: {}
  8.2.0-alpine3.16: {}
  8.2.0-bullseye: {}
  "8.4": {}
  8.4-alpine: {}
  8.4-alpine3.19: {}
  8.4-bookworm: {}
  8.4.0: {}
  8.4.0-alpine: {}
  8.4.0-alpine3.19: {}
  8.4.0-bookworm: {}
  alpine: {}
  alpine3.16: {}
  alpine3.19: {}
  bookworm: {}
  bullseye: {}
  latest: {}
Name: satosa
