Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/11/ubuntu/focal/gzserver11
  File: ""
  GitCommit: 27cc0b68263bbbb10bb58dd814efc0a6b0a01ec7
  Tags:
  - gzserver11
  - gzserver11-focal
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/11/ubuntu/focal/libgazebo11
  File: ""
  GitCommit: 532c4f1af8c9dadb54b0c9769543c67c40c0c84f
  Tags:
  - libgazebo11
  - libgazebo11-focal
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/11/ubuntu/bionic/gzserver11
  File: ""
  GitCommit: 99ff497288ca42e33d777a0d04fb8c026aca2f40
  Tags:
  - gzserver11-bionic
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/11/ubuntu/bionic/libgazebo11
  File: ""
  GitCommit: 99ff497288ca42e33d777a0d04fb8c026aca2f40
  Tags:
  - libgazebo11-bionic
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/9/ubuntu/xenial/gzserver9
  File: ""
  GitCommit: 96c8fa210caaeebd50e067ade05d5fc9a4a60c84
  Tags:
  - gzserver9-xenial
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/9/ubuntu/xenial/libgazebo9
  File: ""
  GitCommit: 96c8fa210caaeebd50e067ade05d5fc9a4a60c84
  Tags:
  - libgazebo9-xenial
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/9/ubuntu/bionic/gzserver9
  File: ""
  GitCommit: 212f7553882e8f3e96af773ede6ef1848277c09e
  Tags:
  - gzserver9
  - gzserver9-bionic
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/9/ubuntu/bionic/libgazebo9
  File: ""
  GitCommit: 212f7553882e8f3e96af773ede6ef1848277c09e
  Tags:
  - libgazebo9
  - libgazebo9-bionic
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/7/ubuntu/xenial/gzserver7
  File: ""
  GitCommit: c2b11f03428e862ab6c8f106823fac7d9d9ac48c
  Tags:
  - gzserver7
  - gzserver7-xenial
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/7/ubuntu/xenial/libgazebo7
  File: ""
  GitCommit: c2b11f03428e862ab6c8f106823fac7d9d9ac48c
  Tags:
  - libgazebo7
  - libgazebo7-xenial
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/9/debian/stretch/gzserver9
  File: ""
  GitCommit: a6c5b63e1ba4291e94b91ac5ff067c0d3f7d3c37
  Tags:
  - gzserver9-stretch
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/9/debian/stretch/libgazebo9
  File: ""
  GitCommit: a6c5b63e1ba4291e94b91ac5ff067c0d3f7d3c37
  Tags:
  - libgazebo9-stretch
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/10/ubuntu/bionic/gzserver10
  File: ""
  GitCommit: c2b11f03428e862ab6c8f106823fac7d9d9ac48c
  Tags:
  - gzserver10
  - gzserver10-bionic
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/10/ubuntu/bionic/libgazebo10
  File: ""
  GitCommit: c2b11f03428e862ab6c8f106823fac7d9d9ac48c
  Tags:
  - libgazebo10
  - libgazebo10-bionic
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/8/ubuntu/xenial/gzserver8
  File: ""
  GitCommit: ed75e08b51ca57c98fad49705091ceb89a96814c
  Tags:
  - gzserver8
  - gzserver8-xenial
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/8/ubuntu/xenial/libgazebo8
  File: ""
  GitCommit: ed75e08b51ca57c98fad49705091ceb89a96814c
  Tags:
  - libgazebo8
  - libgazebo8-xenial
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/4/ubuntu/trusty/gzserver4
  File: ""
  GitCommit: c5ca5054c6921645802f21e888b79f464863eb1a
  Tags:
  - gzserver4
  - gzserver4-trusty
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/4/ubuntu/trusty/libgazebo4
  File: ""
  GitCommit: c5ca5054c6921645802f21e888b79f464863eb1a
  Tags:
  - libgazebo4
  - libgazebo4-trusty
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/5/ubuntu/trusty/gzserver5
  File: ""
  GitCommit: c5ca5054c6921645802f21e888b79f464863eb1a
  Tags:
  - gzserver5
  - gzserver5-trusty
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/5/ubuntu/trusty/libgazebo5
  File: ""
  GitCommit: c5ca5054c6921645802f21e888b79f464863eb1a
  Tags:
  - libgazebo5
  - libgazebo5-trusty
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/6/ubuntu/trusty/gzserver6
  File: ""
  GitCommit: c5ca5054c6921645802f21e888b79f464863eb1a
  Tags:
  - gzserver6
  - gzserver6-trusty
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: gazebo/6/ubuntu/trusty/libgazebo6
  File: ""
  GitCommit: c5ca5054c6921645802f21e888b79f464863eb1a
  Tags:
  - libgazebo6
  - libgazebo6-trusty
GitRepo: https://github.com/osrf/docker_images.git
KnownTags:
  gzserver4: {}
  gzserver4-trusty: {}
  gzserver5: {}
  gzserver5-trusty: {}
  gzserver6: {}
  gzserver6-trusty: {}
  gzserver7: {}
  gzserver7-xenial: {}
  gzserver8: {}
  gzserver8-xenial: {}
  gzserver9: {}
  gzserver9-bionic: {}
  gzserver9-stretch: {}
  gzserver9-xenial: {}
  gzserver10: {}
  gzserver10-bionic: {}
  gzserver11: {}
  gzserver11-bionic: {}
  gzserver11-focal: {}
  latest: {}
  libgazebo4: {}
  libgazebo4-trusty: {}
  libgazebo5: {}
  libgazebo5-trusty: {}
  libgazebo6: {}
  libgazebo6-trusty: {}
  libgazebo7: {}
  libgazebo7-xenial: {}
  libgazebo8: {}
  libgazebo8-xenial: {}
  libgazebo9: {}
  libgazebo9-bionic: {}
  libgazebo9-stretch: {}
  libgazebo9-xenial: {}
  libgazebo10: {}
  libgazebo10-bionic: {}
  libgazebo11: {}
  libgazebo11-bionic: {}
  libgazebo11-focal: {}
Name: gazebo
