Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  Directory: 3.12.10
  GitCommit: 43d2ceae423b3595499a0b40255a249816490678
  Tags:
  - 3.12.10
  - "3.12"
  - "3"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  Directory: 3.12.10/postgres
  GitCommit: 43d2ceae423b3595499a0b40255a249816490678
  Tags:
  - 3.12.10-postgres
  - 3.12-postgres
  - 3-postgres
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.0.6
  GitCommit: 00936dcf7dbb2399405c53aa05c670fa4bb79736
  Tags:
  - 4.0.6
  - "4.0"
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.2.4
  GitCommit: 3ef0cd8059c71b49b775b017c85ada9d82b113e9
  Tags:
  - 4.2.4
  - "4.2"
  - "4"
  - latest
GitRepo: https://github.com/geonetwork/docker-geonetwork
KnownTags:
  "3": {}
  3-postgres: {}
  "3.12": {}
  3.12-postgres: {}
  3.12.10: {}
  3.12.10-postgres: {}
  "4": {}
  "4.0": {}
  4.0.6: {}
  "4.2": {}
  4.2.4: {}
  latest: {}
Name: geonetwork
