Blocks:
- Architectures:
  - amd64
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  Directory: 2.6/alpine
  GitCommit: 6e5a266c6839d6f84eb84f8430ce13a49c1b0aae
  Tags:
  - 2.6.4-alpine
  - 2.6-alpine
  - 2-alpine
  - alpine
- Architectures:
  - amd64
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  Directory: 2.6/builder
  GitCommit: 8a3bab4e266cc4e32c57d757890bbc1b6ff54e1d
  Tags:
  - 2.6.4-builder-alpine
  - 2.6-builder-alpine
  - 2-builder-alpine
  - builder-alpine
- Architectures:
  - windows-amd64
  Directory: 2.6/windows/1809
  GitCommit: 968a9e779660c4e0711021103eebf610c7979a7e
  Tags:
  - 2.6.4-windowsservercore-1809
  - 2.6-windowsservercore-1809
  - 2-windowsservercore-1809
  - windowsservercore-1809
- Architectures:
  - windows-amd64
  Directory: 2.6/windows/ltsc2022
  GitCommit: 968a9e779660c4e0711021103eebf610c7979a7e
  Tags:
  - 2.6.4-windowsservercore-ltsc2022
  - 2.6-windowsservercore-ltsc2022
  - 2-windowsservercore-ltsc2022
  - windowsservercore-ltsc2022
- Architectures:
  - windows-amd64
  Directory: 2.6/windows-builder/1809
  GitCommit: 8a3bab4e266cc4e32c57d757890bbc1b6ff54e1d
  Tags:
  - 2.6.4-builder-windowsservercore-1809
  - 2.6-builder-windowsservercore-1809
  - 2-builder-windowsservercore-1809
  - builder-windowsservercore-1809
- Architectures:
  - windows-amd64
  Directory: 2.6/windows-builder/ltsc2022
  GitCommit: 8a3bab4e266cc4e32c57d757890bbc1b6ff54e1d
  Tags:
  - 2.6.4-builder-windowsservercore-ltsc2022
  - 2.6-builder-windowsservercore-ltsc2022
  - 2-builder-windowsservercore-ltsc2022
  - builder-windowsservercore-ltsc2022
- Architectures:
  - amd64
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  Directory: 2.7/alpine
  GitCommit: 9821d43cf53bf53071b2bc4cfca1dc3be87bed56
  Tags:
  - 2.7.0-beta.1-alpine
  - 2.7-alpine
- Architectures:
  - amd64
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  Directory: 2.7/builder
  GitCommit: 8a3bab4e266cc4e32c57d757890bbc1b6ff54e1d
  Tags:
  - 2.7.0-beta.1-builder-alpine
  - 2.7-builder-alpine
- Architectures:
  - windows-amd64
  Directory: 2.7/windows/1809
  GitCommit: 9821d43cf53bf53071b2bc4cfca1dc3be87bed56
  Tags:
  - 2.7.0-beta.1-windowsservercore-1809
  - 2.7-windowsservercore-1809
- Architectures:
  - windows-amd64
  Directory: 2.7/windows/ltsc2022
  GitCommit: 9821d43cf53bf53071b2bc4cfca1dc3be87bed56
  Tags:
  - 2.7.0-beta.1-windowsservercore-ltsc2022
  - 2.7-windowsservercore-ltsc2022
- Architectures:
  - windows-amd64
  Directory: 2.7/windows-builder/1809
  GitCommit: 8a3bab4e266cc4e32c57d757890bbc1b6ff54e1d
  Tags:
  - 2.7.0-beta.1-builder-windowsservercore-1809
  - 2.7-builder-windowsservercore-1809
- Architectures:
  - windows-amd64
  Directory: 2.7/windows-builder/ltsc2022
  GitCommit: 8a3bab4e266cc4e32c57d757890bbc1b6ff54e1d
  Tags:
  - 2.7.0-beta.1-builder-windowsservercore-ltsc2022
  - 2.7-builder-windowsservercore-ltsc2022
GitRepo: https://github.com/caddyserver/caddy-docker.git
KnownTags:
  2-alpine: {}
  2-builder-alpine: {}
  2-builder-windowsservercore-1809: {}
  2-builder-windowsservercore-ltsc2022: {}
  2-windowsservercore-1809: {}
  2-windowsservercore-ltsc2022: {}
  2.6-alpine: {}
  2.6-builder-alpine: {}
  2.6-builder-windowsservercore-1809: {}
  2.6-builder-windowsservercore-ltsc2022: {}
  2.6-windowsservercore-1809: {}
  2.6-windowsservercore-ltsc2022: {}
  2.6.4-alpine: {}
  2.6.4-builder-alpine: {}
  2.6.4-builder-windowsservercore-1809: {}
  2.6.4-builder-windowsservercore-ltsc2022: {}
  2.6.4-windowsservercore-1809: {}
  2.6.4-windowsservercore-ltsc2022: {}
  2.7-alpine: {}
  2.7-builder-alpine: {}
  2.7-builder-windowsservercore-1809: {}
  2.7-builder-windowsservercore-ltsc2022: {}
  2.7-windowsservercore-1809: {}
  2.7-windowsservercore-ltsc2022: {}
  2.7.0-beta.1-alpine: {}
  2.7.0-beta.1-builder-alpine: {}
  2.7.0-beta.1-builder-windowsservercore-1809: {}
  2.7.0-beta.1-builder-windowsservercore-ltsc2022: {}
  2.7.0-beta.1-windowsservercore-1809: {}
  2.7.0-beta.1-windowsservercore-ltsc2022: {}
  alpine: {}
  builder-alpine: {}
  builder-windowsservercore-1809: {}
  builder-windowsservercore-ltsc2022: {}
  windowsservercore-1809: {}
  windowsservercore-ltsc2022: {}
Name: caddy
