Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: enterprise/couchbase-server/7.2.0
  GitCommit: 2bd177d6887d051b6981c8c2591af6eed3ae9505
  Tags:
  - 7.2.0
  - enterprise-7.2.0
  - enterprise
  - latest
- Architectures:
  - amd64
  - arm64v8
  Directory: community/couchbase-server/7.2.0
  GitCommit: 2bd177d6887d051b6981c8c2591af6eed3ae9505
  Tags:
  - community-7.2.0
  - community
- Architectures:
  - amd64
  - arm64v8
  Directory: enterprise/couchbase-server/7.1.4
  GitCommit: c497eda885d5b9869ad45d0432e3b382d6b328c1
  Tags:
  - 7.1.4
  - enterprise-7.1.4
- Architectures:
  - amd64
  - arm64v8
  Directory: community/couchbase-server/7.1.1
  GitCommit: bfbb82c084ca3ada6252afbbcb3ca94bb65f1e58
  Tags:
  - community-7.1.1
- Architectures: null
  Directory: enterprise/couchbase-server/7.0.5
  GitCommit: ca816b6ffa5c36007bd4b3386ec24df081a00ea0
  Tags:
  - 7.0.5
  - enterprise-7.0.5
- Architectures: null
  Directory: community/couchbase-server/7.0.2
  GitCommit: aec4494ab5280caf567997d72714f57572a6315b
  Tags:
  - community-7.0.2
- Architectures: null
  Directory: enterprise/couchbase-server/6.6.6
  GitCommit: 8398e79a15da9eef613d0a781ec136a458ea128c
  Tags:
  - 6.6.6
  - enterprise-6.6.6
- Architectures: null
  Directory: community/couchbase-server/6.6.0
  GitCommit: aad4aa9714578906c0c993121654eaeba0bd907c
  Tags:
  - community-6.6.0
- Architectures:
  - amd64
  - arm64v8
  Directory: enterprise/couchbase-server/7.1.3
  GitCommit: ae715392f6a8bff71ce2e5e99d62492d19c85dd2
  Tags:
  - 7.1.3
  - enterprise-7.1.3
- Architectures: null
  Directory: enterprise/couchbase-server/6.6.5
  GitCommit: aad4aa9714578906c0c993121654eaeba0bd907c
  Tags:
  - 6.6.5
  - enterprise-6.6.5
- Architectures: null
  Directory: enterprise/couchbase-server/7.0.4
  GitCommit: bb7d69d6e542a06185f113bde6fb3b580583934c
  Tags:
  - 7.0.4
  - enterprise-7.0.4
- Architectures:
  - amd64
  - arm64v8
  Directory: enterprise/couchbase-server/7.1.2
  GitCommit: ad221952362094016bc532ba6cff3d359742aee5
  Tags:
  - 7.1.2
  - enterprise-7.1.2
- Architectures:
  - amd64
  - arm64v8
  Directory: enterprise/couchbase-server/7.1.1
  GitCommit: bfbb82c084ca3ada6252afbbcb3ca94bb65f1e58
  Tags:
  - 7.1.1
  - enterprise-7.1.1
- Architectures: null
  Directory: enterprise/couchbase-server/7.0.3
  GitCommit: e3c274f39e02aa24e8dc7e486aefba916a7b747a
  Tags:
  - 7.0.3
  - enterprise-7.0.3
- Architectures: null
  Directory: enterprise/couchbase-server/7.1.0/x86_64
  GitCommit: fdaa38c9abfb3e9ed81f622c0f9e91f8e6ba986f
  Tags:
  - 7.1.0
  - enterprise-7.1.0
- Architectures: null
  Directory: community/couchbase-server/7.1.0/x86_64
  GitCommit: fdaa38c9abfb3e9ed81f622c0f9e91f8e6ba986f
  Tags:
  - community-7.1.0
- Architectures: null
  Directory: enterprise/couchbase-server/6.0.5
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 6.0.5
  - enterprise-6.0.5
- Architectures: null
  Directory: enterprise/couchbase-server/6.5.2
  GitCommit: d24fe7e4e45de16395e6da37a97969e8ce198b45
  Tags:
  - 6.5.2
  - enterprise-6.5.2
- Architectures: null
  Directory: enterprise/couchbase-server/6.6.4
  GitCommit: e27aaf8d37861a570ad62a96ea04c84026a59282
  Tags:
  - 6.6.4
  - enterprise-6.6.4
- Architectures: null
  Directory: enterprise/couchbase-server/7.0.2
  GitCommit: aec4494ab5280caf567997d72714f57572a6315b
  Tags:
  - 7.0.2
  - enterprise-7.0.2
- Architectures: null
  Directory: enterprise/couchbase-server/6.6.3
  GitCommit: 3ff26f9a680d1449756b51e753324980087c0548
  Tags:
  - 6.6.3
  - enterprise-6.6.3
- Architectures: null
  Directory: enterprise/couchbase-server/7.0.1
  GitCommit: f412542829939319b5e722fa384c60b68e765bce
  Tags:
  - 7.0.1
  - enterprise-7.0.1
- Architectures: null
  Directory: community/couchbase-server/7.0.1
  GitCommit: f412542829939319b5e722fa384c60b68e765bce
  Tags:
  - community-7.0.1
- Architectures: null
  Directory: enterprise/couchbase-server/7.0.0
  GitCommit: a4a4b016732b4ea3a42ea115f481c66ba69b980d
  Tags:
  - 7.0.0
  - enterprise-7.0.0
- Architectures: null
  Directory: community/couchbase-server/7.0.0
  GitCommit: a4a4b016732b4ea3a42ea115f481c66ba69b980d
  Tags:
  - community-7.0.0
- Architectures: null
  Directory: enterprise/couchbase-server/6.6.2
  GitCommit: 4d5b6101c73d4efe75d2288107f6fe00b1deeff5
  Tags:
  - 6.6.2
  - enterprise-6.6.2
- Architectures: null
  Directory: enterprise/couchbase-server/7.0.0-beta
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 7.0.0-beta
  - enterprise-7.0.0-beta
- Architectures: null
  Directory: community/couchbase-server/7.0.0-beta
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - community-7.0.0-beta
- Architectures: null
  Directory: enterprise/couchbase-server/6.6.1
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 6.6.1
  - enterprise-6.6.1
- Architectures: null
  Directory: enterprise/couchbase-server/6.6.0
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 6.6.0
  - enterprise-6.6.0
- Architectures: null
  Directory: enterprise/couchbase-server/6.5.1
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 6.5.1
  - enterprise-6.5.1
- Architectures: null
  Directory: enterprise/couchbase-server/6.5.0
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 6.5.0
  - enterprise-6.5.0
- Architectures: null
  Directory: enterprise/couchbase-server/6.0.4
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 6.0.4
  - enterprise-6.0.4
- Architectures: null
  Directory: enterprise/couchbase-server/6.0.3
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 6.0.3
  - enterprise-6.0.3
- Architectures: null
  Directory: enterprise/couchbase-server/6.0.2
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 6.0.2
  - enterprise-6.0.2
- Architectures: null
  Directory: enterprise/couchbase-server/6.0.1
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 6.0.1
  - enterprise-6.0.1
- Architectures: null
  Directory: community/couchbase-server/6.5.1
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - community-6.5.1
- Architectures: null
  Directory: community/couchbase-server/6.5.1
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - community-6.5.0
GitRepo: https://github.com/couchbase/docker
KnownTags:
  6.0.1: {}
  6.0.2: {}
  6.0.3: {}
  6.0.4: {}
  6.0.5: {}
  6.5.0: {}
  6.5.1: {}
  6.5.2: {}
  6.6.0: {}
  6.6.1: {}
  6.6.2: {}
  6.6.3: {}
  6.6.4: {}
  6.6.5: {}
  6.6.6: {}
  7.0.0: {}
  7.0.0-beta: {}
  7.0.1: {}
  7.0.2: {}
  7.0.3: {}
  7.0.4: {}
  7.0.5: {}
  7.1.0: {}
  7.1.1: {}
  7.1.2: {}
  7.1.3: {}
  7.1.4: {}
  7.2.0: {}
  community: {}
  community-6.5.0: {}
  community-6.5.1: {}
  community-6.6.0: {}
  community-7.0.0: {}
  community-7.0.0-beta: {}
  community-7.0.1: {}
  community-7.0.2: {}
  community-7.1.0: {}
  community-7.1.1: {}
  community-7.2.0: {}
  enterprise: {}
  enterprise-6.0.1: {}
  enterprise-6.0.2: {}
  enterprise-6.0.3: {}
  enterprise-6.0.4: {}
  enterprise-6.0.5: {}
  enterprise-6.5.0: {}
  enterprise-6.5.1: {}
  enterprise-6.5.2: {}
  enterprise-6.6.0: {}
  enterprise-6.6.1: {}
  enterprise-6.6.2: {}
  enterprise-6.6.3: {}
  enterprise-6.6.4: {}
  enterprise-6.6.5: {}
  enterprise-6.6.6: {}
  enterprise-7.0.0: {}
  enterprise-7.0.0-beta: {}
  enterprise-7.0.1: {}
  enterprise-7.0.2: {}
  enterprise-7.0.3: {}
  enterprise-7.0.4: {}
  enterprise-7.0.5: {}
  enterprise-7.1.0: {}
  enterprise-7.1.1: {}
  enterprise-7.1.2: {}
  enterprise-7.1.3: {}
  enterprise-7.1.4: {}
  enterprise-7.2.0: {}
  latest: {}
Name: couchbase
