Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: enterprise/couchbase-server/7.6.3
  File: ""
  GitCommit: 553d1baa4aa90fe506e1d7bcdf4daec387a110fe
  Tags:
  - 7.6.3
  - enterprise-7.6.3
  - enterprise
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: community/couchbase-server/7.6.2
  File: ""
  GitCommit: 34bb6684dc575f4e0b8b0f16127f5d4188015d8d
  Tags:
  - community-7.6.2
  - community
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: enterprise/couchbase-server/7.2.6
  File: ""
  GitCommit: 857d7bcc814e241fd36aa4dc326dcab37e1d1e73
  Tags:
  - 7.2.6
  - enterprise-7.2.6
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: community/couchbase-server/7.2.4
  File: ""
  GitCommit: 8205e18d139813ac3f72f6dfef9ee9ffbc382e0f
  Tags:
  - community-7.2.4
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: enterprise/couchbase-server/7.1.6
  File: ""
  GitCommit: 8205e18d139813ac3f72f6dfef9ee9ffbc382e0f
  Tags:
  - 7.1.6
  - enterprise-7.1.6
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: community/couchbase-server/7.1.1
  File: ""
  GitCommit: 8205e18d139813ac3f72f6dfef9ee9ffbc382e0f
  Tags:
  - community-7.1.1
- Architectures: null
  Directory: enterprise/couchbase-server/7.0.5
  File: ""
  GitCommit: 8205e18d139813ac3f72f6dfef9ee9ffbc382e0f
  Tags:
  - 7.0.5
  - enterprise-7.0.5
- Architectures: null
  Directory: community/couchbase-server/7.0.2
  File: ""
  GitCommit: 8205e18d139813ac3f72f6dfef9ee9ffbc382e0f
  Tags:
  - community-7.0.2
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: enterprise/couchbase-server/7.2.5
  File: ""
  GitCommit: 58e0549b1e021259a1ce9bb70d70aac4cc5e71da
  Tags:
  - 7.2.5
  - enterprise-7.2.5
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: enterprise/couchbase-server/7.6.2
  File: ""
  GitCommit: ba43d566538a8e0b6315569b94f0a7cf835c222b
  Tags:
  - 7.6.2
  - enterprise-7.6.2
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: enterprise/couchbase-server/7.6.1
  File: ""
  GitCommit: 5268f3a009878a85c70b1461ef32cf8ce21debec
  Tags:
  - 7.6.1
  - enterprise-7.6.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: community/couchbase-server/7.6.1
  File: ""
  GitCommit: 6eb060cef1909e850b0ad4a930cd577a89a6d269
  Tags:
  - community-7.6.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: enterprise/couchbase-server/7.2.4
  File: ""
  GitCommit: 8205e18d139813ac3f72f6dfef9ee9ffbc382e0f
  Tags:
  - 7.2.4
  - enterprise-7.2.4
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: enterprise/couchbase-server/7.6.0
  File: ""
  GitCommit: 203e62f36ce055be75955e073d0000249bf2c040
  Tags:
  - 7.6.0
  - enterprise-7.6.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: community/couchbase-server/7.6.0
  File: ""
  GitCommit: 7148bc241bcdcf8961c34f8adf76ebfb2860ed83
  Tags:
  - community-7.6.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: enterprise/couchbase-server/7.2.3
  File: ""
  GitCommit: 3a446520433f63e3d270f01063b14cb6b6ade12a
  Tags:
  - 7.2.3
  - enterprise-7.2.3
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: community/couchbase-server/7.2.2
  File: ""
  GitCommit: 855d163127ee5e4bc6854714ecd6911f70f27906
  Tags:
  - community-7.2.2
- Architectures: null
  Directory: enterprise/couchbase-server/6.6.6
  File: ""
  GitCommit: 8398e79a15da9eef613d0a781ec136a458ea128c
  Tags:
  - 6.6.6
  - enterprise-6.6.6
- Architectures: null
  Directory: community/couchbase-server/6.6.0
  File: ""
  GitCommit: aad4aa9714578906c0c993121654eaeba0bd907c
  Tags:
  - community-6.6.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: enterprise/couchbase-server/7.2.2
  File: ""
  GitCommit: 855d163127ee5e4bc6854714ecd6911f70f27906
  Tags:
  - 7.2.2
  - enterprise-7.2.2
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: enterprise/couchbase-server/7.1.5
  File: ""
  GitCommit: 1ce6c78f29c9be97c67c2588b1ceaa57ad1b49c6
  Tags:
  - 7.1.5
  - enterprise-7.1.5
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: enterprise/couchbase-server/7.2.1
  File: ""
  GitCommit: 7b023e33d2961ef352c33f3772ca50dfcc797165
  Tags:
  - 7.2.1
  - enterprise-7.2.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: community/couchbase-server/7.2.1
  File: ""
  GitCommit: 7b023e33d2961ef352c33f3772ca50dfcc797165
  Tags:
  - community-7.2.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: enterprise/couchbase-server/7.2.0
  File: ""
  GitCommit: 2bd177d6887d051b6981c8c2591af6eed3ae9505
  Tags:
  - 7.2.0
  - enterprise-7.2.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: community/couchbase-server/7.2.0
  File: ""
  GitCommit: 2bd177d6887d051b6981c8c2591af6eed3ae9505
  Tags:
  - community-7.2.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: enterprise/couchbase-server/7.1.4
  File: ""
  GitCommit: c497eda885d5b9869ad45d0432e3b382d6b328c1
  Tags:
  - 7.1.4
  - enterprise-7.1.4
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: enterprise/couchbase-server/7.1.3
  File: ""
  GitCommit: ae715392f6a8bff71ce2e5e99d62492d19c85dd2
  Tags:
  - 7.1.3
  - enterprise-7.1.3
- Architectures: null
  Directory: enterprise/couchbase-server/6.6.5
  File: ""
  GitCommit: aad4aa9714578906c0c993121654eaeba0bd907c
  Tags:
  - 6.6.5
  - enterprise-6.6.5
- Architectures: null
  Directory: enterprise/couchbase-server/7.0.4
  File: ""
  GitCommit: bb7d69d6e542a06185f113bde6fb3b580583934c
  Tags:
  - 7.0.4
  - enterprise-7.0.4
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: enterprise/couchbase-server/7.1.2
  File: ""
  GitCommit: ad221952362094016bc532ba6cff3d359742aee5
  Tags:
  - 7.1.2
  - enterprise-7.1.2
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: enterprise/couchbase-server/7.1.1
  File: ""
  GitCommit: bfbb82c084ca3ada6252afbbcb3ca94bb65f1e58
  Tags:
  - 7.1.1
  - enterprise-7.1.1
- Architectures: null
  Directory: enterprise/couchbase-server/7.0.3
  File: ""
  GitCommit: e3c274f39e02aa24e8dc7e486aefba916a7b747a
  Tags:
  - 7.0.3
  - enterprise-7.0.3
- Architectures: null
  Directory: enterprise/couchbase-server/7.1.0/x86_64
  File: ""
  GitCommit: fdaa38c9abfb3e9ed81f622c0f9e91f8e6ba986f
  Tags:
  - 7.1.0
  - enterprise-7.1.0
- Architectures: null
  Directory: community/couchbase-server/7.1.0/x86_64
  File: ""
  GitCommit: fdaa38c9abfb3e9ed81f622c0f9e91f8e6ba986f
  Tags:
  - community-7.1.0
- Architectures: null
  Directory: enterprise/couchbase-server/6.0.5
  File: ""
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 6.0.5
  - enterprise-6.0.5
- Architectures: null
  Directory: enterprise/couchbase-server/6.5.2
  File: ""
  GitCommit: d24fe7e4e45de16395e6da37a97969e8ce198b45
  Tags:
  - 6.5.2
  - enterprise-6.5.2
- Architectures: null
  Directory: enterprise/couchbase-server/6.6.4
  File: ""
  GitCommit: e27aaf8d37861a570ad62a96ea04c84026a59282
  Tags:
  - 6.6.4
  - enterprise-6.6.4
- Architectures: null
  Directory: enterprise/couchbase-server/7.0.2
  File: ""
  GitCommit: aec4494ab5280caf567997d72714f57572a6315b
  Tags:
  - 7.0.2
  - enterprise-7.0.2
- Architectures: null
  Directory: enterprise/couchbase-server/6.6.3
  File: ""
  GitCommit: 3ff26f9a680d1449756b51e753324980087c0548
  Tags:
  - 6.6.3
  - enterprise-6.6.3
- Architectures: null
  Directory: enterprise/couchbase-server/7.0.1
  File: ""
  GitCommit: f412542829939319b5e722fa384c60b68e765bce
  Tags:
  - 7.0.1
  - enterprise-7.0.1
- Architectures: null
  Directory: community/couchbase-server/7.0.1
  File: ""
  GitCommit: f412542829939319b5e722fa384c60b68e765bce
  Tags:
  - community-7.0.1
- Architectures: null
  Directory: enterprise/couchbase-server/7.0.0
  File: ""
  GitCommit: a4a4b016732b4ea3a42ea115f481c66ba69b980d
  Tags:
  - 7.0.0
  - enterprise-7.0.0
- Architectures: null
  Directory: community/couchbase-server/7.0.0
  File: ""
  GitCommit: a4a4b016732b4ea3a42ea115f481c66ba69b980d
  Tags:
  - community-7.0.0
- Architectures: null
  Directory: enterprise/couchbase-server/6.6.2
  File: ""
  GitCommit: 4d5b6101c73d4efe75d2288107f6fe00b1deeff5
  Tags:
  - 6.6.2
  - enterprise-6.6.2
- Architectures: null
  Directory: enterprise/couchbase-server/7.0.0-beta
  File: ""
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 7.0.0-beta
  - enterprise-7.0.0-beta
- Architectures: null
  Directory: community/couchbase-server/7.0.0-beta
  File: ""
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - community-7.0.0-beta
- Architectures: null
  Directory: enterprise/couchbase-server/6.6.1
  File: ""
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 6.6.1
  - enterprise-6.6.1
- Architectures: null
  Directory: enterprise/couchbase-server/6.6.0
  File: ""
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 6.6.0
  - enterprise-6.6.0
- Architectures: null
  Directory: enterprise/couchbase-server/6.5.1
  File: ""
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 6.5.1
  - enterprise-6.5.1
- Architectures: null
  Directory: enterprise/couchbase-server/6.5.0
  File: ""
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 6.5.0
  - enterprise-6.5.0
- Architectures: null
  Directory: enterprise/couchbase-server/6.0.4
  File: ""
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 6.0.4
  - enterprise-6.0.4
- Architectures: null
  Directory: enterprise/couchbase-server/6.0.3
  File: ""
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 6.0.3
  - enterprise-6.0.3
- Architectures: null
  Directory: enterprise/couchbase-server/6.0.2
  File: ""
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 6.0.2
  - enterprise-6.0.2
- Architectures: null
  Directory: enterprise/couchbase-server/6.0.1
  File: ""
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - 6.0.1
  - enterprise-6.0.1
- Architectures: null
  Directory: community/couchbase-server/6.5.1
  File: ""
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - community-6.5.1
- Architectures: null
  Directory: community/couchbase-server/6.5.1
  File: ""
  GitCommit: 5929be778eb5306f116f71cc9a0a23fea6d9a7aa
  Tags:
  - community-6.5.0
GitRepo: https://github.com/couchbase/docker
KnownTags:
  6.0.1: {}
  6.0.2: {}
  6.0.3: {}
  6.0.4: {}
  6.0.5: {}
  6.5.0: {}
  6.5.1: {}
  6.5.2: {}
  6.6.0: {}
  6.6.1: {}
  6.6.2: {}
  6.6.3: {}
  6.6.4: {}
  6.6.5: {}
  6.6.6: {}
  7.0.0: {}
  7.0.0-beta: {}
  7.0.1: {}
  7.0.2: {}
  7.0.3: {}
  7.0.4: {}
  7.0.5: {}
  7.1.0: {}
  7.1.1: {}
  7.1.2: {}
  7.1.3: {}
  7.1.4: {}
  7.1.5: {}
  7.1.6: {}
  7.2.0: {}
  7.2.1: {}
  7.2.2: {}
  7.2.3: {}
  7.2.4: {}
  7.2.5: {}
  7.2.6: {}
  7.6.0: {}
  7.6.1: {}
  7.6.2: {}
  7.6.3: {}
  community: {}
  community-6.5.0: {}
  community-6.5.1: {}
  community-6.6.0: {}
  community-7.0.0: {}
  community-7.0.0-beta: {}
  community-7.0.1: {}
  community-7.0.2: {}
  community-7.1.0: {}
  community-7.1.1: {}
  community-7.2.0: {}
  community-7.2.1: {}
  community-7.2.2: {}
  community-7.2.4: {}
  community-7.6.0: {}
  community-7.6.1: {}
  community-7.6.2: {}
  enterprise: {}
  enterprise-6.0.1: {}
  enterprise-6.0.2: {}
  enterprise-6.0.3: {}
  enterprise-6.0.4: {}
  enterprise-6.0.5: {}
  enterprise-6.5.0: {}
  enterprise-6.5.1: {}
  enterprise-6.5.2: {}
  enterprise-6.6.0: {}
  enterprise-6.6.1: {}
  enterprise-6.6.2: {}
  enterprise-6.6.3: {}
  enterprise-6.6.4: {}
  enterprise-6.6.5: {}
  enterprise-6.6.6: {}
  enterprise-7.0.0: {}
  enterprise-7.0.0-beta: {}
  enterprise-7.0.1: {}
  enterprise-7.0.2: {}
  enterprise-7.0.3: {}
  enterprise-7.0.4: {}
  enterprise-7.0.5: {}
  enterprise-7.1.0: {}
  enterprise-7.1.1: {}
  enterprise-7.1.2: {}
  enterprise-7.1.3: {}
  enterprise-7.1.4: {}
  enterprise-7.1.5: {}
  enterprise-7.1.6: {}
  enterprise-7.2.0: {}
  enterprise-7.2.1: {}
  enterprise-7.2.2: {}
  enterprise-7.2.3: {}
  enterprise-7.2.4: {}
  enterprise-7.2.5: {}
  enterprise-7.2.6: {}
  enterprise-7.6.0: {}
  enterprise-7.6.1: {}
  enterprise-7.6.2: {}
  enterprise-7.6.3: {}
  latest: {}
Name: couchbase
