Blocks:
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: f49afec82b84319bcf5d3021a161b437973b00c8
  Tags:
  - "37"
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: 7be687ad846a04a1779152e9fe40bc380549ba58
  Tags:
  - "38"
  - latest
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: 30d3a14457213b49f5be3f6cd6f9924de0a9d32e
  Tags:
  - "39"
  - rawhide
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: a08e597f3f6b6525b4a9aa4436555087cdd11189
  Tags:
  - "36"
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: 493d6eda2434bfdac64d61016aa6b9dc33cf4bc5
  Tags:
  - "35"
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  - arm32v7
  Directory: ""
  GitCommit: 8adf82f023696a50cf9016a3611e3fe75c7e2cfc
  Tags:
  - "34"
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  - arm32v7
  Directory: ""
  GitCommit: cec7e68b76f504a1310ba12ce6e4a8d6fe2b4660
  Tags:
  - "33"
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  - arm32v7
  Directory: ""
  GitCommit: ddec1000ce5ba6f6d48b83092baa0931c71463d2
  Tags:
  - "32"
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: 619a9d98269d556d030648ad486bb2c9f50f1768
  Tags:
  - "31"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  Directory: ""
  GitCommit: 035aa2a3970e4e10a9a6ae0b79322b882bfe50d3
  Tags:
  - "26"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  Directory: ""
  GitCommit: e1796b2753d5a5731de5915661e4639c4342b950
  Tags:
  - "27"
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  - arm32v7
  Directory: ""
  GitCommit: aa106da2be30656a7ccb32b96f6788031ce8656f
  Tags:
  - "28"
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  - arm32v7
  Directory: ""
  GitCommit: 4dbc2ccd3b4d52258981eaf12043025054d53023
  Tags:
  - "29"
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: ec092e1e4679f955d142b91f85ecd30a4f14a6ed
  Tags:
  - "30"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - s390x
  Directory: ""
  GitCommit: dee23ddc2f0c8bdfe8be0c37dd93ffec00cfa969
  Tags:
  - branched
- Architectures:
  - amd64
  Directory: ""
  GitCommit: d5dd6eb44f0651788edb6f81a5537c09b07022c4
  Tags:
  - modular
  - 26-modular
- Architectures:
  - amd64
  - arm32v7
  Directory: ""
  GitCommit: 2dc7762f57aac299ea93a58eb386bf1a9b31356f
  Tags:
  - "25"
- Architectures: null
  Directory: ""
  GitCommit: f3726622b5012c1f374bf9f596616eab3cd4988c
  Tags:
  - "24"
- Architectures: null
  Directory: ""
  GitCommit: ec63b8db44c2d8c97e29faeb55955ca25bd9076e
  Tags:
  - "23"
- Architectures: null
  Directory: ""
  GitCommit: bccd42bf4e9102ef10eff372488167948fdd0430
  Tags:
  - "22"
- Architectures: null
  Directory: ""
  GitCommit: e32493b9601c3535cd6e0d0a8ff61d8fa95afb83
  Tags:
  - "21"
- Architectures: null
  Directory: ""
  GitCommit: 10ada29063147fde9e39190f4c2344b6e6e659e6
  Tags:
  - "20"
  - heisenbug
- Architectures:
  - amd64
  Directory: ""
  GitCommit: d5dd6eb44f0651788edb6f81a5537c09b07022c4
  Tags:
  - latest-modular
GitRepo: https://github.com/fedora-cloud/docker-brew-fedora.git
KnownTags:
  "20": {}
  "21": {}
  "22": {}
  "23": {}
  "24": {}
  "25": {}
  "26": {}
  26-modular: {}
  "27": {}
  "28": {}
  "29": {}
  "30": {}
  "31": {}
  "32": {}
  "33": {}
  "34": {}
  "35": {}
  "36": {}
  "37": {}
  "38": {}
  "39": {}
  branched: {}
  heisenbug: {}
  latest: {}
  latest-modular: {}
  modular: {}
  rawhide: {}
Name: fedora
