Blocks:
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: f49afec82b84319bcf5d3021a161b437973b00c8
  Tags:
  - "37"
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: 7be687ad846a04a1779152e9fe40bc380549ba58
  Tags:
  - "38"
  - latest
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: 30d3a14457213b49f5be3f6cd6f9924de0a9d32e
  Tags:
  - "39"
  - rawhide
GitRepo: https://github.com/fedora-cloud/docker-brew-fedora.git
KnownTags:
  "37": {}
  "38": {}
  "39": {}
  latest: {}
  rawhide: {}
Name: fedora
