Blocks:
- Architectures: null
  Directory: 1.2.4
  GitCommit: 14c749848c8ff7c955f2b29c57e327ae80fbbb7e
  Tags:
  - 1.2.4-temurin
  - 1.2-temurin
- Architectures: null
  Directory: 2.4.0
  GitCommit: a81f9686e8a13dbf428864482f2d0bba50e9c414
  Tags:
  - 2.4.0-temurin
  - 2.4-temurin
  - latest
GitRepo: https://github.com/31z4/storm-docker.git
KnownTags:
  1.2-temurin: {}
  1.2.4-temurin: {}
  2.4-temurin: {}
  2.4.0-temurin: {}
  latest: {}
Name: storm
