Blocks:
- Architectures: null
  Directory: 2.8.3
  File: ""
  GitCommit: 78e73fe01431a2b3fe35071fcaaaa1726a0e3736
  Tags:
  - 2.8.3-jre17
  - 2.8-jre17
  - 2.8.3
  - "2.8"
  - latest
- Architectures: null
  Directory: 2.8.3-jre21
  File: ""
  GitCommit: 78e73fe01431a2b3fe35071fcaaaa1726a0e3736
  Tags:
  - 2.8.3-jre21
  - 2.8-jre21
- Architectures: null
  Directory: 2.8.2
  File: ""
  GitCommit: 8f90c62992f17324add5537a121c0f60636e8171
  Tags:
  - 2.8.2-jre17
  - 2.8.2
- Architectures: null
  Directory: 2.8.2-jre21
  File: ""
  GitCommit: 8f90c62992f17324add5537a121c0f60636e8171
  Tags:
  - 2.8.2-jre21
- Architectures: null
  Directory: 2.8.1
  File: ""
  GitCommit: c81967cfcd43d2535f097f0c68eacdbf4ec778cf
  Tags:
  - 2.8.1-jre17
  - 2.8.1
- Architectures: null
  Directory: 2.8.1-jre21
  File: ""
  GitCommit: c81967cfcd43d2535f097f0c68eacdbf4ec778cf
  Tags:
  - 2.8.1-jre21
- Architectures: null
  Directory: 2.8.0
  File: ""
  GitCommit: fefacef2f400d8f437675b11e08bc6098a91c188
  Tags:
  - 2.8.0
- Architectures: null
  Directory: 2.8.0
  File: ""
  GitCommit: fefacef2f400d8f437675b11e08bc6098a91c188
  Tags:
  - 2.8.0-jre17
- Architectures: null
  Directory: 2.7.1
  File: ""
  GitCommit: 59ee14a11bd6d890c8ff3ed7a327b8464ab79f3a
  Tags:
  - 2.7.1
  - "2.7"
- Architectures: null
  Directory: 2.7.1-jre17
  File: ""
  GitCommit: 59ee14a11bd6d890c8ff3ed7a327b8464ab79f3a
  Tags:
  - 2.7.1-jre17
  - 2.7-jre17
- Architectures: null
  Directory: 2.7.0
  File: ""
  GitCommit: 4980d0d2b0d40c525f88622adf1547a20054adb6
  Tags:
  - 2.7.0
- Architectures: null
  Directory: 2.7.0-jre17
  File: ""
  GitCommit: 4980d0d2b0d40c525f88622adf1547a20054adb6
  Tags:
  - 2.7.0-jre17
- Architectures: null
  Directory: 2.6.4
  File: ""
  GitCommit: 3d67ed2cbc3d15b210840745292d53c0ece4f63c
  Tags:
  - 2.6.4
  - "2.6"
- Architectures: null
  Directory: 2.6.4-jre17
  File: ""
  GitCommit: 3d67ed2cbc3d15b210840745292d53c0ece4f63c
  Tags:
  - 2.6.4-jre17
  - 2.6-jre17
- Architectures: null
  Directory: 2.6.3
  File: ""
  GitCommit: adb8344286f15872ecebb2796ad7ee0791f09883
  Tags:
  - 2.6.3
- Architectures: null
  Directory: 2.6.3-jre17
  File: ""
  GitCommit: e7117105eb207e0ffad071d429e7c3de8c0864ce
  Tags:
  - 2.6.3-jre17
- Architectures: null
  Directory: 2.6.2
  File: ""
  GitCommit: d8c821ffb599be733400c98cc10fe4c05966b552
  Tags:
  - 2.6.2
- Architectures: null
  Directory: 2.6.2-jre17
  File: ""
  GitCommit: 31209f0cde237834a3602a382e69a6caa6bdcffc
  Tags:
  - 2.6.2-jre17
- Architectures: null
  Directory: 2.6.1
  File: ""
  GitCommit: d1f8af26ccf800531cc773a39fac9e30efa94bca
  Tags:
  - 2.6.1
- Architectures: null
  Directory: 2.6.0
  File: ""
  GitCommit: 965de975c7af0ed35174b4276971c52965b0fa0b
  Tags:
  - 2.6.0
- Architectures: null
  Directory: 1.2.4
  File: ""
  GitCommit: 14c749848c8ff7c955f2b29c57e327ae80fbbb7e
  Tags:
  - 1.2.4-temurin
  - 1.2-temurin
- Architectures: null
  Directory: 2.4.0
  File: ""
  GitCommit: a81f9686e8a13dbf428864482f2d0bba50e9c414
  Tags:
  - 2.4.0-temurin
  - 2.4-temurin
- Architectures: null
  Directory: 2.5.0
  File: ""
  GitCommit: 8e162f994d36bfae7f13a32ceb4193d185b9a89e
  Tags:
  - 2.5.0
  - "2.5"
- Architectures: null
  Directory: 1.2.4
  File: ""
  GitCommit: f72658afa5e9c4ee4d4d5ef5cf9b32b226d0ed19
  Tags:
  - 1.2.4
  - "1.2"
- Architectures: null
  Directory: 2.4.0
  File: ""
  GitCommit: f72658afa5e9c4ee4d4d5ef5cf9b32b226d0ed19
  Tags:
  - 2.4.0
  - "2.4"
- Architectures: null
  Directory: 2.3.0
  File: ""
  GitCommit: a80831113011cf40a53e91e98790e99ad5a76280
  Tags:
  - 2.3.0
  - "2.3"
- Architectures: null
  Directory: 1.1.3
  File: ""
  GitCommit: 664a7f4730f58be00fd7fe0526d2c13180107c6f
  Tags:
  - 1.1.3
  - "1.1"
- Architectures: null
  Directory: 1.2.3
  File: ""
  GitCommit: 664a7f4730f58be00fd7fe0526d2c13180107c6f
  Tags:
  - 1.2.3
- Architectures: null
  Directory: 2.2.0
  File: ""
  GitCommit: 9eae4ab08d30cfab29c784b4d9e7d1c187fa0348
  Tags:
  - 2.2.0
  - "2.2"
- Architectures: null
  Directory: 2.1.0
  File: ""
  GitCommit: 664a7f4730f58be00fd7fe0526d2c13180107c6f
  Tags:
  - 2.1.0
  - "2.1"
- Architectures: null
  Directory: 2.0.0
  File: ""
  GitCommit: f98a59dfc28739e8aa0b9ede44f069ef21e077a4
  Tags:
  - 2.0.0
  - "2.0"
- Architectures: null
  Directory: 1.2.2
  File: ""
  GitCommit: 2cdf3784eb167e112e21deca4d4be91eb997b672
  Tags:
  - 1.2.2
- Architectures: null
  Directory: 1.0.6
  File: ""
  GitCommit: 9986213e09356e2d5230e6af9338052ce858b224
  Tags:
  - 1.0.6
  - "1.0"
- Architectures: null
  Directory: 1.1.2
  File: ""
  GitCommit: 9986213e09356e2d5230e6af9338052ce858b224
  Tags:
  - 1.1.2
- Architectures: null
  Directory: 1.2.1
  File: ""
  GitCommit: 9b5187aea15c0e21d082b1f041cdc2f7a892dc26
  Tags:
  - 1.2.1
- Architectures: null
  Directory: 1.2.0
  File: ""
  GitCommit: 9986213e09356e2d5230e6af9338052ce858b224
  Tags:
  - 1.2.0
- Architectures: null
  Directory: 0.9.7
  File: ""
  GitCommit: 6e94e11977556f0f4a99633b1f835f13d20c1e30
  Tags:
  - 0.9.7
  - "0.9"
- Architectures: null
  Directory: 0.10.2
  File: ""
  GitCommit: 6e94e11977556f0f4a99633b1f835f13d20c1e30
  Tags:
  - 0.10.2
  - "0.10"
- Architectures: null
  Directory: 1.0.5
  File: ""
  GitCommit: 60316c9351be7dedd39cbcc308dc1fe5c00e44a5
  Tags:
  - 1.0.5
- Architectures: null
  Directory: 1.1.1
  File: ""
  GitCommit: 35207c57594856c661adcea5063584eb22534ddb
  Tags:
  - 1.1.1
- Architectures: null
  Directory: 1.0.3
  File: ""
  GitCommit: 35207c57594856c661adcea5063584eb22534ddb
  Tags:
  - 1.0.3
- Architectures: null
  Directory: 1.1.0
  File: ""
  GitCommit: e20c50c9704ed64765ba80e6964df4c0c189be3e
  Tags:
  - 1.1.0
- Architectures: null
  Directory: 1.0.2
  File: ""
  GitCommit: 93746fa3936afb3751565860632d3e49d53e9b0e
  Tags:
  - 1.0.2
GitRepo: https://github.com/apache/storm-docker.git
KnownTags:
  "0.9": {}
  0.9.7: {}
  "0.10": {}
  0.10.2: {}
  "1.0": {}
  1.0.2: {}
  1.0.3: {}
  1.0.5: {}
  1.0.6: {}
  "1.1": {}
  1.1.0: {}
  1.1.1: {}
  1.1.2: {}
  1.1.3: {}
  "1.2": {}
  1.2-temurin: {}
  1.2.0: {}
  1.2.1: {}
  1.2.2: {}
  1.2.3: {}
  1.2.4: {}
  1.2.4-temurin: {}
  "2.0": {}
  2.0.0: {}
  "2.1": {}
  2.1.0: {}
  "2.2": {}
  2.2.0: {}
  "2.3": {}
  2.3.0: {}
  "2.4": {}
  2.4-temurin: {}
  2.4.0: {}
  2.4.0-temurin: {}
  "2.5": {}
  2.5.0: {}
  "2.6": {}
  2.6-jre17: {}
  2.6.0: {}
  2.6.1: {}
  2.6.2: {}
  2.6.2-jre17: {}
  2.6.3: {}
  2.6.3-jre17: {}
  2.6.4: {}
  2.6.4-jre17: {}
  "2.7": {}
  2.7-jre17: {}
  2.7.0: {}
  2.7.0-jre17: {}
  2.7.1: {}
  2.7.1-jre17: {}
  "2.8": {}
  2.8-jre17: {}
  2.8-jre21: {}
  2.8.0: {}
  2.8.0-jre17: {}
  2.8.1: {}
  2.8.1-jre17: {}
  2.8.1-jre21: {}
  2.8.2: {}
  2.8.2-jre17: {}
  2.8.2-jre21: {}
  2.8.3: {}
  2.8.3-jre17: {}
  2.8.3-jre21: {}
  latest: {}
Name: storm
