Blocks:
- Architectures:
  - arm32v6
  - arm64v8
  - amd64
  Directory: develop
  GitCommit: 80fba087712325adc72a96265d4984c6760aff1a
  Tags:
  - develop
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  Directory: "1.9"
  GitCommit: 80fba087712325adc72a96265d4984c6760aff1a
  Tags:
  - "1.9"
  - 1.9.5
  - stable
  - latest
GitRepo: https://github.com/eggheads/eggdrop-docker.git
KnownTags:
  "1.9": {}
  1.9.5: {}
  develop: {}
  latest: {}
  stable: {}
Name: eggdrop
