Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.12-rc/bookworm
  GitCommit: 3889ee887a25814ba59c379f0260e86d0394c41e
  Tags:
  - 3.12.0b3-bookworm
  - 3.12-rc-bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.12-rc/slim-bookworm
  GitCommit: 3889ee887a25814ba59c379f0260e86d0394c41e
  Tags:
  - 3.12.0b3-slim-bookworm
  - 3.12-rc-slim-bookworm
  - 3.12.0b3-slim
  - 3.12-rc-slim
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.12-rc/bullseye
  GitCommit: 3889ee887a25814ba59c379f0260e86d0394c41e
  Tags:
  - 3.12.0b3-bullseye
  - 3.12-rc-bullseye
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.12-rc/slim-bullseye
  GitCommit: 3889ee887a25814ba59c379f0260e86d0394c41e
  Tags:
  - 3.12.0b3-slim-bullseye
  - 3.12-rc-slim-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.12-rc/alpine3.18
  GitCommit: 3889ee887a25814ba59c379f0260e86d0394c41e
  Tags:
  - 3.12.0b3-alpine3.18
  - 3.12-rc-alpine3.18
  - 3.12.0b3-alpine
  - 3.12-rc-alpine
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.12-rc/alpine3.17
  GitCommit: 3889ee887a25814ba59c379f0260e86d0394c41e
  Tags:
  - 3.12.0b3-alpine3.17
  - 3.12-rc-alpine3.17
- Architectures:
  - windows-amd64
  Directory: 3.12-rc/windows/windowsservercore-ltsc2022
  GitCommit: 3889ee887a25814ba59c379f0260e86d0394c41e
  Tags:
  - 3.12.0b3-windowsservercore-ltsc2022
  - 3.12-rc-windowsservercore-ltsc2022
- Architectures:
  - windows-amd64
  Directory: 3.12-rc/windows/windowsservercore-1809
  GitCommit: 3889ee887a25814ba59c379f0260e86d0394c41e
  Tags:
  - 3.12.0b3-windowsservercore-1809
  - 3.12-rc-windowsservercore-1809
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.11/bookworm
  GitCommit: 5d908b0477c003712550c84ac4d133367b912f78
  Tags:
  - 3.11.4-bookworm
  - 3.11-bookworm
  - 3-bookworm
  - bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.11/slim-bookworm
  GitCommit: 5d908b0477c003712550c84ac4d133367b912f78
  Tags:
  - 3.11.4-slim-bookworm
  - 3.11-slim-bookworm
  - 3-slim-bookworm
  - slim-bookworm
  - 3.11.4-slim
  - 3.11-slim
  - 3-slim
  - slim
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.11/bullseye
  GitCommit: b744d9708a2fb8e2295198ef146341c415e9bc28
  Tags:
  - 3.11.4-bullseye
  - 3.11-bullseye
  - 3-bullseye
  - bullseye
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.11/slim-bullseye
  GitCommit: 5d908b0477c003712550c84ac4d133367b912f78
  Tags:
  - 3.11.4-slim-bullseye
  - 3.11-slim-bullseye
  - 3-slim-bullseye
  - slim-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.11/alpine3.18
  GitCommit: b744d9708a2fb8e2295198ef146341c415e9bc28
  Tags:
  - 3.11.4-alpine3.18
  - 3.11-alpine3.18
  - 3-alpine3.18
  - alpine3.18
  - 3.11.4-alpine
  - 3.11-alpine
  - 3-alpine
  - alpine
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.11/alpine3.17
  GitCommit: b744d9708a2fb8e2295198ef146341c415e9bc28
  Tags:
  - 3.11.4-alpine3.17
  - 3.11-alpine3.17
  - 3-alpine3.17
  - alpine3.17
- Architectures:
  - windows-amd64
  Directory: 3.11/windows/windowsservercore-ltsc2022
  GitCommit: b744d9708a2fb8e2295198ef146341c415e9bc28
  Tags:
  - 3.11.4-windowsservercore-ltsc2022
  - 3.11-windowsservercore-ltsc2022
  - 3-windowsservercore-ltsc2022
  - windowsservercore-ltsc2022
- Architectures:
  - windows-amd64
  Directory: 3.11/windows/windowsservercore-1809
  GitCommit: b744d9708a2fb8e2295198ef146341c415e9bc28
  Tags:
  - 3.11.4-windowsservercore-1809
  - 3.11-windowsservercore-1809
  - 3-windowsservercore-1809
  - windowsservercore-1809
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.10/bookworm
  GitCommit: 5d908b0477c003712550c84ac4d133367b912f78
  Tags:
  - 3.10.12-bookworm
  - 3.10-bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.10/slim-bookworm
  GitCommit: 5d908b0477c003712550c84ac4d133367b912f78
  Tags:
  - 3.10.12-slim-bookworm
  - 3.10-slim-bookworm
  - 3.10.12-slim
  - 3.10-slim
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.10/bullseye
  GitCommit: 8f971d595fff0cc134370916a069bfedc5887308
  Tags:
  - 3.10.12-bullseye
  - 3.10-bullseye
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.10/slim-bullseye
  GitCommit: 5d908b0477c003712550c84ac4d133367b912f78
  Tags:
  - 3.10.12-slim-bullseye
  - 3.10-slim-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.10/alpine3.18
  GitCommit: 8f971d595fff0cc134370916a069bfedc5887308
  Tags:
  - 3.10.12-alpine3.18
  - 3.10-alpine3.18
  - 3.10.12-alpine
  - 3.10-alpine
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.10/alpine3.17
  GitCommit: 8f971d595fff0cc134370916a069bfedc5887308
  Tags:
  - 3.10.12-alpine3.17
  - 3.10-alpine3.17
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 3.9/bookworm
  GitCommit: 5d908b0477c003712550c84ac4d133367b912f78
  Tags:
  - 3.9.17-bookworm
  - 3.9-bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 3.9/slim-bookworm
  GitCommit: 5d908b0477c003712550c84ac4d133367b912f78
  Tags:
  - 3.9.17-slim-bookworm
  - 3.9-slim-bookworm
  - 3.9.17-slim
  - 3.9-slim
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 3.9/bullseye
  GitCommit: 40bd50cfcf3551fc506b45e47003db9c52c5fec7
  Tags:
  - 3.9.17-bullseye
  - 3.9-bullseye
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 3.9/slim-bullseye
  GitCommit: 5d908b0477c003712550c84ac4d133367b912f78
  Tags:
  - 3.9.17-slim-bullseye
  - 3.9-slim-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.9/alpine3.18
  GitCommit: 40bd50cfcf3551fc506b45e47003db9c52c5fec7
  Tags:
  - 3.9.17-alpine3.18
  - 3.9-alpine3.18
  - 3.9.17-alpine
  - 3.9-alpine
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.9/alpine3.17
  GitCommit: 40bd50cfcf3551fc506b45e47003db9c52c5fec7
  Tags:
  - 3.9.17-alpine3.17
  - 3.9-alpine3.17
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 3.8/bookworm
  GitCommit: 5d908b0477c003712550c84ac4d133367b912f78
  Tags:
  - 3.8.17-bookworm
  - 3.8-bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 3.8/slim-bookworm
  GitCommit: 5d908b0477c003712550c84ac4d133367b912f78
  Tags:
  - 3.8.17-slim-bookworm
  - 3.8-slim-bookworm
  - 3.8.17-slim
  - 3.8-slim
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 3.8/bullseye
  GitCommit: db8907eb3797ad147b59759aa1e6d7708a3fc2ce
  Tags:
  - 3.8.17-bullseye
  - 3.8-bullseye
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 3.8/slim-bullseye
  GitCommit: 5d908b0477c003712550c84ac4d133367b912f78
  Tags:
  - 3.8.17-slim-bullseye
  - 3.8-slim-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.8/alpine3.18
  GitCommit: db8907eb3797ad147b59759aa1e6d7708a3fc2ce
  Tags:
  - 3.8.17-alpine3.18
  - 3.8-alpine3.18
  - 3.8.17-alpine
  - 3.8-alpine
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.8/alpine3.17
  GitCommit: db8907eb3797ad147b59759aa1e6d7708a3fc2ce
  Tags:
  - 3.8.17-alpine3.17
  - 3.8-alpine3.17
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 3.7/bookworm
  GitCommit: 5d908b0477c003712550c84ac4d133367b912f78
  Tags:
  - 3.7.17-bookworm
  - 3.7-bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 3.7/slim-bookworm
  GitCommit: 5d908b0477c003712550c84ac4d133367b912f78
  Tags:
  - 3.7.17-slim-bookworm
  - 3.7-slim-bookworm
  - 3.7.17-slim
  - 3.7-slim
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 3.7/bullseye
  GitCommit: 00b80a3dfc595e9c58ec52cc9ae8349cf10767a4
  Tags:
  - 3.7.17-bullseye
  - 3.7-bullseye
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 3.7/slim-bullseye
  GitCommit: 5d908b0477c003712550c84ac4d133367b912f78
  Tags:
  - 3.7.17-slim-bullseye
  - 3.7-slim-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.7/alpine3.18
  GitCommit: 00b80a3dfc595e9c58ec52cc9ae8349cf10767a4
  Tags:
  - 3.7.17-alpine3.18
  - 3.7-alpine3.18
  - 3.7.17-alpine
  - 3.7-alpine
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 3.7/alpine3.17
  GitCommit: 00b80a3dfc595e9c58ec52cc9ae8349cf10767a4
  Tags:
  - 3.7.17-alpine3.17
  - 3.7-alpine3.17
GitRepo: https://github.com/docker-library/python.git
KnownTags:
  3-alpine: {}
  3-alpine3.17: {}
  3-alpine3.18: {}
  3-bookworm: {}
  3-bullseye: {}
  3-slim: {}
  3-slim-bookworm: {}
  3-slim-bullseye: {}
  3-windowsservercore-1809: {}
  3-windowsservercore-ltsc2022: {}
  3.7-alpine: {}
  3.7-alpine3.17: {}
  3.7-alpine3.18: {}
  3.7-bookworm: {}
  3.7-bullseye: {}
  3.7-slim: {}
  3.7-slim-bookworm: {}
  3.7-slim-bullseye: {}
  3.7.17-alpine: {}
  3.7.17-alpine3.17: {}
  3.7.17-alpine3.18: {}
  3.7.17-bookworm: {}
  3.7.17-bullseye: {}
  3.7.17-slim: {}
  3.7.17-slim-bookworm: {}
  3.7.17-slim-bullseye: {}
  3.8-alpine: {}
  3.8-alpine3.17: {}
  3.8-alpine3.18: {}
  3.8-bookworm: {}
  3.8-bullseye: {}
  3.8-slim: {}
  3.8-slim-bookworm: {}
  3.8-slim-bullseye: {}
  3.8.17-alpine: {}
  3.8.17-alpine3.17: {}
  3.8.17-alpine3.18: {}
  3.8.17-bookworm: {}
  3.8.17-bullseye: {}
  3.8.17-slim: {}
  3.8.17-slim-bookworm: {}
  3.8.17-slim-bullseye: {}
  3.9-alpine: {}
  3.9-alpine3.17: {}
  3.9-alpine3.18: {}
  3.9-bookworm: {}
  3.9-bullseye: {}
  3.9-slim: {}
  3.9-slim-bookworm: {}
  3.9-slim-bullseye: {}
  3.9.17-alpine: {}
  3.9.17-alpine3.17: {}
  3.9.17-alpine3.18: {}
  3.9.17-bookworm: {}
  3.9.17-bullseye: {}
  3.9.17-slim: {}
  3.9.17-slim-bookworm: {}
  3.9.17-slim-bullseye: {}
  3.10-alpine: {}
  3.10-alpine3.17: {}
  3.10-alpine3.18: {}
  3.10-bookworm: {}
  3.10-bullseye: {}
  3.10-slim: {}
  3.10-slim-bookworm: {}
  3.10-slim-bullseye: {}
  3.10.12-alpine: {}
  3.10.12-alpine3.17: {}
  3.10.12-alpine3.18: {}
  3.10.12-bookworm: {}
  3.10.12-bullseye: {}
  3.10.12-slim: {}
  3.10.12-slim-bookworm: {}
  3.10.12-slim-bullseye: {}
  3.11-alpine: {}
  3.11-alpine3.17: {}
  3.11-alpine3.18: {}
  3.11-bookworm: {}
  3.11-bullseye: {}
  3.11-slim: {}
  3.11-slim-bookworm: {}
  3.11-slim-bullseye: {}
  3.11-windowsservercore-1809: {}
  3.11-windowsservercore-ltsc2022: {}
  3.11.4-alpine: {}
  3.11.4-alpine3.17: {}
  3.11.4-alpine3.18: {}
  3.11.4-bookworm: {}
  3.11.4-bullseye: {}
  3.11.4-slim: {}
  3.11.4-slim-bookworm: {}
  3.11.4-slim-bullseye: {}
  3.11.4-windowsservercore-1809: {}
  3.11.4-windowsservercore-ltsc2022: {}
  3.12-rc-alpine: {}
  3.12-rc-alpine3.17: {}
  3.12-rc-alpine3.18: {}
  3.12-rc-bookworm: {}
  3.12-rc-bullseye: {}
  3.12-rc-slim: {}
  3.12-rc-slim-bookworm: {}
  3.12-rc-slim-bullseye: {}
  3.12-rc-windowsservercore-1809: {}
  3.12-rc-windowsservercore-ltsc2022: {}
  3.12.0b3-alpine: {}
  3.12.0b3-alpine3.17: {}
  3.12.0b3-alpine3.18: {}
  3.12.0b3-bookworm: {}
  3.12.0b3-bullseye: {}
  3.12.0b3-slim: {}
  3.12.0b3-slim-bookworm: {}
  3.12.0b3-slim-bullseye: {}
  3.12.0b3-windowsservercore-1809: {}
  3.12.0b3-windowsservercore-ltsc2022: {}
  alpine: {}
  alpine3.17: {}
  alpine3.18: {}
  bookworm: {}
  bullseye: {}
  slim: {}
  slim-bookworm: {}
  slim-bullseye: {}
  windowsservercore-1809: {}
  windowsservercore-ltsc2022: {}
Name: python
