Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: ros/melodic/ubuntu/bionic/ros-core
  GitCommit: 3f4fbca923d80f834f3a89b5960bad5582652519
  Tags:
  - melodic-ros-core
  - melodic-ros-core-bionic
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: ros/melodic/ubuntu/bionic/ros-base
  GitCommit: df19ab7d5993d3b78a908362cdcd1479a8e78b35
  Tags:
  - melodic-ros-base
  - melodic-ros-base-bionic
  - melodic
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: ros/melodic/ubuntu/bionic/robot
  GitCommit: df19ab7d5993d3b78a908362cdcd1479a8e78b35
  Tags:
  - melodic-robot
  - melodic-robot-bionic
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: ros/melodic/ubuntu/bionic/perception
  GitCommit: df19ab7d5993d3b78a908362cdcd1479a8e78b35
  Tags:
  - melodic-perception
  - melodic-perception-bionic
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: ros/noetic/ubuntu/focal/ros-core
  GitCommit: 3f4fbca923d80f834f3a89b5960bad5582652519
  Tags:
  - noetic-ros-core
  - noetic-ros-core-focal
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: ros/noetic/ubuntu/focal/ros-base
  GitCommit: df19ab7d5993d3b78a908362cdcd1479a8e78b35
  Tags:
  - noetic-ros-base
  - noetic-ros-base-focal
  - noetic
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: ros/noetic/ubuntu/focal/robot
  GitCommit: df19ab7d5993d3b78a908362cdcd1479a8e78b35
  Tags:
  - noetic-robot
  - noetic-robot-focal
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: ros/noetic/ubuntu/focal/perception
  GitCommit: df19ab7d5993d3b78a908362cdcd1479a8e78b35
  Tags:
  - noetic-perception
  - noetic-perception-focal
- Architectures:
  - amd64
  - arm64v8
  Directory: ros/noetic/debian/buster/ros-core
  GitCommit: 3f4fbca923d80f834f3a89b5960bad5582652519
  Tags:
  - noetic-ros-core-buster
- Architectures:
  - amd64
  - arm64v8
  Directory: ros/noetic/debian/buster/ros-base
  GitCommit: df19ab7d5993d3b78a908362cdcd1479a8e78b35
  Tags:
  - noetic-ros-base-buster
- Architectures:
  - amd64
  - arm64v8
  Directory: ros/noetic/debian/buster/robot
  GitCommit: df19ab7d5993d3b78a908362cdcd1479a8e78b35
  Tags:
  - noetic-robot-buster
- Architectures:
  - amd64
  - arm64v8
  Directory: ros/noetic/debian/buster/perception
  GitCommit: df19ab7d5993d3b78a908362cdcd1479a8e78b35
  Tags:
  - noetic-perception-buster
- Architectures:
  - amd64
  - arm64v8
  Directory: ros/foxy/ubuntu/focal/ros-core
  GitCommit: 3f4fbca923d80f834f3a89b5960bad5582652519
  Tags:
  - foxy-ros-core
  - foxy-ros-core-focal
- Architectures:
  - amd64
  - arm64v8
  Directory: ros/foxy/ubuntu/focal/ros-base
  GitCommit: df19ab7d5993d3b78a908362cdcd1479a8e78b35
  Tags:
  - foxy-ros-base
  - foxy-ros-base-focal
  - foxy
- Architectures:
  - amd64
  - arm64v8
  Directory: ros/foxy/ubuntu/focal/ros1-bridge
  GitCommit: c40ef6e5116c88f44e9ef3694614c1e8a60725a0
  Tags:
  - foxy-ros1-bridge
  - foxy-ros1-bridge-focal
- Architectures:
  - amd64
  - arm64v8
  Directory: ros/humble/ubuntu/jammy/ros-core
  GitCommit: 3f4fbca923d80f834f3a89b5960bad5582652519
  Tags:
  - humble-ros-core
  - humble-ros-core-jammy
- Architectures:
  - amd64
  - arm64v8
  Directory: ros/humble/ubuntu/jammy/ros-base
  GitCommit: 20e3ba685bb353a3c00be9ba01c1b7a6823c9472
  Tags:
  - humble-ros-base
  - humble-ros-base-jammy
  - humble
  - latest
- Architectures:
  - amd64
  - arm64v8
  Directory: ros/humble/ubuntu/jammy/perception
  GitCommit: 20d40c96b426b8956dec203e236abff2ec29b188
  Tags:
  - humble-perception
  - humble-perception-jammy
- Architectures:
  - amd64
  - arm64v8
  Directory: ros/iron/ubuntu/jammy/ros-core
  GitCommit: bca53bf4c09d771be3ff735da4157203b53ebc2b
  Tags:
  - iron-ros-core
  - iron-ros-core-jammy
- Architectures:
  - amd64
  - arm64v8
  Directory: ros/iron/ubuntu/jammy/ros-base
  GitCommit: bca53bf4c09d771be3ff735da4157203b53ebc2b
  Tags:
  - iron-ros-base
  - iron-ros-base-jammy
  - iron
- Architectures:
  - amd64
  - arm64v8
  Directory: ros/iron/ubuntu/jammy/perception
  GitCommit: bca53bf4c09d771be3ff735da4157203b53ebc2b
  Tags:
  - iron-perception
  - iron-perception-jammy
- Architectures:
  - amd64
  - arm64v8
  Directory: ros/rolling/ubuntu/jammy/ros-core
  GitCommit: 73c1bf4c30e97d5d3d7c2aaddc8137cae2411409
  Tags:
  - rolling-ros-core
  - rolling-ros-core-jammy
- Architectures:
  - amd64
  - arm64v8
  Directory: ros/rolling/ubuntu/jammy/ros-base
  GitCommit: 73c1bf4c30e97d5d3d7c2aaddc8137cae2411409
  Tags:
  - rolling-ros-base
  - rolling-ros-base-jammy
  - rolling
- Architectures:
  - amd64
  - arm64v8
  Directory: ros/rolling/ubuntu/jammy/perception
  GitCommit: 73c1bf4c30e97d5d3d7c2aaddc8137cae2411409
  Tags:
  - rolling-perception
  - rolling-perception-jammy
GitRepo: https://github.com/osrf/docker_images.git
KnownTags:
  foxy: {}
  foxy-ros-base: {}
  foxy-ros-base-focal: {}
  foxy-ros-core: {}
  foxy-ros-core-focal: {}
  foxy-ros1-bridge: {}
  foxy-ros1-bridge-focal: {}
  humble: {}
  humble-perception: {}
  humble-perception-jammy: {}
  humble-ros-base: {}
  humble-ros-base-jammy: {}
  humble-ros-core: {}
  humble-ros-core-jammy: {}
  iron: {}
  iron-perception: {}
  iron-perception-jammy: {}
  iron-ros-base: {}
  iron-ros-base-jammy: {}
  iron-ros-core: {}
  iron-ros-core-jammy: {}
  latest: {}
  melodic: {}
  melodic-perception: {}
  melodic-perception-bionic: {}
  melodic-robot: {}
  melodic-robot-bionic: {}
  melodic-ros-base: {}
  melodic-ros-base-bionic: {}
  melodic-ros-core: {}
  melodic-ros-core-bionic: {}
  noetic: {}
  noetic-perception: {}
  noetic-perception-buster: {}
  noetic-perception-focal: {}
  noetic-robot: {}
  noetic-robot-buster: {}
  noetic-robot-focal: {}
  noetic-ros-base: {}
  noetic-ros-base-buster: {}
  noetic-ros-base-focal: {}
  noetic-ros-core: {}
  noetic-ros-core-buster: {}
  noetic-ros-core-focal: {}
  rolling: {}
  rolling-perception: {}
  rolling-perception-jammy: {}
  rolling-ros-base: {}
  rolling-ros-base-jammy: {}
  rolling-ros-core: {}
  rolling-ros-core-jammy: {}
Name: ros
