Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: 9/community
  GitCommit: ""
  Tags:
  - 9.9.1-community
  - 9.9-community
  - 9-community
  - lts
  - lts-community
- Architectures:
  - amd64
  - arm64v8
  Directory: 9/developer
  GitCommit: ""
  Tags:
  - 9.9.1-developer
  - 9.9-developer
  - 9-developer
  - lts-developer
- Architectures:
  - amd64
  - arm64v8
  Directory: 9/enterprise
  GitCommit: ""
  Tags:
  - 9.9.1-enterprise
  - 9.9-enterprise
  - 9-enterprise
  - lts-enterprise
- Architectures:
  - amd64
  - arm64v8
  Directory: 9/datacenter/app
  GitCommit: ""
  Tags:
  - 9.9.1-datacenter-app
  - 9.9-datacenter-app
  - 9-datacenter-app
  - lts-datacenter-app
- Architectures:
  - amd64
  - arm64v8
  Directory: 9/datacenter/search
  GitCommit: ""
  Tags:
  - 9.9.1-datacenter-search
  - 9.9-datacenter-search
  - 9-datacenter-search
  - lts-datacenter-search
- Architectures:
  - amd64
  - arm64v8
  Directory: 10/community
  GitCommit: ""
  Tags:
  - 10.1.0-community
  - 10.1-community
  - 10-community
  - community
  - latest
- Architectures:
  - amd64
  - arm64v8
  Directory: 10/developer
  GitCommit: ""
  Tags:
  - 10.1.0-developer
  - 10.1-developer
  - 10-developer
  - developer
- Architectures:
  - amd64
  - arm64v8
  Directory: 10/enterprise
  GitCommit: ""
  Tags:
  - 10.1.0-enterprise
  - 10.1-enterprise
  - 10-enterprise
  - enterprise
- Architectures:
  - amd64
  - arm64v8
  Directory: 10/datacenter/app
  GitCommit: ""
  Tags:
  - 10.1.0-datacenter-app
  - 10.1-datacenter-app
  - 10-datacenter-app
  - datacenter-app
- Architectures:
  - amd64
  - arm64v8
  Directory: 10/datacenter/search
  GitCommit: ""
  Tags:
  - 10.1.0-datacenter-search
  - 10.1-datacenter-search
  - 10-datacenter-search
  - datacenter-search
GitRepo: https://github.com/SonarSource/docker-sonarqube.git
KnownTags:
  9-community: {}
  9-datacenter-app: {}
  9-datacenter-search: {}
  9-developer: {}
  9-enterprise: {}
  9.9-community: {}
  9.9-datacenter-app: {}
  9.9-datacenter-search: {}
  9.9-developer: {}
  9.9-enterprise: {}
  9.9.1-community: {}
  9.9.1-datacenter-app: {}
  9.9.1-datacenter-search: {}
  9.9.1-developer: {}
  9.9.1-enterprise: {}
  10-community: {}
  10-datacenter-app: {}
  10-datacenter-search: {}
  10-developer: {}
  10-enterprise: {}
  10.1-community: {}
  10.1-datacenter-app: {}
  10.1-datacenter-search: {}
  10.1-developer: {}
  10.1-enterprise: {}
  10.1.0-community: {}
  10.1.0-datacenter-app: {}
  10.1.0-datacenter-search: {}
  10.1.0-developer: {}
  10.1.0-enterprise: {}
  community: {}
  datacenter-app: {}
  datacenter-search: {}
  developer: {}
  enterprise: {}
  latest: {}
  lts: {}
  lts-community: {}
  lts-datacenter-app: {}
  lts-datacenter-search: {}
  lts-developer: {}
  lts-enterprise: {}
Name: sonarqube
