Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 4.3/bullseye
  GitCommit: 4e55b2953c28c448f92aaf265168c1bf85b4867f
  Tags:
  - 4.3.1-bullseye
  - 4.3-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 4.3/buster
  GitCommit: 4e55b2953c28c448f92aaf265168c1bf85b4867f
  Tags:
  - 4.3.1-buster
  - 4.3-buster
- Architectures:
  - windows-amd64
  Directory: 4.3/windowsservercore-ltsc2022
  GitCommit: 1a4e5d4fbf207a4ed5a10db34e31826f4fc46c82
  Tags:
  - 4.3.1-windowsservercore-ltsc2022
  - 4.3-windowsservercore-ltsc2022
- Architectures:
  - windows-amd64
  Directory: 4.3/windowsservercore-1809
  GitCommit: 1a4e5d4fbf207a4ed5a10db34e31826f4fc46c82
  Tags:
  - 4.3.1-windowsservercore-1809
  - 4.3-windowsservercore-1809
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.3/alpine3.18
  GitCommit: b7003bc3280e69dc057ef0e6e8dfb8fd44ce4741
  Tags:
  - 4.3.1-alpine3.18
  - 4.3-alpine3.18
  - 4.3.1-alpine
  - 4.3-alpine
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.3/alpine3.17
  GitCommit: 1a4e5d4fbf207a4ed5a10db34e31826f4fc46c82
  Tags:
  - 4.3.1-alpine3.17
  - 4.3-alpine3.17
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.3/alpine3.16
  GitCommit: 1a4e5d4fbf207a4ed5a10db34e31826f4fc46c82
  Tags:
  - 4.3.1-alpine3.16
  - 4.3-alpine3.16
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.3/alpine3.15
  GitCommit: 1a4e5d4fbf207a4ed5a10db34e31826f4fc46c82
  Tags:
  - 4.3.1-alpine3.15
  - 4.3-alpine3.15
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 4.2/bullseye
  GitCommit: 4e55b2953c28c448f92aaf265168c1bf85b4867f
  Tags:
  - 4.2.5-bullseye
  - 4.2-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 4.2/buster
  GitCommit: 4e55b2953c28c448f92aaf265168c1bf85b4867f
  Tags:
  - 4.2.5-buster
  - 4.2-buster
- Architectures:
  - windows-amd64
  Directory: 4.2/windowsservercore-ltsc2022
  GitCommit: c0367972017a7b87845bf33477e29b1fe64ccc4a
  Tags:
  - 4.2.5-windowsservercore-ltsc2022
  - 4.2-windowsservercore-ltsc2022
- Architectures:
  - windows-amd64
  Directory: 4.2/windowsservercore-1809
  GitCommit: c0367972017a7b87845bf33477e29b1fe64ccc4a
  Tags:
  - 4.2.5-windowsservercore-1809
  - 4.2-windowsservercore-1809
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.2/alpine3.18
  GitCommit: b7003bc3280e69dc057ef0e6e8dfb8fd44ce4741
  Tags:
  - 4.2.5-alpine3.18
  - 4.2-alpine3.18
  - 4.2.5-alpine
  - 4.2-alpine
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.2/alpine3.17
  GitCommit: 40bf9156af6f198cd7a57dbfd452e24dc1ceb94e
  Tags:
  - 4.2.5-alpine3.17
  - 4.2-alpine3.17
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.2/alpine3.16
  GitCommit: 5f520ca3ba5942ab581369bab2cbda2b8c4ab992
  Tags:
  - 4.2.5-alpine3.16
  - 4.2-alpine3.16
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.2/alpine3.15
  GitCommit: 83789c10dc601064a234fd559206d1ec252228d7
  Tags:
  - 4.2.5-alpine3.15
  - 4.2-alpine3.15
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 4.1/bullseye
  GitCommit: 4e55b2953c28c448f92aaf265168c1bf85b4867f
  Tags:
  - 4.1.5-bullseye
  - 4.1-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 4.1/buster
  GitCommit: 4e55b2953c28c448f92aaf265168c1bf85b4867f
  Tags:
  - 4.1.5-buster
  - 4.1-buster
- Architectures:
  - windows-amd64
  Directory: 4.1/windowsservercore-ltsc2022
  GitCommit: c0367972017a7b87845bf33477e29b1fe64ccc4a
  Tags:
  - 4.1.5-windowsservercore-ltsc2022
  - 4.1-windowsservercore-ltsc2022
- Architectures:
  - windows-amd64
  Directory: 4.1/windowsservercore-1809
  GitCommit: c0367972017a7b87845bf33477e29b1fe64ccc4a
  Tags:
  - 4.1.5-windowsservercore-1809
  - 4.1-windowsservercore-1809
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.1/alpine3.18
  GitCommit: b7003bc3280e69dc057ef0e6e8dfb8fd44ce4741
  Tags:
  - 4.1.5-alpine3.18
  - 4.1-alpine3.18
  - 4.1.5-alpine
  - 4.1-alpine
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.1/alpine3.17
  GitCommit: 40bf9156af6f198cd7a57dbfd452e24dc1ceb94e
  Tags:
  - 4.1.5-alpine3.17
  - 4.1-alpine3.17
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.1/alpine3.16
  GitCommit: 5f520ca3ba5942ab581369bab2cbda2b8c4ab992
  Tags:
  - 4.1.5-alpine3.16
  - 4.1-alpine3.16
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.1/alpine3.15
  GitCommit: b0098b4b730d0d9ff21dbf3d543464228d6b7e99
  Tags:
  - 4.1.5-alpine3.15
  - 4.1-alpine3.15
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 4.0/bullseye
  GitCommit: 4e55b2953c28c448f92aaf265168c1bf85b4867f
  Tags:
  - 4.0.5-bullseye
  - 4.0-bullseye
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 4.0/buster
  GitCommit: 4e55b2953c28c448f92aaf265168c1bf85b4867f
  Tags:
  - 4.0.5-buster
  - 4.0-buster
- Architectures:
  - windows-amd64
  Directory: 4.0/windowsservercore-ltsc2022
  GitCommit: c0367972017a7b87845bf33477e29b1fe64ccc4a
  Tags:
  - 4.0.5-windowsservercore-ltsc2022
  - 4.0-windowsservercore-ltsc2022
- Architectures:
  - windows-amd64
  Directory: 4.0/windowsservercore-1809
  GitCommit: c0367972017a7b87845bf33477e29b1fe64ccc4a
  Tags:
  - 4.0.5-windowsservercore-1809
  - 4.0-windowsservercore-1809
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.0/alpine3.18
  GitCommit: b7003bc3280e69dc057ef0e6e8dfb8fd44ce4741
  Tags:
  - 4.0.5-alpine3.18
  - 4.0-alpine3.18
  - 4.0.5-alpine
  - 4.0-alpine
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.0/alpine3.17
  GitCommit: 40bf9156af6f198cd7a57dbfd452e24dc1ceb94e
  Tags:
  - 4.0.5-alpine3.17
  - 4.0-alpine3.17
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.0/alpine3.16
  GitCommit: 5f520ca3ba5942ab581369bab2cbda2b8c4ab992
  Tags:
  - 4.0.5-alpine3.16
  - 4.0-alpine3.16
- Architectures:
  - amd64
  - arm64v8
  Directory: 4.0/alpine3.15
  GitCommit: b0098b4b730d0d9ff21dbf3d543464228d6b7e99
  Tags:
  - 4.0.5-alpine3.15
  - 4.0-alpine3.15
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 3.4/buster
  GitCommit: 4e55b2953c28c448f92aaf265168c1bf85b4867f
  Tags:
  - 3.4.7-buster
  - 3.4-buster
- Architectures:
  - windows-amd64
  Directory: 3.4/windowsservercore-ltsc2022
  GitCommit: c0367972017a7b87845bf33477e29b1fe64ccc4a
  Tags:
  - 3.4.7-windowsservercore-ltsc2022
  - 3.4-windowsservercore-ltsc2022
- Architectures:
  - windows-amd64
  Directory: 3.4/windowsservercore-1809
  GitCommit: c0367972017a7b87845bf33477e29b1fe64ccc4a
  Tags:
  - 3.4.7-windowsservercore-1809
  - 3.4-windowsservercore-1809
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 3.3/buster
  GitCommit: 4e55b2953c28c448f92aaf265168c1bf85b4867f
  Tags:
  - 3.3.0-rc.1-buster
  - 3.3.0-buster
  - 3.3-buster
- Architectures:
  - windows-amd64
  Directory: 3.3/windowsservercore-ltsc2022
  GitCommit: c0367972017a7b87845bf33477e29b1fe64ccc4a
  Tags:
  - 3.3.0-rc.1-windowsservercore-ltsc2022
  - 3.3.0-windowsservercore-ltsc2022
  - 3.3-windowsservercore-ltsc2022
- Architectures:
  - windows-amd64
  Directory: 3.3/windowsservercore-1809
  GitCommit: c0367972017a7b87845bf33477e29b1fe64ccc4a
  Tags:
  - 3.3.0-rc.1-windowsservercore-1809
  - 3.3.0-windowsservercore-1809
  - 3.3-windowsservercore-1809
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 3.2/buster
  GitCommit: 4e55b2953c28c448f92aaf265168c1bf85b4867f
  Tags:
  - 3.2.1-buster
  - 3.2-buster
- Architectures:
  - windows-amd64
  Directory: 3.2/windowsservercore-ltsc2022
  GitCommit: c0367972017a7b87845bf33477e29b1fe64ccc4a
  Tags:
  - 3.2.1-windowsservercore-ltsc2022
  - 3.2-windowsservercore-ltsc2022
- Architectures:
  - windows-amd64
  Directory: 3.2/windowsservercore-1809
  GitCommit: c0367972017a7b87845bf33477e29b1fe64ccc4a
  Tags:
  - 3.2.1-windowsservercore-1809
  - 3.2-windowsservercore-1809
- Architectures:
  - windows-amd64
  Directory: 3.1/windowsservercore-ltsc2022
  GitCommit: c0367972017a7b87845bf33477e29b1fe64ccc4a
  Tags:
  - 3.1.3-windowsservercore-ltsc2022
  - 3.1-windowsservercore-ltsc2022
- Architectures:
  - windows-amd64
  Directory: 3.1/windowsservercore-1809
  GitCommit: c0367972017a7b87845bf33477e29b1fe64ccc4a
  Tags:
  - 3.1.3-windowsservercore-1809
  - 3.1-windowsservercore-1809
GitRepo: https://github.com/HaxeFoundation/docker-library-haxe.git
KnownTags:
  3.1-windowsservercore-1809: {}
  3.1-windowsservercore-ltsc2022: {}
  3.1.3-windowsservercore-1809: {}
  3.1.3-windowsservercore-ltsc2022: {}
  3.2-buster: {}
  3.2-windowsservercore-1809: {}
  3.2-windowsservercore-ltsc2022: {}
  3.2.1-buster: {}
  3.2.1-windowsservercore-1809: {}
  3.2.1-windowsservercore-ltsc2022: {}
  3.3-buster: {}
  3.3-windowsservercore-1809: {}
  3.3-windowsservercore-ltsc2022: {}
  3.3.0-buster: {}
  3.3.0-rc.1-buster: {}
  3.3.0-rc.1-windowsservercore-1809: {}
  3.3.0-rc.1-windowsservercore-ltsc2022: {}
  3.3.0-windowsservercore-1809: {}
  3.3.0-windowsservercore-ltsc2022: {}
  3.4-buster: {}
  3.4-windowsservercore-1809: {}
  3.4-windowsservercore-ltsc2022: {}
  3.4.7-buster: {}
  3.4.7-windowsservercore-1809: {}
  3.4.7-windowsservercore-ltsc2022: {}
  4.0-alpine: {}
  4.0-alpine3.15: {}
  4.0-alpine3.16: {}
  4.0-alpine3.17: {}
  4.0-alpine3.18: {}
  4.0-bullseye: {}
  4.0-buster: {}
  4.0-windowsservercore-1809: {}
  4.0-windowsservercore-ltsc2022: {}
  4.0.5-alpine: {}
  4.0.5-alpine3.15: {}
  4.0.5-alpine3.16: {}
  4.0.5-alpine3.17: {}
  4.0.5-alpine3.18: {}
  4.0.5-bullseye: {}
  4.0.5-buster: {}
  4.0.5-windowsservercore-1809: {}
  4.0.5-windowsservercore-ltsc2022: {}
  4.1-alpine: {}
  4.1-alpine3.15: {}
  4.1-alpine3.16: {}
  4.1-alpine3.17: {}
  4.1-alpine3.18: {}
  4.1-bullseye: {}
  4.1-buster: {}
  4.1-windowsservercore-1809: {}
  4.1-windowsservercore-ltsc2022: {}
  4.1.5-alpine: {}
  4.1.5-alpine3.15: {}
  4.1.5-alpine3.16: {}
  4.1.5-alpine3.17: {}
  4.1.5-alpine3.18: {}
  4.1.5-bullseye: {}
  4.1.5-buster: {}
  4.1.5-windowsservercore-1809: {}
  4.1.5-windowsservercore-ltsc2022: {}
  4.2-alpine: {}
  4.2-alpine3.15: {}
  4.2-alpine3.16: {}
  4.2-alpine3.17: {}
  4.2-alpine3.18: {}
  4.2-bullseye: {}
  4.2-buster: {}
  4.2-windowsservercore-1809: {}
  4.2-windowsservercore-ltsc2022: {}
  4.2.5-alpine: {}
  4.2.5-alpine3.15: {}
  4.2.5-alpine3.16: {}
  4.2.5-alpine3.17: {}
  4.2.5-alpine3.18: {}
  4.2.5-bullseye: {}
  4.2.5-buster: {}
  4.2.5-windowsservercore-1809: {}
  4.2.5-windowsservercore-ltsc2022: {}
  4.3-alpine: {}
  4.3-alpine3.15: {}
  4.3-alpine3.16: {}
  4.3-alpine3.17: {}
  4.3-alpine3.18: {}
  4.3-bullseye: {}
  4.3-buster: {}
  4.3-windowsservercore-1809: {}
  4.3-windowsservercore-ltsc2022: {}
  4.3.1-alpine: {}
  4.3.1-alpine3.15: {}
  4.3.1-alpine3.16: {}
  4.3.1-alpine3.17: {}
  4.3.1-alpine3.18: {}
  4.3.1-bullseye: {}
  4.3.1-buster: {}
  4.3.1-windowsservercore-1809: {}
  4.3.1-windowsservercore-ltsc2022: {}
Name: haxe
