Blocks:
- Architectures:
  - s390x
  Directory: ""
  GitCommit: 1aa7d3771b2ced8b8b5cdc9a1a1752d93c56a60e
  Tags:
  - "7"
  - 7.7.1908
  - latest
GitRepo: https://github.com/nealef/clefos.git
KnownTags:
  "7": {}
  7.7.1908: {}
  latest: {}
Name: clefos
