Blocks:
- Architectures:
  - amd64
  - ppc64le
  - s390x
  Directory: ibmjava/8/jre/ubuntu
  GitCommit: 4d75307c2faab96cd8a3b1c91fa0d8e59dcfa4b6
  Tags:
  - 8-jre
  - jre
  - "8"
  - latest
- Architectures:
  - amd64
  - ppc64le
  - s390x
  Directory: ibmjava/8/sfj/ubuntu
  GitCommit: 4d75307c2faab96cd8a3b1c91fa0d8e59dcfa4b6
  Tags:
  - 8-sfj
  - sfj
- Architectures:
  - amd64
  - ppc64le
  - s390x
  Directory: ibmjava/8/sdk/ubuntu
  GitCommit: 4d75307c2faab96cd8a3b1c91fa0d8e59dcfa4b6
  Tags:
  - 8-sdk
  - sdk
- Architectures:
  - amd64
  Directory: ibmjava/8/jre/alpine
  GitCommit: 2df7f5dd5dff7effe2038d4dc1d35dddfd3ca277
  Tags:
  - 8-jre-alpine
  - jre-alpine
- Architectures:
  - amd64
  Directory: ibmjava/8/sfj/alpine
  GitCommit: 2df7f5dd5dff7effe2038d4dc1d35dddfd3ca277
  Tags:
  - 8-sfj-alpine
  - sfj-alpine
- Architectures:
  - amd64
  Directory: ibmjava/8/sdk/alpine
  GitCommit: 2df7f5dd5dff7effe2038d4dc1d35dddfd3ca277
  Tags:
  - 8-sdk-alpine
  - sdk-alpine
- Architectures:
  - amd64
  - ppc64le
  - s390x
  Directory: ibmjava/11/jdk/ubuntu
  GitCommit: c14f45f7de370a12d59c2aacdd0e914bd0ff3c00
  Tags:
  - 11-jdk
  - "11"
- Architectures:
  - amd64
  - i386
  - ppc64le
  - s390x
  Directory: ibmjava/9/sdk/ubuntu
  GitCommit: 8d11fe57d3603fcf9e014aca252b6f345eca6561
  Tags:
  - 9-sdk
- Architectures:
  - amd64
  Directory: ibmjava/9/sdk/alpine
  GitCommit: 8d11fe57d3603fcf9e014aca252b6f345eca6561
  Tags:
  - 9-sdk-alpine
GitRepo: https://github.com/ibmruntimes/ci.docker.git
KnownTags:
  "8": {}
  8-jre: {}
  8-jre-alpine: {}
  8-sdk: {}
  8-sdk-alpine: {}
  8-sfj: {}
  8-sfj-alpine: {}
  9-sdk: {}
  9-sdk-alpine: {}
  "11": {}
  11-jdk: {}
  jre: {}
  jre-alpine: {}
  latest: {}
  sdk: {}
  sdk-alpine: {}
  sfj: {}
  sfj-alpine: {}
Name: ibmjava
