Blocks:
- Architectures:
  - amd64
  - ppc64le
  - s390x
  Directory: ibmjava/8/jre/ubuntu
  GitCommit: 672528f0c259480073bb491193c44fc12159ab03
  Tags:
  - 8-jre
  - jre
  - "8"
  - latest
- Architectures:
  - amd64
  - ppc64le
  - s390x
  Directory: ibmjava/8/sfj/ubuntu
  GitCommit: 672528f0c259480073bb491193c44fc12159ab03
  Tags:
  - 8-sfj
  - sfj
- Architectures:
  - amd64
  - ppc64le
  - s390x
  Directory: ibmjava/8/sdk/ubuntu
  GitCommit: 672528f0c259480073bb491193c44fc12159ab03
  Tags:
  - 8-sdk
  - sdk
GitRepo: https://github.com/ibmruntimes/ci.docker.git
KnownTags:
  "8": {}
  8-jre: {}
  8-sdk: {}
  8-sfj: {}
  jre: {}
  latest: {}
  sdk: {}
  sfj: {}
Name: ibmjava
