Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: 5/debian
  GitCommit: c603ddb07cb2b5db98bdf1e53c0225c3ab124f2c
  Tags:
  - 5.52.1
  - "5.52"
  - "5"
  - latest
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  Directory: 5/alpine
  GitCommit: c603ddb07cb2b5db98bdf1e53c0225c3ab124f2c
  Tags:
  - 5.52.1-alpine
  - 5.52-alpine
  - 5-alpine
  - alpine
GitRepo: https://github.com/docker-library/ghost.git
KnownTags:
  "5": {}
  5-alpine: {}
  "5.52": {}
  5.52-alpine: {}
  5.52.1: {}
  5.52.1-alpine: {}
  alpine: {}
  latest: {}
Name: ghost
