Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: alpine
  File: ""
  GitCommit: fa2707c3b24bbd99710a100d7859566fa28817b8
  Tags:
  - 1.x
  - 1.16.x
  - 1.16.11
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: alpine
  File: ""
  GitCommit: 704432298a3b9a99de87fcb19b33962e6995b7a3
  Tags:
  - 1.16.10
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: alpine
  File: ""
  GitCommit: 2d67c88c4fff2779a969bd740c936dd9c23722e1
  Tags:
  - 1.16.9
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: alpine
  File: ""
  GitCommit: 1c32904ed7f7cec69863e8fdb7a3cc4c4869b9d8
  Tags:
  - 1.16.7
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: alpine
  File: ""
  GitCommit: b234fd5473165d79a164b0707827f71be26c8ac5
  Tags:
  - 1.16.6
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: alpine
  File: ""
  GitCommit: 1913ade15763cb26a22286295902bb85eed76dd7
  Tags:
  - 1.16.4
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: alpine
  File: ""
  GitCommit: f7b6973318f32ce5be4e67cd5fb3b43446d32e9a
  Tags:
  - 1.16.3
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: alpine
  File: ""
  GitCommit: 64981a7796a1ac46be96f6207f5c0382a0415c58
  Tags:
  - 1.16.2
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: alpine
  File: ""
  GitCommit: 59683d0fceebef65c87ccc5d6b37ac2010f44583
  Tags:
  - 1.16.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: alpine
  File: ""
  GitCommit: d4e614db72706dbc429ebc7bc88f312dfb2e5f7d
  Tags:
  - 1.16.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: alpine
  File: ""
  GitCommit: 9160d360a01738d82689af2f0f66dea2d48b0b54
  Tags:
  - 1.15.x
  - 1.15.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: alpine
  File: ""
  GitCommit: e2bbae24ae0571e576ccf57387fb603f44ed67b8
  Tags:
  - 1.14.x
  - 1.14.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: alpine
  File: ""
  GitCommit: 0c92fd48415e952be0aa037a1c7355df2da64e0e
  Tags:
  - 1.13.x
  - 1.13.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: alpine
  File: ""
  GitCommit: 7d329fb7c09a5c946bf3661e27abbffddd3b09ea
  Tags:
  - 1.12.x
  - 1.12.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: alpine
  File: ""
  GitCommit: dde8e25dc3a698482b3fdf086c2a67a4fd471207
  Tags:
  - 1.11.x
  - 1.11.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: alpine
  File: ""
  GitCommit: 266104b97f83e825293bcee6bffa644139628e71
  Tags:
  - 1.10.x
  - 1.10.2
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 182691960d62d9398f7483e9122174124faa02bc
  Tags:
  - 1.9.x
  - 1.9.1
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: df515d429bd06c596839d512290cc3fd3a3ba82b
  Tags:
  - 1.8.x
  - 1.8.2
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: b715a408bd5c39636c0925b1739ffbc71072cc70
  Tags:
  - 1.7.x
  - 1.7.3
GitRepo: https://github.com/ExpressGateway/docker-express-gateway.git
KnownTags:
  1.7.3: {}
  1.7.x: {}
  1.8.2: {}
  1.8.x: {}
  1.9.1: {}
  1.9.x: {}
  1.10.2: {}
  1.10.x: {}
  1.11.0: {}
  1.11.x: {}
  1.12.0: {}
  1.12.x: {}
  1.13.0: {}
  1.13.x: {}
  1.14.0: {}
  1.14.x: {}
  1.15.0: {}
  1.15.x: {}
  1.16.0: {}
  1.16.1: {}
  1.16.2: {}
  1.16.3: {}
  1.16.4: {}
  1.16.6: {}
  1.16.7: {}
  1.16.9: {}
  1.16.10: {}
  1.16.11: {}
  1.16.x: {}
  1.x: {}
  latest: {}
Name: express-gateway
