Blocks:
- Architectures:
  - arm64v8
  - amd64
  - ppc64le
  - s390x
  Directory: alpine
  GitCommit: fa2707c3b24bbd99710a100d7859566fa28817b8
  Tags:
  - 1.x
  - 1.16.x
  - 1.16.11
  - latest
GitRepo: https://github.com/ExpressGateway/docker-express-gateway.git
KnownTags:
  1.16.11: {}
  1.16.x: {}
  1.x: {}
  latest: {}
Name: express-gateway
