Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 3454a52b4ad48e22b95e706dba9ff953cf84c2b1
  Tags:
  - 0.9.9
  - "0.9"
  - "0"
  - latest
GitRepo: https://github.com/idno/Known-Docker.git
KnownTags:
  "0": {}
  "0.9": {}
  0.9.9: {}
  latest: {}
Name: known
