Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "26"
  GitCommit: 91311b4b6e25a98416f87f77004361ce7439fece
  Tags:
  - 26.0.1.0
  - 26.0.1
  - "26.0"
  - "26"
  - latest
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 26/slim
  GitCommit: 91311b4b6e25a98416f87f77004361ce7439fece
  Tags:
  - 26.0.1.0-slim
  - 26.0.1-slim
  - 26.0-slim
  - 26-slim
  - slim
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 26/alpine
  GitCommit: 91311b4b6e25a98416f87f77004361ce7439fece
  Tags:
  - 26.0.1.0-alpine
  - 26.0.1-alpine
  - 26.0-alpine
  - 26-alpine
  - alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "25"
  GitCommit: 91311b4b6e25a98416f87f77004361ce7439fece
  Tags:
  - 25.3.2.2
  - 25.3.2
  - "25.3"
  - "25"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 25/slim
  GitCommit: 91311b4b6e25a98416f87f77004361ce7439fece
  Tags:
  - 25.3.2.2-slim
  - 25.3.2-slim
  - 25.3-slim
  - 25-slim
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 25/alpine
  GitCommit: 91311b4b6e25a98416f87f77004361ce7439fece
  Tags:
  - 25.3.2.2-alpine
  - 25.3.2-alpine
  - 25.3-alpine
  - 25-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "24"
  GitCommit: c5450a00c47ee731ff185f17f0931c8b8fa8cbcc
  Tags:
  - 24.3.4.12
  - 24.3.4
  - "24.3"
  - "24"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 24/slim
  GitCommit: c5450a00c47ee731ff185f17f0931c8b8fa8cbcc
  Tags:
  - 24.3.4.12-slim
  - 24.3.4-slim
  - 24.3-slim
  - 24-slim
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 24/alpine
  GitCommit: c5450a00c47ee731ff185f17f0931c8b8fa8cbcc
  Tags:
  - 24.3.4.12-alpine
  - 24.3.4-alpine
  - 24.3-alpine
  - 24-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: "23"
  GitCommit: 91311b4b6e25a98416f87f77004361ce7439fece
  Tags:
  - 23.3.4.19
  - 23.3.4
  - "23.3"
  - "23"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 23/slim
  GitCommit: 91311b4b6e25a98416f87f77004361ce7439fece
  Tags:
  - 23.3.4.19-slim
  - 23.3.4-slim
  - 23.3-slim
  - 23-slim
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 23/alpine
  GitCommit: 91311b4b6e25a98416f87f77004361ce7439fece
  Tags:
  - 23.3.4.19-alpine
  - 23.3.4-alpine
  - 23.3-alpine
  - 23-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: "22"
  GitCommit: 33d107cb0428c2eeb9d2c3a5cdbc5a6f83bea897
  Tags:
  - 22.3.4.26
  - 22.3.4
  - "22.3"
  - "22"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 22/slim
  GitCommit: 33d107cb0428c2eeb9d2c3a5cdbc5a6f83bea897
  Tags:
  - 22.3.4.26-slim
  - 22.3.4-slim
  - 22.3-slim
  - 22-slim
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 22/alpine
  GitCommit: 33d107cb0428c2eeb9d2c3a5cdbc5a6f83bea897
  Tags:
  - 22.3.4.26-alpine
  - 22.3.4-alpine
  - 22.3-alpine
  - 22-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: "21"
  GitCommit: fd21a3bf876b240b413d2cd4543d832dca466c5c
  Tags:
  - 21.3.8.24
  - 21.3.8
  - "21.3"
  - "21"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 21/slim
  GitCommit: fd21a3bf876b240b413d2cd4543d832dca466c5c
  Tags:
  - 21.3.8.24-slim
  - 21.3.8-slim
  - 21.3-slim
  - 21-slim
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: "20"
  GitCommit: fd21a3bf876b240b413d2cd4543d832dca466c5c
  Tags:
  - 20.3.8.26
  - 20.3.8
  - "20.3"
  - "20"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 20/slim
  GitCommit: fd21a3bf876b240b413d2cd4543d832dca466c5c
  Tags:
  - 20.3.8.26-slim
  - 20.3.8-slim
  - 20.3-slim
  - 20-slim
GitRepo: https://github.com/erlang/docker-erlang-otp.git
KnownTags:
  "20": {}
  20-slim: {}
  "20.3": {}
  20.3-slim: {}
  20.3.8: {}
  20.3.8-slim: {}
  20.3.8.26: {}
  20.3.8.26-slim: {}
  "21": {}
  21-slim: {}
  "21.3": {}
  21.3-slim: {}
  21.3.8: {}
  21.3.8-slim: {}
  21.3.8.24: {}
  21.3.8.24-slim: {}
  "22": {}
  22-alpine: {}
  22-slim: {}
  "22.3": {}
  22.3-alpine: {}
  22.3-slim: {}
  22.3.4: {}
  22.3.4-alpine: {}
  22.3.4-slim: {}
  22.3.4.26: {}
  22.3.4.26-alpine: {}
  22.3.4.26-slim: {}
  "23": {}
  23-alpine: {}
  23-slim: {}
  "23.3": {}
  23.3-alpine: {}
  23.3-slim: {}
  23.3.4: {}
  23.3.4-alpine: {}
  23.3.4-slim: {}
  23.3.4.19: {}
  23.3.4.19-alpine: {}
  23.3.4.19-slim: {}
  "24": {}
  24-alpine: {}
  24-slim: {}
  "24.3": {}
  24.3-alpine: {}
  24.3-slim: {}
  24.3.4: {}
  24.3.4-alpine: {}
  24.3.4-slim: {}
  24.3.4.12: {}
  24.3.4.12-alpine: {}
  24.3.4.12-slim: {}
  "25": {}
  25-alpine: {}
  25-slim: {}
  "25.3": {}
  25.3-alpine: {}
  25.3-slim: {}
  25.3.2: {}
  25.3.2-alpine: {}
  25.3.2-slim: {}
  25.3.2.2: {}
  25.3.2.2-alpine: {}
  25.3.2.2-slim: {}
  "26": {}
  26-alpine: {}
  26-slim: {}
  "26.0": {}
  26.0-alpine: {}
  26.0-slim: {}
  26.0.1: {}
  26.0.1-alpine: {}
  26.0.1-slim: {}
  26.0.1.0: {}
  26.0.1.0-alpine: {}
  26.0.1.0-slim: {}
  alpine: {}
  latest: {}
  slim: {}
Name: erlang
