Blocks:
- Architectures:
  - amd64
  Directory: sl7
  GitCommit: c369b631e3de151d68e9d02c08e66590048e6230
  Tags:
  - "7"
  - latest
- Architectures:
  - amd64
  Directory: sl6
  GitCommit: cee76508f6b6a7f83842d944d687366ca99f78c9
  Tags:
  - "6"
GitRepo: https://github.com/scientificlinux/sl-docker.git
KnownTags:
  "6": {}
  "7": {}
  latest: {}
Name: sl
