Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: sl7
  GitCommit: 6774a5c2862153082a4f2271aa6073b5bd823e6b
  Tags:
  - "7"
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: sl6
  GitCommit: cee76508f6b6a7f83842d944d687366ca99f78c9
  Tags:
  - "6"
GitRepo: https://github.com/scientificlinux/sl-docker.git
KnownTags:
  "6": {}
  "7": {}
  latest: {}
Name: sl
