Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: sl7
  File: ""
  GitCommit: bf1a75fd29d02465952d829b66a5f9081113555e
  Tags:
  - "7"
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: sl6
  File: ""
  GitCommit: cee76508f6b6a7f83842d944d687366ca99f78c9
  Tags:
  - "6"
GitRepo: https://github.com/scientificlinux/sl-docker.git
KnownTags:
  "6": {}
  "7": {}
  latest: {}
Name: sl
