Blocks:
- Architectures:
  - amd64
  Directory: sl7
  GitCommit: c369b631e3de151d68e9d02c08e66590048e6230
  Tags:
  - "7"
  - latest
GitRepo: https://github.com/scientificlinux/sl-docker.git
KnownTags:
  "7": {}
  latest: {}
Name: sl
