Blocks:
- Architectures:
  - amd64
  Directory: "16.0"
  GitCommit: ""
  Tags:
  - "16.0"
  - "16"
  - latest
- Architectures:
  - amd64
  Directory: "15.0"
  GitCommit: ""
  Tags:
  - "15.0"
  - "15"
- Architectures:
  - amd64
  Directory: "14.0"
  GitCommit: ""
  Tags:
  - "14.0"
  - "14"
GitRepo: https://github.com/odoo/docker
KnownTags:
  "14": {}
  "14.0": {}
  "15": {}
  "15.0": {}
  "16": {}
  "16.0": {}
  latest: {}
Name: odoo
