Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "16.0"
  File: ""
  GitCommit: d04d885eea6b8f60ada727fcc498f5a8fd44da51
  Tags:
  - "16.0"
  - "16"
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "15.0"
  File: ""
  GitCommit: d04d885eea6b8f60ada727fcc498f5a8fd44da51
  Tags:
  - "15.0"
  - "15"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "14.0"
  File: ""
  GitCommit: d04d885eea6b8f60ada727fcc498f5a8fd44da51
  Tags:
  - "14.0"
  - "14"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "13.0"
  File: ""
  GitCommit: 26df6d6eef8df7a9927fbdade79772455de7e8eb
  Tags:
  - "13.0"
  - "13"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "12.0"
  File: ""
  GitCommit: 4f79a47adddee4538ab5d89624e3b6b7c600156f
  Tags:
  - "12.0"
  - "12"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "11.0"
  File: ""
  GitCommit: 1bddcda4b2ef30c7443ebe0cae43d17f92aa43cd
  Tags:
  - "11.0"
  - "11"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "10.0"
  File: ""
  GitCommit: b5f088de13927177263d6cbc5ebf7d39de4dcfa7
  Tags:
  - "10.0"
  - "10"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "9.0"
  File: ""
  GitCommit: a7e2eb4193e9e1de98ce9e3e7462593a49c191a8
  Tags:
  - "9.0"
  - "9"
GitRepo: https://github.com/odoo/docker
KnownTags:
  "9": {}
  "9.0": {}
  "10": {}
  "10.0": {}
  "11": {}
  "11.0": {}
  "12": {}
  "12.0": {}
  "13": {}
  "13.0": {}
  "14": {}
  "14.0": {}
  "15": {}
  "15.0": {}
  "16": {}
  "16.0": {}
  latest: {}
Name: odoo
