Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "16.0"
  GitCommit: ""
  Tags:
  - "16.0"
  - "16"
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "15.0"
  GitCommit: ""
  Tags:
  - "15.0"
  - "15"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "14.0"
  GitCommit: ""
  Tags:
  - "14.0"
  - "14"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "13.0"
  GitCommit: ""
  Tags:
  - "13.0"
  - "13"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "12.0"
  GitCommit: ""
  Tags:
  - "12.0"
  - "12"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "11.0"
  GitCommit: ""
  Tags:
  - "11.0"
  - "11"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "10.0"
  GitCommit: ""
  Tags:
  - "10.0"
  - "10"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "9.0"
  GitCommit: ""
  Tags:
  - "9.0"
  - "9"
GitRepo: https://github.com/odoo/docker
KnownTags:
  "9": {}
  "9.0": {}
  "10": {}
  "10.0": {}
  "11": {}
  "11.0": {}
  "12": {}
  "12.0": {}
  "13": {}
  "13.0": {}
  "14": {}
  "14.0": {}
  "15": {}
  "15.0": {}
  "16": {}
  "16.0": {}
  latest: {}
Name: odoo
