Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "17.0"
  File: ""
  GitCommit: c8297f5332271108e7e477afe8e8e17ca73afdd7
  Tags:
  - 17.0-20240711
  - "17.0"
  - "17"
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "16.0"
  File: ""
  GitCommit: c8297f5332271108e7e477afe8e8e17ca73afdd7
  Tags:
  - 16.0-20240711
  - "16.0"
  - "16"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "15.0"
  File: ""
  GitCommit: c8297f5332271108e7e477afe8e8e17ca73afdd7
  Tags:
  - 15.0-20240711
  - "15.0"
  - "15"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "17.0"
  File: ""
  GitCommit: a25c36df57efc4fe900f04b97cef0e92d5f1a09f
  Tags:
  - 17.0-20240624
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "16.0"
  File: ""
  GitCommit: a25c36df57efc4fe900f04b97cef0e92d5f1a09f
  Tags:
  - 16.0-20240624
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "15.0"
  File: ""
  GitCommit: a25c36df57efc4fe900f04b97cef0e92d5f1a09f
  Tags:
  - 15.0-20240624
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "17.0"
  File: ""
  GitCommit: 30416a3c40b5b3dbadd1d7d3c7e79f478fcbb74b
  Tags:
  - 17.0-20240603
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "16.0"
  File: ""
  GitCommit: 30416a3c40b5b3dbadd1d7d3c7e79f478fcbb74b
  Tags:
  - 16.0-20240603
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "15.0"
  File: ""
  GitCommit: 30416a3c40b5b3dbadd1d7d3c7e79f478fcbb74b
  Tags:
  - 15.0-20240603
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "17.0"
  File: ""
  GitCommit: ea74918b211215176bda85854a771be1c5c97871
  Tags:
  - 17.0-20240522
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "16.0"
  File: ""
  GitCommit: ea74918b211215176bda85854a771be1c5c97871
  Tags:
  - 16.0-20240522
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "15.0"
  File: ""
  GitCommit: ea74918b211215176bda85854a771be1c5c97871
  Tags:
  - 15.0-20240522
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "14.0"
  File: ""
  GitCommit: 3864188c94c33dace7d4b5f6767e00a4328fe08c
  Tags:
  - "14.0"
  - "14"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "13.0"
  File: ""
  GitCommit: 26df6d6eef8df7a9927fbdade79772455de7e8eb
  Tags:
  - "13.0"
  - "13"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "12.0"
  File: ""
  GitCommit: 4f79a47adddee4538ab5d89624e3b6b7c600156f
  Tags:
  - "12.0"
  - "12"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "11.0"
  File: ""
  GitCommit: 1bddcda4b2ef30c7443ebe0cae43d17f92aa43cd
  Tags:
  - "11.0"
  - "11"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "10.0"
  File: ""
  GitCommit: b5f088de13927177263d6cbc5ebf7d39de4dcfa7
  Tags:
  - "10.0"
  - "10"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "9.0"
  File: ""
  GitCommit: a7e2eb4193e9e1de98ce9e3e7462593a49c191a8
  Tags:
  - "9.0"
  - "9"
GitRepo: https://github.com/odoo/docker
KnownTags:
  "9": {}
  "9.0": {}
  "10": {}
  "10.0": {}
  "11": {}
  "11.0": {}
  "12": {}
  "12.0": {}
  "13": {}
  "13.0": {}
  "14": {}
  "14.0": {}
  "15": {}
  "15.0": {}
  15.0-20240522: {}
  15.0-20240603: {}
  15.0-20240624: {}
  15.0-20240711: {}
  "16": {}
  "16.0": {}
  16.0-20240522: {}
  16.0-20240603: {}
  16.0-20240624: {}
  16.0-20240711: {}
  "17": {}
  "17.0": {}
  17.0-20240522: {}
  17.0-20240603: {}
  17.0-20240624: {}
  17.0-20240711: {}
  latest: {}
Name: odoo
