Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: 10.10.0/mono
  GitCommit: ""
  Tags:
  - latest
  - "10"
  - "10.10"
  - 10.10.0
- Architectures: null
  Directory: 4.1.34/mono
  GitCommit: ""
  Tags:
  - "4"
  - "4.1"
  - 4.1.34
- Architectures: null
  Directory: 10.10.0/netcore
  GitCommit: ""
  Tags:
  - netcore
  - 10-netcore
  - 10.10-netcore
  - 10.10.0-netcore
- Architectures:
  - amd64
  - arm64v8
  Directory: 10.7.0/mono
  GitCommit: ""
  Tags:
  - "10.7"
  - 10.7.0
- Architectures: null
  Directory: 10.7.0/netcore
  GitCommit: ""
  Tags:
  - 10.7-netcore
  - 10.7.0-netcore
- Architectures:
  - amd64
  - arm64v8
  Directory: 10.6.0/mono
  GitCommit: ""
  Tags:
  - "10.6"
  - 10.6.0
- Architectures: null
  Directory: 10.6.0/netcore
  GitCommit: ""
  Tags:
  - 10.6-netcore
  - 10.6.0-netcore
- Architectures:
  - amd64
  - arm64v8
  Directory: 10.2.3/mono
  GitCommit: ""
  Tags:
  - "10.2"
  - 10.2.3
- Architectures: null
  Directory: 10.2.3/netcore
  GitCommit: ""
  Tags:
  - 10.2-netcore
  - 10.2.3-netcore
- Architectures:
  - amd64
  - arm64v8
  Directory: 10.2.1/mono
  GitCommit: ""
  Tags:
  - 10.2.1
- Architectures: null
  Directory: 4.0.1.1
  GitCommit: ""
  Tags:
  - "4.0"
  - 4.0.1
  - 4.0.1.1
- Architectures: null
  Directory: 10.2.1/netcore
  GitCommit: ""
  Tags:
  - 10.2.1-netcore
- Architectures:
  - amd64
  - arm64v8
  Directory: 10.0.2/mono
  GitCommit: ""
  Tags:
  - "10.0"
  - 10.0.2
- Architectures: null
  Directory: 10.0.2/netcore
  GitCommit: ""
  Tags:
  - 10.0-netcore
  - 10.0.2-netcore
- Architectures: null
  Directory: 4.1.34/netcore
  GitCommit: ""
  Tags:
  - 4-netcore
  - 4.1-netcore
  - 4.1.34-netcore
- Architectures: null
  Directory: 4.1.29/mono
  GitCommit: a58f8a05cd4995b1daf1a41692a84d3a003b160b
  Tags:
  - 4.1.29
- Architectures: null
  Directory: 4.1.28/mono
  GitCommit: 58be3b5a99a5170b8277c60c77cf163ce66a733f
  Tags:
  - 4.1.28
- Architectures: null
  Directory: 4.1.18/mono
  GitCommit: ad4c4d67a1975b2b0ff0acc49dc46b3271836831
  Tags:
  - 4.1.18
- Architectures: null
  Directory: 4.1.0.1/mono
  GitCommit: a28196740e38035beea04c41d5862136413281e3
  Tags:
  - 4.1.0.1
- Architectures: null
  Directory: 4.0.0.4
  GitCommit: a28196740e38035beea04c41d5862136413281e3
  Tags:
  - 4.0.0.4
- Architectures: null
  Directory: 4.1.25/mono
  GitCommit: 96cd7752113e7b4e32fbd6437600816f4b361994
  Tags:
  - 4.1.25
- Architectures: null
  Directory: 4.1.18/mono-wheezy
  GitCommit: 33b5be9aea66ea1d258daf23055fa6d9bcb164ff
  Tags:
  - 4.1.18-wheezy-slim
- Architectures: null
  Directory: 4.1.18/mono-wheezy
  GitCommit: 0d86b281d7e8fccfe463d098310a5fd521f0276a
  Tags:
  - 4.1.18-wheezy
- Architectures: null
  Directory: 4.1.18/mono-wheezy
  GitCommit: 0d86b281d7e8fccfe463d098310a5fd521f0276a
  Tags:
  - 4.1.18-wheezy-beta
- Architectures: null
  Directory: 4.1.29/netcore
  GitCommit: ""
  Tags:
  - core
  - 4-core
  - 4.1-core
  - 4.1.29-core
GitRepo: https://github.com/fsprojects/docker-fsharp.git
KnownTags:
  "4": {}
  4-core: {}
  4-netcore: {}
  "4.0": {}
  4.0.0.4: {}
  4.0.1: {}
  4.0.1.1: {}
  "4.1": {}
  4.1-core: {}
  4.1-netcore: {}
  4.1.0.1: {}
  4.1.18: {}
  4.1.18-wheezy: {}
  4.1.18-wheezy-beta: {}
  4.1.18-wheezy-slim: {}
  4.1.25: {}
  4.1.28: {}
  4.1.29: {}
  4.1.29-core: {}
  4.1.34: {}
  4.1.34-netcore: {}
  "10": {}
  10-netcore: {}
  "10.0": {}
  10.0-netcore: {}
  10.0.2: {}
  10.0.2-netcore: {}
  "10.2": {}
  10.2-netcore: {}
  10.2.1: {}
  10.2.1-netcore: {}
  10.2.3: {}
  10.2.3-netcore: {}
  "10.6": {}
  10.6-netcore: {}
  10.6.0: {}
  10.6.0-netcore: {}
  "10.7": {}
  10.7-netcore: {}
  10.7.0: {}
  10.7.0-netcore: {}
  "10.10": {}
  10.10-netcore: {}
  10.10.0: {}
  10.10.0-netcore: {}
  core: {}
  latest: {}
  netcore: {}
Name: fsharp
