Blocks:
- Architectures: null
  Directory: ""
  GitCommit: cab21d1a3a25bf15d24f27a156d3df894123bb10
  Tags:
  - "6.3"
  - latest
- Architectures: null
  Directory: ""
  GitCommit: 9714dcc94eb558508f085835a329a44f5c3cb52e
  Tags:
  - 6.2.3-b1
- Architectures: null
  Directory: ""
  GitCommit: 899560a46feaddb077f0ec93b5da3e01be7abbe0
  Tags:
  - 6.2.3
- Architectures: null
  Directory: ""
  GitCommit: c6b68c650da8a95d9b258b4fe1f930fa9be737a6
  Tags:
  - 6.2.2
- Architectures: null
  Directory: ""
  GitCommit: 8577cb90ed86ef24248d1283f032c541a38d38ea
  Tags:
  - 6.1.3
- Architectures: null
  Directory: ""
  GitCommit: 189a4f2db783d5052add54f2c07ca7a3b860c685
  Tags:
  - 6.0.2
- Architectures: null
  Directory: ""
  GitCommit: e97e55f0a21aae880a0054ef764cea0cb37e1e05
  Tags:
  - 6.2.1
- Architectures: null
  Directory: ""
  GitCommit: 558d384db05b003735f876a2d8a96aa3d404bfb4
  Tags:
  - "6.2"
- Architectures: null
  Directory: ""
  GitCommit: a4d6289629004ca954b8a24890eac4d4dc83a597
  Tags:
  - 6.1.2
- Architectures: null
  Directory: ""
  GitCommit: 84d84260f98ef3895465d87da1786afabde8a8b2
  Tags:
  - 6.1.1
- Architectures: null
  Directory: ""
  GitCommit: 7d002ee69a68f8a8f640ce7fbf7fd47b526123d0
  Tags:
  - "6.1"
- Architectures: null
  Directory: ""
  GitCommit: 3e3e2ce680e57828a145151a2ee609b34e1501d2
  Tags:
  - 6.0.1
- Architectures: null
  Directory: ""
  GitCommit: 80bd9752fac5793594ddc80943ecdcf88e25f3b1
  Tags:
  - "6.0"
- Architectures: null
  Directory: ""
  GitCommit: 03bd2800e83bf262d07b53f067758115fa6f05fc
  Tags:
  - 6.0-beta1
- Architectures: null
  Directory: ""
  GitCommit: 48e66a18fb4fa3933a1aafce48be75cc4b18a765
  Tags:
  - 6.0-alpha3
- Architectures: null
  Directory: ""
  GitCommit: 77c7c86d82aeee270cf23ef1272cfd95767df3c4
  Tags:
  - 6.0-alpha2
- Architectures: null
  Directory: ""
  GitCommit: b87b3bb7e28e61cd9d76262e897451e2b466d265
  Tags:
  - 6.0-alpha1
GitRepo: https://github.com/Silverpeas/docker-silverpeas-prod.git
KnownTags:
  "6.0": {}
  6.0-alpha1: {}
  6.0-alpha2: {}
  6.0-alpha3: {}
  6.0-beta1: {}
  6.0.1: {}
  6.0.2: {}
  "6.1": {}
  6.1.1: {}
  6.1.2: {}
  6.1.3: {}
  "6.2": {}
  6.2.1: {}
  6.2.2: {}
  6.2.3: {}
  6.2.3-b1: {}
  "6.3": {}
  latest: {}
Name: silverpeas
