Blocks:
- Architectures: null
  Directory: ""
  GitCommit: cab21d1a3a25bf15d24f27a156d3df894123bb10
  Tags:
  - "6.3"
  - latest
- Architectures: null
  Directory: ""
  GitCommit: 9714dcc94eb558508f085835a329a44f5c3cb52e
  Tags:
  - 6.2.3-b1
GitRepo: https://github.com/Silverpeas/docker-silverpeas-prod.git
KnownTags:
  6.2.3-b1: {}
  "6.3": {}
  latest: {}
Name: silverpeas
