Blocks:
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: fcf9d53b1a68f23841fc71a9210a83142a6a87d7
  Tags:
  - 6.4.5
  - latest
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: fb25885d1cd43172693b3acf79e9fac056a9db34
  Tags:
  - 6.3.6
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 2094ddb26caec9820d1852a9fa2bc3c2c84a1ada
  Tags:
  - 6.4.4
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 79cad3dae9a20fb2fb404fba5641c5921d410112
  Tags:
  - 6.4.3
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: c80ded6919cdf9e1d3e50f2dcef80e32b497fbc1
  Tags:
  - 6.4.2
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 126477050a7890b45fd57eebe471bfdcff20643d
  Tags:
  - 6.3.5
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 10abc2b0ea09cceedb65cf58a2cf843992d88a27
  Tags:
  - 6.4.1
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: c3054e40add18fd254afdd07a2b206be6a4d3530
  Tags:
  - "6.4"
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 0ab5ec380118de3c070135446eabd3d94dfa0395
  Tags:
  - 6.3.4
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 58fcac8f9759d8ba09ca23bc2106a2a7c5a5217f
  Tags:
  - 6.3.3
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 9714dcc94eb558508f085835a329a44f5c3cb52e
  Tags:
  - 6.2.3-b1
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 46663472900c69ea9b5aeec78fb827184c9109bf
  Tags:
  - 6.3.2
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: c1fa483e14efa07680009a9f177b94072ab24827
  Tags:
  - 6.3.1
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: cab21d1a3a25bf15d24f27a156d3df894123bb10
  Tags:
  - "6.3"
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 899560a46feaddb077f0ec93b5da3e01be7abbe0
  Tags:
  - 6.2.3
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: c6b68c650da8a95d9b258b4fe1f930fa9be737a6
  Tags:
  - 6.2.2
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 8577cb90ed86ef24248d1283f032c541a38d38ea
  Tags:
  - 6.1.3
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 189a4f2db783d5052add54f2c07ca7a3b860c685
  Tags:
  - 6.0.2
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: e97e55f0a21aae880a0054ef764cea0cb37e1e05
  Tags:
  - 6.2.1
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 558d384db05b003735f876a2d8a96aa3d404bfb4
  Tags:
  - "6.2"
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: a4d6289629004ca954b8a24890eac4d4dc83a597
  Tags:
  - 6.1.2
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 84d84260f98ef3895465d87da1786afabde8a8b2
  Tags:
  - 6.1.1
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 7d002ee69a68f8a8f640ce7fbf7fd47b526123d0
  Tags:
  - "6.1"
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 3e3e2ce680e57828a145151a2ee609b34e1501d2
  Tags:
  - 6.0.1
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 80bd9752fac5793594ddc80943ecdcf88e25f3b1
  Tags:
  - "6.0"
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 03bd2800e83bf262d07b53f067758115fa6f05fc
  Tags:
  - 6.0-beta1
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 48e66a18fb4fa3933a1aafce48be75cc4b18a765
  Tags:
  - 6.0-alpha3
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: 77c7c86d82aeee270cf23ef1272cfd95767df3c4
  Tags:
  - 6.0-alpha2
- Architectures: null
  Directory: ""
  File: ""
  GitCommit: b87b3bb7e28e61cd9d76262e897451e2b466d265
  Tags:
  - 6.0-alpha1
GitRepo: https://github.com/Silverpeas/docker-silverpeas-prod.git
KnownTags:
  "6.0": {}
  6.0-alpha1: {}
  6.0-alpha2: {}
  6.0-alpha3: {}
  6.0-beta1: {}
  6.0.1: {}
  6.0.2: {}
  "6.1": {}
  6.1.1: {}
  6.1.2: {}
  6.1.3: {}
  "6.2": {}
  6.2.1: {}
  6.2.2: {}
  6.2.3: {}
  6.2.3-b1: {}
  "6.3": {}
  6.3.1: {}
  6.3.2: {}
  6.3.3: {}
  6.3.4: {}
  6.3.5: {}
  6.3.6: {}
  "6.4": {}
  6.4.1: {}
  6.4.2: {}
  6.4.3: {}
  6.4.4: {}
  6.4.5: {}
  latest: {}
Name: silverpeas
