Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 3.4.1-nouveau
  File: ""
  GitCommit: dfee1197c932a48e760a20375ef6f051b0498ec3
  Tags:
  - latest
  - 3.4.1
  - "3.4"
  - "3"
GitRepo: https://github.com/apache/couchdb-docker
KnownTags:
  "3": {}
  "3.4": {}
  3.4.1: {}
  latest: {}
Name: couchdb-nouveau
