Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: "4.4"
  GitCommit: 129bff4ea692ede8157aa3165a8c278bf982f47d
  Tags:
  - 4.4.18
  - "4.4"
  - "4"
- Architectures:
  - amd64
  - arm64v8
  Directory: "5.0"
  GitCommit: ee9c3fd710eb7f04df3843656ec21a1be361afd5
  Tags:
  - 5.0.26
  - "5.0"
  - "5"
  - latest
GitRepo: https://github.com/emqx/emqx-docker.git
KnownTags:
  "4": {}
  "4.4": {}
  4.4.18: {}
  "5": {}
  "5.0": {}
  5.0.26: {}
  latest: {}
Name: emqx
