Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.1"
  File: Dockerfile
  GitCommit: dfa1507bc031b4f24ffa29f838dbad1868e35d01
  Tags:
  - 5.1.6
  - "5.1"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.2"
  File: Dockerfile
  GitCommit: eb71b6a3cca1505e14d4b0e6fcd50a43330125bb
  Tags:
  - 5.2.1
  - "5.2"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.3"
  File: Dockerfile
  GitCommit: 1572ca48b4bc890edfc157b00be271d9a1b878d4
  Tags:
  - 5.3.2
  - "5.3"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.4"
  File: Dockerfile
  GitCommit: a180d28d9a6b4ebc752aa2de3a456887f4a416cc
  Tags:
  - 5.4.1
  - "5.4"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.5"
  File: Dockerfile
  GitCommit: 17a2814880d4852d0611c06c31007ca2a2633199
  Tags:
  - 5.5.1
  - "5.5"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.6"
  File: Dockerfile
  GitCommit: e0af46182038ded4d6f45879846ddf765b6b5613
  Tags:
  - 5.6.1
  - "5.6"
  - "5"
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.6"
  File: Dockerfile
  GitCommit: 17a2814880d4852d0611c06c31007ca2a2633199
  Tags:
  - 5.6.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.5"
  File: Dockerfile
  GitCommit: 66e23a1daf5526c3c1edcd51b338ad24db628734
  Tags:
  - 5.5.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.4"
  File: Dockerfile
  GitCommit: 753e8c47442682d4b96dbd280f0a6d44ca09a5fa
  Tags:
  - 5.4.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.0"
  File: Dockerfile
  GitCommit: 5fa7e9eac34517170ade58660cb65e5a5870c783
  Tags:
  - 5.0.26
  - "5.0"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.3"
  File: Dockerfile
  GitCommit: 93a2f78567c5007a9d76786f7324dcf2dcfccd15
  Tags:
  - 5.3.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.3"
  File: Dockerfile
  GitCommit: b831255e1b833d4e56110904b1cb6d4eb899efda
  Tags:
  - 5.3.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.1"
  File: Dockerfile
  GitCommit: 3a19847806d3ca16fb8eb61cecc28a91b74c92e4
  Tags:
  - 5.1.5-build.3
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "4.4"
  File: Dockerfile
  GitCommit: 5fa7e9eac34517170ade58660cb65e5a5870c783
  Tags:
  - 4.4.19
  - "4.4"
  - "4"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.1"
  File: Dockerfile
  GitCommit: e5d98d7a6d6de0ad22e5f1be79b65228232871cd
  Tags:
  - 5.1.3
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.1"
  File: Dockerfile
  GitCommit: 302615a79671ed6499640ced5c297b2c1cce9f36
  Tags:
  - 5.1.2
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.1"
  File: Dockerfile
  GitCommit: 5fa7e9eac34517170ade58660cb65e5a5870c783
  Tags:
  - 5.1.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "4.4"
  File: Dockerfile
  GitCommit: 129bff4ea692ede8157aa3165a8c278bf982f47d
  Tags:
  - 4.4.18
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.1"
  File: Dockerfile
  GitCommit: 0d41c4cf54ee2e670ba14cf821581d8999205996
  Tags:
  - 5.1.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.0"
  File: Dockerfile
  GitCommit: a751d86bd0a1ed0785cf960f77f1a44ba7296825
  Tags:
  - 5.0.25
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.0"
  File: Dockerfile
  GitCommit: 7585bcd6f772834c6bdd4a94be9ee4e71c9d4772
  Tags:
  - 5.0.24
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "4.4"
  File: Dockerfile
  GitCommit: 95eb1259e59178c6b641d2379318c77c3beb84e8
  Tags:
  - 4.4.17
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.0"
  File: Dockerfile
  GitCommit: 95eb1259e59178c6b641d2379318c77c3beb84e8
  Tags:
  - 5.0.23
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "4.4"
  File: Dockerfile
  GitCommit: 69e50460c940c4943b9051732fa155b8940e1c71
  Tags:
  - 4.4.16
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.0"
  File: Dockerfile
  GitCommit: 73b32fe8b71f5e2bb9634b0a6c69d5f50709e18b
  Tags:
  - 5.0.22
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.0"
  File: Dockerfile
  GitCommit: 8bda3215370c60fdefd197e2d033ed0bc12a2ade
  Tags:
  - 5.0.21
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.0"
  File: Dockerfile
  GitCommit: 69e50460c940c4943b9051732fa155b8940e1c71
  Tags:
  - 5.0.20
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "4.3"
  File: Dockerfile
  GitCommit: 964890ab6381f7026fd11094ae43d7cf744ea780
  Tags:
  - 4.3.22
  - "4.3"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "4.4"
  File: Dockerfile
  GitCommit: 964890ab6381f7026fd11094ae43d7cf744ea780
  Tags:
  - 4.4.15
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "4.4"
  File: Dockerfile
  GitCommit: 194c8de35500c5e08c0ec73a199f854356c50349
  Tags:
  - 4.4.14
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.0"
  File: Dockerfile
  GitCommit: 194c8de35500c5e08c0ec73a199f854356c50349
  Tags:
  - 5.0.19
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.0"
  File: Dockerfile
  GitCommit: e641751b483a9d59b8878540de86aa3c72c9704d
  Tags:
  - 5.0.17
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.0"
  File: Dockerfile
  GitCommit: 1d6a50b9423b745ae274611088343d9b40bea601
  Tags:
  - 5.0.16
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.0"
  File: Dockerfile
  GitCommit: 26fbd6165d43d3f2f2d6ab55267425cbdc2aa176
  Tags:
  - 5.0.15
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.0"
  File: Dockerfile
  GitCommit: dd291f55ea33fd2567a31b712b504f7df5438021
  Tags:
  - 5.0.14
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "4.4"
  File: Dockerfile
  GitCommit: 851c0845da8078770fb01ff958733f4989e3a8bc
  Tags:
  - 4.4.11
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.0"
  File: Dockerfile
  GitCommit: 6d3892a93f4e6bc3f28bbc23015c46af4d14bec8
  Tags:
  - 5.0.13
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.0"
  File: Dockerfile
  GitCommit: b623c29ceb438c8fad0dd4d508e3ce601f05791f
  Tags:
  - 5.0.12
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.0"
  File: Dockerfile
  GitCommit: 851c0845da8078770fb01ff958733f4989e3a8bc
  Tags:
  - 5.0.11
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "4.3"
  File: Dockerfile
  GitCommit: be51f664546d862443a73c367e48d49eef2393a5
  Tags:
  - 4.3.15
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "4.4"
  File: Dockerfile
  GitCommit: be51f664546d862443a73c367e48d49eef2393a5
  Tags:
  - 4.4.4
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "4.3"
  File: Dockerfile
  GitCommit: 6a9fdac90acb0bda15ec41ba3396150a05435fe8
  Tags:
  - 4.3.5
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "4.4"
  File: Dockerfile
  GitCommit: 15a67ceb5bf2402bca50a7968c9703e7de8fe9da
  Tags:
  - 4.4.3
- Architectures: null
  Directory: "4.4"
  File: Dockerfile
  GitCommit: 6a9fdac90acb0bda15ec41ba3396150a05435fe8
  Tags:
  - 4.4.2
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "5.2"
  File: Dockerfile
  GitCommit: be20872df0bc1def66b1ed203a24c6d17b859890
  Tags:
  - 5.2.0-build.1
GitRepo: https://github.com/emqx/emqx-docker.git
KnownTags:
  "4": {}
  "4.3": {}
  4.3.5: {}
  4.3.15: {}
  4.3.22: {}
  "4.4": {}
  4.4.2: {}
  4.4.3: {}
  4.4.4: {}
  4.4.11: {}
  4.4.14: {}
  4.4.15: {}
  4.4.16: {}
  4.4.17: {}
  4.4.18: {}
  4.4.19: {}
  "5": {}
  "5.0": {}
  5.0.11: {}
  5.0.12: {}
  5.0.13: {}
  5.0.14: {}
  5.0.15: {}
  5.0.16: {}
  5.0.17: {}
  5.0.19: {}
  5.0.20: {}
  5.0.21: {}
  5.0.22: {}
  5.0.23: {}
  5.0.24: {}
  5.0.25: {}
  5.0.26: {}
  "5.1": {}
  5.1.0: {}
  5.1.1: {}
  5.1.2: {}
  5.1.3: {}
  5.1.5-build.3: {}
  5.1.6: {}
  "5.2": {}
  5.2.0-build.1: {}
  5.2.1: {}
  "5.3": {}
  5.3.0: {}
  5.3.1: {}
  5.3.2: {}
  "5.4": {}
  5.4.0: {}
  5.4.1: {}
  "5.5": {}
  5.5.0: {}
  5.5.1: {}
  "5.6": {}
  5.6.0: {}
  5.6.1: {}
  latest: {}
Name: emqx
