Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: mainline/debian
  GitCommit: 7870605f4b93d86e898af291086d77ab9e6b96e3
  Tags:
  - 1.25.1
  - mainline
  - "1"
  - "1.25"
  - latest
  - 1.25.1-bookworm
  - mainline-bookworm
  - 1-bookworm
  - 1.25-bookworm
  - bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: mainline/debian-perl
  GitCommit: 7870605f4b93d86e898af291086d77ab9e6b96e3
  Tags:
  - 1.25.1-perl
  - mainline-perl
  - 1-perl
  - 1.25-perl
  - perl
  - 1.25.1-bookworm-perl
  - mainline-bookworm-perl
  - 1-bookworm-perl
  - 1.25-bookworm-perl
  - bookworm-perl
- Architectures:
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  - i386
  - amd64
  Directory: mainline/alpine
  GitCommit: 7870605f4b93d86e898af291086d77ab9e6b96e3
  Tags:
  - 1.25.1-alpine
  - mainline-alpine
  - 1-alpine
  - 1.25-alpine
  - alpine
  - 1.25.1-alpine3.17
  - mainline-alpine3.17
  - 1-alpine3.17
  - 1.25-alpine3.17
  - alpine3.17
- Architectures:
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  - i386
  - amd64
  Directory: mainline/alpine-perl
  GitCommit: 7870605f4b93d86e898af291086d77ab9e6b96e3
  Tags:
  - 1.25.1-alpine-perl
  - mainline-alpine-perl
  - 1-alpine-perl
  - 1.25-alpine-perl
  - alpine-perl
  - 1.25.1-alpine3.17-perl
  - mainline-alpine3.17-perl
  - 1-alpine3.17-perl
  - 1.25-alpine3.17-perl
  - alpine3.17-perl
- Architectures:
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  - i386
  - amd64
  Directory: mainline/alpine-slim
  GitCommit: 7870605f4b93d86e898af291086d77ab9e6b96e3
  Tags:
  - 1.25.1-alpine-slim
  - mainline-alpine-slim
  - 1-alpine-slim
  - 1.25-alpine-slim
  - alpine-slim
  - 1.25.1-alpine3.17-slim
  - mainline-alpine3.17-slim
  - 1-alpine3.17-slim
  - 1.25-alpine3.17-slim
  - alpine3.17-slim
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: stable/debian
  GitCommit: 1a8d87b69760693a8e33cd8a9e0c2e5f0e8b0e3c
  Tags:
  - 1.24.0
  - stable
  - "1.24"
  - 1.24.0-bullseye
  - stable-bullseye
  - 1.24-bullseye
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: stable/debian-perl
  GitCommit: 1a8d87b69760693a8e33cd8a9e0c2e5f0e8b0e3c
  Tags:
  - 1.24.0-perl
  - stable-perl
  - 1.24-perl
  - 1.24.0-bullseye-perl
  - stable-bullseye-perl
  - 1.24-bullseye-perl
- Architectures:
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  - i386
  - amd64
  Directory: stable/alpine
  GitCommit: 1a8d87b69760693a8e33cd8a9e0c2e5f0e8b0e3c
  Tags:
  - 1.24.0-alpine
  - stable-alpine
  - 1.24-alpine
  - 1.24.0-alpine3.17
  - stable-alpine3.17
  - 1.24-alpine3.17
- Architectures:
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  - i386
  - amd64
  Directory: stable/alpine-perl
  GitCommit: 1a8d87b69760693a8e33cd8a9e0c2e5f0e8b0e3c
  Tags:
  - 1.24.0-alpine-perl
  - stable-alpine-perl
  - 1.24-alpine-perl
  - 1.24.0-alpine3.17-perl
  - stable-alpine3.17-perl
  - 1.24-alpine3.17-perl
- Architectures:
  - arm64v8
  - arm32v6
  - arm32v7
  - ppc64le
  - s390x
  - i386
  - amd64
  Directory: stable/alpine-slim
  GitCommit: 1a8d87b69760693a8e33cd8a9e0c2e5f0e8b0e3c
  Tags:
  - 1.24.0-alpine-slim
  - stable-alpine-slim
  - 1.24-alpine-slim
  - 1.24.0-alpine3.17-slim
  - stable-alpine3.17-slim
  - 1.24-alpine3.17-slim
GitRepo: https://github.com/nginxinc/docker-nginx.git
KnownTags:
  "1": {}
  1-alpine: {}
  1-alpine-perl: {}
  1-alpine-slim: {}
  1-alpine3.17: {}
  1-alpine3.17-perl: {}
  1-alpine3.17-slim: {}
  1-bookworm: {}
  1-bookworm-perl: {}
  1-perl: {}
  "1.24": {}
  1.24-alpine: {}
  1.24-alpine-perl: {}
  1.24-alpine-slim: {}
  1.24-alpine3.17: {}
  1.24-alpine3.17-perl: {}
  1.24-alpine3.17-slim: {}
  1.24-bullseye: {}
  1.24-bullseye-perl: {}
  1.24-perl: {}
  1.24.0: {}
  1.24.0-alpine: {}
  1.24.0-alpine-perl: {}
  1.24.0-alpine-slim: {}
  1.24.0-alpine3.17: {}
  1.24.0-alpine3.17-perl: {}
  1.24.0-alpine3.17-slim: {}
  1.24.0-bullseye: {}
  1.24.0-bullseye-perl: {}
  1.24.0-perl: {}
  "1.25": {}
  1.25-alpine: {}
  1.25-alpine-perl: {}
  1.25-alpine-slim: {}
  1.25-alpine3.17: {}
  1.25-alpine3.17-perl: {}
  1.25-alpine3.17-slim: {}
  1.25-bookworm: {}
  1.25-bookworm-perl: {}
  1.25-perl: {}
  1.25.1: {}
  1.25.1-alpine: {}
  1.25.1-alpine-perl: {}
  1.25.1-alpine-slim: {}
  1.25.1-alpine3.17: {}
  1.25.1-alpine3.17-perl: {}
  1.25.1-alpine3.17-slim: {}
  1.25.1-bookworm: {}
  1.25.1-bookworm-perl: {}
  1.25.1-perl: {}
  alpine: {}
  alpine-perl: {}
  alpine-slim: {}
  alpine3.17: {}
  alpine3.17-perl: {}
  alpine3.17-slim: {}
  bookworm: {}
  bookworm-perl: {}
  latest: {}
  mainline: {}
  mainline-alpine: {}
  mainline-alpine-perl: {}
  mainline-alpine-slim: {}
  mainline-alpine3.17: {}
  mainline-alpine3.17-perl: {}
  mainline-alpine3.17-slim: {}
  mainline-bookworm: {}
  mainline-bookworm-perl: {}
  mainline-perl: {}
  perl: {}
  stable: {}
  stable-alpine: {}
  stable-alpine-perl: {}
  stable-alpine-slim: {}
  stable-alpine3.17: {}
  stable-alpine3.17-perl: {}
  stable-alpine3.17-slim: {}
  stable-bullseye: {}
  stable-bullseye-perl: {}
  stable-perl: {}
Name: nginx
