Blocks:
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: 3.9/bookworm
  GitCommit: 4a2918a33ab52da23ce6cd3b0754ba54521cf1e0
  Tags:
  - 3.9-7.3.12-bookworm
  - 3.9-7.3-bookworm
  - 3.9-7-bookworm
  - 3.9-bookworm
  - 3-7.3.12-bookworm
  - 3-7.3-bookworm
  - 3-7-bookworm
  - 3-bookworm
  - bookworm
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: 3.9/slim-bookworm
  GitCommit: 4a2918a33ab52da23ce6cd3b0754ba54521cf1e0
  Tags:
  - 3.9-7.3.12-slim-bookworm
  - 3.9-7.3-slim-bookworm
  - 3.9-7-slim-bookworm
  - 3.9-slim-bookworm
  - 3-7.3.12-slim-bookworm
  - 3-7.3-slim-bookworm
  - 3-7-slim-bookworm
  - 3-slim-bookworm
  - slim-bookworm
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: 3.9/bullseye
  GitCommit: 4a2918a33ab52da23ce6cd3b0754ba54521cf1e0
  Tags:
  - 3.9-7.3.12-bullseye
  - 3.9-7.3-bullseye
  - 3.9-7-bullseye
  - 3.9-bullseye
  - 3-7.3.12-bullseye
  - 3-7.3-bullseye
  - 3-7-bullseye
  - 3-bullseye
  - bullseye
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: 3.9/slim-bullseye
  GitCommit: 4a2918a33ab52da23ce6cd3b0754ba54521cf1e0
  Tags:
  - 3.9-7.3.12-slim
  - 3.9-7.3-slim
  - 3.9-7-slim
  - 3.9-slim
  - 3-7.3.12-slim
  - 3-7.3-slim
  - 3-7-slim
  - 3-slim
  - slim
  - 3.9-7.3.12-slim-bullseye
  - 3.9-7.3-slim-bullseye
  - 3.9-7-slim-bullseye
  - 3.9-slim-bullseye
  - 3-7.3.12-slim-bullseye
  - 3-7.3-slim-bullseye
  - 3-7-slim-bullseye
  - 3-slim-bullseye
  - slim-bullseye
- Architectures:
  - windows-amd64
  Directory: 3.9/windows/windowsservercore-ltsc2022
  GitCommit: 4a2918a33ab52da23ce6cd3b0754ba54521cf1e0
  Tags:
  - 3.9-7.3.12-windowsservercore-ltsc2022
  - 3.9-7.3-windowsservercore-ltsc2022
  - 3.9-7-windowsservercore-ltsc2022
  - 3.9-windowsservercore-ltsc2022
  - 3-7.3.12-windowsservercore-ltsc2022
  - 3-7.3-windowsservercore-ltsc2022
  - 3-7-windowsservercore-ltsc2022
  - 3-windowsservercore-ltsc2022
  - windowsservercore-ltsc2022
- Architectures:
  - windows-amd64
  Directory: 3.9/windows/windowsservercore-1809
  GitCommit: 4a2918a33ab52da23ce6cd3b0754ba54521cf1e0
  Tags:
  - 3.9-7.3.12-windowsservercore-1809
  - 3.9-7.3-windowsservercore-1809
  - 3.9-7-windowsservercore-1809
  - 3.9-windowsservercore-1809
  - 3-7.3.12-windowsservercore-1809
  - 3-7.3-windowsservercore-1809
  - 3-7-windowsservercore-1809
  - 3-windowsservercore-1809
  - windowsservercore-1809
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: 3.8/bookworm
  GitCommit: 9a9efe06150ce464f288617c8e3ec765bb93250e
  Tags:
  - 3.8-7.3.11-bookworm
  - 3.8-7.3-bookworm
  - 3.8-7-bookworm
  - 3.8-bookworm
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: 3.8/slim-bookworm
  GitCommit: 9a9efe06150ce464f288617c8e3ec765bb93250e
  Tags:
  - 3.8-7.3.11-slim-bookworm
  - 3.8-7.3-slim-bookworm
  - 3.8-7-slim-bookworm
  - 3.8-slim-bookworm
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: 3.8/bullseye
  GitCommit: 9a9efe06150ce464f288617c8e3ec765bb93250e
  Tags:
  - 3.8-7.3.11-bullseye
  - 3.8-7.3-bullseye
  - 3.8-7-bullseye
  - 3.8-bullseye
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: 3.8/slim-bullseye
  GitCommit: 9a9efe06150ce464f288617c8e3ec765bb93250e
  Tags:
  - 3.8-7.3.11-slim
  - 3.8-7.3-slim
  - 3.8-7-slim
  - 3.8-slim
  - 3.8-7.3.11-slim-bullseye
  - 3.8-7.3-slim-bullseye
  - 3.8-7-slim-bullseye
  - 3.8-slim-bullseye
- Architectures:
  - windows-amd64
  Directory: 3.8/windows/windowsservercore-ltsc2022
  GitCommit: 86944b577ee5ad8fe08db64900a9151abd5a8e3b
  Tags:
  - 3.8-7.3.11-windowsservercore-ltsc2022
  - 3.8-7.3-windowsservercore-ltsc2022
  - 3.8-7-windowsservercore-ltsc2022
  - 3.8-windowsservercore-ltsc2022
- Architectures:
  - windows-amd64
  Directory: 3.8/windows/windowsservercore-1809
  GitCommit: 86944b577ee5ad8fe08db64900a9151abd5a8e3b
  Tags:
  - 3.8-7.3.11-windowsservercore-1809
  - 3.8-7.3-windowsservercore-1809
  - 3.8-7-windowsservercore-1809
  - 3.8-windowsservercore-1809
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: 2.7/bookworm
  GitCommit: 7f83ea84de775fa51b6c7c4e66ceafaf14948199
  Tags:
  - 2.7-7.3.12-bookworm
  - 2.7-7.3-bookworm
  - 2.7-7-bookworm
  - 2.7-bookworm
  - 2-7.3.12-bookworm
  - 2-7.3-bookworm
  - 2-7-bookworm
  - 2-bookworm
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: 2.7/slim-bookworm
  GitCommit: 7f83ea84de775fa51b6c7c4e66ceafaf14948199
  Tags:
  - 2.7-7.3.12-slim-bookworm
  - 2.7-7.3-slim-bookworm
  - 2.7-7-slim-bookworm
  - 2.7-slim-bookworm
  - 2-7.3.12-slim-bookworm
  - 2-7.3-slim-bookworm
  - 2-7-slim-bookworm
  - 2-slim-bookworm
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: 2.7/bullseye
  GitCommit: 7f83ea84de775fa51b6c7c4e66ceafaf14948199
  Tags:
  - 2.7-7.3.12-bullseye
  - 2.7-7.3-bullseye
  - 2.7-7-bullseye
  - 2.7-bullseye
  - 2-7.3.12-bullseye
  - 2-7.3-bullseye
  - 2-7-bullseye
  - 2-bullseye
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: 2.7/slim-bullseye
  GitCommit: 7f83ea84de775fa51b6c7c4e66ceafaf14948199
  Tags:
  - 2.7-7.3.12-slim
  - 2.7-7.3-slim
  - 2.7-7-slim
  - 2.7-slim
  - 2-7.3.12-slim
  - 2-7.3-slim
  - 2-7-slim
  - 2-slim
  - 2.7-7.3.12-slim-bullseye
  - 2.7-7.3-slim-bullseye
  - 2.7-7-slim-bullseye
  - 2.7-slim-bullseye
  - 2-7.3.12-slim-bullseye
  - 2-7.3-slim-bullseye
  - 2-7-slim-bullseye
  - 2-slim-bullseye
- Architectures:
  - windows-amd64
  Directory: 2.7/windows/windowsservercore-ltsc2022
  GitCommit: 7f83ea84de775fa51b6c7c4e66ceafaf14948199
  Tags:
  - 2.7-7.3.12-windowsservercore-ltsc2022
  - 2.7-7.3-windowsservercore-ltsc2022
  - 2.7-7-windowsservercore-ltsc2022
  - 2.7-windowsservercore-ltsc2022
  - 2-7.3.12-windowsservercore-ltsc2022
  - 2-7.3-windowsservercore-ltsc2022
  - 2-7-windowsservercore-ltsc2022
  - 2-windowsservercore-ltsc2022
- Architectures:
  - windows-amd64
  Directory: 2.7/windows/windowsservercore-1809
  GitCommit: 7f83ea84de775fa51b6c7c4e66ceafaf14948199
  Tags:
  - 2.7-7.3.12-windowsservercore-1809
  - 2.7-7.3-windowsservercore-1809
  - 2.7-7-windowsservercore-1809
  - 2.7-windowsservercore-1809
  - 2-7.3.12-windowsservercore-1809
  - 2-7.3-windowsservercore-1809
  - 2-7-windowsservercore-1809
  - 2-windowsservercore-1809
GitRepo: https://github.com/docker-library/pypy.git
KnownTags:
  2-7-bookworm: {}
  2-7-bullseye: {}
  2-7-slim: {}
  2-7-slim-bookworm: {}
  2-7-slim-bullseye: {}
  2-7-windowsservercore-1809: {}
  2-7-windowsservercore-ltsc2022: {}
  2-7.3-bookworm: {}
  2-7.3-bullseye: {}
  2-7.3-slim: {}
  2-7.3-slim-bookworm: {}
  2-7.3-slim-bullseye: {}
  2-7.3-windowsservercore-1809: {}
  2-7.3-windowsservercore-ltsc2022: {}
  2-7.3.12-bookworm: {}
  2-7.3.12-bullseye: {}
  2-7.3.12-slim: {}
  2-7.3.12-slim-bookworm: {}
  2-7.3.12-slim-bullseye: {}
  2-7.3.12-windowsservercore-1809: {}
  2-7.3.12-windowsservercore-ltsc2022: {}
  2-bookworm: {}
  2-bullseye: {}
  2-slim: {}
  2-slim-bookworm: {}
  2-slim-bullseye: {}
  2-windowsservercore-1809: {}
  2-windowsservercore-ltsc2022: {}
  2.7-7-bookworm: {}
  2.7-7-bullseye: {}
  2.7-7-slim: {}
  2.7-7-slim-bookworm: {}
  2.7-7-slim-bullseye: {}
  2.7-7-windowsservercore-1809: {}
  2.7-7-windowsservercore-ltsc2022: {}
  2.7-7.3-bookworm: {}
  2.7-7.3-bullseye: {}
  2.7-7.3-slim: {}
  2.7-7.3-slim-bookworm: {}
  2.7-7.3-slim-bullseye: {}
  2.7-7.3-windowsservercore-1809: {}
  2.7-7.3-windowsservercore-ltsc2022: {}
  2.7-7.3.12-bookworm: {}
  2.7-7.3.12-bullseye: {}
  2.7-7.3.12-slim: {}
  2.7-7.3.12-slim-bookworm: {}
  2.7-7.3.12-slim-bullseye: {}
  2.7-7.3.12-windowsservercore-1809: {}
  2.7-7.3.12-windowsservercore-ltsc2022: {}
  2.7-bookworm: {}
  2.7-bullseye: {}
  2.7-slim: {}
  2.7-slim-bookworm: {}
  2.7-slim-bullseye: {}
  2.7-windowsservercore-1809: {}
  2.7-windowsservercore-ltsc2022: {}
  3-7-bookworm: {}
  3-7-bullseye: {}
  3-7-slim: {}
  3-7-slim-bookworm: {}
  3-7-slim-bullseye: {}
  3-7-windowsservercore-1809: {}
  3-7-windowsservercore-ltsc2022: {}
  3-7.3-bookworm: {}
  3-7.3-bullseye: {}
  3-7.3-slim: {}
  3-7.3-slim-bookworm: {}
  3-7.3-slim-bullseye: {}
  3-7.3-windowsservercore-1809: {}
  3-7.3-windowsservercore-ltsc2022: {}
  3-7.3.12-bookworm: {}
  3-7.3.12-bullseye: {}
  3-7.3.12-slim: {}
  3-7.3.12-slim-bookworm: {}
  3-7.3.12-slim-bullseye: {}
  3-7.3.12-windowsservercore-1809: {}
  3-7.3.12-windowsservercore-ltsc2022: {}
  3-bookworm: {}
  3-bullseye: {}
  3-slim: {}
  3-slim-bookworm: {}
  3-slim-bullseye: {}
  3-windowsservercore-1809: {}
  3-windowsservercore-ltsc2022: {}
  3.8-7-bookworm: {}
  3.8-7-bullseye: {}
  3.8-7-slim: {}
  3.8-7-slim-bookworm: {}
  3.8-7-slim-bullseye: {}
  3.8-7-windowsservercore-1809: {}
  3.8-7-windowsservercore-ltsc2022: {}
  3.8-7.3-bookworm: {}
  3.8-7.3-bullseye: {}
  3.8-7.3-slim: {}
  3.8-7.3-slim-bookworm: {}
  3.8-7.3-slim-bullseye: {}
  3.8-7.3-windowsservercore-1809: {}
  3.8-7.3-windowsservercore-ltsc2022: {}
  3.8-7.3.11-bookworm: {}
  3.8-7.3.11-bullseye: {}
  3.8-7.3.11-slim: {}
  3.8-7.3.11-slim-bookworm: {}
  3.8-7.3.11-slim-bullseye: {}
  3.8-7.3.11-windowsservercore-1809: {}
  3.8-7.3.11-windowsservercore-ltsc2022: {}
  3.8-bookworm: {}
  3.8-bullseye: {}
  3.8-slim: {}
  3.8-slim-bookworm: {}
  3.8-slim-bullseye: {}
  3.8-windowsservercore-1809: {}
  3.8-windowsservercore-ltsc2022: {}
  3.9-7-bookworm: {}
  3.9-7-bullseye: {}
  3.9-7-slim: {}
  3.9-7-slim-bookworm: {}
  3.9-7-slim-bullseye: {}
  3.9-7-windowsservercore-1809: {}
  3.9-7-windowsservercore-ltsc2022: {}
  3.9-7.3-bookworm: {}
  3.9-7.3-bullseye: {}
  3.9-7.3-slim: {}
  3.9-7.3-slim-bookworm: {}
  3.9-7.3-slim-bullseye: {}
  3.9-7.3-windowsservercore-1809: {}
  3.9-7.3-windowsservercore-ltsc2022: {}
  3.9-7.3.12-bookworm: {}
  3.9-7.3.12-bullseye: {}
  3.9-7.3.12-slim: {}
  3.9-7.3.12-slim-bookworm: {}
  3.9-7.3.12-slim-bullseye: {}
  3.9-7.3.12-windowsservercore-1809: {}
  3.9-7.3.12-windowsservercore-ltsc2022: {}
  3.9-bookworm: {}
  3.9-bullseye: {}
  3.9-slim: {}
  3.9-slim-bookworm: {}
  3.9-slim-bullseye: {}
  3.9-windowsservercore-1809: {}
  3.9-windowsservercore-ltsc2022: {}
  bookworm: {}
  bullseye: {}
  slim: {}
  slim-bookworm: {}
  slim-bullseye: {}
  windowsservercore-1809: {}
  windowsservercore-ltsc2022: {}
Name: pypy
