Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: ""
  GitCommit: ""
  Tags:
  - "2023"
  - latest
  - 2023.0.20230614.0
- Architectures:
  - amd64
  - arm64v8
  Directory: ""
  GitCommit: ""
  Tags:
  - "2"
  - 2.0.20230612.0
- Architectures:
  - amd64
  Directory: ""
  GitCommit: ""
  Tags:
  - "1"
  - "2018.03"
  - 2018.03.0.20230607.0
GitRepo: https://github.com/amazonlinux/container-images.git
KnownTags:
  "1": {}
  "2": {}
  2.0.20230612.0: {}
  "2018.03": {}
  2018.03.0.20230607.0: {}
  "2023": {}
  2023.0.20230614.0: {}
  latest: {}
Name: amazonlinux
