Blocks:
- Architectures:
  - amd64
  Directory: "7.10"
  GitCommit: f253a2398dbc39b42ca6ff84f2adeda8c1e8287e
  Tags:
  - "7.10"
  - "7"
  - LTS-2015
- Architectures:
  - amd64
  Directory: "8.10"
  GitCommit: f253a2398dbc39b42ca6ff84f2adeda8c1e8287e
  Tags:
  - "8.10"
  - "8"
  - LTS-2016
- Architectures:
  - amd64
  Directory: "9.10"
  GitCommit: f253a2398dbc39b42ca6ff84f2adeda8c1e8287e
  Tags:
  - "9.10"
  - "9"
  - LTS-2017
- Architectures:
  - amd64
  Directory: "10.10"
  GitCommit: f253a2398dbc39b42ca6ff84f2adeda8c1e8287e
  Tags:
  - "10.10"
  - "10"
  - LTS-2019
  - LTS
  - FT
  - latest
- Architectures: null
  Directory: "10.1"
  GitCommit: 25b599a0a9a26412d00915506b080ec85e1dc56d
  Tags:
  - "10.1"
- Architectures: null
  Directory: "10.2"
  GitCommit: 5c0031a6e7ac1f52a9ce80b26fd8e764d319a8b0
  Tags:
  - "10.2"
- Architectures: null
  Directory: "10.3"
  GitCommit: 7be68c0016f9697792dfe01129e9ab12f47bfe3e
  Tags:
  - "10.3"
- Architectures: null
  Directory: "9.3"
  GitCommit: 261cb4cb5bee049a8c756366b5257b4bc48e811d
  Tags:
  - "9.3"
- Architectures: null
  Directory: "6.0"
  GitCommit: 4da3ff891d3d6911304cbbe0895333ae4c84ffa7
  Tags:
  - "6.0"
  - "6"
  - LTS-2014
- Architectures: null
  Directory: "9.2"
  GitCommit: 2a9207e3abcb6db16311af3c7548cef3fbd1638c
  Tags:
  - "9.2"
- Architectures: null
  Directory: "9.1"
  GitCommit: 20df98ce84f12cd3cfdcfd08ab8c9e029f7f01ab
  Tags:
  - "9.1"
- Architectures: null
  Directory: "8.3"
  GitCommit: ""
  Tags:
  - "8.3"
- Architectures: null
  Directory: "8.2"
  GitCommit: ""
  Tags:
  - "8.2"
GitRepo: https://github.com/nuxeo/docker-nuxeo.git
KnownTags:
  "6": {}
  "6.0": {}
  "7": {}
  "7.10": {}
  "8": {}
  "8.2": {}
  "8.3": {}
  "8.10": {}
  "9": {}
  "9.1": {}
  "9.2": {}
  "9.3": {}
  "9.10": {}
  "10": {}
  "10.1": {}
  "10.2": {}
  "10.3": {}
  "10.10": {}
  FT: {}
  LTS: {}
  LTS-2014: {}
  LTS-2015: {}
  LTS-2016: {}
  LTS-2017: {}
  LTS-2019: {}
  latest: {}
Name: nuxeo
