Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  GitCommit: a40c8da9d2c2925bdd78b9a6d1b6da3fe89322d1
  Tags:
  - 5.6.0
  - "5.6"
  - "5"
  - latest
GitRepo: https://github.com/kaazing/gateway.docker.git
KnownTags:
  "5": {}
  "5.6": {}
  5.6.0: {}
  latest: {}
Name: kaazing-gateway
