Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: "13"
  GitCommit: 46628bc0702798f6ff9f923650361f46f9eb2af2
  Tags:
  - 13.1.0
  - "13.1"
  - "13"
  - latest
  - 13.1.0-bookworm
  - 13.1-bookworm
  - 13-bookworm
  - bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: "12"
  GitCommit: 9677600371602a897f576cf1d85852a3a26f71af
  Tags:
  - 12.3.0
  - "12.3"
  - "12"
  - 12.3.0-bookworm
  - 12.3-bookworm
  - 12-bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: "11"
  GitCommit: 8896a6fe1d596abcaea6c75c98337885ba4c27e8
  Tags:
  - 11.4.0
  - "11.4"
  - "11"
  - 11.4.0-bookworm
  - 11.4-bookworm
  - 11-bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: "10"
  GitCommit: 392d8bf4ee9d494f03331c540c1f0d7f32259ff1
  Tags:
  - 10.4.0
  - "10.4"
  - "10"
  - 10.4.0-bookworm
  - 10.4-bookworm
  - 10-bookworm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: "9"
  GitCommit: 0d98f7923b5ed7f5baec2506413c99e920cf6661
  Tags:
  - 9.5.0
  - "9.5"
  - "9"
  - 9.5.0-bookworm
  - 9.5-bookworm
  - 9-bookworm
GitRepo: https://github.com/docker-library/gcc.git
KnownTags:
  "9": {}
  9-bookworm: {}
  "9.5": {}
  9.5-bookworm: {}
  9.5.0: {}
  9.5.0-bookworm: {}
  "10": {}
  10-bookworm: {}
  "10.4": {}
  10.4-bookworm: {}
  10.4.0: {}
  10.4.0-bookworm: {}
  "11": {}
  11-bookworm: {}
  "11.4": {}
  11.4-bookworm: {}
  11.4.0: {}
  11.4.0-bookworm: {}
  "12": {}
  12-bookworm: {}
  "12.3": {}
  12.3-bookworm: {}
  12.3.0: {}
  12.3.0-bookworm: {}
  "13": {}
  13-bookworm: {}
  "13.1": {}
  13.1-bookworm: {}
  13.1.0: {}
  13.1.0-bookworm: {}
  bookworm: {}
  latest: {}
Name: gcc
