Blocks:
- Architectures: null
  Directory: ""
  File: Dockerfile
  GitCommit: 079c4169361e913b9477fc1fd93692974d4f10c5
  Tags:
  - "4.29"
  - 4.29.2
  - latest
- Architectures: null
  Directory: ""
  File: Dockerfile.alpine
  GitCommit: 079c4169361e913b9477fc1fd93692974d4f10c5
  Tags:
  - 4.29-alpine
  - 4.29.2-alpine
  - alpine
- Architectures: null
  Directory: ""
  File: Dockerfile
  GitCommit: 07e271e1a0d33b7670c5abcaf940e83bc0d17418
  Tags:
  - 4.29.1
- Architectures: null
  Directory: ""
  File: Dockerfile.alpine
  GitCommit: 07e271e1a0d33b7670c5abcaf940e83bc0d17418
  Tags:
  - 4.29.1-alpine
- Architectures: null
  Directory: ""
  File: Dockerfile
  GitCommit: 6903fb3ab80cde8a9a763fd230bfa66449fe5ca5
  Tags:
  - 4.29.0
- Architectures: null
  Directory: ""
  File: Dockerfile.alpine
  GitCommit: 6903fb3ab80cde8a9a763fd230bfa66449fe5ca5
  Tags:
  - 4.29.0-alpine
- Architectures: null
  Directory: ""
  File: Dockerfile
  GitCommit: 666d1c82ff5b6f3a282a7dc2767ae6d95be82ad3
  Tags:
  - "4.28"
  - 4.28.0
  - 4.28.0.1
- Architectures: null
  Directory: ""
  File: Dockerfile.alpine
  GitCommit: 666d1c82ff5b6f3a282a7dc2767ae6d95be82ad3
  Tags:
  - 4.28-alpine
  - 4.28.0-alpine
  - 4.28.0.1-alpine
- Architectures: null
  Directory: ""
  File: Dockerfile
  GitCommit: 7229778e4e912224ff54dbae0e05aae149544ed2
  Tags:
  - "4.27"
  - 4.27.0
- Architectures: null
  Directory: ""
  File: Dockerfile.alpine
  GitCommit: 7229778e4e912224ff54dbae0e05aae149544ed2
  Tags:
  - 4.27-alpine
  - 4.27.0-alpine
GitRepo: https://github.com/liquibase/docker.git
KnownTags:
  "4.27": {}
  4.27-alpine: {}
  4.27.0: {}
  4.27.0-alpine: {}
  "4.28": {}
  4.28-alpine: {}
  4.28.0: {}
  4.28.0-alpine: {}
  4.28.0.1: {}
  4.28.0.1-alpine: {}
  "4.29": {}
  4.29-alpine: {}
  4.29.0: {}
  4.29.0-alpine: {}
  4.29.1: {}
  4.29.1-alpine: {}
  4.29.2: {}
  4.29.2-alpine: {}
  alpine: {}
  latest: {}
Name: liquibase
