Blocks:
- Architectures: null
  Directory: ""
  File: Dockerfile
  GitCommit: 7229778e4e912224ff54dbae0e05aae149544ed2
  Tags:
  - "4.27"
  - 4.27.0
  - latest
- Architectures: null
  Directory: ""
  File: Dockerfile.alpine
  GitCommit: 7229778e4e912224ff54dbae0e05aae149544ed2
  Tags:
  - 4.27-alpine
  - 4.27.0-alpine
  - alpine
GitRepo: https://github.com/liquibase/docker.git
KnownTags:
  "4.27": {}
  4.27-alpine: {}
  4.27.0: {}
  4.27.0-alpine: {}
  alpine: {}
  latest: {}
Name: liquibase
