Blocks:
- Architectures: null
  Directory: ""
  File: Dockerfile
  GitCommit: e54a7dd42e0afd00fa3a85d3ef3d90a3b583c613
  Tags:
  - "4.33"
  - 4.33.0
  - latest
- Architectures: null
  Directory: ""
  File: Dockerfile.alpine
  GitCommit: e54a7dd42e0afd00fa3a85d3ef3d90a3b583c613
  Tags:
  - 4.33-alpine
  - 4.33.0-alpine
  - alpine
- Architectures: null
  Directory: ""
  File: Dockerfile
  GitCommit: 5f25f074861b619a8bd3a3147d3ceeafb672f717
  Tags:
  - "4.32"
  - 4.32.0
- Architectures: null
  Directory: ""
  File: Dockerfile.alpine
  GitCommit: 5f25f074861b619a8bd3a3147d3ceeafb672f717
  Tags:
  - 4.32-alpine
  - 4.32.0-alpine
- Architectures: null
  Directory: ""
  File: Dockerfile
  GitCommit: 721daba2f67968383d82ce61e2f6891f444685ee
  Tags:
  - "4.31"
  - 4.31.1
- Architectures: null
  Directory: ""
  File: Dockerfile.alpine
  GitCommit: 721daba2f67968383d82ce61e2f6891f444685ee
  Tags:
  - 4.31-alpine
  - 4.31.1-alpine
- Architectures: null
  Directory: ""
  File: Dockerfile
  GitCommit: e348326855672a5d20d1789cfdab1ac8b2a6afa2
  Tags:
  - 4.31.0
- Architectures: null
  Directory: ""
  File: Dockerfile.alpine
  GitCommit: e348326855672a5d20d1789cfdab1ac8b2a6afa2
  Tags:
  - 4.31.0-alpine
- Architectures: null
  Directory: ""
  File: Dockerfile
  GitCommit: f86be8a84c919e1c3a6c8d9f9917cf3ee1c3f455
  Tags:
  - "4.30"
  - 4.30.0
- Architectures: null
  Directory: ""
  File: Dockerfile.alpine
  GitCommit: f86be8a84c919e1c3a6c8d9f9917cf3ee1c3f455
  Tags:
  - 4.30-alpine
  - 4.30.0-alpine
- Architectures: null
  Directory: ""
  File: Dockerfile
  GitCommit: 13d063767623e282539b232a3a9ed19f4b3d7bbd
  Tags:
  - "4.29"
  - 4.29.2
- Architectures: null
  Directory: ""
  File: Dockerfile.alpine
  GitCommit: 13d063767623e282539b232a3a9ed19f4b3d7bbd
  Tags:
  - 4.29-alpine
  - 4.29.2-alpine
- Architectures: null
  Directory: ""
  File: Dockerfile
  GitCommit: 07e271e1a0d33b7670c5abcaf940e83bc0d17418
  Tags:
  - 4.29.1
- Architectures: null
  Directory: ""
  File: Dockerfile.alpine
  GitCommit: 07e271e1a0d33b7670c5abcaf940e83bc0d17418
  Tags:
  - 4.29.1-alpine
- Architectures: null
  Directory: ""
  File: Dockerfile
  GitCommit: 6903fb3ab80cde8a9a763fd230bfa66449fe5ca5
  Tags:
  - 4.29.0
- Architectures: null
  Directory: ""
  File: Dockerfile.alpine
  GitCommit: 6903fb3ab80cde8a9a763fd230bfa66449fe5ca5
  Tags:
  - 4.29.0-alpine
- Architectures: null
  Directory: ""
  File: Dockerfile
  GitCommit: 666d1c82ff5b6f3a282a7dc2767ae6d95be82ad3
  Tags:
  - "4.28"
  - 4.28.0
  - 4.28.0.1
- Architectures: null
  Directory: ""
  File: Dockerfile.alpine
  GitCommit: 666d1c82ff5b6f3a282a7dc2767ae6d95be82ad3
  Tags:
  - 4.28-alpine
  - 4.28.0-alpine
  - 4.28.0.1-alpine
- Architectures: null
  Directory: ""
  File: Dockerfile
  GitCommit: 7229778e4e912224ff54dbae0e05aae149544ed2
  Tags:
  - "4.27"
  - 4.27.0
- Architectures: null
  Directory: ""
  File: Dockerfile.alpine
  GitCommit: 7229778e4e912224ff54dbae0e05aae149544ed2
  Tags:
  - 4.27-alpine
  - 4.27.0-alpine
GitRepo: https://github.com/liquibase/docker.git
KnownTags:
  "4.27": {}
  4.27-alpine: {}
  4.27.0: {}
  4.27.0-alpine: {}
  "4.28": {}
  4.28-alpine: {}
  4.28.0: {}
  4.28.0-alpine: {}
  4.28.0.1: {}
  4.28.0.1-alpine: {}
  "4.29": {}
  4.29-alpine: {}
  4.29.0: {}
  4.29.0-alpine: {}
  4.29.1: {}
  4.29.1-alpine: {}
  4.29.2: {}
  4.29.2-alpine: {}
  "4.30": {}
  4.30-alpine: {}
  4.30.0: {}
  4.30.0-alpine: {}
  "4.31": {}
  4.31-alpine: {}
  4.31.0: {}
  4.31.0-alpine: {}
  4.31.1: {}
  4.31.1-alpine: {}
  "4.32": {}
  4.32-alpine: {}
  4.32.0: {}
  4.32.0-alpine: {}
  "4.33": {}
  4.33-alpine: {}
  4.33.0: {}
  4.33.0-alpine: {}
  alpine: {}
  latest: {}
Name: liquibase
