Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 2023.05/apache
  GitCommit: cf6182cea754b768b60605543807c7afb6fcb993
  Tags:
  - 2023.05-apache
  - apache
  - stable-apache
  - "2023.05"
  - latest
  - stable
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 2023.05/fpm
  GitCommit: cf6182cea754b768b60605543807c7afb6fcb993
  Tags:
  - 2023.05-fpm
  - fpm
  - stable-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2023.05/fpm-alpine
  GitCommit: cf6182cea754b768b60605543807c7afb6fcb993
  Tags:
  - 2023.05-fpm-alpine
  - fpm-alpine
  - stable-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 2023.09-dev/apache
  GitCommit: cf6182cea754b768b60605543807c7afb6fcb993
  Tags:
  - 2023.09-dev-apache
  - dev-apache
  - 2023.09-dev
  - dev
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: 2023.09-dev/fpm
  GitCommit: cf6182cea754b768b60605543807c7afb6fcb993
  Tags:
  - 2023.09-dev-fpm
  - dev-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2023.09-dev/fpm-alpine
  GitCommit: cf6182cea754b768b60605543807c7afb6fcb993
  Tags:
  - 2023.09-dev-fpm-alpine
  - dev-fpm-alpine
GitRepo: https://github.com/friendica/docker.git
KnownTags:
  "2023.05": {}
  2023.05-apache: {}
  2023.05-fpm: {}
  2023.05-fpm-alpine: {}
  2023.09-dev: {}
  2023.09-dev-apache: {}
  2023.09-dev-fpm: {}
  2023.09-dev-fpm-alpine: {}
  apache: {}
  dev: {}
  dev-apache: {}
  dev-fpm: {}
  dev-fpm-alpine: {}
  fpm: {}
  fpm-alpine: {}
  latest: {}
  stable: {}
  stable-apache: {}
  stable-fpm: {}
  stable-fpm-alpine: {}
Name: friendica
