Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: 2.3.1809/x86_64/
      File: ""
      GitCommit: db22e2c392c3922d2c674110c90667576618f348
      GitFetch: refs/heads/v2.3.1809-amd64
    arm64v8:
      Architecture: arm64v8
      Directory: 2.3.1809/aarch64/
      File: ""
      GitCommit: 6b013446976a40f497470975238f5d002d9fff30
      GitFetch: refs/heads/v2.3.1809-arm64
  Directory: ""
  GitCommit: ""
  Tags:
  - 2.3.1809
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: 2.3.1806/x86_64/
      File: ""
      GitCommit: e304245f74141e6e856a017c8d204c27300c1da8
      GitFetch: refs/heads/v2.3.1806-amd64
    arm64v8:
      Architecture: arm64v8
      Directory: 2.3.1806/aarch64/
      File: ""
      GitCommit: 3cc318b6aaaeb3c69c3ee577f06c1a42c20c9ec5
      GitFetch: refs/heads/v2.3.1806-arm64
  Directory: ""
  GitCommit: ""
  Tags:
  - 2.3.1806
- Architectures:
    amd64:
      Architecture: amd64
      Directory: 2.3.1803/x86_64/
      File: ""
      GitCommit: 5afd15edcd49671adefb6dff87537f2943ae1107
      GitFetch: refs/heads/v2.3.1803-amd64
    arm64v8:
      Architecture: arm64v8
      Directory: 2.3.1803/aarch64/
      File: ""
      GitCommit: 319851fa9feead40201cb2a20b6b8b65e0815429
      GitFetch: refs/heads/v2.3.1803-arm64
  Directory: ""
  GitCommit: ""
  Tags:
  - 2.3.1803
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: "2.2"
  GitCommit: 959f378638f222bd1eebe8dccf267cccbc118174
  Tags:
  - "2.2"
GitRepo: https://github.com/euleros/euleros-docker-images.git
KnownTags:
  "2.2": {}
  2.3.1803: {}
  2.3.1806: {}
  2.3.1809: {}
  latest: {}
Name: euleros
