Blocks:
- Architectures:
  - arm64v8
  - amd64
  Directory: ""
  GitCommit: ""
  Tags:
  - 2.3.1809
  - latest
- Architectures:
  - arm64v8
  - amd64
  Directory: ""
  GitCommit: ""
  Tags:
  - 2.3.1806
- Architectures:
  - arm64v8
  - amd64
  Directory: ""
  GitCommit: ""
  Tags:
  - 2.3.1803
- Architectures:
  - amd64
  Directory: "2.2"
  GitCommit: 959f378638f222bd1eebe8dccf267cccbc118174
  Tags:
  - "2.2"
GitRepo: https://github.com/euleros/euleros-docker-images.git
KnownTags:
  "2.2": {}
  2.3.1803: {}
  2.3.1806: {}
  2.3.1809: {}
  latest: {}
Name: euleros
