Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: ""
  GitCommit: 067e6df19c568e101a42dc71b77f6a2de5992c70
  Tags:
  - "8"
  - latest
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: ""
  GitCommit: 067e6df19c568e101a42dc71b77f6a2de5992c70
  Tags:
  - "7"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: ""
  GitCommit: 067e6df19c568e101a42dc71b77f6a2de5992c70
  Tags:
  - cauldron
GitRepo: https://github.com/juanluisbaptiste/docker-brew-mageia.git
KnownTags:
  "7": {}
  "8": {}
  cauldron: {}
  latest: {}
Name: mageia
