Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: dist/8/x86_64
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: dist/8/armv7hl
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: dist/8/aarch64
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  GitCommit: 067e6df19c568e101a42dc71b77f6a2de5992c70
  Tags:
  - "8"
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: dist/7/x86_64
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: dist/7/armv7hl
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: dist/7/aarch64
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  GitCommit: 067e6df19c568e101a42dc71b77f6a2de5992c70
  Tags:
  - "7"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: dist/cauldron/x86_64
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: dist/cauldron/armv7hl
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: dist/cauldron/aarch64
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  GitCommit: 067e6df19c568e101a42dc71b77f6a2de5992c70
  Tags:
  - cauldron
- Architectures:
    amd64:
      Architecture: amd64
      Directory: dist/8/x86_64
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: dist/8/armv7hl
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: dist/8/aarch64
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  GitCommit: 82850f6d718b6acb6ecb279ace398a6c219b0d1e
  Tags:
  - rc
- Architectures:
    amd64:
      Architecture: amd64
      Directory: dist/6/x86_64
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: dist/6/armv7hl
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  GitCommit: ""
  Tags:
  - "6"
- Architectures: null
  Directory: "5"
  GitCommit: f60e1b20a5e31e72b4f49c878160dfa95f49a911
  Tags:
  - "5"
  - "5.1"
GitRepo: https://github.com/juanluisbaptiste/docker-brew-mageia.git
KnownTags:
  "5": {}
  "5.1": {}
  "6": {}
  "7": {}
  "8": {}
  cauldron: {}
  latest: {}
  rc: {}
Name: mageia
