Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2.9.3
  File: ""
  GitCommit: bac1c35e5818831f0669176ab140e34705185b55
  Tags:
  - 2.9.3
  - "2.9"
  - "2"
  - latest
GitRepo: https://github.com/krakendio/docker-library.git
KnownTags:
  "2": {}
  "2.9": {}
  2.9.3: {}
  latest: {}
Name: krakend
