Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2.10.2
  File: ""
  GitCommit: 3017b6a9345534b54243c35b76f865121e8d50bf
  Tags:
  - 2.10.2
  - "2.10"
  - "2"
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2.10.1
  File: ""
  GitCommit: 12b7569e8fd292713ce18bcc4eb1e4e033e1f721
  Tags:
  - 2.10.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2.10.0
  File: ""
  GitCommit: e251c6c6db51dcd34e11cc507830cfc200d652c1
  Tags:
  - 2.10.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2.9.4
  File: ""
  GitCommit: 899edf02008935285c06b651706d74c275459420
  Tags:
  - 2.9.4
  - "2.9"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 2.9.3
  File: ""
  GitCommit: bac1c35e5818831f0669176ab140e34705185b55
  Tags:
  - 2.9.3
GitRepo: https://github.com/krakendio/docker-library.git
KnownTags:
  "2": {}
  "2.9": {}
  2.9.3: {}
  2.9.4: {}
  "2.10": {}
  2.10.0: {}
  2.10.1: {}
  2.10.2: {}
  latest: {}
Name: krakend
