Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: ""
  GitCommit: ""
  Tags:
  - "3.4"
  - latest
- Architectures:
  - amd64
  - arm64v8
  Directory: ""
  GitCommit: ""
  Tags:
  - "3.2"
GitRepo: https://github.com/cruxlinux/docker-crux
KnownTags:
  "3.2": {}
  "3.4": {}
  latest: {}
Name: crux
