Blocks:
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: v1.16/alpine
  GitCommit: b1a4d1d1ff36c6904c7f4a5e94a09e7938dab9ef
  Tags:
  - v1.16.0-1.0
  - v1.16-1
  - latest
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: v1.16/debian
  GitCommit: b1a4d1d1ff36c6904c7f4a5e94a09e7938dab9ef
  Tags:
  - v1.16.0-debian-1.0
  - v1.16-debian-1
GitRepo: https://github.com/fluent/fluentd-docker-image.git
KnownTags:
  latest: {}
  v1.16-1: {}
  v1.16-debian-1: {}
  v1.16.0-1.0: {}
  v1.16.0-debian-1.0: {}
Name: fluentd
