Blocks:
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: v1.16/alpine
  GitCommit: b1a4d1d1ff36c6904c7f4a5e94a09e7938dab9ef
  Tags:
  - v1.16.0-1.0
  - v1.16-1
  - latest
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: v1.16/debian
  GitCommit: b1a4d1d1ff36c6904c7f4a5e94a09e7938dab9ef
  Tags:
  - v1.16.0-debian-1.0
  - v1.16-debian-1
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: v1.14/alpine
  GitCommit: a9e4cee765c7aaf7876d6fe3282aa565dbcdc2a4
  Tags:
  - v1.14.0-1.0
  - v1.14-1
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: v1.14/debian
  GitCommit: a9e4cee765c7aaf7876d6fe3282aa565dbcdc2a4
  Tags:
  - v1.14.0-debian-1.0
  - v1.14-debian-1
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: v1.9/alpine
  GitCommit: b9cb2826b85900f960e256b2426a033e7cacfd6c
  Tags:
  - v1.9.1-1.0
  - v1.9-1
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: v1.9/debian
  GitCommit: b9cb2826b85900f960e256b2426a033e7cacfd6c
  Tags:
  - v1.9.1-debian-1.0
  - v1.9-debian-1
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: v1.8/alpine
  GitCommit: 739d5d6407264a79669f008e9859d87d83e84c32
  Tags:
  - v1.8.1-1.0
  - v1.8-1
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: v1.8/debian
  GitCommit: 739d5d6407264a79669f008e9859d87d83e84c32
  Tags:
  - v1.8.1-debian-1.0
  - v1.8-debian-1
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: v1.6/alpine
  GitCommit: afd86b680c14633d7ebdb2d6c24cab5ae6183826
  Tags:
  - v1.6.2-1.0
  - v1.6-1
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: v1.6/debian
  GitCommit: afd86b680c14633d7ebdb2d6c24cab5ae6183826
  Tags:
  - v1.6.2-debian-1.0
  - v1.6-debian-1
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: v1.4/alpine
  GitCommit: dabca3c327d08be6d43a8919316a57ca2228e603
  Tags:
  - v1.4.2-2.0
  - v1.4-2
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: v1.4/debian
  GitCommit: dabca3c327d08be6d43a8919316a57ca2228e603
  Tags:
  - v1.4.2-debian-2.0
  - v1.4-debian-2
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: v1.3/alpine
  GitCommit: 82b73cc11a01626efb95f4f78fa0b67653602d61
  Tags:
  - v1.3.3-1.0
  - v1.3-1
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: v1.3/alpine-onbuild
  GitCommit: 82b73cc11a01626efb95f4f78fa0b67653602d61
  Tags:
  - v1.3.3-onbuild-1.0
  - v1.3-onbuild-1
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: v1.3/debian
  GitCommit: 82b73cc11a01626efb95f4f78fa0b67653602d61
  Tags:
  - v1.3.3-debian-1.0
  - v1.3-debian-1
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: v1.3/debian-onbuild
  GitCommit: 82b73cc11a01626efb95f4f78fa0b67653602d61
  Tags:
  - v1.3.3-debian-onbuild-1.0
  - v1.3-debian-onbuild-1
GitRepo: https://github.com/fluent/fluentd-docker-image.git
KnownTags:
  latest: {}
  v1.3-1: {}
  v1.3-debian-1: {}
  v1.3-debian-onbuild-1: {}
  v1.3-onbuild-1: {}
  v1.3.3-1.0: {}
  v1.3.3-debian-1.0: {}
  v1.3.3-debian-onbuild-1.0: {}
  v1.3.3-onbuild-1.0: {}
  v1.4-2: {}
  v1.4-debian-2: {}
  v1.4.2-2.0: {}
  v1.4.2-debian-2.0: {}
  v1.6-1: {}
  v1.6-debian-1: {}
  v1.6.2-1.0: {}
  v1.6.2-debian-1.0: {}
  v1.8-1: {}
  v1.8-debian-1: {}
  v1.8.1-1.0: {}
  v1.8.1-debian-1.0: {}
  v1.9-1: {}
  v1.9-debian-1: {}
  v1.9.1-1.0: {}
  v1.9.1-debian-1.0: {}
  v1.14-1: {}
  v1.14-debian-1: {}
  v1.14.0-1.0: {}
  v1.14.0-debian-1.0: {}
  v1.16-1: {}
  v1.16-debian-1: {}
  v1.16.0-1.0: {}
  v1.16.0-debian-1.0: {}
Name: fluentd
