Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: b711c66be5de3caade38361bd974134e1291a929
  Tags:
  - 3.6.0-apache
  - 3.6-apache
  - 3-apache
  - apache
  - 3.6.0
  - "3.6"
  - "3"
  - latest
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: b711c66be5de3caade38361bd974134e1291a929
  Tags:
  - 3.6.0-fpm
  - 3.6-fpm
  - 3-fpm
  - fpm
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: b711c66be5de3caade38361bd974134e1291a929
  Tags:
  - 3.6.0-fpm-alpine
  - 3.6-fpm-alpine
  - 3-fpm-alpine
  - fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 89d38796efe1063e84d8dee3e7c74d04cb240abc
  Tags:
  - 3.5.1-apache
  - 3.5-apache
  - 3.5.1
  - "3.5"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 89d38796efe1063e84d8dee3e7c74d04cb240abc
  Tags:
  - 3.5.1-fpm
  - 3.5-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 89d38796efe1063e84d8dee3e7c74d04cb240abc
  Tags:
  - 3.5.1-fpm-alpine
  - 3.5-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: edd76a3640e34e8318f7dbb08b4875838cb83e0c
  Tags:
  - 3.5.0-apache
  - 3.5.0
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: edd76a3640e34e8318f7dbb08b4875838cb83e0c
  Tags:
  - 3.5.0-fpm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: c985c710bcd7ff07a79efd60433bc7f0d1674c28
  Tags:
  - 3.4.0-apache
  - 3.4-apache
  - 3.4.0
  - "3.4"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: c985c710bcd7ff07a79efd60433bc7f0d1674c28
  Tags:
  - 3.4.0-fpm
  - 3.4-fpm
- Architectures: null
  Directory: apache
  GitCommit: f2d71a5128a243c2791d1626b10d6637a5a40ced
  Tags:
  - 3.3.0-apache
  - 3.3-apache
  - 3.3.0
  - "3.3"
- Architectures: null
  Directory: fpm
  GitCommit: f2d71a5128a243c2791d1626b10d6637a5a40ced
  Tags:
  - 3.3.0-fpm
  - 3.3-fpm
- Architectures: null
  Directory: apache
  GitCommit: baf563abb7b48d9cb852c37713080f3e979097c3
  Tags:
  - 3.2.1-apache
  - 3.2-apache
  - 3.2.1
  - "3.2"
- Architectures: null
  Directory: fpm
  GitCommit: baf563abb7b48d9cb852c37713080f3e979097c3
  Tags:
  - 3.2.1-fpm
  - 3.2-fpm
- Architectures: null
  Directory: apache
  GitCommit: b5782462cddfd5c5ff7da5e19bb83b901e079781
  Tags:
  - 3.2.0-apache
  - 3.2.0
- Architectures: null
  Directory: fpm
  GitCommit: b5782462cddfd5c5ff7da5e19bb83b901e079781
  Tags:
  - 3.2.0-fpm
- Architectures: null
  Directory: apache
  GitCommit: dddf0af92dc1a1e5c6bfd4ac26b884aaaad56dd7
  Tags:
  - 3.1.1-apache
  - 3.1-apache
  - 3.1.1
  - "3.1"
- Architectures: null
  Directory: fpm
  GitCommit: dddf0af92dc1a1e5c6bfd4ac26b884aaaad56dd7
  Tags:
  - 3.1.1-fpm
  - 3.1-fpm
- Architectures: null
  Directory: apache
  GitCommit: 1f844a0de9e1ef018cdf8541a90620fd22a8c7a7
  Tags:
  - 3.1.0-apache
  - 3.1.0
- Architectures: null
  Directory: fpm
  GitCommit: 1f844a0de9e1ef018cdf8541a90620fd22a8c7a7
  Tags:
  - 3.1.0-fpm
- Architectures: null
  Directory: apache
  GitCommit: 4d9eadce21a4900442b16a3ef4c8ab7582cc7c83
  Tags:
  - 3.0.4-apache
  - 3.0-apache
  - 3.0.4
  - "3.0"
- Architectures: null
  Directory: fpm
  GitCommit: 4d9eadce21a4900442b16a3ef4c8ab7582cc7c83
  Tags:
  - 3.0.4-fpm
  - 3.0-fpm
- Architectures: null
  Directory: apache
  GitCommit: b00cca0f4bce10167cda80c6ca640ffc771812df
  Tags:
  - 3.0.3-apache
  - 3.0.3
- Architectures: null
  Directory: fpm
  GitCommit: b00cca0f4bce10167cda80c6ca640ffc771812df
  Tags:
  - 3.0.3-fpm
- Architectures: null
  Directory: ""
  GitCommit: ddc78a24c43759a671d27054f20b15644a36af45
  Tags:
  - 3.0.2
- Architectures: null
  Directory: ""
  GitCommit: b38670f41cce0b02b63ce6478ebbb0cbd3122eac
  Tags:
  - 3.0.1
- Architectures: null
  Directory: ""
  GitCommit: 864ad02f7f84d7d4c44bf3ee839fc0383eb8dad7
  Tags:
  - 3.0.0
- Architectures: null
  Directory: ""
  GitCommit: b511e57a17ab57d9f2e947fc391f004990d7f1d3
  Tags:
  - 2.17.1
  - "2.17"
  - "2"
- Architectures: null
  Directory: ""
  GitCommit: 555a9ee606bf7cb702e8b01cdf1fceaaf8a03a89
  Tags:
  - 2.17.0
- Architectures: null
  Directory: ""
  GitCommit: 93ad1ed911e037431200e361f9735ea8a2a44c26
  Tags:
  - 2.16.5
  - "2.16"
- Architectures: null
  Directory: ""
  GitCommit: 2f8892a595e78b966141d70d51fdef5e6d627298
  Tags:
  - 2.16.2
- Architectures:
  - amd64
  Directory: fpm-alpine
  GitCommit: 5c658b823d5687b4a259fe35de87542db0b6ec4e
  Tags:
  - 3.5.0-fpm-alpine
GitRepo: https://github.com/matomo-org/docker.git
KnownTags:
  "2": {}
  "2.16": {}
  2.16.2: {}
  2.16.5: {}
  "2.17": {}
  2.17.0: {}
  2.17.1: {}
  "3": {}
  3-apache: {}
  3-fpm: {}
  3-fpm-alpine: {}
  "3.0": {}
  3.0-apache: {}
  3.0-fpm: {}
  3.0.0: {}
  3.0.1: {}
  3.0.2: {}
  3.0.3: {}
  3.0.3-apache: {}
  3.0.3-fpm: {}
  3.0.4: {}
  3.0.4-apache: {}
  3.0.4-fpm: {}
  "3.1": {}
  3.1-apache: {}
  3.1-fpm: {}
  3.1.0: {}
  3.1.0-apache: {}
  3.1.0-fpm: {}
  3.1.1: {}
  3.1.1-apache: {}
  3.1.1-fpm: {}
  "3.2": {}
  3.2-apache: {}
  3.2-fpm: {}
  3.2.0: {}
  3.2.0-apache: {}
  3.2.0-fpm: {}
  3.2.1: {}
  3.2.1-apache: {}
  3.2.1-fpm: {}
  "3.3": {}
  3.3-apache: {}
  3.3-fpm: {}
  3.3.0: {}
  3.3.0-apache: {}
  3.3.0-fpm: {}
  "3.4": {}
  3.4-apache: {}
  3.4-fpm: {}
  3.4.0: {}
  3.4.0-apache: {}
  3.4.0-fpm: {}
  "3.5": {}
  3.5-apache: {}
  3.5-fpm: {}
  3.5-fpm-alpine: {}
  3.5.0: {}
  3.5.0-apache: {}
  3.5.0-fpm: {}
  3.5.0-fpm-alpine: {}
  3.5.1: {}
  3.5.1-apache: {}
  3.5.1-fpm: {}
  3.5.1-fpm-alpine: {}
  "3.6": {}
  3.6-apache: {}
  3.6-fpm: {}
  3.6-fpm-alpine: {}
  3.6.0: {}
  3.6.0-apache: {}
  3.6.0-fpm: {}
  3.6.0-fpm-alpine: {}
  apache: {}
  fpm: {}
  fpm-alpine: {}
  latest: {}
Name: piwik
