Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.9.4
  File: ""
  GitCommit: 2074042d4d24204201c26ce799b59fb67a44cf2e
  Tags:
  - 0.9.4
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.9.3
  File: ""
  GitCommit: fa9dcae65a51f3649b60a970add65a6553274f36
  Tags:
  - 0.9.3
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.9.2
  File: ""
  GitCommit: 5d6718573955995c3f39a859f58655eed323b3b8
  Tags:
  - 0.9.2
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.9.1
  File: ""
  GitCommit: c2776cc6a5adedddcdeb49e8613f64704ccb4c27
  Tags:
  - 0.9.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.9.0
  File: ""
  GitCommit: 4136139fef1359b203ca474a0105cbece05177e9
  Tags:
  - 0.9.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.8.9
  File: ""
  GitCommit: 447d3785ef7a5aeae008abd74a3b387e2908cf3c
  Tags:
  - 0.8.9
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.8.8
  File: ""
  GitCommit: 9d436f593619de8d85f9da72330d37bdb5a052c6
  Tags:
  - 0.8.8
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.8.7
  File: ""
  GitCommit: ec634f6011bf283d76b90e7c126db63653fb2162
  Tags:
  - 0.8.7
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.8.6
  File: ""
  GitCommit: a6c6a4ee84c8410772e56c3b0588cde1728168a9
  Tags:
  - 0.8.6
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.8.5
  File: ""
  GitCommit: 0929ac5d2e12037741789bed7a6cf2694887f776
  Tags:
  - 0.8.5
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.8.4
  File: ""
  GitCommit: 68375d5f34d01ee894aae48bd001863a7fce0faf
  Tags:
  - 0.8.4
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.8.3
  File: ""
  GitCommit: 7ae99319347dfa931810f576a5fe194c85e3b5e7
  Tags:
  - 0.8.3
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.8.2
  File: ""
  GitCommit: b90afa9b60e9df6c596a4d6db4ef726ff132d7ee
  Tags:
  - 0.8.2
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.8.1
  File: ""
  GitCommit: 4af02b9e4413f141078641b690bb114a929f414c
  Tags:
  - 0.8.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.8.0
  File: ""
  GitCommit: 66d6a4190b098f95c1e2b9382ded51a340c815d0
  Tags:
  - 0.8.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.7.4
  File: ""
  GitCommit: 0ea1be5ada7c57564afb40d303b32eea3282c778
  Tags:
  - 0.7.4
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.7.3
  File: ""
  GitCommit: c63bbed490a94a2ea89c6ea656592f15ffb9cb92
  Tags:
  - 0.7.3
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.7.2
  File: ""
  GitCommit: 0219b73c95231b3fc13824a4a672a8c5356c97a4
  Tags:
  - 0.7.2
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.7.1
  File: ""
  GitCommit: 0219b73c95231b3fc13824a4a672a8c5356c97a4
  Tags:
  - 0.7.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.7.0
  File: ""
  GitCommit: 5b7397c54592869513947460ba94ba2a22fd9814
  Tags:
  - 0.7.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.17
  File: ""
  GitCommit: 0418873db1cd80bc7fd2aa655e627fa8ff647535
  Tags:
  - 0.6.17
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.16
  File: ""
  GitCommit: f99c6a69f9d7c6dec9d313a21183e54f1e49f6bf
  Tags:
  - 0.6.16
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.15
  File: ""
  GitCommit: 94971338b498dca6144ed3d2b7dceb045aac0d0f
  Tags:
  - 0.6.15
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.14
  File: ""
  GitCommit: 2246f69504648eda098c878430dd5c26364ba24b
  Tags:
  - 0.6.14
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.13
  File: ""
  GitCommit: e91a3e1f2859e57cd9f4371ba2a2308a35f2b546
  Tags:
  - 0.6.13
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.12
  File: ""
  GitCommit: e91a3e1f2859e57cd9f4371ba2a2308a35f2b546
  Tags:
  - 0.6.12
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.11
  File: ""
  GitCommit: 8da89a87d29d1b6d5a52e3064722d9a24a4c39fb
  Tags:
  - 0.6.11
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.10
  File: ""
  GitCommit: c2b622e7f59546d9fb338c81fa82d405a8767485
  Tags:
  - 0.6.10
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.9
  File: ""
  GitCommit: b0579bf17de8f41b162e150b00a87b95648258ee
  Tags:
  - 0.6.9
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.8
  File: ""
  GitCommit: 6b8ef445c0f34f1f04ab54ec0024ded213567ac5
  Tags:
  - 0.6.8
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.7
  File: ""
  GitCommit: 5cd07f115f16d10095a385a73568a4e60caf278b
  Tags:
  - 0.6.7
GitRepo: https://github.com/wallarm/api-firewall-docker.git
KnownTags:
  0.6.7: {}
  0.6.8: {}
  0.6.9: {}
  0.6.10: {}
  0.6.11: {}
  0.6.12: {}
  0.6.13: {}
  0.6.14: {}
  0.6.15: {}
  0.6.16: {}
  0.6.17: {}
  0.7.0: {}
  0.7.1: {}
  0.7.2: {}
  0.7.3: {}
  0.7.4: {}
  0.8.0: {}
  0.8.1: {}
  0.8.2: {}
  0.8.3: {}
  0.8.4: {}
  0.8.5: {}
  0.8.6: {}
  0.8.7: {}
  0.8.8: {}
  0.8.9: {}
  0.9.0: {}
  0.9.1: {}
  0.9.2: {}
  0.9.3: {}
  0.9.4: {}
  latest: {}
Name: api-firewall
