Blocks:
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: 0.6.11
  GitCommit: 8da89a87d29d1b6d5a52e3064722d9a24a4c39fb
  Tags:
  - 0.6.11
  - latest
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: 0.6.10
  GitCommit: c2b622e7f59546d9fb338c81fa82d405a8767485
  Tags:
  - 0.6.10
- Architectures:
  - amd64
  - arm64v8
  - i386
  Directory: 0.6.9
  GitCommit: b0579bf17de8f41b162e150b00a87b95648258ee
  Tags:
  - 0.6.9
GitRepo: https://github.com/wallarm/api-firewall-docker.git
KnownTags:
  0.6.9: {}
  0.6.10: {}
  0.6.11: {}
  latest: {}
Name: api-firewall
