Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.15
  File: ""
  GitCommit: 94971338b498dca6144ed3d2b7dceb045aac0d0f
  Tags:
  - 0.6.15
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.14
  File: ""
  GitCommit: 2246f69504648eda098c878430dd5c26364ba24b
  Tags:
  - 0.6.14
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.13
  File: ""
  GitCommit: e91a3e1f2859e57cd9f4371ba2a2308a35f2b546
  Tags:
  - 0.6.13
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.12
  File: ""
  GitCommit: e91a3e1f2859e57cd9f4371ba2a2308a35f2b546
  Tags:
  - 0.6.12
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.11
  File: ""
  GitCommit: 8da89a87d29d1b6d5a52e3064722d9a24a4c39fb
  Tags:
  - 0.6.11
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.10
  File: ""
  GitCommit: c2b622e7f59546d9fb338c81fa82d405a8767485
  Tags:
  - 0.6.10
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.9
  File: ""
  GitCommit: b0579bf17de8f41b162e150b00a87b95648258ee
  Tags:
  - 0.6.9
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.8
  File: ""
  GitCommit: 6b8ef445c0f34f1f04ab54ec0024ded213567ac5
  Tags:
  - 0.6.8
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 0.6.7
  File: ""
  GitCommit: 5cd07f115f16d10095a385a73568a4e60caf278b
  Tags:
  - 0.6.7
GitRepo: https://github.com/wallarm/api-firewall-docker.git
KnownTags:
  0.6.7: {}
  0.6.8: {}
  0.6.9: {}
  0.6.10: {}
  0.6.11: {}
  0.6.12: {}
  0.6.13: {}
  0.6.14: {}
  0.6.15: {}
  latest: {}
Name: api-firewall
