Blocks:
- Architectures:
  - amd64
  - i386
  - arm64v8
  - arm32v7
  - ppc64le
  Directory: ""
  GitCommit: 75c4d0029825ab9802240f2a086395d728e1853f
  Tags:
  - p10
  - latest
- Architectures:
  - amd64
  - i386
  - arm64v8
  - arm32v7
  - ppc64le
  Directory: ""
  GitCommit: d1f01d08ac608909403bc99501af07065d7be769
  Tags:
  - p9
- Architectures:
  - amd64
  - i386
  - arm64v8
  - arm32v7
  - ppc64le
  Directory: ""
  GitCommit: cf707869d0d33a76fa3eed5eb2592c07a0a11e23
  Tags:
  - sisyphus
- Architectures:
  - amd64
  - i386
  Directory: ""
  GitCommit: 0455bb56cfb875deb95a74042f1f37c0428fe8ae
  Tags:
  - p8
GitRepo: https://github.com/alt-cloud/docker-brew-alt.git
KnownTags:
  latest: {}
  p8: {}
  p9: {}
  p10: {}
  sisyphus: {}
Name: alt
