Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: aarch64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: fa2dd8158cb2fae6f6beb1b75ce521a906defdb6
  Tags:
  - p10
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: aarch64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
    riscv64:
      Architecture: riscv64
      Directory: riscv64/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 22fa2c4589ddd9a413c483e03258a8e337dfe195
  Tags:
  - sisyphus
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: aarch64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: c2d543714938d5ab0d474f584e0b11b527e08943
  Tags:
  - p11
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: armh/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: aarch64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ppc64le/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 29295d2ce735b810bf3b20938c96b7a42b72804d
  Tags:
  - p9
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 0455bb56cfb875deb95a74042f1f37c0428fe8ae
  Tags:
  - p8
GitRepo: https://github.com/alt-cloud/docker-brew-alt.git
KnownTags:
  latest: {}
  p8: {}
  p9: {}
  p10: {}
  p11: {}
  sisyphus: {}
Name: alt
