Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: armh/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: aarch64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ppc64le/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  GitCommit: 75c4d0029825ab9802240f2a086395d728e1853f
  Tags:
  - p10
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: armh/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: aarch64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ppc64le/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  GitCommit: d1f01d08ac608909403bc99501af07065d7be769
  Tags:
  - p9
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: armh/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: aarch64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ppc64le/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  GitCommit: cf707869d0d33a76fa3eed5eb2592c07a0a11e23
  Tags:
  - sisyphus
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  GitCommit: 0455bb56cfb875deb95a74042f1f37c0428fe8ae
  Tags:
  - p8
GitRepo: https://github.com/alt-cloud/docker-brew-alt.git
KnownTags:
  latest: {}
  p8: {}
  p9: {}
  p10: {}
  sisyphus: {}
Name: alt
