Blocks:
- Architectures:
  - amd64
  - i386
  - arm64v8
  - arm32v7
  - ppc64le
  Directory: ""
  GitCommit: b231d221f40d951338c30902735044a36bb1895f
  Tags:
  - p10
  - latest
- Architectures:
  - amd64
  - i386
  - arm64v8
  - arm32v7
  - ppc64le
  Directory: ""
  GitCommit: fa873ac1d6ad83275982565b82b67b009969fd6a
  Tags:
  - p9
- Architectures:
  - amd64
  - i386
  - arm64v8
  - arm32v7
  - ppc64le
  Directory: ""
  GitCommit: a7155b68c43e43d50c162e355946303abf76f7d8
  Tags:
  - sisyphus
- Architectures:
  - amd64
  - i386
  Directory: ""
  GitCommit: 0455bb56cfb875deb95a74042f1f37c0428fe8ae
  Tags:
  - p8
GitRepo: https://github.com/alt-cloud/docker-brew-alt.git
KnownTags:
  latest: {}
  p8: {}
  p9: {}
  p10: {}
  sisyphus: {}
Name: alt
