Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: aarch64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: ef522411b7245d758aa8c8a24a0575c742fac1a2
  Tags:
  - p10
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: aarch64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
    riscv64:
      Architecture: riscv64
      Directory: riscv64/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: f6fcb549885ee57d7bbb53a22484ee16cb9413b0
  Tags:
  - sisyphus
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: aarch64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 068702e0e800b291f7853380450a5557e56900c3
  Tags:
  - p11
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: armh/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: aarch64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ppc64le/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 29295d2ce735b810bf3b20938c96b7a42b72804d
  Tags:
  - p9
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 0455bb56cfb875deb95a74042f1f37c0428fe8ae
  Tags:
  - p8
GitRepo: https://github.com/alt-cloud/docker-brew-alt.git
KnownTags:
  latest: {}
  p8: {}
  p9: {}
  p10: {}
  p11: {}
  sisyphus: {}
Name: alt
