Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: aarch64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 920886636db2d75287b93587f841b2fdb46ec711
  Tags:
  - p10
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: aarch64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
    riscv64:
      Architecture: riscv64
      Directory: riscv64/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: a700dbea4a6d8aa769e1cfcf651bdf162494b518
  Tags:
  - sisyphus
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: aarch64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: bf8979511d2508a410db13b840302df6ccbb59a6
  Tags:
  - p11
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: armh/
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: aarch64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
    ppc64le:
      Architecture: ppc64le
      Directory: ppc64le/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 29295d2ce735b810bf3b20938c96b7a42b72804d
  Tags:
  - p9
- Architectures:
    amd64:
      Architecture: amd64
      Directory: x86_64/
      File: ""
      GitCommit: ""
      GitFetch: ""
    i386:
      Architecture: i386
      Directory: i586/
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: ""
  File: ""
  GitCommit: 0455bb56cfb875deb95a74042f1f37c0428fe8ae
  Tags:
  - p8
GitRepo: https://github.com/alt-cloud/docker-brew-alt.git
KnownTags:
  latest: {}
  p8: {}
  p9: {}
  p10: {}
  p11: {}
  sisyphus: {}
Name: alt
