Blocks:
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 8.2.1
  - "8.2"
  - latest
GitRepo: https://github.com/convertigo/convertigo
KnownTags:
  "8.2": {}
  8.2.1: {}
  latest: {}
Name: convertigo
