Blocks:
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 8.2.1
  - "8.2"
  - latest
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 8.2.0
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 8.1.0
  - "8.1"
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 8.0.2
  - "8.0"
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 8.0.1
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 8.0.0
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 7.9.8
  - "7.9"
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 7.9.7
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 7.9.6
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 7.9.5
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 7.9.4
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 7.9.3
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 7.9.2
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 7.9.1
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 7.9.0
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 7.8.0
  - "7.8"
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 7.7.0
  - "7.7"
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 7.6.6
  - "7.6"
- Architectures:
  - amd64
  Directory: docker/slim
  GitCommit: ""
  Tags:
  - 7.6.6-slim
  - 7.6-slim
  - slim
- Architectures:
  - amd64
  Directory: docker/openj9
  GitCommit: ""
  Tags:
  - 7.6.6-openj9
  - 7.6-openj9
  - openj9
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 7.6.5
- Architectures:
  - amd64
  Directory: docker/slim
  GitCommit: ""
  Tags:
  - 7.6.5-slim
- Architectures:
  - amd64
  Directory: docker/openj9
  GitCommit: ""
  Tags:
  - 7.6.5-openj9
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 7.6.4
- Architectures:
  - amd64
  Directory: docker/slim
  GitCommit: ""
  Tags:
  - 7.6.4-slim
- Architectures:
  - amd64
  Directory: docker/openj9
  GitCommit: ""
  Tags:
  - 7.6.4-openj9
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 7.6.3
- Architectures:
  - amd64
  Directory: docker/slim
  GitCommit: ""
  Tags:
  - 7.6.3-slim
- Architectures:
  - amd64
  Directory: docker/openj9
  GitCommit: ""
  Tags:
  - 7.6.3-openj9
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 7.6.2
- Architectures:
  - amd64
  Directory: docker/slim
  GitCommit: ""
  Tags:
  - 7.6.2-slim
- Architectures:
  - amd64
  Directory: docker/openj9
  GitCommit: ""
  Tags:
  - 7.6.2-openj9
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 7.6.1
- Architectures:
  - amd64
  Directory: docker/slim
  GitCommit: ""
  Tags:
  - 7.6.1-slim
- Architectures:
  - amd64
  Directory: docker/openj9
  GitCommit: ""
  Tags:
  - 7.6.1-openj9
- Architectures:
  - amd64
  Directory: docker/default
  GitCommit: ""
  Tags:
  - 7.6.0
- Architectures:
  - amd64
  Directory: docker/slim
  GitCommit: ""
  Tags:
  - 7.6.0-slim
- Architectures:
  - amd64
  Directory: docker/openj9
  GitCommit: ""
  Tags:
  - 7.6.0-openj9
- Architectures:
  - amd64
  Directory: 7.5/7.5.7
  GitCommit: ""
  Tags:
  - 7.5.7
  - "7.5"
- Architectures:
  - amd64
  Directory: 7.5/7.5.7/slim
  GitCommit: ""
  Tags:
  - 7.5.7-slim
  - 7.5-slim
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  Directory: 7.5/7.5.7/alpine
  GitCommit: ""
  Tags:
  - 7.5.7-alpine
  - 7.5-alpine
  - alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 7.4/7.4.8
  GitCommit: ""
  Tags:
  - 7.4.8
  - "7.4"
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  Directory: 7.4/7.4.8/alpine
  GitCommit: ""
  Tags:
  - 7.4.8-alpine
  - 7.4-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 7.5/7.5.6
  GitCommit: ""
  Tags:
  - 7.5.6
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  Directory: 7.5/7.5.6/alpine
  GitCommit: ""
  Tags:
  - 7.5.6-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 7.5/7.5.5
  GitCommit: ""
  Tags:
  - 7.5.5
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  Directory: 7.5/7.5.5/alpine
  GitCommit: ""
  Tags:
  - 7.5.5-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 7.5/7.5.4
  GitCommit: ""
  Tags:
  - 7.5.4
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  Directory: 7.5/7.5.4/alpine
  GitCommit: ""
  Tags:
  - 7.5.4-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 7.5/7.5.3
  GitCommit: ""
  Tags:
  - 7.5.3
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  Directory: 7.5/7.5.3/alpine
  GitCommit: ""
  Tags:
  - 7.5.3-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 7.5/7.5.2
  GitCommit: ""
  Tags:
  - 7.5.2
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  Directory: 7.5/7.5.2/alpine
  GitCommit: ""
  Tags:
  - 7.5.2-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 7.5/7.5.1
  GitCommit: ""
  Tags:
  - 7.5.1
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  Directory: 7.5/7.5.1/alpine
  GitCommit: ""
  Tags:
  - 7.5.1-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 7.5/7.5.0
  GitCommit: ""
  Tags:
  - 7.5.0
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  Directory: 7.5/7.5.0/alpine
  GitCommit: ""
  Tags:
  - 7.5.0-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: 7.4/7.4.7
  GitCommit: ""
  Tags:
  - 7.4.7
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  Directory: 7.4/7.4.7/alpine
  GitCommit: ""
  Tags:
  - 7.4.7-alpine
- Architectures: null
  Directory: 7.4/7.4.7/web-connector
  GitCommit: dc3d5543b5de1813bf05c5abc937164a662bb491
  Tags:
  - web-connector-7.4.7
  - web-connector-7.4
  - web-connector
- Architectures: null
  Directory: 7.4/7.4.6
  GitCommit: fb5ac90d57ebb78b00fe1bdb306bef7ad268cce5
  Tags:
  - 7.4.6
- Architectures: null
  Directory: 7.4/7.4.6/web-connector
  GitCommit: fb5ac90d57ebb78b00fe1bdb306bef7ad268cce5
  Tags:
  - web-connector-7.4.6
- Architectures: null
  Directory: 7.4/7.4.5
  GitCommit: 866dff0b76231906e1efdeafd63fe522d20b6c05
  Tags:
  - 7.4.5
- Architectures: null
  Directory: 7.4/7.4.5/web-connector
  GitCommit: 866dff0b76231906e1efdeafd63fe522d20b6c05
  Tags:
  - web-connector-7.4.5
- Architectures:
  - amd64
  - i386
  Directory: 7.5/7.5.0/web-connector
  GitCommit: 441d7c87c39353e40124d5b77a18a037d8650a70
  Tags:
  - web-connector-7.5.0
  - web-connector-7.7
- Architectures:
  - amd64
  Directory: docker/aks
  GitCommit: ""
  Tags:
  - 7.7.0-aks
  - 7.7-aks
  - aks
GitRepo: https://github.com/convertigo/convertigo
KnownTags:
  "7.4": {}
  7.4-alpine: {}
  7.4.5: {}
  7.4.6: {}
  7.4.7: {}
  7.4.7-alpine: {}
  7.4.8: {}
  7.4.8-alpine: {}
  "7.5": {}
  7.5-alpine: {}
  7.5-slim: {}
  7.5.0: {}
  7.5.0-alpine: {}
  7.5.1: {}
  7.5.1-alpine: {}
  7.5.2: {}
  7.5.2-alpine: {}
  7.5.3: {}
  7.5.3-alpine: {}
  7.5.4: {}
  7.5.4-alpine: {}
  7.5.5: {}
  7.5.5-alpine: {}
  7.5.6: {}
  7.5.6-alpine: {}
  7.5.7: {}
  7.5.7-alpine: {}
  7.5.7-slim: {}
  "7.6": {}
  7.6-openj9: {}
  7.6-slim: {}
  7.6.0: {}
  7.6.0-openj9: {}
  7.6.0-slim: {}
  7.6.1: {}
  7.6.1-openj9: {}
  7.6.1-slim: {}
  7.6.2: {}
  7.6.2-openj9: {}
  7.6.2-slim: {}
  7.6.3: {}
  7.6.3-openj9: {}
  7.6.3-slim: {}
  7.6.4: {}
  7.6.4-openj9: {}
  7.6.4-slim: {}
  7.6.5: {}
  7.6.5-openj9: {}
  7.6.5-slim: {}
  7.6.6: {}
  7.6.6-openj9: {}
  7.6.6-slim: {}
  "7.7": {}
  7.7-aks: {}
  7.7.0: {}
  7.7.0-aks: {}
  "7.8": {}
  7.8.0: {}
  "7.9": {}
  7.9.0: {}
  7.9.1: {}
  7.9.2: {}
  7.9.3: {}
  7.9.4: {}
  7.9.5: {}
  7.9.6: {}
  7.9.7: {}
  7.9.8: {}
  "8.0": {}
  8.0.0: {}
  8.0.1: {}
  8.0.2: {}
  "8.1": {}
  8.1.0: {}
  "8.2": {}
  8.2.0: {}
  8.2.1: {}
  aks: {}
  alpine: {}
  latest: {}
  openj9: {}
  slim: {}
  web-connector: {}
  web-connector-7.4: {}
  web-connector-7.4.5: {}
  web-connector-7.4.6: {}
  web-connector-7.4.7: {}
  web-connector-7.5.0: {}
  web-connector-7.7: {}
Name: convertigo
