Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fresh/debian
  GitCommit: f3fa117d1308e0b521d617045666b9bb284f63b7
  Tags:
  - fresh
  - 7.3.0
  - "7.3"
  - latest
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fresh/alpine
  GitCommit: f3fa117d1308e0b521d617045666b9bb284f63b7
  Tags:
  - fresh-alpine
  - 7.3.0-alpine
  - 7.3-alpine
  - alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: old/debian
  GitCommit: 34226613b148a3f7ca7fd6cc232fe8fb5e38aff5
  Tags:
  - old
  - 7.2.1
  - "7.2"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: old/alpine
  GitCommit: 34226613b148a3f7ca7fd6cc232fe8fb5e38aff5
  Tags:
  - old-alpine
  - 7.2.1-alpine
  - 7.2-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: stable/debian
  GitCommit: e7acf36bd4afd05427bc3fb251ae4b3374168f27
  Tags:
  - stable
  - 6.0.11
  - "6.0"
GitRepo: https://github.com/varnish/docker-varnish.git
KnownTags:
  "6.0": {}
  6.0.11: {}
  "7.2": {}
  7.2-alpine: {}
  7.2.1: {}
  7.2.1-alpine: {}
  "7.3": {}
  7.3-alpine: {}
  7.3.0: {}
  7.3.0-alpine: {}
  alpine: {}
  fresh: {}
  fresh-alpine: {}
  latest: {}
  old: {}
  old-alpine: {}
  stable: {}
Name: varnish
