Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fresh/debian
  GitCommit: f3fa117d1308e0b521d617045666b9bb284f63b7
  Tags:
  - fresh
  - 7.3.0
  - "7.3"
  - latest
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fresh/alpine
  GitCommit: f3fa117d1308e0b521d617045666b9bb284f63b7
  Tags:
  - fresh-alpine
  - 7.3.0-alpine
  - 7.3-alpine
  - alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: old/debian
  GitCommit: 34226613b148a3f7ca7fd6cc232fe8fb5e38aff5
  Tags:
  - old
  - 7.2.1
  - "7.2"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: old/alpine
  GitCommit: 34226613b148a3f7ca7fd6cc232fe8fb5e38aff5
  Tags:
  - old-alpine
  - 7.2.1-alpine
  - 7.2-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: stable/debian
  GitCommit: e7acf36bd4afd05427bc3fb251ae4b3374168f27
  Tags:
  - stable
  - 6.0.11
  - "6.0"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: old/debian
  GitCommit: e7acf36bd4afd05427bc3fb251ae4b3374168f27
  Tags:
  - 7.1.2
  - "7.1"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: old/alpine
  GitCommit: e7acf36bd4afd05427bc3fb251ae4b3374168f27
  Tags:
  - 7.1.2-alpine
  - 7.1-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fresh/debian
  GitCommit: 07daf0b299f538c477be8dbac82b4a8e364d0b83
  Tags:
  - 7.2.0
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fresh/alpine
  GitCommit: 4d038be2a5553f08a24dbb357f226131d0339306
  Tags:
  - 7.2.0-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: old/debian
  GitCommit: 07daf0b299f538c477be8dbac82b4a8e364d0b83
  Tags:
  - 7.1.1
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: old/alpine
  GitCommit: 4d038be2a5553f08a24dbb357f226131d0339306
  Tags:
  - 7.1.1-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: stable/debian
  GitCommit: d1212e4b8fd35b58c19b01ed389f8841d0a4ea38
  Tags:
  - 6.0.10
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: old/debian
  GitCommit: eff5fed4545f3de5a64dead871d27a01e94feb90
  Tags:
  - 7.0.3
  - "7.0"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: old/alpine
  GitCommit: eff5fed4545f3de5a64dead871d27a01e94feb90
  Tags:
  - 7.0.3-alpine
  - 7.0-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fresh/debian
  GitCommit: 213ce5361fe416b0125b3843f11bf98cbf68729e
  Tags:
  - 7.1.0
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fresh/alpine
  GitCommit: 213ce5361fe416b0125b3843f11bf98cbf68729e
  Tags:
  - 7.1.0-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: old/debian
  GitCommit: 2012f1cbc7c401d603584ac0b601555af180eb09
  Tags:
  - 7.0.2
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: old/alpine
  GitCommit: 2012f1cbc7c401d603584ac0b601555af180eb09
  Tags:
  - 7.0.2-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: old/debian
  GitCommit: 6423e32e0afd20fa876276e1525cb318920fbefa
  Tags:
  - 6.6.2
  - "6.6"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: old/alpine
  GitCommit: 6423e32e0afd20fa876276e1525cb318920fbefa
  Tags:
  - 6.6.2-alpine
  - 6.6-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fresh/debian
  GitCommit: bb83de3a522067896b9febfe9d9407eab92e0759
  Tags:
  - 7.0.1
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fresh/alpine
  GitCommit: bb83de3a522067896b9febfe9d9407eab92e0759
  Tags:
  - 7.0.1-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: old/debian
  GitCommit: d24057bde1acfa41f5abf1d0d4772eac0bcccf70
  Tags:
  - 6.6.1
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: old/alpine
  GitCommit: d24057bde1acfa41f5abf1d0d4772eac0bcccf70
  Tags:
  - 6.6.1-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: stable/debian
  GitCommit: d24057bde1acfa41f5abf1d0d4772eac0bcccf70
  Tags:
  - 6.0.8
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fresh/debian
  GitCommit: efa8f60de4abc4f388343bcc4088c2564aa89be7
  Tags:
  - 7.0.0
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fresh/alpine
  GitCommit: b4396ad550ffa073bf1e3ceff4ae0ebfcd7023bb
  Tags:
  - 7.0.0-alpine
- Architectures:
  - amd64
  Directory: stable/debian
  GitCommit: 4cfd65e1d3bd4eb9518d8e7590d9fec1de6a50c4
  Tags:
  - 6.0.8-1
- Architectures:
  - amd64
  Directory: fresh/debian
  GitCommit: 4cfd65e1d3bd4eb9518d8e7590d9fec1de6a50c4
  Tags:
  - 6.6.1-1
  - "6"
- Architectures:
  - amd64
  Directory: stable/debian
  GitCommit: 51a66e74c3a56e4def767d3ad3f6c8ad1a4addaa
  Tags:
  - 6.0.7-1
  - 6.0.7
- Architectures:
  - amd64
  Directory: fresh/debian
  GitCommit: 51a66e74c3a56e4def767d3ad3f6c8ad1a4addaa
  Tags:
  - 6.6.0-1
  - 6.6.0
- Architectures:
  - amd64
  Directory: fresh/debian
  GitCommit: f26947e3a1d7ab5e3e76114d58e54f0ddee13534
  Tags:
  - "6.5"
  - 6.5.1-1
  - 6.5.1
- Architectures:
  - amd64
  Directory: stable/debian
  GitCommit: 2459369407fbf77df75d6948ee48de8c814fb3e4
  Tags:
  - 6.0.6-1
  - 6.0.6
- Architectures:
  - amd64
  Directory: fresh/debian
  GitCommit: ec71d5c65972b6fa9b2ec58ed3b131afce9f9578
  Tags:
  - "6.4"
  - 6.4.0-1
  - 6.4.0
- Architectures:
  - amd64
  Directory: fresh/debian
  GitCommit: a177fa702cf191997094aec9b20951c2012bdc17
  Tags:
  - "6.3"
  - 6.3.2-1
  - 6.3.2
- Architectures:
  - amd64
  Directory: fresh/debian
  GitCommit: fe5dc755a0325fd106f798de97d30dbd9d9ce836
  Tags:
  - 6.3.1-1
  - 6.3.1
- Architectures:
  - amd64
  Directory: stable/debian
  GitCommit: fe5dc755a0325fd106f798de97d30dbd9d9ce836
  Tags:
  - 6.0.5-1
  - 6.0.5
- Architectures:
  - amd64
  Directory: fresh/debian
  GitCommit: 50071fbb9b49fb793fd3570a647a6aa04fae6d7b
  Tags:
  - 6.3.0-1
  - 6.3.0
- Architectures:
  - amd64
  Directory: stable/debian
  GitCommit: 62fa33d7e54b02665c4c898dd1d5234ab57e098d
  Tags:
  - 6.0.4-1
  - 6.0.4
- Architectures:
  - amd64
  Directory: fresh/debian
  GitCommit: 62fa33d7e54b02665c4c898dd1d5234ab57e098d
  Tags:
  - "6.2"
  - 6.2.1-1
  - 6.2.1
- Architectures:
  - amd64
  Directory: fresh/debian
  GitCommit: b7f54428d14d6c5c9758f741a74f4b6d329212f1
  Tags:
  - 6.2.0-1
  - 6.2.0
- Architectures:
  - amd64
  Directory: stable/debian
  GitCommit: b7f54428d14d6c5c9758f741a74f4b6d329212f1
  Tags:
  - 6.0.3-1
  - 6.0.3
GitRepo: https://github.com/varnish/docker-varnish.git
KnownTags:
  "6": {}
  "6.0": {}
  6.0.3: {}
  6.0.3-1: {}
  6.0.4: {}
  6.0.4-1: {}
  6.0.5: {}
  6.0.5-1: {}
  6.0.6: {}
  6.0.6-1: {}
  6.0.7: {}
  6.0.7-1: {}
  6.0.8: {}
  6.0.8-1: {}
  6.0.10: {}
  6.0.11: {}
  "6.2": {}
  6.2.0: {}
  6.2.0-1: {}
  6.2.1: {}
  6.2.1-1: {}
  "6.3": {}
  6.3.0: {}
  6.3.0-1: {}
  6.3.1: {}
  6.3.1-1: {}
  6.3.2: {}
  6.3.2-1: {}
  "6.4": {}
  6.4.0: {}
  6.4.0-1: {}
  "6.5": {}
  6.5.1: {}
  6.5.1-1: {}
  "6.6": {}
  6.6-alpine: {}
  6.6.0: {}
  6.6.0-1: {}
  6.6.1: {}
  6.6.1-1: {}
  6.6.1-alpine: {}
  6.6.2: {}
  6.6.2-alpine: {}
  "7.0": {}
  7.0-alpine: {}
  7.0.0: {}
  7.0.0-alpine: {}
  7.0.1: {}
  7.0.1-alpine: {}
  7.0.2: {}
  7.0.2-alpine: {}
  7.0.3: {}
  7.0.3-alpine: {}
  "7.1": {}
  7.1-alpine: {}
  7.1.0: {}
  7.1.0-alpine: {}
  7.1.1: {}
  7.1.1-alpine: {}
  7.1.2: {}
  7.1.2-alpine: {}
  "7.2": {}
  7.2-alpine: {}
  7.2.0: {}
  7.2.0-alpine: {}
  7.2.1: {}
  7.2.1-alpine: {}
  "7.3": {}
  7.3-alpine: {}
  7.3.0: {}
  7.3.0-alpine: {}
  alpine: {}
  fresh: {}
  fresh-alpine: {}
  latest: {}
  old: {}
  old-alpine: {}
  stable: {}
Name: varnish
