Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 1969cbd6d7dd410df84a18f539836ed4e0788324
  Tags:
  - 4.0.0-apache
  - 4.0-apache
  - 4-apache
  - apache
  - 4.0.0
  - "4.0"
  - "4"
  - latest
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 1969cbd6d7dd410df84a18f539836ed4e0788324
  Tags:
  - 4.0.0-fpm-alpine
  - 4.0-fpm-alpine
  - 4-fpm-alpine
  - fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 1969cbd6d7dd410df84a18f539836ed4e0788324
  Tags:
  - 4.0.0-fpm
  - 4.0-fpm
  - 4-fpm
  - fpm
GitRepo: https://github.com/monicahq/docker.git
KnownTags:
  "4": {}
  4-apache: {}
  4-fpm: {}
  4-fpm-alpine: {}
  "4.0": {}
  4.0-apache: {}
  4.0-fpm: {}
  4.0-fpm-alpine: {}
  4.0.0: {}
  4.0.0-apache: {}
  4.0.0-fpm: {}
  4.0.0-fpm-alpine: {}
  apache: {}
  fpm: {}
  fpm-alpine: {}
  latest: {}
Name: monica
