Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 1969cbd6d7dd410df84a18f539836ed4e0788324
  Tags:
  - 4.0.0-apache
  - 4.0-apache
  - 4-apache
  - apache
  - 4.0.0
  - "4.0"
  - "4"
  - latest
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 1969cbd6d7dd410df84a18f539836ed4e0788324
  Tags:
  - 4.0.0-fpm-alpine
  - 4.0-fpm-alpine
  - 4-fpm-alpine
  - fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 1969cbd6d7dd410df84a18f539836ed4e0788324
  Tags:
  - 4.0.0-fpm
  - 4.0-fpm
  - 4-fpm
  - fpm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: c0340b2017890e6a465d1d4ee03331d2effc0335
  Tags:
  - 3.7.0-apache
  - 3.7-apache
  - 3-apache
  - 3.7.0
  - "3.7"
  - "3"
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: c0340b2017890e6a465d1d4ee03331d2effc0335
  Tags:
  - 3.7.0-fpm-alpine
  - 3.7-fpm-alpine
  - 3-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: c0340b2017890e6a465d1d4ee03331d2effc0335
  Tags:
  - 3.7.0-fpm
  - 3.7-fpm
  - 3-fpm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 437356f9ed4fe4e22f12fc38451ae494f971175c
  Tags:
  - 3.6.1-apache
  - 3.6-apache
  - 3.6.1
  - "3.6"
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 437356f9ed4fe4e22f12fc38451ae494f971175c
  Tags:
  - 3.6.1-fpm-alpine
  - 3.6-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 437356f9ed4fe4e22f12fc38451ae494f971175c
  Tags:
  - 3.6.1-fpm
  - 3.6-fpm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: f9840328c1c811d21a59a5757ac3b8a2f67d623d
  Tags:
  - 3.6.0-apache
  - 3.6.0
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: f9840328c1c811d21a59a5757ac3b8a2f67d623d
  Tags:
  - 3.6.0-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: f9840328c1c811d21a59a5757ac3b8a2f67d623d
  Tags:
  - 3.6.0-fpm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 03744c868b21cdd00d66e329b105f8b3d22c1173
  Tags:
  - 3.5.0-apache
  - 3.5-apache
  - 3.5.0
  - "3.5"
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 03744c868b21cdd00d66e329b105f8b3d22c1173
  Tags:
  - 3.5.0-fpm-alpine
  - 3.5-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 03744c868b21cdd00d66e329b105f8b3d22c1173
  Tags:
  - 3.5.0-fpm
  - 3.5-fpm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 62974d66881d7ba2b7172ea1d82b88485f65c579
  Tags:
  - 3.4.0-apache
  - 3.4-apache
  - 3.4.0
  - "3.4"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 62974d66881d7ba2b7172ea1d82b88485f65c579
  Tags:
  - 3.4.0-fpm
  - 3.4-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 62974d66881d7ba2b7172ea1d82b88485f65c579
  Tags:
  - 3.4.0-fpm-alpine
  - 3.4-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: c64d562e0d9473d55dea0053ff42fa2589af94b9
  Tags:
  - 3.3.1-apache
  - 3.3-apache
  - 3.3.1
  - "3.3"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: c64d562e0d9473d55dea0053ff42fa2589af94b9
  Tags:
  - 3.3.1-fpm
  - 3.3-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: c64d562e0d9473d55dea0053ff42fa2589af94b9
  Tags:
  - 3.3.1-fpm-alpine
  - 3.3-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: c019441ad5fd5ccc83e6dbaaa3c102f9fef85be2
  Tags:
  - 3.2.0-apache
  - 3.2-apache
  - 3.2.0
  - "3.2"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: c019441ad5fd5ccc83e6dbaaa3c102f9fef85be2
  Tags:
  - 3.2.0-fpm
  - 3.2-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: c019441ad5fd5ccc83e6dbaaa3c102f9fef85be2
  Tags:
  - 3.2.0-fpm-alpine
  - 3.2-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 3e867efc6b6a7904297fd388f93c8a9bdaa04321
  Tags:
  - 3.1.3-apache
  - 3.1-apache
  - 3.1.3
  - "3.1"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 3e867efc6b6a7904297fd388f93c8a9bdaa04321
  Tags:
  - 3.1.3-fpm
  - 3.1-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 3e867efc6b6a7904297fd388f93c8a9bdaa04321
  Tags:
  - 3.1.3-fpm-alpine
  - 3.1-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 00a09024b1012db35f96af9c379829663b814853
  Tags:
  - 3.1.1-apache
  - 3.1.1
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 00a09024b1012db35f96af9c379829663b814853
  Tags:
  - 3.1.1-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 00a09024b1012db35f96af9c379829663b814853
  Tags:
  - 3.1.1-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 8e338da17d09d8b9a0b7b8c4aa734ecd400bca07
  Tags:
  - 3.0.1-apache
  - 3.0-apache
  - 3.0.1
  - "3.0"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 8e338da17d09d8b9a0b7b8c4aa734ecd400bca07
  Tags:
  - 3.0.1-fpm
  - 3.0-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 8e338da17d09d8b9a0b7b8c4aa734ecd400bca07
  Tags:
  - 3.0.1-fpm-alpine
  - 3.0-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 219154530e308d10d6dff32274ca1a8384c8f471
  Tags:
  - 3.0.0-apache
  - 3.0.0
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 219154530e308d10d6dff32274ca1a8384c8f471
  Tags:
  - 3.0.0-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 219154530e308d10d6dff32274ca1a8384c8f471
  Tags:
  - 3.0.0-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 58e3d7ac1610d85fdab3824c4054f71bc7372c9b
  Tags:
  - 2.22.0-apache
  - 2.22-apache
  - 2-apache
  - 2.22.0
  - "2.22"
  - "2"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 58e3d7ac1610d85fdab3824c4054f71bc7372c9b
  Tags:
  - 2.22.0-fpm
  - 2.22-fpm
  - 2-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 58e3d7ac1610d85fdab3824c4054f71bc7372c9b
  Tags:
  - 2.22.0-fpm-alpine
  - 2.22-fpm-alpine
  - 2-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: b3f212609d699f9090f6087bd93d05405ef75ce8
  Tags:
  - 2.21.0-apache
  - 2.21-apache
  - 2.21.0
  - "2.21"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: b3f212609d699f9090f6087bd93d05405ef75ce8
  Tags:
  - 2.21.0-fpm
  - 2.21-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: b3f212609d699f9090f6087bd93d05405ef75ce8
  Tags:
  - 2.21.0-fpm-alpine
  - 2.21-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 0930aec604aa54e3a5bfceb003ebe4f176808900
  Tags:
  - 2.20.0-apache
  - 2.20-apache
  - 2.20.0
  - "2.20"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 0930aec604aa54e3a5bfceb003ebe4f176808900
  Tags:
  - 2.20.0-fpm
  - 2.20-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 0930aec604aa54e3a5bfceb003ebe4f176808900
  Tags:
  - 2.20.0-fpm-alpine
  - 2.20-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 1c9fd657cfc59067da9b30479ddf5cd04750b392
  Tags:
  - 2.19.1-apache
  - 2.19-apache
  - 2.19.1
  - "2.19"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 1c9fd657cfc59067da9b30479ddf5cd04750b392
  Tags:
  - 2.19.1-fpm
  - 2.19-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 1c9fd657cfc59067da9b30479ddf5cd04750b392
  Tags:
  - 2.19.1-fpm-alpine
  - 2.19-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: fd973cc5c4990a023fb8030f4665cd418e672de3
  Tags:
  - 2.19.0-apache
  - 2.19.0
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: fd973cc5c4990a023fb8030f4665cd418e672de3
  Tags:
  - 2.19.0-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: fd973cc5c4990a023fb8030f4665cd418e672de3
  Tags:
  - 2.19.0-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 7a83d357006fe1b7947717d75842ea4d6f720ac5
  Tags:
  - 2.18.0-apache
  - 2.18-apache
  - 2.18.0
  - "2.18"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 7a83d357006fe1b7947717d75842ea4d6f720ac5
  Tags:
  - 2.18.0-fpm
  - 2.18-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 7a83d357006fe1b7947717d75842ea4d6f720ac5
  Tags:
  - 2.18.0-fpm-alpine
  - 2.18-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 94858ec2e15109a62707f784a2bc0ca63d58cf8b
  Tags:
  - 2.17.0-apache
  - 2.17-apache
  - 2.17.0
  - "2.17"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 94858ec2e15109a62707f784a2bc0ca63d58cf8b
  Tags:
  - 2.17.0-fpm
  - 2.17-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 94858ec2e15109a62707f784a2bc0ca63d58cf8b
  Tags:
  - 2.17.0-fpm-alpine
  - 2.17-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: apache
  GitCommit: 424ad3109b5b6adb4353dfb08cb26c1f3dd70fad
  Tags:
  - 2.16.0-apache
  - 2.16-apache
  - 2.16.0
  - "2.16"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: fpm
  GitCommit: 424ad3109b5b6adb4353dfb08cb26c1f3dd70fad
  Tags:
  - 2.16.0-fpm
  - 2.16-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  Directory: fpm-alpine
  GitCommit: 424ad3109b5b6adb4353dfb08cb26c1f3dd70fad
  Tags:
  - 2.16.0-fpm-alpine
  - 2.16-fpm-alpine
- Architectures:
  - amd64
  Directory: scripts/docker/apache/
  GitCommit: e3c79ada95ba6b34281628ee044a7bf0e9920f26
  Tags:
  - 2.16.0-alpine-apache
  - 2.16.0-alpine
  - alpine
- Architectures:
  - amd64
  Directory: scripts/docker/php-apache/
  GitCommit: e3c79ada95ba6b34281628ee044a7bf0e9920f26
  Tags:
  - 2.16.0-php-apache
  - php-apache
- Architectures:
  - amd64
  Directory: scripts/docker/fpm/
  GitCommit: e3c79ada95ba6b34281628ee044a7bf0e9920f26
  Tags:
  - 2.16.0-alpine-fpm
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 8118ac0f51564c16d68131dae301b7151d323a39
  Tags:
  - 3.1.0-apache
  - 3.1.0
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 8118ac0f51564c16d68131dae301b7151d323a39
  Tags:
  - 3.1.0-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 8118ac0f51564c16d68131dae301b7151d323a39
  Tags:
  - 3.1.0-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 52bd2372273966570048e6e193c37df974446f5a
  Tags:
  - 3.3.0-apache
  - 3.3.0
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 52bd2372273966570048e6e193c37df974446f5a
  Tags:
  - 3.3.0-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 52bd2372273966570048e6e193c37df974446f5a
  Tags:
  - 3.3.0-fpm-alpine
GitRepo: https://github.com/monicahq/docker.git
KnownTags:
  "2": {}
  2-apache: {}
  2-fpm: {}
  2-fpm-alpine: {}
  "2.16": {}
  2.16-apache: {}
  2.16-fpm: {}
  2.16-fpm-alpine: {}
  2.16.0: {}
  2.16.0-alpine: {}
  2.16.0-alpine-apache: {}
  2.16.0-alpine-fpm: {}
  2.16.0-apache: {}
  2.16.0-fpm: {}
  2.16.0-fpm-alpine: {}
  2.16.0-php-apache: {}
  "2.17": {}
  2.17-apache: {}
  2.17-fpm: {}
  2.17-fpm-alpine: {}
  2.17.0: {}
  2.17.0-apache: {}
  2.17.0-fpm: {}
  2.17.0-fpm-alpine: {}
  "2.18": {}
  2.18-apache: {}
  2.18-fpm: {}
  2.18-fpm-alpine: {}
  2.18.0: {}
  2.18.0-apache: {}
  2.18.0-fpm: {}
  2.18.0-fpm-alpine: {}
  "2.19": {}
  2.19-apache: {}
  2.19-fpm: {}
  2.19-fpm-alpine: {}
  2.19.0: {}
  2.19.0-apache: {}
  2.19.0-fpm: {}
  2.19.0-fpm-alpine: {}
  2.19.1: {}
  2.19.1-apache: {}
  2.19.1-fpm: {}
  2.19.1-fpm-alpine: {}
  "2.20": {}
  2.20-apache: {}
  2.20-fpm: {}
  2.20-fpm-alpine: {}
  2.20.0: {}
  2.20.0-apache: {}
  2.20.0-fpm: {}
  2.20.0-fpm-alpine: {}
  "2.21": {}
  2.21-apache: {}
  2.21-fpm: {}
  2.21-fpm-alpine: {}
  2.21.0: {}
  2.21.0-apache: {}
  2.21.0-fpm: {}
  2.21.0-fpm-alpine: {}
  "2.22": {}
  2.22-apache: {}
  2.22-fpm: {}
  2.22-fpm-alpine: {}
  2.22.0: {}
  2.22.0-apache: {}
  2.22.0-fpm: {}
  2.22.0-fpm-alpine: {}
  "3": {}
  3-apache: {}
  3-fpm: {}
  3-fpm-alpine: {}
  "3.0": {}
  3.0-apache: {}
  3.0-fpm: {}
  3.0-fpm-alpine: {}
  3.0.0: {}
  3.0.0-apache: {}
  3.0.0-fpm: {}
  3.0.0-fpm-alpine: {}
  3.0.1: {}
  3.0.1-apache: {}
  3.0.1-fpm: {}
  3.0.1-fpm-alpine: {}
  "3.1": {}
  3.1-apache: {}
  3.1-fpm: {}
  3.1-fpm-alpine: {}
  3.1.0: {}
  3.1.0-apache: {}
  3.1.0-fpm: {}
  3.1.0-fpm-alpine: {}
  3.1.1: {}
  3.1.1-apache: {}
  3.1.1-fpm: {}
  3.1.1-fpm-alpine: {}
  3.1.3: {}
  3.1.3-apache: {}
  3.1.3-fpm: {}
  3.1.3-fpm-alpine: {}
  "3.2": {}
  3.2-apache: {}
  3.2-fpm: {}
  3.2-fpm-alpine: {}
  3.2.0: {}
  3.2.0-apache: {}
  3.2.0-fpm: {}
  3.2.0-fpm-alpine: {}
  "3.3": {}
  3.3-apache: {}
  3.3-fpm: {}
  3.3-fpm-alpine: {}
  3.3.0: {}
  3.3.0-apache: {}
  3.3.0-fpm: {}
  3.3.0-fpm-alpine: {}
  3.3.1: {}
  3.3.1-apache: {}
  3.3.1-fpm: {}
  3.3.1-fpm-alpine: {}
  "3.4": {}
  3.4-apache: {}
  3.4-fpm: {}
  3.4-fpm-alpine: {}
  3.4.0: {}
  3.4.0-apache: {}
  3.4.0-fpm: {}
  3.4.0-fpm-alpine: {}
  "3.5": {}
  3.5-apache: {}
  3.5-fpm: {}
  3.5-fpm-alpine: {}
  3.5.0: {}
  3.5.0-apache: {}
  3.5.0-fpm: {}
  3.5.0-fpm-alpine: {}
  "3.6": {}
  3.6-apache: {}
  3.6-fpm: {}
  3.6-fpm-alpine: {}
  3.6.0: {}
  3.6.0-apache: {}
  3.6.0-fpm: {}
  3.6.0-fpm-alpine: {}
  3.6.1: {}
  3.6.1-apache: {}
  3.6.1-fpm: {}
  3.6.1-fpm-alpine: {}
  "3.7": {}
  3.7-apache: {}
  3.7-fpm: {}
  3.7-fpm-alpine: {}
  3.7.0: {}
  3.7.0-apache: {}
  3.7.0-fpm: {}
  3.7.0-fpm-alpine: {}
  "4": {}
  4-apache: {}
  4-fpm: {}
  4-fpm-alpine: {}
  "4.0": {}
  4.0-apache: {}
  4.0-fpm: {}
  4.0-fpm-alpine: {}
  4.0.0: {}
  4.0.0-apache: {}
  4.0.0-fpm: {}
  4.0.0-fpm-alpine: {}
  alpine: {}
  apache: {}
  fpm: {}
  fpm-alpine: {}
  latest: {}
  php-apache: {}
Name: monica
