Blocks:
- Architectures: null
  Directory: full
  GitCommit: ""
  Tags:
  - 1.8.2
  - "1.8"
  - latest
- Architectures: null
  Directory: slim
  GitCommit: ""
  Tags:
  - 1.8.2-slim
  - 1.8-slim
  - slim
GitRepo: https://github.com/znc/znc-docker.git
KnownTags:
  "1.8": {}
  1.8-slim: {}
  1.8.2: {}
  1.8.2-slim: {}
  latest: {}
  slim: {}
Name: znc
