Blocks:
- Architectures: null
  Directory: full
  GitCommit: ""
  Tags:
  - 1.8.2
  - "1.8"
  - latest
- Architectures: null
  Directory: slim
  GitCommit: ""
  Tags:
  - 1.8.2-slim
  - 1.8-slim
  - slim
- Architectures: null
  Directory: full
  GitCommit: ""
  Tags:
  - 1.8.1
- Architectures: null
  Directory: slim
  GitCommit: ""
  Tags:
  - 1.8.1-slim
- Architectures: null
  Directory: full
  GitCommit: 91f58af10b62197187af1f0a9695488e88279e98
  Tags:
  - 1.8.0
- Architectures: null
  Directory: slim
  GitCommit: 91f58af10b62197187af1f0a9695488e88279e98
  Tags:
  - 1.8.0-slim
- Architectures: null
  Directory: full
  GitCommit: ""
  Tags:
  - 1.7.5
  - "1.7"
- Architectures: null
  Directory: slim
  GitCommit: ""
  Tags:
  - 1.7.5-slim
  - 1.7-slim
- Architectures: null
  Directory: full
  GitCommit: ""
  Tags:
  - 1.7.4
- Architectures: null
  Directory: slim
  GitCommit: ""
  Tags:
  - 1.7.4-slim
- Architectures: null
  Directory: full
  GitCommit: ""
  Tags:
  - 1.7.3
- Architectures: null
  Directory: slim
  GitCommit: ""
  Tags:
  - 1.7.3-slim
- Architectures: null
  Directory: full
  GitCommit: ""
  Tags:
  - 1.7.2
- Architectures: null
  Directory: slim
  GitCommit: ""
  Tags:
  - 1.7.2-slim
- Architectures: null
  Directory: full
  GitCommit: ""
  Tags:
  - 1.7.1
- Architectures: null
  Directory: slim
  GitCommit: ""
  Tags:
  - 1.7.1-slim
- Architectures: null
  Directory: full
  GitCommit: ""
  Tags:
  - 1.7.0
- Architectures: null
  Directory: slim
  GitCommit: ""
  Tags:
  - 1.7.0-slim
- Architectures: null
  Directory: full
  GitCommit: ""
  Tags:
  - 1.6.6
  - "1.6"
- Architectures: null
  Directory: slim
  GitCommit: ""
  Tags:
  - 1.6.6-slim
  - 1.6-slim
- Architectures: null
  Directory: full
  GitCommit: ""
  Tags:
  - 1.6.5
- Architectures: null
  Directory: slim
  GitCommit: ""
  Tags:
  - 1.6.5-slim
- Architectures: null
  Directory: full
  GitCommit: 4656af8c0a93cae3f59af966970f0716709caec7
  Tags:
  - 1.6.4
- Architectures: null
  Directory: slim
  GitCommit: 4656af8c0a93cae3f59af966970f0716709caec7
  Tags:
  - 1.6.4-slim
- Architectures: null
  Directory: small
  GitCommit: 4f709903f42373069bd97cc55a31e4bd4b3fae03
  Tags:
  - 1.6.4-small
  - 1.6-small
  - small
GitRepo: https://github.com/znc/znc-docker.git
KnownTags:
  "1.6": {}
  1.6-slim: {}
  1.6-small: {}
  1.6.4: {}
  1.6.4-slim: {}
  1.6.4-small: {}
  1.6.5: {}
  1.6.5-slim: {}
  1.6.6: {}
  1.6.6-slim: {}
  "1.7": {}
  1.7-slim: {}
  1.7.0: {}
  1.7.0-slim: {}
  1.7.1: {}
  1.7.1-slim: {}
  1.7.2: {}
  1.7.2-slim: {}
  1.7.3: {}
  1.7.3-slim: {}
  1.7.4: {}
  1.7.4-slim: {}
  1.7.5: {}
  1.7.5-slim: {}
  "1.8": {}
  1.8-slim: {}
  1.8.0: {}
  1.8.0-slim: {}
  1.8.1: {}
  1.8.1-slim: {}
  1.8.2: {}
  1.8.2-slim: {}
  latest: {}
  slim: {}
  small: {}
Name: znc
