Blocks:
- Architectures: null
  Directory: full
  File: ""
  GitCommit: 83082df630a0da0ef2d3724aa0299fba193ac096
  Tags:
  - 1.10.0
  - "1.10"
  - latest
- Architectures: null
  Directory: slim
  File: ""
  GitCommit: 83082df630a0da0ef2d3724aa0299fba193ac096
  Tags:
  - 1.10.0-slim
  - 1.10-slim
  - slim
- Architectures: null
  Directory: full
  File: ""
  GitCommit: 14890ffcd1006eefbe0e2aeb9ea389b49eb995ce
  Tags:
  - 1.9.1
  - "1.9"
- Architectures: null
  Directory: slim
  File: ""
  GitCommit: 14890ffcd1006eefbe0e2aeb9ea389b49eb995ce
  Tags:
  - 1.9.1-slim
  - 1.9-slim
- Architectures: null
  Directory: full
  File: ""
  GitCommit: 8638ba43acaef4bff2d4d39668c1992f411230a6
  Tags:
  - 1.9.0
- Architectures: null
  Directory: slim
  File: ""
  GitCommit: 8638ba43acaef4bff2d4d39668c1992f411230a6
  Tags:
  - 1.9.0-slim
- Architectures: null
  Directory: full
  File: ""
  GitCommit: d5bb727806f238f95bc74fcc182042932cd60c11
  Tags:
  - 1.8.2
  - "1.8"
- Architectures: null
  Directory: slim
  File: ""
  GitCommit: d5bb727806f238f95bc74fcc182042932cd60c11
  Tags:
  - 1.8.2-slim
  - 1.8-slim
- Architectures: null
  Directory: full
  File: ""
  GitCommit: cb2cabf8d63bc992f530b0fb86d0ad9cf955819d
  Tags:
  - 1.8.1
- Architectures: null
  Directory: slim
  File: ""
  GitCommit: cb2cabf8d63bc992f530b0fb86d0ad9cf955819d
  Tags:
  - 1.8.1-slim
- Architectures: null
  Directory: full
  File: ""
  GitCommit: 91f58af10b62197187af1f0a9695488e88279e98
  Tags:
  - 1.8.0
- Architectures: null
  Directory: slim
  File: ""
  GitCommit: 91f58af10b62197187af1f0a9695488e88279e98
  Tags:
  - 1.8.0-slim
- Architectures: null
  Directory: full
  File: ""
  GitCommit: 8549b62a7e44cb6c2d1fde3839461ceddebac15d
  Tags:
  - 1.7.5
  - "1.7"
- Architectures: null
  Directory: slim
  File: ""
  GitCommit: 8549b62a7e44cb6c2d1fde3839461ceddebac15d
  Tags:
  - 1.7.5-slim
  - 1.7-slim
- Architectures: null
  Directory: full
  File: ""
  GitCommit: e1047ff1ab0d4e2b4bca71fb65b16645c2ffa0a1
  Tags:
  - 1.7.4
- Architectures: null
  Directory: slim
  File: ""
  GitCommit: e1047ff1ab0d4e2b4bca71fb65b16645c2ffa0a1
  Tags:
  - 1.7.4-slim
- Architectures: null
  Directory: full
  File: ""
  GitCommit: c75452c182d9e06e84f7ad7e1958e8e6063eb38a
  Tags:
  - 1.7.3
- Architectures: null
  Directory: slim
  File: ""
  GitCommit: c75452c182d9e06e84f7ad7e1958e8e6063eb38a
  Tags:
  - 1.7.3-slim
- Architectures: null
  Directory: full
  File: ""
  GitCommit: 4da25330d7d4415507c5abd24efa74130243a5b3
  Tags:
  - 1.7.2
- Architectures: null
  Directory: slim
  File: ""
  GitCommit: 4da25330d7d4415507c5abd24efa74130243a5b3
  Tags:
  - 1.7.2-slim
- Architectures: null
  Directory: full
  File: ""
  GitCommit: e1b3356c689e2b6171252770a17ffb662fdb4d8c
  Tags:
  - 1.7.1
- Architectures: null
  Directory: slim
  File: ""
  GitCommit: e1b3356c689e2b6171252770a17ffb662fdb4d8c
  Tags:
  - 1.7.1-slim
- Architectures: null
  Directory: full
  File: ""
  GitCommit: 39116f34fa92cb9c9b170c60bfb32411d408a582
  Tags:
  - 1.7.0
- Architectures: null
  Directory: slim
  File: ""
  GitCommit: 39116f34fa92cb9c9b170c60bfb32411d408a582
  Tags:
  - 1.7.0-slim
- Architectures: null
  Directory: full
  File: ""
  GitCommit: 87d5d3c2f138540a97cd067fa869fab5eeeca3b8
  Tags:
  - 1.6.6
  - "1.6"
- Architectures: null
  Directory: slim
  File: ""
  GitCommit: 87d5d3c2f138540a97cd067fa869fab5eeeca3b8
  Tags:
  - 1.6.6-slim
  - 1.6-slim
- Architectures: null
  Directory: full
  File: ""
  GitCommit: 7f4f14214b67e540892a281d69f855aefcef35ce
  Tags:
  - 1.6.5
- Architectures: null
  Directory: slim
  File: ""
  GitCommit: 7f4f14214b67e540892a281d69f855aefcef35ce
  Tags:
  - 1.6.5-slim
- Architectures: null
  Directory: full
  File: ""
  GitCommit: 4656af8c0a93cae3f59af966970f0716709caec7
  Tags:
  - 1.6.4
- Architectures: null
  Directory: slim
  File: ""
  GitCommit: 4656af8c0a93cae3f59af966970f0716709caec7
  Tags:
  - 1.6.4-slim
- Architectures: null
  Directory: small
  File: ""
  GitCommit: 4f709903f42373069bd97cc55a31e4bd4b3fae03
  Tags:
  - 1.6.4-small
  - 1.6-small
  - small
GitRepo: https://github.com/znc/znc-docker.git
KnownTags:
  "1.6": {}
  1.6-slim: {}
  1.6-small: {}
  1.6.4: {}
  1.6.4-slim: {}
  1.6.4-small: {}
  1.6.5: {}
  1.6.5-slim: {}
  1.6.6: {}
  1.6.6-slim: {}
  "1.7": {}
  1.7-slim: {}
  1.7.0: {}
  1.7.0-slim: {}
  1.7.1: {}
  1.7.1-slim: {}
  1.7.2: {}
  1.7.2-slim: {}
  1.7.3: {}
  1.7.3-slim: {}
  1.7.4: {}
  1.7.4-slim: {}
  1.7.5: {}
  1.7.5-slim: {}
  "1.8": {}
  1.8-slim: {}
  1.8.0: {}
  1.8.0-slim: {}
  1.8.1: {}
  1.8.1-slim: {}
  1.8.2: {}
  1.8.2-slim: {}
  "1.9": {}
  1.9-slim: {}
  1.9.0: {}
  1.9.0-slim: {}
  1.9.1: {}
  1.9.1-slim: {}
  "1.10": {}
  1.10-slim: {}
  1.10.0: {}
  1.10.0-slim: {}
  latest: {}
  slim: {}
  small: {}
Name: znc
