Blocks:
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: 96c180e154599cb2831d58f8ef290967ee12e3b9
  Tags:
  - "8"
  - "8.8"
  - 8.8-20230524
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: 96c180e154599cb2831d58f8ef290967ee12e3b9
  Tags:
  - 8-minimal
  - 8.8-minimal
  - 8.8-minimal-20230524
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: 600467393dc75d3768196215ea1c122b552b9728
  Tags:
  - latest
  - "9"
  - "9.2"
  - 9.2-20230512
- Architectures:
  - amd64
  - arm64v8
  - ppc64le
  - s390x
  Directory: ""
  GitCommit: 600467393dc75d3768196215ea1c122b552b9728
  Tags:
  - minimal
  - 9-minimal
  - 9.2-minimal
  - 9.2-minimal-20230512
GitRepo: https://github.com/AlmaLinux/docker-images.git
KnownTags:
  "8": {}
  8-minimal: {}
  "8.8": {}
  8.8-20230524: {}
  8.8-minimal: {}
  8.8-minimal-20230524: {}
  "9": {}
  9-minimal: {}
  "9.2": {}
  9.2-20230512: {}
  9.2-minimal: {}
  9.2-minimal-20230512: {}
  latest: {}
  minimal: {}
Name: almalinux
