Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: bookworm
  GitCommit: ""
  Tags:
  - bookworm
  - bookworm-20230612
  - "12.0"
  - "12"
  - latest
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: bookworm/backports
  GitCommit: ""
  Tags:
  - bookworm-backports
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: bookworm/slim
  GitCommit: ""
  Tags:
  - bookworm-slim
  - bookworm-20230612-slim
  - 12.0-slim
  - 12-slim
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: bullseye
  GitCommit: ""
  Tags:
  - bullseye
  - bullseye-20230612
  - "11.7"
  - "11"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: bullseye/backports
  GitCommit: ""
  Tags:
  - bullseye-backports
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: bullseye/slim
  GitCommit: ""
  Tags:
  - bullseye-slim
  - bullseye-20230612-slim
  - 11.7-slim
  - 11-slim
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: buster
  GitCommit: ""
  Tags:
  - buster
  - buster-20230612
  - "10.13"
  - "10"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: buster/backports
  GitCommit: ""
  Tags:
  - buster-backports
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: buster/slim
  GitCommit: ""
  Tags:
  - buster-slim
  - buster-20230612-slim
  - 10.13-slim
  - 10-slim
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - riscv64
  - s390x
  Directory: experimental
  GitCommit: ""
  Tags:
  - experimental
  - experimental-20230612
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: oldoldstable
  GitCommit: ""
  Tags:
  - oldoldstable
  - oldoldstable-20230612
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: oldoldstable/backports
  GitCommit: ""
  Tags:
  - oldoldstable-backports
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  Directory: oldoldstable/slim
  GitCommit: ""
  Tags:
  - oldoldstable-slim
  - oldoldstable-20230612-slim
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: oldstable
  GitCommit: ""
  Tags:
  - oldstable
  - oldstable-20230612
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: oldstable/backports
  GitCommit: ""
  Tags:
  - oldstable-backports
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: oldstable/slim
  GitCommit: ""
  Tags:
  - oldstable-slim
  - oldstable-20230612-slim
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: rc-buggy
  GitCommit: ""
  Tags:
  - rc-buggy
  - rc-buggy-20230612
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - riscv64
  - s390x
  Directory: sid
  GitCommit: ""
  Tags:
  - sid
  - sid-20230612
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - riscv64
  - s390x
  Directory: sid/slim
  GitCommit: ""
  Tags:
  - sid-slim
  - sid-20230612-slim
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: stable
  GitCommit: ""
  Tags:
  - stable
  - stable-20230612
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: stable/backports
  GitCommit: ""
  Tags:
  - stable-backports
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: stable/slim
  GitCommit: ""
  Tags:
  - stable-slim
  - stable-20230612-slim
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: testing
  GitCommit: ""
  Tags:
  - testing
  - testing-20230612
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: testing/backports
  GitCommit: ""
  Tags:
  - testing-backports
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: testing/slim
  GitCommit: ""
  Tags:
  - testing-slim
  - testing-20230612-slim
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: trixie
  GitCommit: ""
  Tags:
  - trixie
  - trixie-20230612
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: trixie/backports
  GitCommit: ""
  Tags:
  - trixie-backports
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: trixie/slim
  GitCommit: ""
  Tags:
  - trixie-slim
  - trixie-20230612-slim
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - riscv64
  - s390x
  Directory: unstable
  GitCommit: ""
  Tags:
  - unstable
  - unstable-20230612
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - riscv64
  - s390x
  Directory: unstable/slim
  GitCommit: ""
  Tags:
  - unstable-slim
  - unstable-20230612-slim
GitRepo: https://github.com/debuerreotype/docker-debian-artifacts.git
KnownTags:
  "10": {}
  10-slim: {}
  "10.13": {}
  10.13-slim: {}
  "11": {}
  11-slim: {}
  "11.7": {}
  11.7-slim: {}
  "12": {}
  12-slim: {}
  "12.0": {}
  12.0-slim: {}
  bookworm: {}
  bookworm-20230612: {}
  bookworm-20230612-slim: {}
  bookworm-backports: {}
  bookworm-slim: {}
  bullseye: {}
  bullseye-20230612: {}
  bullseye-20230612-slim: {}
  bullseye-backports: {}
  bullseye-slim: {}
  buster: {}
  buster-20230612: {}
  buster-20230612-slim: {}
  buster-backports: {}
  buster-slim: {}
  experimental: {}
  experimental-20230612: {}
  latest: {}
  oldoldstable: {}
  oldoldstable-20230612: {}
  oldoldstable-20230612-slim: {}
  oldoldstable-backports: {}
  oldoldstable-slim: {}
  oldstable: {}
  oldstable-20230612: {}
  oldstable-20230612-slim: {}
  oldstable-backports: {}
  oldstable-slim: {}
  rc-buggy: {}
  rc-buggy-20230612: {}
  sid: {}
  sid-20230612: {}
  sid-20230612-slim: {}
  sid-slim: {}
  stable: {}
  stable-20230612: {}
  stable-20230612-slim: {}
  stable-backports: {}
  stable-slim: {}
  testing: {}
  testing-20230612: {}
  testing-20230612-slim: {}
  testing-backports: {}
  testing-slim: {}
  trixie: {}
  trixie-20230612: {}
  trixie-20230612-slim: {}
  trixie-backports: {}
  trixie-slim: {}
  unstable: {}
  unstable-20230612: {}
  unstable-20230612-slim: {}
  unstable-slim: {}
Name: debian
