Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: "4.1"
  GitCommit: 676c7fb1737244ff736edc56064af335cf9d466f
  Tags:
  - 4.1.2
  - "4.1"
  - "4"
  - latest
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: "4.0"
  GitCommit: 4802b868f5684890ed82a6ec1c8b32141c0dc73c
  Tags:
  - 4.0.10
  - "4.0"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  Directory: "3.11"
  GitCommit: 7f0ca5fd56b2397688f4de64cd5d15ef54b581ec
  Tags:
  - 3.11.15
  - "3.11"
  - "3"
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  Directory: "3.0"
  GitCommit: 0472adffa9e3b3361f2dbe4b089592d1cb84d36d
  Tags:
  - 3.0.29
  - "3.0"
GitRepo: https://github.com/docker-library/cassandra.git
KnownTags:
  "3": {}
  "3.0": {}
  3.0.29: {}
  "3.11": {}
  3.11.15: {}
  "4": {}
  "4.0": {}
  4.0.10: {}
  "4.1": {}
  4.1.2: {}
  latest: {}
Name: cassandra
