Blocks:
- Architectures: null
  Directory: 9.1.10/bullseye
  GitCommit: ""
  Tags:
  - latest
  - 9.1.10
- Architectures: null
  Directory: 9.0.4/bullseye
  GitCommit: ""
  Tags:
  - stable
  - 9.0.4
- Architectures: null
  Directory: 9.1.9/bullseye
  GitCommit: ""
  Tags:
  - 9.1.9
- Architectures: null
  Directory: 9.1.8/bullseye
  GitCommit: ""
  Tags:
  - 9.1.8
- Architectures: null
  Directory: 9.1.5/bullseye
  GitCommit: ""
  Tags:
  - 9.1.5
- Architectures: null
  Directory: 9.1.4/bullseye
  GitCommit: ""
  Tags:
  - 9.1.4
- Architectures: null
  Directory: 9.1.1/bullseye
  GitCommit: ""
  Tags:
  - 9.1.1
- Architectures: null
  Directory: 9.0.2/bullseye
  GitCommit: ""
  Tags:
  - 9.0.2
- Architectures: null
  Directory: 8.5.20/bullseye
  GitCommit: ""
  Tags:
  - 8.5.20
- Architectures: null
  Directory: 9.0.0/bullseye
  GitCommit: ""
  Tags:
  - 9.0.0
- Architectures: null
  Directory: 8.4.2/bullseye
  GitCommit: ""
  Tags:
  - 8.4.2
- Architectures: null
  Directory: 8.5.17/bullseye
  GitCommit: ""
  Tags:
  - 8.5.17
- Architectures: null
  Directory: 8.5.10/bullseye
  GitCommit: ""
  Tags:
  - 8.5.10
- Architectures: null
  Directory: 8.5.5/bullseye
  GitCommit: ""
  Tags:
  - 8.5.5
- Architectures: null
  Directory: 8.4.1/bullseye
  GitCommit: ""
  Tags:
  - 8.4.1
- Architectures: null
  Directory: 8.5.3/bullseye
  GitCommit: ""
  Tags:
  - 8.5.3
- Architectures: null
  Directory: 8.5.2/bullseye
  GitCommit: ""
  Tags:
  - 8.5.2
- Architectures: null
  Directory: 8.3.29/stretch
  GitCommit: ""
  Tags:
  - 8.3.29
- Architectures: null
  Directory: 8.4.0/stretch
  GitCommit: ""
  Tags:
  - 8.4.0
- Architectures: null
  Directory: 8.2.4/stretch
  GitCommit: ""
  Tags:
  - 8.2.4
- Architectures: null
  Directory: 8.3.26/stretch
  GitCommit: ""
  Tags:
  - 8.3.26
- Architectures: null
  Directory: 8.3.18/stretch
  GitCommit: ""
  Tags:
  - 8.3.18
- Architectures: null
  Directory: 8.3.13/stretch
  GitCommit: ""
  Tags:
  - 8.3.13
- Architectures: null
  Directory: 8.2.3/stretch
  GitCommit: ""
  Tags:
  - 8.2.3
- Architectures: null
  Directory: 8.2.2/stretch
  GitCommit: ""
  Tags:
  - 8.2.2
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 8.2.0/stretch
  GitCommit: ""
  Tags:
  - 8.2.0
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 8.1.30/stretch
  GitCommit: ""
  Tags:
  - 8.1.30
- Architectures: null
  Directory: 8.0.3/stretch
  GitCommit: ""
  Tags:
  - 8.0.3
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 8.1.15/stretch
  GitCommit: ""
  Tags:
  - 8.1.15
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 8.1.12/stretch
  GitCommit: ""
  Tags:
  - 8.1.12
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 8.1.8/stretch
  GitCommit: ""
  Tags:
  - 8.1.8
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 8.1.6/stretch
  GitCommit: ""
  Tags:
  - 8.1.6
- Architectures: null
  Directory: 8.0.0/stretch
  GitCommit: ""
  Tags:
  - 8.0.0
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 8.1.5/stretch
  GitCommit: ""
  Tags:
  - 8.1.5
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 8.1.4/stretch
  GitCommit: ""
  Tags:
  - 8.1.4
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 8.1.2/stretch
  GitCommit: ""
  Tags:
  - 8.1.2
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 8.1.1/stretch
  GitCommit: ""
  Tags:
  - 8.1.1
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 8.1.0/stretch
  GitCommit: ""
  Tags:
  - 8.1.0
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 7.7.25/stretch
  GitCommit: ""
  Tags:
  - 7.7.25
- Architectures: null
  Directory: 7.6.4/stretch
  GitCommit: ""
  Tags:
  - 7.6.4
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 7.7.22/stretch
  GitCommit: ""
  Tags:
  - 7.7.22
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 7.7.21/stretch
  GitCommit: ""
  Tags:
  - 7.7.21
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 7.7.20/stretch
  GitCommit: ""
  Tags:
  - 7.7.20
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 7.7.19/stretch
  GitCommit: ""
  Tags:
  - 7.7.19
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 7.7.18/stretch
  GitCommit: ""
  Tags:
  - 7.7.18
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: 7.7.17/stretch
  GitCommit: ""
  Tags:
  - 7.7.17
- Architectures:
  - amd64
  - arm32v7
  Directory: 7.7.16/stretch
  GitCommit: ""
  Tags:
  - 7.7.16
- Architectures:
  - amd64
  - arm32v7
  Directory: 7.7.14/stretch
  GitCommit: ""
  Tags:
  - 7.7.14
- Architectures:
  - amd64
  - arm32v7
  Directory: 7.7.13/stretch
  GitCommit: ""
  Tags:
  - 7.7.13
- Architectures:
  - amd64
  - arm32v7
  Directory: 7.7.12/stretch
  GitCommit: ""
  Tags:
  - 7.7.12
- Architectures:
  - amd64
  - arm32v7
  Directory: 7.7.11/stretch
  GitCommit: ""
  Tags:
  - 7.7.11
- Architectures:
  - amd64
  - arm32v7
  Directory: 7.7.10/stretch
  GitCommit: ""
  Tags:
  - 7.7.10
- Architectures:
  - amd64
  - arm32v7
  Directory: 7.7.9/stretch
  GitCommit: ""
  Tags:
  - 7.7.9
- Architectures:
  - amd64
  - arm32v7
  Directory: 7.7.8/stretch
  GitCommit: ""
  Tags:
  - 7.7.8
- Architectures:
  - amd64
  - arm32v7
  Directory: 7.7.7/stretch
  GitCommit: ""
  Tags:
  - 7.7.7
- Architectures: null
  Directory: 7.6.3/stretch
  GitCommit: 2fbb0429d19cf02b3332432124b349c62397fa5c
  Tags:
  - 7.6.3
- Architectures: null
  Directory: 7.7.5/stretch
  GitCommit: 9ca2f2d53548670fc65f23c31c72516962f9509d
  Tags:
  - 7.7.5
- Architectures: null
  Directory: 7.7.4/stretch
  GitCommit: 9fc0c0b9d4c0f678238c1eb85780661c16201f90
  Tags:
  - 7.7.4
- Architectures: null
  Directory: 7.7.2/stretch
  GitCommit: 7e43714b2b424a54dfef3099c0bc0b27b1e202ef
  Tags:
  - 7.7.2
- Architectures: null
  Directory: 7.6.0/stretch
  GitCommit: 96f1963cd93da79eecd6fc7442ab301135a982f5
  Tags:
  - 7.6.0
- Architectures: null
  Directory: 7.7.1/stretch
  GitCommit: 96c86a17801437c3424834721a171a6521cc8d30
  Tags:
  - 7.7.1
- Architectures: null
  Directory: 7.7.0/stretch
  GitCommit: a90c231a9bc888705b72f0fca1f0774897dfba54
  Tags:
  - 7.7.0
- Architectures: null
  Directory: 7.5.15/stretch
  GitCommit: 31e2158e7ba2bb2fa9ebff7c0717c476244506bb
  Tags:
  - 7.5.15
- Architectures: null
  Directory: 7.5.14/stretch
  GitCommit: b76acfff26b916351287a562d98b29c199c188ab
  Tags:
  - 7.5.14
- Architectures: null
  Directory: 7.5.13/stretch
  GitCommit: 47b7841a2ab6eadea32f6104bc62a779c682e47e
  Tags:
  - 7.5.13
- Architectures: null
  Directory: 7.5.12/stretch
  GitCommit: c62441347c7984269ab315fbf042850cbe3407fa
  Tags:
  - 7.5.12
- Architectures: null
  Directory: 7.5.11/stretch
  GitCommit: e8d1f0bf3db5e9cbfa331aba06bb740a76a81f83
  Tags:
  - 7.5.11
- Architectures: null
  Directory: 7.5.7/jessie
  GitCommit: 05c70112197e4c59da8af37743a493ca9a3266fb
  Tags:
  - 7.5.7
GitRepo: https://github.com/SWI-Prolog/docker-swipl.git
KnownTags:
  7.5.7: {}
  7.5.11: {}
  7.5.12: {}
  7.5.13: {}
  7.5.14: {}
  7.5.15: {}
  7.6.0: {}
  7.6.3: {}
  7.6.4: {}
  7.7.0: {}
  7.7.1: {}
  7.7.2: {}
  7.7.4: {}
  7.7.5: {}
  7.7.7: {}
  7.7.8: {}
  7.7.9: {}
  7.7.10: {}
  7.7.11: {}
  7.7.12: {}
  7.7.13: {}
  7.7.14: {}
  7.7.16: {}
  7.7.17: {}
  7.7.18: {}
  7.7.19: {}
  7.7.20: {}
  7.7.21: {}
  7.7.22: {}
  7.7.25: {}
  8.0.0: {}
  8.0.3: {}
  8.1.0: {}
  8.1.1: {}
  8.1.2: {}
  8.1.4: {}
  8.1.5: {}
  8.1.6: {}
  8.1.8: {}
  8.1.12: {}
  8.1.15: {}
  8.1.30: {}
  8.2.0: {}
  8.2.2: {}
  8.2.3: {}
  8.2.4: {}
  8.3.13: {}
  8.3.18: {}
  8.3.26: {}
  8.3.29: {}
  8.4.0: {}
  8.4.1: {}
  8.4.2: {}
  8.5.2: {}
  8.5.3: {}
  8.5.5: {}
  8.5.10: {}
  8.5.17: {}
  8.5.20: {}
  9.0.0: {}
  9.0.2: {}
  9.0.4: {}
  9.1.1: {}
  9.1.4: {}
  9.1.5: {}
  9.1.8: {}
  9.1.9: {}
  9.1.10: {}
  latest: {}
  stable: {}
Name: swipl
