Blocks:
- Architectures: null
  Directory: 9.1.21/bookworm
  File: ""
  GitCommit: 1a0a739f7edf19f4282958568ac8245f4410e1b1
  Tags:
  - latest
  - 9.1.21
- Architectures: null
  Directory: 9.0.4/bullseye
  File: ""
  GitCommit: 1a0a739f7edf19f4282958568ac8245f4410e1b1
  Tags:
  - stable
  - 9.0.4
- Architectures: null
  Directory: 9.1.19/bullseye
  File: ""
  GitCommit: aed2f55c031507e8fe2a2fede471ffbb5ced5af0
  Tags:
  - 9.1.19
- Architectures: null
  Directory: 9.1.17/bullseye
  File: ""
  GitCommit: 9369a643cd0ca2f7b2741d65b45e9b3ab36ea378
  Tags:
  - 9.1.17
- Architectures: null
  Directory: 9.1.14/bullseye
  File: ""
  GitCommit: 80927128dd1cf6f3a87290adaf35bff9e50d808d
  Tags:
  - 9.1.14
- Architectures: null
  Directory: 9.1.13/bullseye
  File: ""
  GitCommit: e3851850186cded44b986da8095df36f5d87f0df
  Tags:
  - 9.1.13
- Architectures: null
  Directory: 9.1.11/bullseye
  File: ""
  GitCommit: 8e1d5c2336b3b1856b479aab170108a452200d1e
  Tags:
  - 9.1.11
- Architectures: null
  Directory: 9.1.10/bullseye
  File: ""
  GitCommit: a96b8e1155f4f6997895bf5e4aa5f4e61fb69bed
  Tags:
  - 9.1.10
- Architectures: null
  Directory: 9.1.9/bullseye
  File: ""
  GitCommit: 61526b09a94f046988e74f9162d898fc7203d1f4
  Tags:
  - 9.1.9
- Architectures: null
  Directory: 9.1.8/bullseye
  File: ""
  GitCommit: 6b9f59764967f0b615220c939aedc9eec22cce23
  Tags:
  - 9.1.8
- Architectures: null
  Directory: 9.1.5/bullseye
  File: ""
  GitCommit: 67b156afb3feb8e0a4537bfb7671662f12526156
  Tags:
  - 9.1.5
- Architectures: null
  Directory: 9.1.4/bullseye
  File: ""
  GitCommit: 366d912cf8e9c8ba3783a76acf57380d7a281883
  Tags:
  - 9.1.4
- Architectures: null
  Directory: 9.1.1/bullseye
  File: ""
  GitCommit: d74a1b64f53d54d7ed6e74b3c36e5c6799e8964e
  Tags:
  - 9.1.1
- Architectures: null
  Directory: 9.0.2/bullseye
  File: ""
  GitCommit: d74a1b64f53d54d7ed6e74b3c36e5c6799e8964e
  Tags:
  - 9.0.2
- Architectures: null
  Directory: 8.5.20/bullseye
  File: ""
  GitCommit: 9983349510aaf24b76b5d2798da28369b889f729
  Tags:
  - 8.5.20
- Architectures: null
  Directory: 9.0.0/bullseye
  File: ""
  GitCommit: 489f7db3d9f6116df6ef0e1efa1d3bdcfb38cc36
  Tags:
  - 9.0.0
- Architectures: null
  Directory: 8.4.2/bullseye
  File: ""
  GitCommit: c4ca1b9ddd9c416ad22c3775d82921c1a2b69c2b
  Tags:
  - 8.4.2
- Architectures: null
  Directory: 8.5.17/bullseye
  File: ""
  GitCommit: 0bd1466f1bfbd7a78d1af9ca5cd12705c0855f65
  Tags:
  - 8.5.17
- Architectures: null
  Directory: 8.5.10/bullseye
  File: ""
  GitCommit: b4cd0de2f6872a4270bba62d430e10de0b7663d8
  Tags:
  - 8.5.10
- Architectures: null
  Directory: 8.5.5/bullseye
  File: ""
  GitCommit: 0feeb46c7fba8ec663af620e86193b6f36ea7148
  Tags:
  - 8.5.5
- Architectures: null
  Directory: 8.4.1/bullseye
  File: ""
  GitCommit: 2a84498401b2a11a3693536310d04e1491864db9
  Tags:
  - 8.4.1
- Architectures: null
  Directory: 8.5.3/bullseye
  File: ""
  GitCommit: 77a23351c6f1079f80c7f3b8a7c8f0fb98afd138
  Tags:
  - 8.5.3
- Architectures: null
  Directory: 8.5.2/bullseye
  File: ""
  GitCommit: cd4fbab463d93710ea0d48aad3dbc7ad1876549c
  Tags:
  - 8.5.2
- Architectures: null
  Directory: 8.3.29/stretch
  File: ""
  GitCommit: ca3e88bd44217c3effa881d30b19d7eb1ec1260a
  Tags:
  - 8.3.29
- Architectures: null
  Directory: 8.4.0/stretch
  File: ""
  GitCommit: ca3e88bd44217c3effa881d30b19d7eb1ec1260a
  Tags:
  - 8.4.0
- Architectures: null
  Directory: 8.2.4/stretch
  File: ""
  GitCommit: a776612673d5026596594620aaa8602940d495cf
  Tags:
  - 8.2.4
- Architectures: null
  Directory: 8.3.26/stretch
  File: ""
  GitCommit: 03cfc00242c65ac7bcc1f99cb2bd67babb1c3c44
  Tags:
  - 8.3.26
- Architectures: null
  Directory: 8.3.18/stretch
  File: ""
  GitCommit: 5310e0a5c70dd4e6121d96b1d0b50d4d1dafd04d
  Tags:
  - 8.3.18
- Architectures: null
  Directory: 8.3.13/stretch
  File: ""
  GitCommit: 09749734edb1e4c567a93e5e713b4004fd589a53
  Tags:
  - 8.3.13
- Architectures: null
  Directory: 8.2.3/stretch
  File: ""
  GitCommit: 09749734edb1e4c567a93e5e713b4004fd589a53
  Tags:
  - 8.2.3
- Architectures: null
  Directory: 8.2.2/stretch
  File: ""
  GitCommit: 648de9790d5b9cd69a777bb23777b811f92c1609
  Tags:
  - 8.2.2
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8.2.0/stretch
  File: ""
  GitCommit: 4a4f42a99acffc2f1c193ac69971e7e721abbf3c
  Tags:
  - 8.2.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8.1.30/stretch
  File: ""
  GitCommit: 0b4a94d8ca1ce9a973d8159393eff69a36fafe4e
  Tags:
  - 8.1.30
- Architectures: null
  Directory: 8.0.3/stretch
  File: ""
  GitCommit: 0b4a94d8ca1ce9a973d8159393eff69a36fafe4e
  Tags:
  - 8.0.3
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8.1.15/stretch
  File: ""
  GitCommit: 2a375e3ca58d1a8bdbec1444b59ff68f3ef91f86
  Tags:
  - 8.1.15
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8.1.12/stretch
  File: ""
  GitCommit: 87ae5e3e6e67594f835dfb34ffa2c57d7ed65ce1
  Tags:
  - 8.1.12
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8.1.8/stretch
  File: ""
  GitCommit: b9018ff59091e52925de90ae1e73d281031d06e9
  Tags:
  - 8.1.8
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8.1.6/stretch
  File: ""
  GitCommit: f2abb30cffae0af6e27207dafd9e181e61abe315
  Tags:
  - 8.1.6
- Architectures: null
  Directory: 8.0.0/stretch
  File: ""
  GitCommit: f2abb30cffae0af6e27207dafd9e181e61abe315
  Tags:
  - 8.0.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8.1.5/stretch
  File: ""
  GitCommit: 7e4bc6b609d9d93f1a82e1b9b7e2691d6f282bd9
  Tags:
  - 8.1.5
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8.1.4/stretch
  File: ""
  GitCommit: 05b8eb396d68c1bf8e143f631cb0bd5df7e23040
  Tags:
  - 8.1.4
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8.1.2/stretch
  File: ""
  GitCommit: 39dce967080da421e35ff48ce8a06c3680176fe1
  Tags:
  - 8.1.2
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8.1.1/stretch
  File: ""
  GitCommit: dc49d3fa26703cc8ebaae999a680a62984ee385d
  Tags:
  - 8.1.1
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 8.1.0/stretch
  File: ""
  GitCommit: 8081278f32f38fe206d27d8183b292c9ad1140da
  Tags:
  - 8.1.0
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 7.7.25/stretch
  File: ""
  GitCommit: f06a5ab71fcca1676a79a4baa8d6ccb091f03b6a
  Tags:
  - 7.7.25
- Architectures: null
  Directory: 7.6.4/stretch
  File: ""
  GitCommit: f06a5ab71fcca1676a79a4baa8d6ccb091f03b6a
  Tags:
  - 7.6.4
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 7.7.22/stretch
  File: ""
  GitCommit: ca31851cdd4101aefd5e8172e7fe33e062be2ee7
  Tags:
  - 7.7.22
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 7.7.21/stretch
  File: ""
  GitCommit: 1d06a09d029ed545f01076049408c1dee081d045
  Tags:
  - 7.7.21
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 7.7.20/stretch
  File: ""
  GitCommit: 599c776108e4cb86002c857dd9deee36f5388778
  Tags:
  - 7.7.20
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 7.7.19/stretch
  File: ""
  GitCommit: 1e124ba47bcc2ff0eaa7c357543bbdf723050025
  Tags:
  - 7.7.19
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 7.7.18/stretch
  File: ""
  GitCommit: 23bb74f08a23927ec15908fe374c6b098ee12f42
  Tags:
  - 7.7.18
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 7.7.17/stretch
  File: ""
  GitCommit: f8541e1a854320134936a20532a83b8179c02e66
  Tags:
  - 7.7.17
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 7.7.16/stretch
  File: ""
  GitCommit: 9938de3c91a33af80b5fd6a93d4f592c8d95003a
  Tags:
  - 7.7.16
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 7.7.14/stretch
  File: ""
  GitCommit: b16e9a5bb4709876756948f3c223d203b569942c
  Tags:
  - 7.7.14
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 7.7.13/stretch
  File: ""
  GitCommit: 9e5b018bc518736af3ec0005831a2a4d1a53cff5
  Tags:
  - 7.7.13
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 7.7.12/stretch
  File: ""
  GitCommit: 933c99a079ea1db144e5bddd8ecdbe7ff17cb4a0
  Tags:
  - 7.7.12
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 7.7.11/stretch
  File: ""
  GitCommit: 41b691546a116ce357192de19798dd68a7aa8223
  Tags:
  - 7.7.11
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 7.7.10/stretch
  File: ""
  GitCommit: fec30af23c6f68f227bced29053bb45334893c6c
  Tags:
  - 7.7.10
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 7.7.9/stretch
  File: ""
  GitCommit: 49d87bcac8f23de646e70250a5e08c6dcf3c9208
  Tags:
  - 7.7.9
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 7.7.8/stretch
  File: ""
  GitCommit: 42160906df31e8bb72d1d4222aaecafd1ff1a405
  Tags:
  - 7.7.8
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm32v7:
      Architecture: arm32v7
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: 7.7.7/stretch
  File: ""
  GitCommit: 2fbb0429d19cf02b3332432124b349c62397fa5c
  Tags:
  - 7.7.7
- Architectures: null
  Directory: 7.6.3/stretch
  File: ""
  GitCommit: 2fbb0429d19cf02b3332432124b349c62397fa5c
  Tags:
  - 7.6.3
- Architectures: null
  Directory: 7.7.5/stretch
  File: ""
  GitCommit: 9ca2f2d53548670fc65f23c31c72516962f9509d
  Tags:
  - 7.7.5
- Architectures: null
  Directory: 7.7.4/stretch
  File: ""
  GitCommit: 9fc0c0b9d4c0f678238c1eb85780661c16201f90
  Tags:
  - 7.7.4
- Architectures: null
  Directory: 7.7.2/stretch
  File: ""
  GitCommit: 7e43714b2b424a54dfef3099c0bc0b27b1e202ef
  Tags:
  - 7.7.2
- Architectures: null
  Directory: 7.6.0/stretch
  File: ""
  GitCommit: 96f1963cd93da79eecd6fc7442ab301135a982f5
  Tags:
  - 7.6.0
- Architectures: null
  Directory: 7.7.1/stretch
  File: ""
  GitCommit: 96c86a17801437c3424834721a171a6521cc8d30
  Tags:
  - 7.7.1
- Architectures: null
  Directory: 7.7.0/stretch
  File: ""
  GitCommit: a90c231a9bc888705b72f0fca1f0774897dfba54
  Tags:
  - 7.7.0
- Architectures: null
  Directory: 7.5.15/stretch
  File: ""
  GitCommit: 31e2158e7ba2bb2fa9ebff7c0717c476244506bb
  Tags:
  - 7.5.15
- Architectures: null
  Directory: 7.5.14/stretch
  File: ""
  GitCommit: b76acfff26b916351287a562d98b29c199c188ab
  Tags:
  - 7.5.14
- Architectures: null
  Directory: 7.5.13/stretch
  File: ""
  GitCommit: 47b7841a2ab6eadea32f6104bc62a779c682e47e
  Tags:
  - 7.5.13
- Architectures: null
  Directory: 7.5.12/stretch
  File: ""
  GitCommit: c62441347c7984269ab315fbf042850cbe3407fa
  Tags:
  - 7.5.12
- Architectures: null
  Directory: 7.5.11/stretch
  File: ""
  GitCommit: e8d1f0bf3db5e9cbfa331aba06bb740a76a81f83
  Tags:
  - 7.5.11
- Architectures: null
  Directory: 7.5.7/jessie
  File: ""
  GitCommit: 05c70112197e4c59da8af37743a493ca9a3266fb
  Tags:
  - 7.5.7
GitRepo: https://github.com/SWI-Prolog/docker-swipl.git
KnownTags:
  7.5.7: {}
  7.5.11: {}
  7.5.12: {}
  7.5.13: {}
  7.5.14: {}
  7.5.15: {}
  7.6.0: {}
  7.6.3: {}
  7.6.4: {}
  7.7.0: {}
  7.7.1: {}
  7.7.2: {}
  7.7.4: {}
  7.7.5: {}
  7.7.7: {}
  7.7.8: {}
  7.7.9: {}
  7.7.10: {}
  7.7.11: {}
  7.7.12: {}
  7.7.13: {}
  7.7.14: {}
  7.7.16: {}
  7.7.17: {}
  7.7.18: {}
  7.7.19: {}
  7.7.20: {}
  7.7.21: {}
  7.7.22: {}
  7.7.25: {}
  8.0.0: {}
  8.0.3: {}
  8.1.0: {}
  8.1.1: {}
  8.1.2: {}
  8.1.4: {}
  8.1.5: {}
  8.1.6: {}
  8.1.8: {}
  8.1.12: {}
  8.1.15: {}
  8.1.30: {}
  8.2.0: {}
  8.2.2: {}
  8.2.3: {}
  8.2.4: {}
  8.3.13: {}
  8.3.18: {}
  8.3.26: {}
  8.3.29: {}
  8.4.0: {}
  8.4.1: {}
  8.4.2: {}
  8.5.2: {}
  8.5.3: {}
  8.5.5: {}
  8.5.10: {}
  8.5.17: {}
  8.5.20: {}
  9.0.0: {}
  9.0.2: {}
  9.0.4: {}
  9.1.1: {}
  9.1.4: {}
  9.1.5: {}
  9.1.8: {}
  9.1.9: {}
  9.1.10: {}
  9.1.11: {}
  9.1.13: {}
  9.1.14: {}
  9.1.17: {}
  9.1.19: {}
  9.1.21: {}
  latest: {}
  stable: {}
Name: swipl
