Blocks:
- Architectures: null
  Directory: 9.1.10/bullseye
  GitCommit: ""
  Tags:
  - latest
  - 9.1.10
- Architectures: null
  Directory: 9.0.4/bullseye
  GitCommit: ""
  Tags:
  - stable
  - 9.0.4
GitRepo: https://github.com/SWI-Prolog/docker-swipl.git
KnownTags:
  9.0.4: {}
  9.1.10: {}
  latest: {}
  stable: {}
Name: swipl
