Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: 242f3c62ba1ceee0a3633045fc4fd9277cb86cd3
  Tags:
  - 2.4.57
  - "2.4"
  - "2"
  - latest
  - 2.4.57-bookworm
  - 2.4-bookworm
  - 2-bookworm
  - bookworm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: c87146e71508462f0ebd5de9890a0f8bb3b98c8f
  Tags:
  - 2.4.57-alpine
  - 2.4-alpine
  - 2-alpine
  - alpine
  - 2.4.57-alpine3.18
  - 2.4-alpine3.18
  - 2-alpine3.18
  - alpine3.18
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: ef41771bcc6367657fdbf1cdae028f2e1e32d222
  Tags:
  - 2.4.57-bullseye
  - 2.4-bullseye
  - 2-bullseye
  - bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: 7d6139b45f2e9a3146c2062894aca949cba91bba
  Tags:
  - 2.4.57-alpine3.17
  - 2.4-alpine3.17
  - 2-alpine3.17
  - alpine3.17
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: 91b7aa1f6c74ea2cae12a6cd6d02b03cf0c17db5
  Tags:
  - 2.4.56
  - 2.4.56-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: 91b7aa1f6c74ea2cae12a6cd6d02b03cf0c17db5
  Tags:
  - 2.4.56-alpine
  - 2.4.56-alpine3.17
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: 8bee4e1d12ad36ee34a40ae82746bc04a858e220
  Tags:
  - 2.4.55
  - 2.4.55-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: 8bee4e1d12ad36ee34a40ae82746bc04a858e220
  Tags:
  - 2.4.55-alpine
  - 2.4.55-alpine3.17
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: f3b7fd9c8ef59d1ad46c8b2a27df3e02d822834f
  Tags:
  - 2.4.54
  - 2.4.54-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: a8768519be284075c5cafd0ed6645d3bedaad6b1
  Tags:
  - 2.4.54-alpine
  - 2.4.54-alpine3.17
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: f3b7fd9c8ef59d1ad46c8b2a27df3e02d822834f
  Tags:
  - 2.4.54-alpine3.16
  - 2.4-alpine3.16
  - 2-alpine3.16
  - alpine3.16
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: 95c96d27c0c0a191f3fd1e7e9c5daa2b2fd0b8d5
  Tags:
  - 2.4.53
  - 2.4.53-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: c9123d74afc519c9566650baa5f1c97eff8b1e29
  Tags:
  - 2.4.53-alpine
  - 2.4.53-alpine3.16
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: 95c96d27c0c0a191f3fd1e7e9c5daa2b2fd0b8d5
  Tags:
  - 2.4.53-alpine3.15
  - 2.4-alpine3.15
  - 2-alpine3.15
  - alpine3.15
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: a7acc047c8970e0502f4c6b577775f840f1f99b6
  Tags:
  - 2.4.52
  - 2.4.52-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: a7acc047c8970e0502f4c6b577775f840f1f99b6
  Tags:
  - 2.4.52-alpine
  - 2.4.52-alpine3.15
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: 1665deed67e5b7e8d3bd5c08f29cb50d469e7d44
  Tags:
  - 2.4.51
  - 2.4.51-bullseye
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: 444663e2aea781b11c165219697d5621fe5d1a95
  Tags:
  - 2.4.51-alpine
  - 2.4.51-alpine3.15
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: 0ea87f3ee87fff6c7550763710ea2693c22f3966
  Tags:
  - 2.4.51-alpine3.14
  - 2.4-alpine3.14
  - 2-alpine3.14
  - alpine3.14
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: 4d89a55e9e5742bebd10fddf83ffb07f2df4d7a0
  Tags:
  - 2.4.51-buster
  - 2.4-buster
  - 2-buster
  - buster
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: 1f123b76be535ae2d577b93d3bf9a298ee897a8c
  Tags:
  - 2.4.50
  - 2.4.50-buster
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: 1f123b76be535ae2d577b93d3bf9a298ee897a8c
  Tags:
  - 2.4.50-alpine
  - 2.4.50-alpine3.14
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: ba836540b5c8a91b8e72a50c660399bb01178a1f
  Tags:
  - 2.4.49
  - 2.4.49-buster
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: 524c7ed345423370c6501c424b4694d517fa47c6
  Tags:
  - 2.4.49-alpine
  - 2.4.49-alpine3.14
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: 208fc2ba9a097530bb0b7386b0c2bebacdfb6c5c
  Tags:
  - 2.4.48
  - 2.4.48-buster
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: 208fc2ba9a097530bb0b7386b0c2bebacdfb6c5c
  Tags:
  - 2.4.48-alpine
  - 2.4.48-alpine3.14
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: 8835b23f748f80bcec510c14b68c84bc37767cdb
  Tags:
  - 2.4.48-alpine3.13
  - 2.4-alpine3.13
  - 2-alpine3.13
  - alpine3.13
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: ff1fcf6790e049650a4a7b7c8c0f3006e2f0e0d7
  Tags:
  - 2.4.46
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: ff1fcf6790e049650a4a7b7c8c0f3006e2f0e0d7
  Tags:
  - 2.4.46-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: 08b2e41e4612102693429001b5f244ff7a0ab824
  Tags:
  - 2.4.47
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: 08b2e41e4612102693429001b5f244ff7a0ab824
  Tags:
  - 2.4.47-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: 6c8e82e20ecefc94c616439f15d14c4bb215b200
  Tags:
  - 2.4.43
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: f5ef4cc849a4ea7ed56e797b86ad06ccf9f93a9a
  Tags:
  - 2.4.43-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: 4faace97468d7bced1ac4a072f89f151359ee9fa
  Tags:
  - 2.4.41
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: 3774290cad50854178dd0fc2b38ba843d2323e05
  Tags:
  - 2.4.41-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: 4f35d1063ac851ee633bcb2072ab4a9c34bcaefa
  Tags:
  - 2.4.39
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: f50f04246dbca7bfda7989692f486860603f4db4
  Tags:
  - 2.4.39-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: f6cb814440756f97821895731765d306528a3429
  Tags:
  - 2.4.38
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: f6cb814440756f97821895731765d306528a3429
  Tags:
  - 2.4.38-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: a426e299988c48f4937dfb4a9a67ac479ca011e1
  Tags:
  - 2.4.37
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: a426e299988c48f4937dfb4a9a67ac479ca011e1
  Tags:
  - 2.4.37-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: c1891301f0941fab9a2b4004b99bd6abc912bde5
  Tags:
  - 2.4.35
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: c1891301f0941fab9a2b4004b99bd6abc912bde5
  Tags:
  - 2.4.35-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - i386
  Directory: "2.4"
  GitCommit: 38842a5d4cdd44ff4888e8540c0da99009790d01
  Tags:
  - 2.4.34
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: 38842a5d4cdd44ff4888e8540c0da99009790d01
  Tags:
  - 2.4.34-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: 3af22f20b54cbb7c76ef4c3b12bd9dcf6cae862b
  Tags:
  - 2.4.33
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: eaf4c70fb21f167f77e0c9d4b6f8b8635b1cb4b6
  Tags:
  - 2.4.33-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: 313bbed20c261f55ba0862b99a48394f81697712
  Tags:
  - 2.4.32
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: f3d0cc50e47823c68c7b3114c9aed2f9814c8acf
  Tags:
  - 2.4.32-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: 17166574dea6a8c574443fc3a06bdb5a8bc97743
  Tags:
  - 2.4.29
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: 2.4/alpine
  GitCommit: 17166574dea6a8c574443fc3a06bdb5a8bc97743
  Tags:
  - 2.4.29-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "2.2"
  GitCommit: 49d553ae79f1b42ba541714c4e611aec5eefdfa8
  Tags:
  - 2.2.34
  - "2.2"
- Architectures:
  - amd64
  Directory: 2.2/alpine
  GitCommit: 49d553ae79f1b42ba541714c4e611aec5eefdfa8
  Tags:
  - 2.2.34-alpine
  - 2.2-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: c14a031c014aa2219aea2e73786f577300756f0b
  Tags:
  - 2.4.28
- Architectures:
  - amd64
  Directory: 2.4/alpine
  GitCommit: c14a031c014aa2219aea2e73786f577300756f0b
  Tags:
  - 2.4.28-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: 109e6332af1ac4176aefd7aad1c28e42f9e10644
  Tags:
  - 2.4.27
- Architectures:
  - amd64
  Directory: 2.4/alpine
  GitCommit: 3d5133cff766a1b6d734c9ac107613b7e53f2378
  Tags:
  - 2.4.27-alpine
- Architectures:
  - amd64
  Directory: 2.4/alpine
  GitCommit: a1e7d8139ce7d7fcb3c439f96021eeca015a6c8d
  Tags:
  - 2.4.25-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "2.2"
  GitCommit: 3e9afb8de1eca87f72b63d767a99ef807829944f
  Tags:
  - 2.2.32
- Architectures:
  - amd64
  Directory: 2.2/alpine
  GitCommit: 3e9afb8de1eca87f72b63d767a99ef807829944f
  Tags:
  - 2.2.32-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: "2.4"
  GitCommit: 3e9afb8de1eca87f72b63d767a99ef807829944f
  Tags:
  - 2.4.25
- Architectures: null
  Directory: "2.2"
  GitCommit: fa5223d83a5225aa3fd5b23229b785c7764142bf
  Tags:
  - 2.2.31
- Architectures: null
  Directory: 2.2/alpine
  GitCommit: 41d8483def4933a805bc6413b5a60df17a94b949
  Tags:
  - 2.2.31-alpine
- Architectures: null
  Directory: "2.4"
  GitCommit: abcf2cd7064bd5b29347eb4b42c1530fb41f757f
  Tags:
  - 2.4.23
- Architectures: null
  Directory: 2.4/alpine
  GitCommit: fa5223d83a5225aa3fd5b23229b785c7764142bf
  Tags:
  - 2.4.23-alpine
- Architectures: null
  Directory: "2.4"
  GitCommit: 07de32639616a6d307c3f4bb56a01d408d1765d6
  Tags:
  - 2.4.20
GitRepo: https://github.com/docker-library/httpd.git
KnownTags:
  "2": {}
  2-alpine: {}
  2-alpine3.13: {}
  2-alpine3.14: {}
  2-alpine3.15: {}
  2-alpine3.16: {}
  2-alpine3.17: {}
  2-alpine3.18: {}
  2-bookworm: {}
  2-bullseye: {}
  2-buster: {}
  "2.2": {}
  2.2-alpine: {}
  2.2.31: {}
  2.2.31-alpine: {}
  2.2.32: {}
  2.2.32-alpine: {}
  2.2.34: {}
  2.2.34-alpine: {}
  "2.4": {}
  2.4-alpine: {}
  2.4-alpine3.13: {}
  2.4-alpine3.14: {}
  2.4-alpine3.15: {}
  2.4-alpine3.16: {}
  2.4-alpine3.17: {}
  2.4-alpine3.18: {}
  2.4-bookworm: {}
  2.4-bullseye: {}
  2.4-buster: {}
  2.4.20: {}
  2.4.23: {}
  2.4.23-alpine: {}
  2.4.25: {}
  2.4.25-alpine: {}
  2.4.27: {}
  2.4.27-alpine: {}
  2.4.28: {}
  2.4.28-alpine: {}
  2.4.29: {}
  2.4.29-alpine: {}
  2.4.32: {}
  2.4.32-alpine: {}
  2.4.33: {}
  2.4.33-alpine: {}
  2.4.34: {}
  2.4.34-alpine: {}
  2.4.35: {}
  2.4.35-alpine: {}
  2.4.37: {}
  2.4.37-alpine: {}
  2.4.38: {}
  2.4.38-alpine: {}
  2.4.39: {}
  2.4.39-alpine: {}
  2.4.41: {}
  2.4.41-alpine: {}
  2.4.43: {}
  2.4.43-alpine: {}
  2.4.46: {}
  2.4.46-alpine: {}
  2.4.47: {}
  2.4.47-alpine: {}
  2.4.48: {}
  2.4.48-alpine: {}
  2.4.48-alpine3.13: {}
  2.4.48-alpine3.14: {}
  2.4.48-buster: {}
  2.4.49: {}
  2.4.49-alpine: {}
  2.4.49-alpine3.14: {}
  2.4.49-buster: {}
  2.4.50: {}
  2.4.50-alpine: {}
  2.4.50-alpine3.14: {}
  2.4.50-buster: {}
  2.4.51: {}
  2.4.51-alpine: {}
  2.4.51-alpine3.14: {}
  2.4.51-alpine3.15: {}
  2.4.51-bullseye: {}
  2.4.51-buster: {}
  2.4.52: {}
  2.4.52-alpine: {}
  2.4.52-alpine3.15: {}
  2.4.52-bullseye: {}
  2.4.53: {}
  2.4.53-alpine: {}
  2.4.53-alpine3.15: {}
  2.4.53-alpine3.16: {}
  2.4.53-bullseye: {}
  2.4.54: {}
  2.4.54-alpine: {}
  2.4.54-alpine3.16: {}
  2.4.54-alpine3.17: {}
  2.4.54-bullseye: {}
  2.4.55: {}
  2.4.55-alpine: {}
  2.4.55-alpine3.17: {}
  2.4.55-bullseye: {}
  2.4.56: {}
  2.4.56-alpine: {}
  2.4.56-alpine3.17: {}
  2.4.56-bullseye: {}
  2.4.57: {}
  2.4.57-alpine: {}
  2.4.57-alpine3.17: {}
  2.4.57-alpine3.18: {}
  2.4.57-bookworm: {}
  2.4.57-bullseye: {}
  alpine: {}
  alpine3.13: {}
  alpine3.14: {}
  alpine3.15: {}
  alpine3.16: {}
  alpine3.17: {}
  alpine3.18: {}
  bookworm: {}
  bullseye: {}
  buster: {}
  latest: {}
Name: httpd
