Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: 9dc2a99760aa37f4fde4cd35a8fe12ce3991e16c
      GitFetch: refs/heads/Rocky-9.2.20230513-Base-aarch64
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: 1d9cb06268ba4a479b814a2e191a5fa42048872c
      GitFetch: refs/heads/Rocky-9.2.20230513-Base-s390x
  Directory: ""
  GitCommit: 5534796e428e5ac942d820bc96a36a5d0404a8a4
  Tags:
  - 9.2.20230513
  - "9.2"
  - "9"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: e21f7b51dee45dbcea532cbbbae68da7428c7916
      GitFetch: refs/heads/Rocky-9.2.20230513-Minimal-aarch64
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: 275f589f6bcc73828387dc3f1d9d1fc45fef1b07
      GitFetch: refs/heads/Rocky-9.2.20230513-Minimal-s390x
  Directory: ""
  GitCommit: 7be807edccbbb7b64872f1a6b6c24cc2edabf3bd
  Tags:
  - 9.2.20230513-minimal
  - 9.2-minimal
  - 9-minimal
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: 6f4942bfa1d8785ef62f43a8c7daf827b1034796
      GitFetch: refs/heads/Rocky-8.8.20230518-Base-aarch64
  Directory: ""
  GitCommit: 1c46fd092fd28c6192435baa61e66a00e66f7029
  Tags:
  - 8.8.20230518
  - "8.8"
  - "8"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: d96540550efe61b047d17d11d4a7d9f4a9976537
      GitFetch: refs/heads/Rocky-8.8.20230518-Minimal-aarch64
  Directory: ""
  GitCommit: 62c9ffd4470199b37a57ac260d1368ad239d476c
  Tags:
  - 8.8.20230518-minimal
  - 8.8-minimal
  - 8-minimal
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: a44de1cb9192969dacd996beb22c152020908532
      GitFetch: refs/heads/Rocky-9.1.20230215-Base-aarch64
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: 0aee39d093db7f0732854729a0e46bc8092bf607
      GitFetch: refs/heads/Rocky-9.1.20230215-Base-ppc64le
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: 3bd8af8923fd7b0611f1599e347897a6cb9c156b
      GitFetch: refs/heads/Rocky-9.1.20230215-Base-s390x
  Directory: ""
  GitCommit: c554918c3fb7432f70802459ee942fead8121cae
  Tags:
  - 9.1.20230215
  - "9.1"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: 499b1eeb324a768228963568a9b3afdaf5da74dc
      GitFetch: refs/heads/Rocky-9.1.20230215-Minimal-aarch64
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: 4e11f6cf490d560b37bc6b9dffff204d2bc6e5b3
      GitFetch: refs/heads/Rocky-9.1.20230215-Minimal-ppc64le
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: db6eddbb6b6cd097f625a014dcd50a9f152720d2
      GitFetch: refs/heads/Rocky-9.1.20230215-Minimal-s390x
  Directory: ""
  GitCommit: 957dce1794c27b8fc1666f7e283db2ba7ef5b182
  Tags:
  - 9.1.20230215-minimal
  - 9.1-minimal
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: f509fe83af8a893dff234befbc76458f6343b665
      GitFetch: refs/heads/Rocky-8.7.20230215-Base-aarch64
  Directory: ""
  GitCommit: 65d3f79aa8b5d0a9ed1270470e585539f7d59cd1
  Tags:
  - 8.7.20230215
  - "8.7"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: 5e843c299faaa855b6e3810cbf3fa25474415954
      GitFetch: refs/heads/Rocky-8.7.20230215-Minimal-aarch64
  Directory: ""
  GitCommit: a923b0d8957fa92feafaa4f6b00f8df08db796ab
  Tags:
  - 8.7.20230215-minimal
  - 8.7-minimal
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: 3ad7127acab95854d2eba80b7017c8766106cb70
      GitFetch: refs/heads/Rocky-9.1.20221221-Base-aarch64
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: 9f0ff4adfd5a88f0299a077442137c8d6114dd74
      GitFetch: refs/heads/Rocky-9.1.20221221-Base-ppc64le
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: b0df1d4c5e02633923fe95878b290f06a0585aac
      GitFetch: refs/heads/Rocky-9.1.20221221-Base-s390x
  Directory: ""
  GitCommit: 0c5e7578276e2bd1196e340ea98fee112d305bac
  Tags:
  - 9.1.20221221
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: 885022e82bce48d803b78f2ef5bdb0195f44d44b
      GitFetch: refs/heads/Rocky-9.1.20221221-Minimal-aarch64
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: fbcb0a4d53eeb6dec6e7cdf520fdafa709d15ee5
      GitFetch: refs/heads/Rocky-9.1.20221221-Minimal-ppc64le
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: f55e4ef2dbf449c191845d7d3a7b00c9750fd0a2
      GitFetch: refs/heads/Rocky-9.1.20221221-Minimal-s390x
  Directory: ""
  GitCommit: 4925a4ada53dc186b27167d90dbe62c7d62942cc
  Tags:
  - 9.1.20221221-minimal
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: f67799fa9535a3eaff73b6f11b1ca6a734be7649
      GitFetch: refs/heads/Rocky-8.7.20221219-Base-aarch64
  Directory: ""
  GitCommit: 15e9cb0790bed8b6cba7b5cb2ecf3ebab6a0e6ae
  Tags:
  - 8.7.20221219
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: 62b435aa0c81ec8512b31187169126b9453425b0
      GitFetch: refs/heads/Rocky-8.7.20221219-Minimal-aarch64
  Directory: ""
  GitCommit: 263f85f3cc1dfaa1824aeecfe3aee681adafe33f
  Tags:
  - 8.7.20221219-minimal
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: 2610f225cce6316f2796b480178d550cd8629525
      GitFetch: refs/heads/Rocky-9.1.20221123-Base-aarch64
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: 82b28b01dbaff41e8702a1ac1f83937f35ba9355
      GitFetch: refs/heads/Rocky-9.1.20221123-Base-ppc64le
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: 0d7baaa2b72be3a5cadaca63e7dcee03c2771247
      GitFetch: refs/heads/Rocky-9.1.20221123-Base-s390x
  Directory: ""
  GitCommit: 257855c56aac1cb7417b20fd58e5e8f60b276e07
  Tags:
  - 9.1.20221123
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: 48f86388e5f8f47afb4187363c4a3c2a1419a6c2
      GitFetch: refs/heads/Rocky-9.1.20221123-Minimal-aarch64
    ppc64le:
      Architecture: ppc64le
      Directory: ""
      File: ""
      GitCommit: ffa8070ba243e007c599090442247abdcba4afce
      GitFetch: refs/heads/Rocky-9.1.20221123-Minimal-ppc64le
    s390x:
      Architecture: s390x
      Directory: ""
      File: ""
      GitCommit: f4efc0167cee000aa09b2dd7c7f2d7b99799ff21
      GitFetch: refs/heads/Rocky-9.1.20221123-Minimal-s390x
  Directory: ""
  GitCommit: eca5fa31f75936f9a069d8968be0da9f779adfce
  Tags:
  - 9.1.20221123-minimal
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: 78129b594f5318c80fd24b0b0d25dfb35125c9d6
      GitFetch: refs/heads/Rocky-9.0.20220720-Base-aarch64
  Directory: ""
  GitCommit: e3f3c1cbc89d705fad4cb99e5786a4dc7178116c
  Tags:
  - 9.0.20220720
  - "9.0"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: bbea3587002f91144f3195b8b0372f05257fd6f5
      GitFetch: refs/heads/Rocky-9.0.20220720-Minimal-aarch64
  Directory: ""
  GitCommit: ac4d852f696bb2cc96c55f4a54b1fb7d41f5df4f
  Tags:
  - 9.0.20220720-minimal
  - 9.0-minimal
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: 411d541689cc277f778ce5a0aa260d5a82dd83f3
      GitFetch: refs/heads/Rocky-8.6.20220707-Base-aarch64
  Directory: ""
  GitCommit: 09dbe262451ff0e93fe50df95f6811b234d3d509
  Tags:
  - 8.6.20227707
  - "8.6"
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: 5ba5163c86e3a4ef12601ab1ed7ad7580f9c302b
      GitFetch: refs/heads/Rocky-8.6.20220707-Minimal-aarch64
  Directory: ""
  GitCommit: ef6b5ec9cbad530e1ba673e44dcef9d4c5d5df6a
  Tags:
  - 8.6.20220707-minimal
  - 8.6-minimal
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: 395fd4b32a9d2df4851a800d2830af266beca001
      GitFetch: refs/heads/Rocky-9.0.20220712-Base-aarch64
  Directory: ""
  GitCommit: 4a7c10008e051c2c22eff5712ffb4cce7ed357b8
  Tags:
  - 9.0.20220712
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: f86c46c2a5e5ec7ca7c812bd60aa10f539522cf7
      GitFetch: refs/heads/Rocky-9.0.20220712-Minimal-aarch64
  Directory: ""
  GitCommit: 478daae7943db91ad41ef244a3767b90fb1d2521
  Tags:
  - 9.0.20220712-minimal
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: 411d541689cc277f778ce5a0aa260d5a82dd83f3
      GitFetch: refs/heads/Rocky-8.6.20220707-Base-aarch64
  Directory: ""
  GitCommit: 09dbe262451ff0e93fe50df95f6811b234d3d509
  Tags:
  - latest
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: a73d2de52b19977008c07227b7527c719b7db623
      GitFetch: refs/heads/Rocky-8.5.20220308-aarch64
  Directory: ""
  GitCommit: 82660c9c8d02077321bf6b12bd6aa512dbfce4fc
  Tags:
  - 8.5.20220308
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: df726710f2d759478bea1f06946eb168f4cff17a
      GitFetch: refs/heads/Rocky-8.5-aarch64
  Directory: ""
  GitCommit: eee13752a34b9195c97d0bce92c05a838484eee8
  Tags:
  - "8.5"
GitRepo: https://github.com/rocky-linux/sig-cloud-instance-images.git
KnownTags:
  "8": {}
  8-minimal: {}
  "8.5": {}
  8.5.20220308: {}
  "8.6": {}
  8.6-minimal: {}
  8.6.20220707-minimal: {}
  8.6.20227707: {}
  "8.7": {}
  8.7-minimal: {}
  8.7.20221219: {}
  8.7.20221219-minimal: {}
  8.7.20230215: {}
  8.7.20230215-minimal: {}
  "8.8": {}
  8.8-minimal: {}
  8.8.20230518: {}
  8.8.20230518-minimal: {}
  "9": {}
  9-minimal: {}
  "9.0": {}
  9.0-minimal: {}
  9.0.20220712: {}
  9.0.20220712-minimal: {}
  9.0.20220720: {}
  9.0.20220720-minimal: {}
  "9.1": {}
  9.1-minimal: {}
  9.1.20221123: {}
  9.1.20221123-minimal: {}
  9.1.20221221: {}
  9.1.20221221-minimal: {}
  9.1.20230215: {}
  9.1.20230215-minimal: {}
  "9.2": {}
  9.2-minimal: {}
  9.2.20230513: {}
  9.2.20230513-minimal: {}
  latest: {}
Name: rockylinux
