Blocks:
- Architectures:
  - amd64
  - arm64v8
  - s390x
  Directory: ""
  GitCommit: 5534796e428e5ac942d820bc96a36a5d0404a8a4
  Tags:
  - 9.2.20230513
  - "9.2"
  - "9"
- Architectures:
  - amd64
  - arm64v8
  - s390x
  Directory: ""
  GitCommit: 7be807edccbbb7b64872f1a6b6c24cc2edabf3bd
  Tags:
  - 9.2.20230513-minimal
  - 9.2-minimal
  - 9-minimal
- Architectures:
  - amd64
  - arm64v8
  Directory: ""
  GitCommit: 1c46fd092fd28c6192435baa61e66a00e66f7029
  Tags:
  - 8.8.20230518
  - "8.8"
  - "8"
- Architectures:
  - amd64
  - arm64v8
  Directory: ""
  GitCommit: 62c9ffd4470199b37a57ac260d1368ad239d476c
  Tags:
  - 8.8.20230518-minimal
  - 8.8-minimal
  - 8-minimal
GitRepo: https://github.com/rocky-linux/sig-cloud-instance-images.git
KnownTags:
  "8": {}
  8-minimal: {}
  "8.8": {}
  8.8-minimal: {}
  8.8.20230518: {}
  8.8.20230518-minimal: {}
  "9": {}
  9-minimal: {}
  "9.2": {}
  9.2-minimal: {}
  9.2.20230513: {}
  9.2.20230513-minimal: {}
Name: rockylinux
