Blocks:
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  Directory: 0.X
  GitCommit: 6728f1e11112016a3539eec50b8d20b27a31aa40
  Tags:
  - 1.15.3
  - "1.15"
  - latest
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  Directory: 0.X
  GitCommit: 36b73fb81154b668e9c1987fc7011322f33b926e
  Tags:
  - 1.14.7
  - "1.14"
- Architectures:
  - amd64
  - arm32v6
  - arm64v8
  - i386
  Directory: 0.X
  GitCommit: 4e3f7398868f9767d515e91a63b67294f5c97aa9
  Tags:
  - 1.13.8
  - "1.13"
GitRepo: https://github.com/hashicorp/docker-consul.git
KnownTags:
  "1.13": {}
  1.13.8: {}
  "1.14": {}
  1.14.7: {}
  "1.15": {}
  1.15.3: {}
  latest: {}
Name: consul
