Blocks:
- Architectures: null
  Directory: stable
  GitCommit: a03bbe3ae7bbb839c3c69afd4504ca336f7b9cb9
  Tags:
  - latest
  - "0.62"
GitRepo: git://github.com/vaygr/docker-sourcemage
KnownTags:
  "0.62": {}
  latest: {}
Name: sourcemage
