Blocks:
- Architectures: null
  Directory: 8.5/5.6
  GitCommit: ""
  Tags:
  - "8.5"
  - 8.5-php5.6
  - "5.6"
- Architectures: null
  Directory: 9.1/7.1
  GitCommit: ""
  Tags:
  - "9.1"
- Architectures: null
  Directory: "2019.0"
  GitCommit: ""
  Tags:
  - "2019.0"
- Architectures: null
  Directory: "2021.0"
  GitCommit: ""
  Tags:
  - "2021.0"
  - latest
- Architectures: null
  Directory: 2018.0/7.2
  GitCommit: ""
  Tags:
  - "2018.0"
- Architectures: null
  Directory: 8.5/5.5
  GitCommit: ""
  Tags:
  - "5.5"
  - 8.5-php5.5
- Architectures: null
  Directory: 7.0/5.4
  GitCommit: ""
  Tags:
  - "5.4"
  - 7.0-php5.4
- Architectures: null
  Directory: 9.0.1/7.0
  GitCommit: 851cbb2346939e98bb0a8a15cd9973fd950fd66b
  Tags:
  - 9.0.1
  - 9.0.1-php7
GitRepo: https://github.com/zendtech/php-zendserver-docker.git
KnownTags:
  "5.4": {}
  "5.5": {}
  "5.6": {}
  7.0-php5.4: {}
  "8.5": {}
  8.5-php5.5: {}
  8.5-php5.6: {}
  9.0.1: {}
  9.0.1-php7: {}
  "9.1": {}
  "2018.0": {}
  "2019.0": {}
  "2021.0": {}
  latest: {}
Name: php-zendserver
