Blocks:
- Architectures: null
  Directory: 8.5/5.6
  File: ""
  GitCommit: bcd65b82acb4f3b5b67f8c657c52f08bc52d8789
  Tags:
  - "8.5"
  - 8.5-php5.6
  - "5.6"
- Architectures: null
  Directory: 9.1/7.1
  File: ""
  GitCommit: bcd65b82acb4f3b5b67f8c657c52f08bc52d8789
  Tags:
  - "9.1"
- Architectures: null
  Directory: "2019.0"
  File: ""
  GitCommit: bcd65b82acb4f3b5b67f8c657c52f08bc52d8789
  Tags:
  - "2019.0"
- Architectures: null
  Directory: "2021.0"
  File: ""
  GitCommit: bcd65b82acb4f3b5b67f8c657c52f08bc52d8789
  Tags:
  - "2021.0"
  - latest
- Architectures: null
  Directory: 2018.0/7.2
  File: ""
  GitCommit: 7afd3fc8a38fb255a511962077343d1b9078ea13
  Tags:
  - "2018.0"
- Architectures: null
  Directory: 8.5/5.5
  File: ""
  GitCommit: 86e6c5ccb9faaccc3944ef346ebbd9c181835ba7
  Tags:
  - "5.5"
  - 8.5-php5.5
- Architectures: null
  Directory: 7.0/5.4
  File: ""
  GitCommit: 86e6c5ccb9faaccc3944ef346ebbd9c181835ba7
  Tags:
  - "5.4"
  - 7.0-php5.4
- Architectures: null
  Directory: 9.0.1/7.0
  File: ""
  GitCommit: 851cbb2346939e98bb0a8a15cd9973fd950fd66b
  Tags:
  - 9.0.1
  - 9.0.1-php7
GitRepo: https://github.com/zendtech/php-zendserver-docker.git
KnownTags:
  "5.4": {}
  "5.5": {}
  "5.6": {}
  7.0-php5.4: {}
  "8.5": {}
  8.5-php5.5: {}
  8.5-php5.6: {}
  9.0.1: {}
  9.0.1-php7: {}
  "9.1": {}
  "2018.0": {}
  "2019.0": {}
  "2021.0": {}
  latest: {}
Name: php-zendserver
