Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: oci
  GitCommit: ""
  Tags:
  - "20.04"
  - focal-20230605
  - focal
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: oci
  GitCommit: ""
  Tags:
  - "22.04"
  - jammy-20230605
  - jammy
  - latest
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: oci
  GitCommit: ""
  Tags:
  - "22.10"
  - kinetic-20230605
  - kinetic
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: oci
  GitCommit: ""
  Tags:
  - "23.04"
  - lunar-20230615
  - lunar
  - rolling
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - ppc64le
  - s390x
  Directory: oci
  GitCommit: ""
  Tags:
  - "23.10"
  - mantic-20230607
  - mantic
  - devel
GitRepo: https://git.launchpad.net/cloud-images/+oci/ubuntu-base
KnownTags:
  "20.04": {}
  "22.04": {}
  "22.10": {}
  "23.04": {}
  "23.10": {}
  devel: {}
  focal: {}
  focal-20230605: {}
  jammy: {}
  jammy-20230605: {}
  kinetic: {}
  kinetic-20230605: {}
  latest: {}
  lunar: {}
  lunar-20230615: {}
  mantic: {}
  mantic-20230607: {}
  rolling: {}
Name: ubuntu
