Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: server/24.10.1.2812
  File: Dockerfile.ubuntu
  GitCommit: e991ffaf2d96bab935a248d5701c58f637d3040e
  Tags:
  - latest
  - focal
  - "24"
  - 24-focal
  - "24.10"
  - 24.10-focal
  - 24.10.1
  - 24.10.1-focal
  - 24.10.1.2812
  - 24.10.1.2812-focal
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: server/24.9.2.42
  File: Dockerfile.ubuntu
  GitCommit: e991ffaf2d96bab935a248d5701c58f637d3040e
  Tags:
  - "24.9"
  - 24.9-focal
  - 24.9.2
  - 24.9.2-focal
  - 24.9.2.42
  - 24.9.2.42-focal
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: server/24.8.6.70
  File: Dockerfile.ubuntu
  GitCommit: e991ffaf2d96bab935a248d5701c58f637d3040e
  Tags:
  - lts
  - focal-lts
  - "24.8"
  - 24.8-focal
  - 24.8.6
  - 24.8.6-focal
  - 24.8.6.70
  - 24.8.6.70-focal
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: server/24.3.13.40
  File: Dockerfile.ubuntu
  GitCommit: e991ffaf2d96bab935a248d5701c58f637d3040e
  Tags:
  - "24.3"
  - 24.3-focal
  - 24.3.13
  - 24.3.13-focal
  - 24.3.13.40
  - 24.3.13.40-focal
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: server/24.10.1.2812
  File: Dockerfile.ubuntu
  GitCommit: 8f3278549dd6ac2832287c18c6a35a5f90eb3394
  Tags:
  - jammy
  - 24-jammy
  - 24.10-jammy
  - 24.10.1-jammy
  - 24.10.1.2812-jammy
GitRepo: https://github.com/ClickHouse/docker-library.git
KnownTags:
  "24": {}
  24-focal: {}
  24-jammy: {}
  "24.3": {}
  24.3-focal: {}
  24.3.13: {}
  24.3.13-focal: {}
  24.3.13.40: {}
  24.3.13.40-focal: {}
  "24.8": {}
  24.8-focal: {}
  24.8.6: {}
  24.8.6-focal: {}
  24.8.6.70: {}
  24.8.6.70-focal: {}
  "24.9": {}
  24.9-focal: {}
  24.9.2: {}
  24.9.2-focal: {}
  24.9.2.42: {}
  24.9.2.42-focal: {}
  "24.10": {}
  24.10-focal: {}
  24.10-jammy: {}
  24.10.1: {}
  24.10.1-focal: {}
  24.10.1-jammy: {}
  24.10.1.2812: {}
  24.10.1.2812-focal: {}
  24.10.1.2812-jammy: {}
  focal: {}
  focal-lts: {}
  jammy: {}
  latest: {}
  lts: {}
Name: clickhouse
