Blocks:
- Architectures:
    amd64:
      Architecture: amd64
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
    arm64v8:
      Architecture: arm64v8
      Directory: ""
      File: ""
      GitCommit: ""
      GitFetch: ""
  Directory: server/24.10.1.2812
  File: Dockerfile.ubuntu
  GitCommit: 8f3278549dd6ac2832287c18c6a35a5f90eb3394
  Tags:
  - latest
  - jammy
  - "24"
  - 24-jammy
  - "24.10"
  - 24.10-jammy
  - 24.10.1
  - 24.10.1-jammy
  - 24.10.1.2812
  - 24.10.1.2812-jammy
GitRepo: https://github.com/ClickHouse/docker-library.git
KnownTags:
  "24": {}
  24-jammy: {}
  "24.10": {}
  24.10-jammy: {}
  24.10.1: {}
  24.10.1-jammy: {}
  24.10.1.2812: {}
  24.10.1.2812-jammy: {}
  jammy: {}
  latest: {}
Name: clickhouse
