Blocks:
- Architectures: null
  Directory: "9.1"
  GitCommit: 09a7761e841eee7fab758526b14d46ae56134952
  Tags:
  - 9.1.2
  - "9.1"
  - "9"
  - latest
- Architectures: null
  Directory: 9.1/onbuild
  GitCommit: f58f91fe5dc31bfe77af277dae7002a5542326a9
  Tags:
  - 9.1.2-onbuild
  - 9.1-onbuild
  - 9-onbuild
  - onbuild
- Architectures: null
  Directory: "9.0"
  GitCommit: 4b3fad46dbe56285629162e059f4f0e89174b0f9
  Tags:
  - 9.0.0
  - "9.0"
- Architectures: null
  Directory: 9.0/onbuild
  GitCommit: ec474d97d968afdf78f4e489b58c68a2fbc46ee2
  Tags:
  - 9.0.0-onbuild
  - 9.0-onbuild
- Architectures: null
  Directory: "9.1"
  GitCommit: c2df5c220266ab9e8338d88c1ee5d8f5fdbd6cce
  Tags:
  - 9.1.1
- Architectures: null
  Directory: 9.1/onbuild
  GitCommit: f58f91fe5dc31bfe77af277dae7002a5542326a9
  Tags:
  - 9.1.1-onbuild
- Architectures: null
  Directory: "9.1"
  GitCommit: f58f91fe5dc31bfe77af277dae7002a5542326a9
  Tags:
  - 9.1.0
- Architectures: null
  Directory: 9.1/onbuild
  GitCommit: f58f91fe5dc31bfe77af277dae7002a5542326a9
  Tags:
  - 9.1.0-onbuild
- Architectures: null
  Directory: "8.22"
  GitCommit: b7d55c572e0b23c5c537432211823a8677727e1c
  Tags:
  - 8.22.0
  - "8.22"
  - "8"
- Architectures: null
  Directory: 8.22/onbuild
  GitCommit: b7d55c572e0b23c5c537432211823a8677727e1c
  Tags:
  - 8.22.0-onbuild
  - 8.22-onbuild
  - 8-onbuild
- Architectures: null
  Directory: "9.0"
  GitCommit: ec474d97d968afdf78f4e489b58c68a2fbc46ee2
  Tags:
  - 9.0.0rc1
- Architectures: null
  Directory: 9.0/onbuild
  GitCommit: ec474d97d968afdf78f4e489b58c68a2fbc46ee2
  Tags:
  - 9.0.0rc1-onbuild
- Architectures: null
  Directory: "8.21"
  GitCommit: dbfbdb991427d3e2a0d8f1d2698276846176ec40
  Tags:
  - 8.21.0
  - "8.21"
- Architectures: null
  Directory: 8.21/onbuild
  GitCommit: dbfbdb991427d3e2a0d8f1d2698276846176ec40
  Tags:
  - 8.21.0-onbuild
  - 8.21-onbuild
- Architectures: null
  Directory: "8.20"
  GitCommit: 5b3a524591bddce5393a574175439171cdcde5e8
  Tags:
  - 8.20.0
  - "8.20"
- Architectures: null
  Directory: 8.20/onbuild
  GitCommit: 5b3a524591bddce5393a574175439171cdcde5e8
  Tags:
  - 8.20.0-onbuild
  - 8.20-onbuild
- Architectures: null
  Directory: "8.19"
  GitCommit: f7edbbec370da95fe2a2d96e708e732fa74e4900
  Tags:
  - 8.19.0
  - "8.19"
- Architectures: null
  Directory: 8.19/onbuild
  GitCommit: f7edbbec370da95fe2a2d96e708e732fa74e4900
  Tags:
  - 8.19.0-onbuild
  - 8.19-onbuild
- Architectures: null
  Directory: "8.18"
  GitCommit: 7451b44273e5847a0ff261be45603693a21d162e
  Tags:
  - 8.18.0
  - "8.18"
- Architectures: null
  Directory: 8.18/onbuild
  GitCommit: 7451b44273e5847a0ff261be45603693a21d162e
  Tags:
  - 8.18.0-onbuild
  - 8.18-onbuild
- Architectures: null
  Directory: "8.17"
  GitCommit: 35aa3956a16cf82f7419481558132ff8bc8989b1
  Tags:
  - 8.17.0
  - "8.17"
- Architectures: null
  Directory: 8.17/onbuild
  GitCommit: 35aa3956a16cf82f7419481558132ff8bc8989b1
  Tags:
  - 8.17.0-onbuild
  - 8.17-onbuild
- Architectures: null
  Directory: "8.16"
  GitCommit: 3b060a7ceaee5f5b0bdb6cf88e1e0559c62be709
  Tags:
  - 8.16.1
  - "8.16"
- Architectures: null
  Directory: 8.16/onbuild
  GitCommit: 14a4752274f9627ab59cb02ad54801b04c8b3b1d
  Tags:
  - 8.16.1-onbuild
  - 8.16-onbuild
- Architectures: null
  Directory: "8.15"
  GitCommit: a40471912184a4a013d00e13ef1bdca581860bd3
  Tags:
  - 8.15.0
  - "8.15"
- Architectures: null
  Directory: 8.15/onbuild
  GitCommit: a40471912184a4a013d00e13ef1bdca581860bd3
  Tags:
  - 8.15.0-onbuild
  - 8.15-onbuild
- Architectures: null
  Directory: "8.16"
  GitCommit: 14a4752274f9627ab59cb02ad54801b04c8b3b1d
  Tags:
  - 8.16.0
- Architectures: null
  Directory: 8.16/onbuild
  GitCommit: 14a4752274f9627ab59cb02ad54801b04c8b3b1d
  Tags:
  - 8.16.0-onbuild
- Architectures: null
  Directory: "8.14"
  GitCommit: c73e82b78c827de107e055bf0b2a07f395a0650c
  Tags:
  - 8.14.1
  - "8.14"
- Architectures: null
  Directory: 8.14/onbuild
  GitCommit: 02492c01dd4a360b04466ce5a98511d748965c07
  Tags:
  - 8.14.1-onbuild
  - 8.14-onbuild
- Architectures: null
  Directory: "8.13"
  GitCommit: f9835042aadb805e755a826ca7748334b11ef09b
  Tags:
  - 8.13.0
  - "8.13"
- Architectures: null
  Directory: 8.13/onbuild
  GitCommit: f9835042aadb805e755a826ca7748334b11ef09b
  Tags:
  - 8.13.0-onbuild
  - 8.13-onbuild
- Architectures: null
  Directory: "8.14"
  GitCommit: 02492c01dd4a360b04466ce5a98511d748965c07
  Tags:
  - 8.14.0
- Architectures: null
  Directory: 8.14/onbuild
  GitCommit: 02492c01dd4a360b04466ce5a98511d748965c07
  Tags:
  - 8.14.0-onbuild
- Architectures: null
  Directory: "8.12"
  GitCommit: c47576b88672708eeb2a6e2b66cea9dcbfe8c945
  Tags:
  - 8.12.0
  - "8.12"
- Architectures: null
  Directory: 8.12/onbuild
  GitCommit: c47576b88672708eeb2a6e2b66cea9dcbfe8c945
  Tags:
  - 8.12.0-onbuild
  - 8.12-onbuild
- Architectures: null
  Directory: "8.11"
  GitCommit: 60d4b0e5ad293ceabfd0d00ec4bc08c5d353ca2c
  Tags:
  - 8.11.0
  - "8.11"
- Architectures: null
  Directory: 8.11/onbuild
  GitCommit: 60d4b0e5ad293ceabfd0d00ec4bc08c5d353ca2c
  Tags:
  - 8.11.0-onbuild
  - 8.11-onbuild
- Architectures: null
  Directory: "8.10"
  GitCommit: 71597dc5f0532721a3bd24405021e273df471866
  Tags:
  - 8.10.0
  - "8.10"
- Architectures: null
  Directory: 8.10/onbuild
  GitCommit: 8e4ec0e019a9cfc653f09b16531cef507e015af1
  Tags:
  - 8.10.0-onbuild
  - 8.10-onbuild
- Architectures: null
  Directory: "8.9"
  GitCommit: 06d750bddc0e6499446e73ca22fbd4c915b29cbd
  Tags:
  - 8.9.0
  - "8.9"
- Architectures: null
  Directory: 8.9/onbuild
  GitCommit: 06d750bddc0e6499446e73ca22fbd4c915b29cbd
  Tags:
  - 8.9.0-onbuild
  - 8.9-onbuild
- Architectures: null
  Directory: "8.8"
  GitCommit: 90e5f20bf418a42986c9716d07a4de980a4dfc07
  Tags:
  - 8.8.0
  - "8.8"
- Architectures: null
  Directory: 8.8/onbuild
  GitCommit: 90e5f20bf418a42986c9716d07a4de980a4dfc07
  Tags:
  - 8.8.0-onbuild
  - 8.8-onbuild
- Architectures: null
  Directory: "8.7"
  GitCommit: 2bef8f6386c891f9b8ce1d6940f0aff81c25d475
  Tags:
  - 8.7.0
  - "8.7"
- Architectures: null
  Directory: 8.7/onbuild
  GitCommit: 22e75e5254b5707b77a747cd4e90bc4327f2ce9b
  Tags:
  - 8.7.0-onbuild
  - 8.7-onbuild
- Architectures: null
  Directory: "8.6"
  GitCommit: 2bef8f6386c891f9b8ce1d6940f0aff81c25d475
  Tags:
  - 8.6.0
  - "8.6"
- Architectures: null
  Directory: 8.6/onbuild
  GitCommit: 09d2b56ded2f669f40d5295bfe36529bbafb914d
  Tags:
  - 8.6.0-onbuild
  - 8.6-onbuild
- Architectures: null
  Directory: "8.5"
  GitCommit: d69a0096ee2f885047f95bdd2e2edfc761674580
  Tags:
  - 8.5.1
  - "8.5"
- Architectures: null
  Directory: 8.5/onbuild
  GitCommit: ce5121a71f55c2fb0659f552e361b1174c85bccf
  Tags:
  - 8.5.1-onbuild
  - 8.5-onbuild
GitRepo: https://github.com/getsentry/docker-sentry.git
KnownTags:
  "8": {}
  8-onbuild: {}
  "8.5": {}
  8.5-onbuild: {}
  8.5.1: {}
  8.5.1-onbuild: {}
  "8.6": {}
  8.6-onbuild: {}
  8.6.0: {}
  8.6.0-onbuild: {}
  "8.7": {}
  8.7-onbuild: {}
  8.7.0: {}
  8.7.0-onbuild: {}
  "8.8": {}
  8.8-onbuild: {}
  8.8.0: {}
  8.8.0-onbuild: {}
  "8.9": {}
  8.9-onbuild: {}
  8.9.0: {}
  8.9.0-onbuild: {}
  "8.10": {}
  8.10-onbuild: {}
  8.10.0: {}
  8.10.0-onbuild: {}
  "8.11": {}
  8.11-onbuild: {}
  8.11.0: {}
  8.11.0-onbuild: {}
  "8.12": {}
  8.12-onbuild: {}
  8.12.0: {}
  8.12.0-onbuild: {}
  "8.13": {}
  8.13-onbuild: {}
  8.13.0: {}
  8.13.0-onbuild: {}
  "8.14": {}
  8.14-onbuild: {}
  8.14.0: {}
  8.14.0-onbuild: {}
  8.14.1: {}
  8.14.1-onbuild: {}
  "8.15": {}
  8.15-onbuild: {}
  8.15.0: {}
  8.15.0-onbuild: {}
  "8.16": {}
  8.16-onbuild: {}
  8.16.0: {}
  8.16.0-onbuild: {}
  8.16.1: {}
  8.16.1-onbuild: {}
  "8.17": {}
  8.17-onbuild: {}
  8.17.0: {}
  8.17.0-onbuild: {}
  "8.18": {}
  8.18-onbuild: {}
  8.18.0: {}
  8.18.0-onbuild: {}
  "8.19": {}
  8.19-onbuild: {}
  8.19.0: {}
  8.19.0-onbuild: {}
  "8.20": {}
  8.20-onbuild: {}
  8.20.0: {}
  8.20.0-onbuild: {}
  "8.21": {}
  8.21-onbuild: {}
  8.21.0: {}
  8.21.0-onbuild: {}
  "8.22": {}
  8.22-onbuild: {}
  8.22.0: {}
  8.22.0-onbuild: {}
  "9": {}
  9-onbuild: {}
  "9.0": {}
  9.0-onbuild: {}
  9.0.0: {}
  9.0.0-onbuild: {}
  9.0.0rc1: {}
  9.0.0rc1-onbuild: {}
  "9.1": {}
  9.1-onbuild: {}
  9.1.0: {}
  9.1.0-onbuild: {}
  9.1.1: {}
  9.1.1-onbuild: {}
  9.1.2: {}
  9.1.2-onbuild: {}
  latest: {}
  onbuild: {}
Name: sentry
