Blocks:
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: da4b8f273a0a81078185076683ed92a382814ef3
  Tags:
  - 5.2.1-apache
  - 5.2-apache
  - 5-apache
  - apache
  - 5.2.1
  - "5.2"
  - "5"
  - latest
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: da4b8f273a0a81078185076683ed92a382814ef3
  Tags:
  - 5.2.1-fpm
  - 5.2-fpm
  - 5-fpm
  - fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 8674356a6d0f67eb89d0200647832fc3853781fd
  Tags:
  - 5.2.1-fpm-alpine
  - 5.2-fpm-alpine
  - 5-fpm-alpine
  - fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 71d54acc9309c04ed53a148ca1979b6cdc10c5b9
  Tags:
  - 5.2.0-apache
  - 5.2.0
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 71d54acc9309c04ed53a148ca1979b6cdc10c5b9
  Tags:
  - 5.2.0-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 71d54acc9309c04ed53a148ca1979b6cdc10c5b9
  Tags:
  - 5.2.0-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 2b79d7100216ec96d18e0b89508a48fa89c11dd8
  Tags:
  - 5.1.3-apache
  - 5.1-apache
  - 5.1.3
  - "5.1"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 2b79d7100216ec96d18e0b89508a48fa89c11dd8
  Tags:
  - 5.1.3-fpm
  - 5.1-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 2b79d7100216ec96d18e0b89508a48fa89c11dd8
  Tags:
  - 5.1.3-fpm-alpine
  - 5.1-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 935605b8d0a4e8632c1b63fbba4967b22c1a5a15
  Tags:
  - 5.1.1-apache
  - 5.1.1
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 935605b8d0a4e8632c1b63fbba4967b22c1a5a15
  Tags:
  - 5.1.1-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 935605b8d0a4e8632c1b63fbba4967b22c1a5a15
  Tags:
  - 5.1.1-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: 3d8c2ba403fa091a19c6f16762d50663e57f8969
  Tags:
  - 5.1.0-apache
  - 5.1.0
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: 3d8c2ba403fa091a19c6f16762d50663e57f8969
  Tags:
  - 5.1.0-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: 3d8c2ba403fa091a19c6f16762d50663e57f8969
  Tags:
  - 5.1.0-fpm-alpine
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: d383a98040551ecb701b71972f1e46145a868ccb
  Tags:
  - 5.0.4-apache
  - 5.0-apache
  - 5.0.4
  - "5.0"
- Architectures:
  - amd64
  - arm32v5
  - arm32v7
  - arm64v8
  - i386
  - mips64le
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: d383a98040551ecb701b71972f1e46145a868ccb
  Tags:
  - 5.0.4-fpm
  - 5.0-fpm
- Architectures:
  - amd64
  - arm32v6
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: d383a98040551ecb701b71972f1e46145a868ccb
  Tags:
  - 5.0.4-fpm-alpine
  - 5.0-fpm-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: apache
  GitCommit: f464cf5a67f8eae125d7f098892c03dcb5b9858b
  Tags:
  - 5.0.2-apache
  - 5.0.2
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm
  GitCommit: f464cf5a67f8eae125d7f098892c03dcb5b9858b
  Tags:
  - 5.0.2-fpm
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  - i386
  - ppc64le
  - s390x
  Directory: fpm-alpine
  GitCommit: f464cf5a67f8eae125d7f098892c03dcb5b9858b
  Tags:
  - 5.0.2-fpm-alpine
GitRepo: https://github.com/phpmyadmin/docker.git
KnownTags:
  "5": {}
  5-apache: {}
  5-fpm: {}
  5-fpm-alpine: {}
  "5.0": {}
  5.0-apache: {}
  5.0-fpm: {}
  5.0-fpm-alpine: {}
  5.0.2: {}
  5.0.2-apache: {}
  5.0.2-fpm: {}
  5.0.2-fpm-alpine: {}
  5.0.4: {}
  5.0.4-apache: {}
  5.0.4-fpm: {}
  5.0.4-fpm-alpine: {}
  "5.1": {}
  5.1-apache: {}
  5.1-fpm: {}
  5.1-fpm-alpine: {}
  5.1.0: {}
  5.1.0-apache: {}
  5.1.0-fpm: {}
  5.1.0-fpm-alpine: {}
  5.1.1: {}
  5.1.1-apache: {}
  5.1.1-fpm: {}
  5.1.1-fpm-alpine: {}
  5.1.3: {}
  5.1.3-apache: {}
  5.1.3-fpm: {}
  5.1.3-fpm-alpine: {}
  "5.2": {}
  5.2-apache: {}
  5.2-fpm: {}
  5.2-fpm-alpine: {}
  5.2.0: {}
  5.2.0-apache: {}
  5.2.0-fpm: {}
  5.2.0-fpm-alpine: {}
  5.2.1: {}
  5.2.1-apache: {}
  5.2.1-fpm: {}
  5.2.1-fpm-alpine: {}
  apache: {}
  fpm: {}
  fpm-alpine: {}
  latest: {}
Name: phpmyadmin
