Blocks:
- Architectures: null
  Directory: notary-server
  File: ""
  GitCommit: 77b9b7833f8dd6be07104b214193788795a320ff
  Tags:
  - server-0.7.0
  - server
- Architectures: null
  Directory: notary-signer
  File: ""
  GitCommit: 77b9b7833f8dd6be07104b214193788795a320ff
  Tags:
  - signer-0.7.0
  - signer
- Architectures: null
  Directory: notary-server
  File: ""
  GitCommit: fe7543aa8fc466423578b726570192028bbb818c
  Tags:
  - server-0.6.1-2
- Architectures: null
  Directory: notary-signer
  File: ""
  GitCommit: fe7543aa8fc466423578b726570192028bbb818c
  Tags:
  - signer-0.6.1-2
- Architectures: null
  Directory: notary-server
  File: ""
  GitCommit: ee9401173fbe4c672f3e3e71b0881d21f2112eca
  Tags:
  - server-0.6.1-1
- Architectures: null
  Directory: notary-signer
  File: ""
  GitCommit: ee9401173fbe4c672f3e3e71b0881d21f2112eca
  Tags:
  - signer-0.6.1-1
- Architectures: null
  Directory: notary-server
  File: ""
  GitCommit: 6db20782a52c71a48e33a9f075ba632054c0112d
  Tags:
  - server-0.6.1
- Architectures: null
  Directory: notary-signer
  File: ""
  GitCommit: 6db20782a52c71a48e33a9f075ba632054c0112d
  Tags:
  - signer-0.6.1
- Architectures: null
  Directory: notary-server
  File: ""
  GitCommit: ff7ae14c71fa0f87f9e6bd8de81a78c20db66664
  Tags:
  - server-0.5.0
- Architectures: null
  Directory: notary-signer
  File: ""
  GitCommit: ff7ae14c71fa0f87f9e6bd8de81a78c20db66664
  Tags:
  - signer-0.5.0
GitRepo: https://github.com/docker/notary-official-images.git
KnownTags:
  server: {}
  server-0.5.0: {}
  server-0.6.1: {}
  server-0.6.1-1: {}
  server-0.6.1-2: {}
  server-0.7.0: {}
  signer: {}
  signer-0.5.0: {}
  signer-0.6.1: {}
  signer-0.6.1-1: {}
  signer-0.6.1-2: {}
  signer-0.7.0: {}
Name: notary
