Blocks:
- Architectures: null
  Directory: notary-server
  GitCommit: ""
  Tags:
  - server-0.7.0
  - server
- Architectures: null
  Directory: notary-signer
  GitCommit: ""
  Tags:
  - signer-0.7.0
  - signer
GitRepo: https://github.com/docker/notary-official-images.git
KnownTags:
  server: {}
  server-0.7.0: {}
  signer: {}
  signer-0.7.0: {}
Name: notary
