name: promote

on:
  # schedule:
  #   - cron: '0 8 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-promote
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Prepare git
      env:
        GITHUB_USER: 1gtm
        GITHUB_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
      run: |
        set -x
        git config --global user.name "1gtm"
        git config --global user.email "1gtm@appscode.com"
        git config --global \
          url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf \
          "https://github.com"
        # git remote set-url origin https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Log in to the GitHub Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Install crane
      run: |
        # VERSION=$(curl -s "https://api.github.com/repos/google/go-containerregistry/releases/latest" | jq -r '.tag_name')
        # OS=Linux
        # ARCH=x86_64
        # curl -sL "https://github.com/google/go-containerregistry/releases/download/${VERSION}/go-containerregistry_${OS}_${ARCH}.tar.gz" > go-containerregistry.tar.gz
        # tar -zxvf go-containerregistry.tar.gz -C /usr/local/bin/ crane
        cd ..
        git clone https://github.com/gomodules/go-containerregistry.git
        cd go-containerregistry
        git checkout mutate-manifest
        GOBIN=/usr/local/bin go install -v ./...

    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1

    - name: Promote
      run: |
        go run cmd/promote/main.go

    - name: Update repo
      run: |
        git add --all
        if [[ $(git status --porcelain) ]]; then
          git commit -s -a -m "promoted images $(date -u)"
          git fetch origin
          git pull --rebase origin master
          git push origin HEAD
        fi
