name: refresh-docker-library

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-refresh-docker-library
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    # https://stackoverflow.com/a/58393457
    - name: Prepare git
      run: |
        set -x
        git config --global user.name '1gtm'
        git config --global user.email '1gtm@appscode.com'
        git config --global \
          url."https://x-access-token:${GITHUB_TOKEN}@github.com".insteadOf \
          "https://github.com"
        # git remote set-url origin https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

    - name: Refresh
      run: |
        # go run cmd/refresh-docker-library/*.go
        date --rfc-3339=date > ./library/report.txt

    - name: Update repo
      run: |
        git add --all
        git commit -s -a -m "update libary $(date --rfc-3339=date)"
        git push origin HEAD
