name: refresh-library

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: write
      workflows: write
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

    - name: Set up Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
      with:
        go-version: '1.25'

    - name: Prepare git
      run: |
        set -x
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Refresh Library
      run: |
        go run cmd/refresh-library/*.go
        # https://stackoverflow.com/a/23930212
        cat > ./library/README.md <<- EOM
        # Docker Library
        Last Updated: $(date --rfc-3339=date)
        EOM

    - name: Generate Workflows
      run: |
        go run cmd/generate-workflows/*.go

    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1

    - name: Update repo
      run: |
        git add --all
        if [[ $(git status --porcelain) ]]; then
          git commit -s -a -m "update libary $(date --rfc-3339=date)"
          git fetch origin
          git pull --rebase origin master
          git push origin HEAD
        fi
