Blocks:
- Architectures:
  - amd64
  - arm64v8
  Directory: "8.0"
  GitCommit: 1bfa4724fe112b4246672ed2b3c42142f17d5636
  Tags:
  - 8.0.33
  - "8.0"
  - "8"
  - latest
  - 8.0.33-oracle
  - 8.0-oracle
  - 8-oracle
  - oracle
- Architectures:
  - amd64
  Directory: "8.0"
  GitCommit: 611aa464a96f69e5d4d4172b14ca829ded162b42
  Tags:
  - 8.0.33-debian
  - 8.0-debian
  - 8-debian
  - debian
- Architectures:
  - amd64
  Directory: "5.7"
  GitCommit: e4bdff20153e6a05364a8fe80356dcfd502445bd
  Tags:
  - 5.7.42
  - "5.7"
  - "5"
  - 5.7.42-oracle
  - 5.7-oracle
  - 5-oracle
- Architectures:
  - amd64
  Directory: "5.7"
  GitCommit: 611aa464a96f69e5d4d4172b14ca829ded162b42
  Tags:
  - 5.7.42-debian
  - 5.7-debian
  - 5-debian
GitRepo: https://github.com/docker-library/mysql.git
KnownTags:
  "5": {}
  5-debian: {}
  5-oracle: {}
  "5.7": {}
  5.7-debian: {}
  5.7-oracle: {}
  5.7.42: {}
  5.7.42-debian: {}
  5.7.42-oracle: {}
  "8": {}
  8-debian: {}
  8-oracle: {}
  "8.0": {}
  8.0-debian: {}
  8.0-oracle: {}
  8.0.33: {}
  8.0.33-debian: {}
  8.0.33-oracle: {}
  debian: {}
  latest: {}
  oracle: {}
Name: mysql
