Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: telegraf/1.25
  GitCommit: ""
  Tags:
  - "1.25"
  - 1.25.3
- Architectures: null
  Directory: telegraf/1.25/alpine
  GitCommit: ""
  Tags:
  - 1.25-alpine
  - 1.25.3-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: telegraf/1.26
  GitCommit: ""
  Tags:
  - "1.26"
  - 1.26.3
- Architectures:
  - amd64
  - arm64v8
  Directory: telegraf/1.26/alpine
  GitCommit: ""
  Tags:
  - 1.26-alpine
  - 1.26.3-alpine
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: telegraf/1.27
  GitCommit: ""
  Tags:
  - "1.27"
  - 1.27.0
  - latest
- Architectures:
  - amd64
  - arm64v8
  Directory: telegraf/1.27/alpine
  GitCommit: ""
  Tags:
  - 1.27-alpine
  - 1.27.0-alpine
  - alpine
GitRepo: https://github.com/influxdata/influxdata-docker.git
KnownTags:
  "1.25": {}
  1.25-alpine: {}
  1.25.3: {}
  1.25.3-alpine: {}
  "1.26": {}
  1.26-alpine: {}
  1.26.3: {}
  1.26.3-alpine: {}
  "1.27": {}
  1.27-alpine: {}
  1.27.0: {}
  1.27.0-alpine: {}
  alpine: {}
  latest: {}
Name: telegraf
