Blocks:
- Architectures:
  - amd64
  - arm32v7
  - arm64v8
  Directory: influxdb/1.8
  GitCommit: ""
  Tags:
  - "1.8"
  - 1.8.10
- Architectures: null
  Directory: influxdb/1.8/alpine
  GitCommit: ""
  Tags:
  - 1.8-alpine
  - 1.8.10-alpine
- Architectures: null
  Directory: influxdb/1.8/data
  GitCommit: ""
  Tags:
  - 1.8-data
  - 1.8.10-data
  - data
- Architectures: null
  Directory: influxdb/1.8/data/alpine
  GitCommit: ""
  Tags:
  - 1.8-data-alpine
  - 1.8.10-data-alpine
  - data-alpine
- Architectures: null
  Directory: influxdb/1.8/meta
  GitCommit: ""
  Tags:
  - 1.8-meta
  - 1.8.10-meta
  - meta
- Architectures: null
  Directory: influxdb/1.8/meta/alpine
  GitCommit: ""
  Tags:
  - 1.8-meta-alpine
  - 1.8.10-meta-alpine
  - meta-alpine
- Architectures: null
  Directory: influxdb/1.9/data
  GitCommit: ""
  Tags:
  - 1.9-data
  - 1.9.11-data
- Architectures: null
  Directory: influxdb/1.9/data/alpine
  GitCommit: ""
  Tags:
  - 1.9-data-alpine
  - 1.9.11-data-alpine
- Architectures: null
  Directory: influxdb/1.9/meta
  GitCommit: ""
  Tags:
  - 1.9-meta
  - 1.9.11-meta
- Architectures: null
  Directory: influxdb/1.9/meta/alpine
  GitCommit: ""
  Tags:
  - 1.9-meta-alpine
  - 1.9.11-meta-alpine
- Architectures: null
  Directory: influxdb/1.10/data
  GitCommit: ""
  Tags:
  - 1.10-data
  - 1.10.3-data
- Architectures: null
  Directory: influxdb/1.10/data/alpine
  GitCommit: ""
  Tags:
  - 1.10-data-alpine
  - 1.10.3-data-alpine
- Architectures: null
  Directory: influxdb/1.10/meta
  GitCommit: ""
  Tags:
  - 1.10-meta
  - 1.10.3-meta
- Architectures: null
  Directory: influxdb/1.10/meta/alpine
  GitCommit: ""
  Tags:
  - 1.10-meta-alpine
  - 1.10.3-meta-alpine
- Architectures:
  - amd64
  - arm64v8
  Directory: influxdb/2.7
  GitCommit: ""
  Tags:
  - "2.7"
  - 2.7.1
  - latest
- Architectures:
  - amd64
  - arm64v8
  Directory: influxdb/2.7/alpine
  GitCommit: ""
  Tags:
  - 2.7-alpine
  - 2.7.1-alpine
  - alpine
GitRepo: https://github.com/influxdata/influxdata-docker
KnownTags:
  "1.8": {}
  1.8-alpine: {}
  1.8-data: {}
  1.8-data-alpine: {}
  1.8-meta: {}
  1.8-meta-alpine: {}
  1.8.10: {}
  1.8.10-alpine: {}
  1.8.10-data: {}
  1.8.10-data-alpine: {}
  1.8.10-meta: {}
  1.8.10-meta-alpine: {}
  1.9-data: {}
  1.9-data-alpine: {}
  1.9-meta: {}
  1.9-meta-alpine: {}
  1.9.11-data: {}
  1.9.11-data-alpine: {}
  1.9.11-meta: {}
  1.9.11-meta-alpine: {}
  1.10-data: {}
  1.10-data-alpine: {}
  1.10-meta: {}
  1.10-meta-alpine: {}
  1.10.3-data: {}
  1.10.3-data-alpine: {}
  1.10.3-meta: {}
  1.10.3-meta-alpine: {}
  "2.7": {}
  2.7-alpine: {}
  2.7.1: {}
  2.7.1-alpine: {}
  alpine: {}
  data: {}
  data-alpine: {}
  latest: {}
  meta: {}
  meta-alpine: {}
Name: influxdb
