Blocks:
- Architectures:
  - amd64
  Directory: ""
  GitCommit: 507775715a22e419d1c7e42028f7c3b5d9cf0418
  Tags:
  - 3.3.0-alpine
  - alpine
- Architectures:
  - amd64
  - arm64v8
  Directory: ubuntu
  GitCommit: 507775715a22e419d1c7e42028f7c3b5d9cf0418
  Tags:
  - 3.3.0-ubuntu
  - 3.3-ubuntu
  - 3.3.0
  - "3.3"
  - "3"
  - latest
  - ubuntu
- Architectures:
  - amd64
  Directory: ""
  GitCommit: 5641f8836920650fc66c6d36408daf794d730b96
  Tags:
  - 3.2.2-alpine
- Architectures:
  - amd64
  - arm64v8
  Directory: ubuntu
  GitCommit: 5641f8836920650fc66c6d36408daf794d730b96
  Tags:
  - 3.2.2-ubuntu
  - 3.2-ubuntu
  - 3.2.2
  - "3.2"
- Architectures:
  - amd64
  - arm64v8
  Directory: ""
  GitCommit: 5f914be945ec1732837cc4f6463219bed566c7ef
  Tags:
  - 3.1.1-alpine
  - 3.1.1
  - "3.1"
- Architectures:
  - amd64
  - arm64v8
  Directory: ubuntu
  GitCommit: 5f914be945ec1732837cc4f6463219bed566c7ef
  Tags:
  - 3.1.1-ubuntu
  - 3.1-ubuntu
- Architectures:
  - amd64
  - arm64v8
  Directory: ""
  GitCommit: 5a3ee8daf50371db2e3a788abe8f306255eead22
  Tags:
  - 3.0.2-alpine
  - 3.0-alpine
  - 3.0.2
  - "3.0"
- Architectures:
  - amd64
  - arm64v8
  Directory: ubuntu
  GitCommit: 5a3ee8daf50371db2e3a788abe8f306255eead22
  Tags:
  - 3.0.2-ubuntu
  - 3.0-ubuntu
- Architectures:
  - amd64
  - arm64v8
  Directory: alpine
  GitCommit: 7557a360568fb70650d35724462446064ec081b3
  Tags:
  - 2.8.3-alpine
  - 2.8.3
  - "2.8"
- Architectures:
  - amd64
  - arm64v8
  Directory: ubuntu
  GitCommit: 7557a360568fb70650d35724462446064ec081b3
  Tags:
  - 2.8.3-ubuntu
  - 2.8-ubuntu
GitRepo: https://github.com/Kong/docker-kong.git
KnownTags:
  "2.8": {}
  2.8-ubuntu: {}
  2.8.3: {}
  2.8.3-alpine: {}
  2.8.3-ubuntu: {}
  "3": {}
  "3.0": {}
  3.0-alpine: {}
  3.0-ubuntu: {}
  3.0.2: {}
  3.0.2-alpine: {}
  3.0.2-ubuntu: {}
  "3.1": {}
  3.1-ubuntu: {}
  3.1.1: {}
  3.1.1-alpine: {}
  3.1.1-ubuntu: {}
  "3.2": {}
  3.2-ubuntu: {}
  3.2.2: {}
  3.2.2-alpine: {}
  3.2.2-ubuntu: {}
  "3.3": {}
  3.3-ubuntu: {}
  3.3.0: {}
  3.3.0-alpine: {}
  3.3.0-ubuntu: {}
  alpine: {}
  latest: {}
  ubuntu: {}
Name: kong
